import type { ScoringCalibrationRecommendation, ScorelinePlausibilityStatus } from "./scoringV1GameplayCalibration";
import type { CalibrationScenario, ScenarioVariationSummary } from "../simulation";
import type { ReboundDangerLevel, ReboundContinuationType, ReboundWinner } from "../actions";
import type { ReboundType, ReboundZone, ResolvedPossessionAfterShot } from "../actions";
import type { ScoringVersion } from "./scoringRuleTypes";

export type BatchVariationStatus = "VARIED" | "PARTIALLY_VARIED" | "IDENTICAL_OUTPUT_WARNING" | "SEED_NOT_CONNECTED_TO_SIMULATION";

export interface MatchScoringCalibrationSample {
  readonly matchId: string;
  readonly seed: string;
  readonly scenario: CalibrationScenario;
  readonly finalScore: string;
  readonly winner: string;
  readonly scoreDifferential: number;
  readonly totalShots: number;
  readonly shotGoals: number;
  readonly conversionRate: number;
  readonly controlShots: number;
  readonly blitzShots: number;
  readonly controlShotGoals: number;
  readonly blitzShotGoals: number;
  readonly controlPoints: number;
  readonly blitzPoints: number;
  readonly lowQualityShots: number;
  readonly mediumQualityShots: number;
  readonly goodQualityShots: number;
  readonly highQualityShots: number;
  readonly eliteQualityShots: number;
  readonly lowQualityGoals: number;
  readonly highQualityMisses: number;
  readonly forcedShotCount: number;
  readonly cleanWindowShotCount: number;
  readonly forcedShotGoalCount: number;
  readonly cleanWindowGoalCount: number;
  readonly onTargetShotCount: number;
  readonly goalkeeperEvaluatedCount: number;
  readonly goalkeeperInvolvedCount: number;
  readonly goalkeeperSaveCatchDeflectCount: number;
  readonly goalsWithGoalkeeperEvaluated: number;
  readonly goalsWithoutGoalkeeperEvaluated: number;
  readonly caughtByGoalkeeperCount: number;
  readonly savedByGoalkeeperCount: number;
  readonly deflectedByGoalkeeperCount: number;
  readonly blockedByDefenderCount: number;
  readonly missedWideHighCount: number;
  readonly reboundEvents: readonly BatchReboundCalibrationEvent[];
  readonly reboundEventCount: number;
  readonly contestedReboundCount: number;
  readonly resolvedReboundCount: number;
  readonly attackerReboundRecoveryCount: number;
  readonly defenderReboundRecoveryCount: number;
  readonly gkReboundRecoveryCount: number;
  readonly secondShotWindowCount: number;
  readonly scrambleReboundCount: number;
  readonly outOfPlayReboundCount: number;
  readonly unresolvedContestedReboundCount: number;
  readonly contestedCleanWindowCount: number;
  readonly eliteCleanWindowCount: number;
  readonly averageShotQuality: number;
  readonly averageGoalShotQuality: number;
  readonly averageMissShotQuality: number;
  readonly averageGoalkeeperChallenge: number;
  readonly averageDefensiveBlockPressure: number;
  readonly averageFinishingPressure: number;
  readonly averageGoalkeeperChallengeImpact: number;
  readonly averageDefensiveBlockPressureImpact: number;
  readonly averageFinishingPressureImpact: number;
  readonly averageForcedShotPenaltyImpact: number;
  readonly averageCleanWindowBonusImpact: number;
  readonly shotOutcomePattern: string;
  readonly actionOrderSignature: string;
  readonly blowout: boolean;
  readonly notes: string;
}

export interface BatchReboundCalibrationEvent {
  readonly matchId: string;
  readonly seed: string;
  readonly sourceActionId: string;
  readonly sourceOutcome: string;
  readonly reboundType: ReboundType;
  readonly reboundZone: ReboundZone;
  readonly attackingTeamName: string;
  readonly defendingTeamName: string;
  readonly attackingTeamId: string;
  readonly defendingTeamId: string;
  readonly controlStyleVariant: string;
  readonly blitzStyleVariant: string;
  readonly pressureProfile: string;
  readonly nearestAttackers: string;
  readonly nearestDefenders: string;
  readonly goalkeeperRecoveryScore: number;
  readonly attackerReactionScore: number;
  readonly defenderReactionScore: number;
  readonly reboundWinner: ReboundWinner;
  readonly winningPlayer: string;
  readonly nextPossession: ResolvedPossessionAfterShot;
  readonly continuationType: ReboundContinuationType;
  readonly immediateDanger: ReboundDangerLevel;
  readonly reason: string;
}

export interface BatchTeamStyleProfile {
  readonly teamName: string;
  readonly averageShots: number;
  readonly averageGoals: number;
  readonly averagePoints: number;
  readonly conversionRate: number;
  readonly forcedShotRate: number;
  readonly averageShotQuality: number;
  readonly tacticalRead: string;
}

export type StyleBalanceStatus = "BALANCED" | "WATCH" | "IMBALANCED";

export interface BatchStyleBalanceProfile {
  readonly styleVariant: string;
  readonly matches: number;
  readonly shots: number;
  readonly shotGoals: number;
  readonly conversionRate: number;
  readonly pointsPerMatch: number;
  readonly forcedShotRate: number;
  readonly cleanWindowConversionRate: number;
  readonly winContribution: number;
  readonly drawContribution: number;
  readonly lossContribution: number;
}

export interface BatchScoringCalibrationSummary {
  readonly scoringVersion: ScoringVersion;
  readonly scoringRule: string;
  readonly scoreUnit: "POINTS";
  readonly matchesSimulated: number;
  readonly seedsUsed: readonly string[];
  readonly variationStatus: BatchVariationStatus;
  readonly scenarioVariation: ScenarioVariationSummary;
  readonly shotDifficultyCalibrationApplied: boolean;
  readonly cleanWindowCalibrationApplied: boolean;
  readonly conversionTargetRange: "25% to 40%";
  readonly cleanWindowConversionTargetRange: "60% to 75%";
  readonly styleBalanceStatus: StyleBalanceStatus;
  readonly recommendation: ScoringCalibrationRecommendation;
  readonly scorelinePlausibility: ScorelinePlausibilityStatus;
  readonly averageTotalPointsPerMatch: number;
  readonly averageScoreDifferential: number;
  readonly medianScoreDifferential: number;
  readonly blowoutRate: number;
  readonly controlWinRate: number;
  readonly blitzWinRate: number;
  readonly drawRate: number;
  readonly averageShotsPerMatch: number;
  readonly averageShotGoalsPerMatch: number;
  readonly averageConversionRate: number;
  readonly averageControlShots: number;
  readonly averageBlitzShots: number;
  readonly averageControlPoints: number;
  readonly averageBlitzPoints: number;
  readonly averageShotQuality: number;
  readonly averageGoalShotQuality: number;
  readonly averageMissShotQuality: number;
  readonly lowQualityShots: number;
  readonly lowQualityGoals: number;
  readonly lowQualityGoalRate: number;
  readonly highQualityShots: number;
  readonly highQualityMisses: number;
  readonly highQualityMissRate: number;
  readonly forcedShotCount: number;
  readonly forcedShotRate: number;
  readonly forcedShotConversionRate: number;
  readonly cleanWindowConversionRate: number;
  readonly onTargetShotCount: number;
  readonly goalkeeperEvaluatedCount: number;
  readonly goalkeeperInvolvedCount: number;
  readonly goalkeeperSaveCatchDeflectCount: number;
  readonly goalsWithGoalkeeperEvaluated: number;
  readonly goalsWithoutGoalkeeperEvaluated: number;
  readonly caughtByGoalkeeperCount: number;
  readonly savedByGoalkeeperCount: number;
  readonly deflectedByGoalkeeperCount: number;
  readonly blockedByDefenderCount: number;
  readonly missedWideHighCount: number;
  readonly averageGoalkeeperChallengeImpact: number;
  readonly averageDefensiveBlockPressureImpact: number;
  readonly averageFinishingPressureImpact: number;
  readonly averageForcedShotPenaltyImpact: number;
  readonly averageCleanWindowBonusImpact: number;
  readonly contestedCleanWindowCount: number;
  readonly eliteCleanWindowCount: number;
  readonly styleBalanceProfiles: readonly BatchStyleBalanceProfile[];
  readonly samples: readonly MatchScoringCalibrationSample[];
  readonly teamProfiles: readonly BatchTeamStyleProfile[];
  readonly warnings: readonly string[];
}
