import type { ScoringFamilyAttributionWarningCode } from "../../contracts/scoringFamily";

export const SCORING_FAMILY_ATTRIBUTION_WARNING_CODES: readonly ScoringFamilyAttributionWarningCode[] = [
  "UNKNOWN_SCORING_FAMILY",
  "MISSING_SCORING_ACTION",
  "MISSING_SCORE_CHANGE_POINT_VALUE",
  "FAMILY_POINT_VALUE_MISMATCH",
  "INACTIVE_PENALTY_SHOT_USED",
  "AMBIGUOUS_SCORING_FAMILY",
  "LOW_CONFIDENCE_SCORING_ATTRIBUTION",
  "SCORING_EVENT_WITHOUT_OFFICIAL_CONSEQUENCE",
  "SCORE_CHANGE_WITHOUT_SCORING_FAMILY",
];
