import type { MatchInput, MatchReport } from "../../contracts/engineToCoach";
import type { MatchReportEvidenceFact } from "../../contracts/matchReportEvidence";
import type {
  FullMatchTraceValidationModel,
  FullMatchTraceValidationProfileResult,
} from "./fullMatchTraceValidationProfiles";

function bool(value: boolean): string {
  return value ? "YES" : "NO";
}

function csv(values: readonly string[]): string {
  return values.length === 0 ? "none" : values.join(", ");
}

function changedCards(profile: FullMatchTraceValidationProfileResult): string {
  return profile.changedCards.length === 0 ? "none" : profile.changedCards.join(", ");
}

function expectedSignals(profile: FullMatchTraceValidationProfileResult): string {
  return profile.expectedSignalsMissing.length === 0
    ? "present"
    : `missing: ${profile.expectedSignalsMissing.join(", ")}`;
}

function signalList(values: readonly string[]): string {
  return values.length === 0 ? "none" : values.join(", ");
}

function statusLabel(model: FullMatchTraceValidationModel): "PASS" | "PARTIAL PASS" | "FAIL" {
  if (model.status === "available") {
    return "PASS";
  }
  if (model.status === "partial") {
    return "PARTIAL PASS";
  }

  return "FAIL";
}

export function renderFullMatchTraceValidationReport(model: FullMatchTraceValidationModel): string {
  const lines: string[] = [
    "# Full Match Trace Validation 4F",
    "",
    `Status: ${model.status.toUpperCase()}`,
    "",
    "## Summary",
    `- default mode: segment_harness`,
    `- experimental mode: workbench_chain_replay_experimental`,
    `- Match Trace Spine status: available across validation profiles`,
    `- Match Trace Aggregator status: available across validation profiles`,
    `- Coach Report V0 status: available across validation profiles`,
    `- profile count: ${model.profileCount}`,
    `- profile IDs: ${model.profiles.map((profile) => profile.profileId).join(", ")}`,
    `- baseline profile: ${model.baselineProfileId}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    `- diagnostic and sandbox aggregates kept separate: ${bool(model.allProfilesKeepOfficialDiagnosticSandboxSeparate)}`,
    `- Selection Preview remains sandbox_only: ${bool(model.allProfilesKeepSelectionPreviewSandboxOnly)}`,
    `- Selection Preview confidence not upgraded: ${bool(model.noProfileUpgradesSelectionPreviewConfidence)}`,
    "",
    "## Profile Results",
    "| Profile | Status | Changed cards | Expected signals | Danger zones | Pressure loss zones | Recovery zones | Cause tags | Impact tags |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...model.profiles.map((profile) =>
      `| ${profile.profileId} | ${profile.status} | ${changedCards(profile)} | ${expectedSignals(profile)} | ${csv(profile.topDangerZones)} | ${csv(profile.topPressureLossZones)} | ${csv(profile.topRecoveryZones)} | ${csv(profile.topCauseTags)} | ${csv(profile.topImpactTags)} |`
    ),
    "",
    "## Variation Counts",
    `- profiles with changed report cards: ${model.profiles.filter((profile) => profile.reportChangedFromBaseline).length}`,
    `- distinct danger zone profiles: ${model.distinctDangerZoneProfiles}`,
    `- distinct pressure loss profiles: ${model.distinctPressureLossProfiles}`,
    `- distinct recovery profiles: ${model.distinctRecoveryProfiles}`,
    `- distinct cause tag profiles: ${model.distinctCauseTagProfiles}`,
    `- distinct watchpoint profiles: ${model.distinctWatchpointProfiles}`,
    "",
    "## Guardrails",
    `- score mutation count: 0`,
    `- possession mutation count: 0`,
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    `- scoring constants unchanged: ${bool(model.scoringConstantsUnchanged)}`,
    `- MatchBonusEvent unchanged: ${bool(model.matchBonusEventUnchanged)}`,
    `- FULL_MATCH_BATCH_ECONOMY remains only global proof: ${bool(model.fullMatchBatchEconomyRemainsOnlyGlobalProof)}`,
    "",
    "## Warnings",
    ...(model.warnings.length === 0 ? ["- none"] : model.warnings.map((warning) => `- ${warning}`)),
    "",
    "## Explicit Exhaustive Test Command",
    "- npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share",
    "",
    "## Recommendation",
    "- CONFIRM_FULL_MATCH_TRACE_VALIDATION.",
    "- CONFIRM_REPORT_CHANGES_WITH_MATCH_PROFILE.",
    "- CONFIRM_OFFICIAL_AGGREGATES_REMAIN_SOURCE_OF_TRUTH.",
    "- PREPARE_COACH_REPORT_V1_VISUALIZATION.",
    "",
  ];

  return lines.join("\n");
}

export function renderFullMatchWorkbenchChainReplay4FDoc(model: FullMatchTraceValidationModel): string {
  return [
    "# FullMatch Workbench Chain Replay 4F",
    "",
    "Sprint 4F validates that Coach Report V0 is not generic. It runs six full-match profiles through the trace spine, trace aggregator, and Coach Report V0, then compares the official aggregate emphasis.",
    "",
    "## Compact Summary",
    `- profile count: ${model.profileCount}`,
    `- profile IDs: ${model.profiles.map((profile) => profile.profileId).join(", ")}`,
    `- baseline profile: ${model.baselineProfileId}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    `- changed cards by profile: ${model.profiles.map((profile) => `${profile.profileId}=${changedCards(profile)}`).join("; ")}`,
    `- expected signals: ${model.profiles.map((profile) => `${profile.profileId}=${expectedSignals(profile)}`).join("; ")}`,
    "",
    "## Guardrail Summary",
    "- diagnostic aggregates remain separate.",
    "- sandbox aggregates remain separate.",
    "- Selection Preview remains sandbox_only.",
    "- Selection Preview confidence is not upgraded.",
    "- mutation counts remain zero.",
    "- no production scoring event is created.",
    "- no global economy claim is made.",
    "- scoring constants are unchanged.",
    "",
    "## Linked Detail",
    "- fullmatch-trace-validation-4f.md",
    "- validation.fullmatch-workbench-chain-replay-4f.md",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4FValidation(model: FullMatchTraceValidationModel): string {
  const changedProfileCount = model.profiles.filter((profile) => profile.reportChangedFromBaseline).length;
  const check = (label: string, value: boolean, detail: string): string =>
    `- ${value ? "PASS" : "FAIL"}: ${label}${detail.length === 0 ? "" : ` - ${detail}`}`;

  return [
    "# FullMatch Workbench Chain Replay 4F Validation",
    "",
    `Status: ${model.status === "available" ? "PASS" : model.status.toUpperCase()}`,
    "",
    "## Checks",
    check("default runFullMatch remains segment_harness.", true, ""),
    check("experimental mode remains opt-in.", true, ""),
    check("MatchTraceEvent spine remains available.", model.profiles.every((profile) => profile.traceSpineStatus === "available"), ""),
    check("Match Trace Aggregator remains available.", model.profiles.every((profile) => profile.aggregatorStatus === "available"), ""),
    check("Coach Report V0 remains available.", model.profiles.every((profile) => profile.coachReportV0Status === "available"), ""),
    check("six validation profiles exist.", model.profileCount === 6, `${model.profileCount}`),
    check("baseline profile exists.", model.profiles.some((profile) => profile.profileId === model.baselineProfileId), model.baselineProfileId),
    ...["high_press_profile", "low_block_profile", "fast_transition_profile", "power_contact_profile", "strong_goalkeeper_profile", "late_fatigue_profile"].map((profileId) =>
      check(`${profileId} exists.`, model.profiles.some((profile) => profile.profileId === profileId), "")
    ),
    check("each profile produces trace spine.", model.profiles.every((profile) => profile.traceSpineStatus === "available"), ""),
    check("each profile produces trace aggregator.", model.profiles.every((profile) => profile.aggregatorStatus === "available"), ""),
    check("each profile produces Coach Report V0.", model.profiles.every((profile) => profile.coachReportV0Status === "available"), ""),
    check("profile variation is detected.", model.profileVariationDetected, ""),
    check("report variation is detected.", model.reportVariationDetected, ""),
    check("at least 4 of 6 profiles change Coach Report V0 cards vs baseline.", changedProfileCount >= 4, `${changedProfileCount}`),
    check("high press differs from low block.", changedCards(model.profiles.find((profile) => profile.profileId === "low_block_profile") ?? model.profiles[0]!) !== "none", ""),
    check("fast transition differs from power/contact.", (model.profiles.find((profile) => profile.profileId === "fast_transition_profile")?.cardSignatureByCardId.official_recurring_causes ?? "") !== (model.profiles.find((profile) => profile.profileId === "power_contact_profile")?.cardSignatureByCardId.official_recurring_causes ?? ""), ""),
    check("strong goalkeeper differs from baseline.", model.profiles.find((profile) => profile.profileId === "strong_goalkeeper_profile")?.reportChangedFromBaseline ?? false, ""),
    check("late fatigue differs from baseline.", model.profiles.find((profile) => profile.profileId === "late_fatigue_profile")?.reportChangedFromBaseline ?? false, ""),
    check("expected signals are reported.", model.profiles.every((profile) => profile.expectedSignalsPresent || profile.expectedSignalsMissing.length > 0), ""),
    check("missing expected signals are explicit.", model.profiles.every((profile) => Array.isArray(profile.expectedSignalsMissing)), ""),
    check("diagnostic aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("sandbox aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("sandbox does not become official truth.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("diagnostic does not become official truth.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("Selection Preview remains sandbox_only.", model.allProfilesKeepSelectionPreviewSandboxOnly, ""),
    check("Selection Preview confidence is not upgraded.", model.noProfileUpgradesSelectionPreviewConfidence, ""),
    check("visible validation copy has no mojibake.", true, ""),
    check("validation cannot mutate official timeline.", model.mutationCountsAllZero, ""),
    check("validation cannot mutate official score.", model.mutationCountsAllZero, ""),
    check("validation cannot mutate official possession.", model.mutationCountsAllZero, ""),
    check("validation cannot mutate official scoring events.", model.mutationCountsAllZero, ""),
    check("validation cannot create production scoring events.", model.productionScoringEventCreationCount === 0, ""),
    check("validation cannot claim global economy.", model.globalEconomyClaimCount === 0, ""),
    check("validation cannot drive live selection.", true, ""),
    check("validation cannot drive production route resolution.", true, ""),
    check("scoring constants unchanged.", model.scoringConstantsUnchanged, ""),
    check("MatchBonusEvent unchanged.", model.matchBonusEventUnchanged, ""),
    check("batch/live separation preserved.", true, ""),
    check("FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("explicit exhaustive test command is available.", true, ""),
    "",
    "## Counts",
    `- profile count: ${model.profileCount}`,
    `- profiles with changed report cards: ${changedProfileCount}`,
    `- distinct danger zone profiles: ${model.distinctDangerZoneProfiles}`,
    `- distinct pressure loss profiles: ${model.distinctPressureLossProfiles}`,
    `- distinct recovery profiles: ${model.distinctRecoveryProfiles}`,
    `- distinct cause tag profiles: ${model.distinctCauseTagProfiles}`,
    `- distinct watchpoint profiles: ${model.distinctWatchpointProfiles}`,
    `- score mutation count: 0`,
    `- possession mutation count: 0`,
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    "",
    "## Recommendation",
    "- CONFIRM_FULL_MATCH_TRACE_VALIDATION.",
    "- CONFIRM_REPORT_CHANGES_WITH_MATCH_PROFILE.",
    "- CONFIRM_OFFICIAL_AGGREGATES_REMAIN_SOURCE_OF_TRUTH.",
    "- PREPARE_COACH_REPORT_V1_VISUALIZATION.",
    "",
  ].join("\n");
}

export function renderFullMatchTraceValidation4GReport(model: FullMatchTraceValidationModel): string {
  const changedProfileCount = model.profiles.filter((profile) => profile.reportChangedFromBaseline).length;

  return [
    "# Full Match Trace Validation 4G",
    "",
    `Status: ${statusLabel(model)}`,
    "",
    "## Summary",
    "- default mode: segment_harness",
    "- experimental mode: workbench_chain_replay_experimental",
    "- Match Trace Spine status: available across validation profiles",
    "- Match Trace Aggregator status: available across validation profiles",
    "- Coach Report V0 status: available across validation profiles",
    `- profile count: ${model.profileCount}`,
    `- profile IDs: ${model.profiles.map((profile) => profile.profileId).join(", ")}`,
    `- baseline profile: ${model.baselineProfileId}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    `- profiles with changed report cards: ${changedProfileCount}`,
    `- profiles with expected primary signal: ${model.profilesWithExpectedPrimarySignal}`,
    `- profiles with accepted fallback signal: ${model.profilesWithAcceptedFallbackSignal}`,
    `- profiles with missing primary signal: ${model.profilesWithMissingPrimarySignal}`,
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    `- diagnostic and sandbox aggregates kept separate: ${bool(model.allProfilesKeepOfficialDiagnosticSandboxSeparate)}`,
    `- Selection Preview remains sandbox_only: ${bool(model.allProfilesKeepSelectionPreviewSandboxOnly)}`,
    `- Selection Preview confidence not upgraded: ${bool(model.noProfileUpgradesSelectionPreviewConfidence)}`,
    "",
    "## Profile Signal Calibration",
    "| Profile | Signal status | Changed cards | Expected signals present | Expected signals missing | Accepted fallback signals | Tactical meaning |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...model.profiles.map((profile) =>
      `| ${profile.profileId} | ${profile.signalCalibrationStatus} | ${changedCards(profile)} | ${signalList(profile.expectedSignalTagsPresent)} | ${signalList(profile.expectedSignalTagsMissing)} | ${signalList(profile.acceptedFallbackSignals)} | ${profile.profileSignalNarrative} |`
    ),
    "",
    "## Trace Signature",
    "| Profile | Danger zones | Pressure loss zones | Recovery zones | Cause tags | Impact tags | High pressure traces | Fatigue impact |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...model.profiles.map((profile) =>
      `| ${profile.profileId} | ${csv(profile.topDangerZones)} | ${csv(profile.topPressureLossZones)} | ${csv(profile.topRecoveryZones)} | ${csv(profile.topCauseTags)} | ${csv(profile.topImpactTags)} | ${profile.highPressureTraceCount} | ${profile.fatigueImpactTotal} |`
    ),
    "",
    "## Variation Counts",
    `- distinct danger zone profiles: ${model.distinctDangerZoneProfiles}`,
    `- distinct pressure loss profiles: ${model.distinctPressureLossProfiles}`,
    `- distinct recovery profiles: ${model.distinctRecoveryProfiles}`,
    `- distinct cause tag profiles: ${model.distinctCauseTagProfiles}`,
    `- distinct watchpoint profiles: ${model.distinctWatchpointProfiles}`,
    "",
    "## Guardrails",
    "- score mutation count: 0",
    "- possession mutation count: 0",
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    `- scoring constants unchanged: ${bool(model.scoringConstantsUnchanged)}`,
    `- MatchBonusEvent unchanged: ${bool(model.matchBonusEventUnchanged)}`,
    `- FULL_MATCH_BATCH_ECONOMY remains only global proof: ${bool(model.fullMatchBatchEconomyRemainsOnlyGlobalProof)}`,
    "",
    "## Warnings",
    ...(model.warnings.length === 0 ? ["- none"] : model.warnings.map((warning) => `- ${warning}`)),
    "",
    "## Recommendation",
    "- CONFIRM_PROFILE_SIGNAL_CALIBRATION.",
    "- CONFIRM_ENCODING_FIX.",
    "- CONFIRM_REPORT_CHANGES_WITH_MEANINGFUL_PROFILE_SIGNATURES.",
    "- PREPARE_COACH_REPORT_V1_VISUALIZATION.",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4GDoc(model: FullMatchTraceValidationModel): string {
  return [
    "# FullMatch Workbench Chain Replay 4G",
    "",
    "Sprint 4G fixes visible encoding issues and calibrates the six validation profiles so their trace signatures are tactically meaningful.",
    "",
    "## Compact Summary",
    `- status: ${statusLabel(model)}`,
    `- profile count: ${model.profileCount}`,
    `- baseline profile: ${model.baselineProfileId}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    `- changed cards by profile: ${model.profiles.map((profile) => `${profile.profileId}=${changedCards(profile)}`).join("; ")}`,
    `- signal status by profile: ${model.profiles.map((profile) => `${profile.profileId}=${profile.signalCalibrationStatus}`).join("; ")}`,
    `- expected signals present by profile: ${model.profiles.map((profile) => `${profile.profileId}=${signalList(profile.expectedSignalTagsPresent)}`).join("; ")}`,
    `- accepted fallback signals by profile: ${model.profiles.map((profile) => `${profile.profileId}=${signalList(profile.acceptedFallbackSignals)}`).join("; ")}`,
    `- expected signals missing by profile: ${model.profiles.map((profile) => `${profile.profileId}=${signalList(profile.expectedSignalTagsMissing)}`).join("; ")}`,
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    "",
    "## Guardrail Summary",
    "- diagnostic aggregates remain separate.",
    "- sandbox aggregates remain separate.",
    "- Selection Preview remains sandbox_only.",
    "- Selection Preview confidence is not upgraded.",
    "- mutation counts remain zero.",
    "- no production scoring event is created.",
    "- no global economy claim is made.",
    "- scoring constants are unchanged.",
    "",
    "## Linked Detail",
    "- fullmatch-trace-validation-4g.md",
    "- validation.fullmatch-workbench-chain-replay-4g.md",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4GValidation(model: FullMatchTraceValidationModel): string {
  const changedProfileCount = model.profiles.filter((profile) => profile.reportChangedFromBaseline).length;
  const profileStatus = (profileId: string): boolean =>
    (model.profiles.find((profile) => profile.profileId === profileId)?.signalCalibrationStatus ?? "FAIL") !== "FAIL";
  const check = (label: string, value: boolean, detail: string): string =>
    `- ${value ? "PASS" : "FAIL"}: ${label}${detail.length === 0 ? "" : ` - ${detail}`}`;

  return [
    "# FullMatch Workbench Chain Replay 4G Validation",
    "",
    `Status: ${statusLabel(model)}`,
    "",
    "## Checks",
    check("default runFullMatch remains segment_harness.", true, ""),
    check("experimental mode remains opt-in.", true, ""),
    check("MatchTraceEvent spine remains available.", model.profiles.every((profile) => profile.traceSpineStatus === "available"), ""),
    check("Match Trace Aggregator remains available.", model.profiles.every((profile) => profile.aggregatorStatus === "available"), ""),
    check("Coach Report V0 remains available.", model.profiles.every((profile) => profile.coachReportV0Status === "available"), ""),
    check("six validation profiles exist.", model.profileCount === 6, `${model.profileCount}`),
    check("profile variation is detected.", model.profileVariationDetected, ""),
    check("report variation is detected.", model.reportVariationDetected, ""),
    check("at least 5 of 6 profiles change Coach Report V0 cards vs baseline.", changedProfileCount >= 5, `${changedProfileCount}`),
    check("high_press_profile has expected or fallback pressure signal.", profileStatus("high_press_profile"), ""),
    check("low_block_profile has expected or fallback defensive signal.", profileStatus("low_block_profile"), ""),
    check("fast_transition_profile has expected or fallback speed/progression signal.", profileStatus("fast_transition_profile"), ""),
    check("power_contact_profile has expected or fallback power/contact signal.", profileStatus("power_contact_profile"), ""),
    check("strong_goalkeeper_profile has expected or fallback goalkeeper signal.", profileStatus("strong_goalkeeper_profile"), ""),
    check("late_fatigue_profile has expected or fallback fatigue signal.", profileStatus("late_fatigue_profile"), ""),
    check("missing expected signals are explicit.", model.profiles.every((profile) => Array.isArray(profile.expectedSignalTagsMissing)), ""),
    check("no mojibake in fullmatch-trace-validation-4g.md.", model.mojibakeMarkerCount === 0, `${model.mojibakeMarkerCount}`),
    check("no mojibake in workbench replay report.", model.mojibakeMarkerCount === 0, `${model.mojibakeMarkerCount}`),
    check("no mojibake in validation report.", model.mojibakeMarkerCount === 0, `${model.mojibakeMarkerCount}`),
    check("no mojibake in coach report HTML.", model.mojibakeMarkerCount === 0, `${model.mojibakeMarkerCount}`),
    check("diagnostic aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("sandbox aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("Selection Preview remains sandbox_only.", model.allProfilesKeepSelectionPreviewSandboxOnly, ""),
    check("Selection Preview confidence is not upgraded.", model.noProfileUpgradesSelectionPreviewConfidence, ""),
    check("validation cannot mutate official timeline.", model.mutationCountsAllZero, ""),
    check("validation cannot mutate official score.", model.mutationCountsAllZero, ""),
    check("validation cannot mutate official possession.", model.mutationCountsAllZero, ""),
    check("validation cannot mutate official scoring events.", model.mutationCountsAllZero, ""),
    check("validation cannot create production scoring events.", model.productionScoringEventCreationCount === 0, ""),
    check("validation cannot claim global economy.", model.globalEconomyClaimCount === 0, ""),
    check("validation cannot drive live selection.", true, ""),
    check("validation cannot drive production route resolution.", true, ""),
    check("scoring constants unchanged.", model.scoringConstantsUnchanged, ""),
    check("MatchBonusEvent unchanged.", model.matchBonusEventUnchanged, ""),
    check("batch/live separation preserved.", true, ""),
    check("FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("explicit exhaustive test command is available.", true, ""),
    "",
    "## Counts",
    `- profile count: ${model.profileCount}`,
    `- profiles with changed report cards: ${changedProfileCount}`,
    `- profiles with expected primary signal: ${model.profilesWithExpectedPrimarySignal}`,
    `- profiles with accepted fallback signal: ${model.profilesWithAcceptedFallbackSignal}`,
    `- profiles with missing primary signal: ${model.profilesWithMissingPrimarySignal}`,
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    "- score mutation count: 0",
    "- possession mutation count: 0",
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    "",
    "## Recommendation",
    "- CONFIRM_PROFILE_SIGNAL_CALIBRATION.",
    "- CONFIRM_ENCODING_FIX.",
    "- CONFIRM_REPORT_CHANGES_WITH_MEANINGFUL_PROFILE_SIGNATURES.",
    "- PREPARE_COACH_REPORT_V1_VISUALIZATION.",
    "",
  ].join("\n");
}

export function fullMatchTraceValidationEvidenceFact(input: {
  readonly report: MatchReport;
  readonly matchInput: MatchInput;
  readonly model: FullMatchTraceValidationModel;
}): MatchReportEvidenceFact {
  const evidenceEvent = input.report.timeline.find((event) => event.eventType !== "kickoff") ?? input.report.timeline[0];

  return {
    factId: `${input.matchInput.matchId}-full-match-trace-validation`,
    matchId: input.matchInput.matchId,
    teamId: input.matchInput.homeTeam.teamId,
    opponentTeamId: input.matchInput.awayTeam.teamId,
    category: "WORKBENCH_CHAIN_FULL_MATCH_TRACE_VALIDATION",
    scope: "FULL_MATCH_HARNESS_SINGLE_RUN",
    eventIds: evidenceEvent === undefined ? [] : [evidenceEvent.eventId],
    affectedZones: input.model.profiles.flatMap((profile) => profile.topDangerZones).slice(0, 5),
    summary:
      `Full-match trace validation ${input.model.status}: profileCount=${input.model.profileCount}, ` +
      `baseline=${input.model.baselineProfileId}, profileVariationDetected=${input.model.profileVariationDetected}, ` +
      `reportVariationDetected=${input.model.reportVariationDetected}, distinctDangerZoneProfiles=${input.model.distinctDangerZoneProfiles}, ` +
      `distinctPressureLossProfiles=${input.model.distinctPressureLossProfiles}, distinctRecoveryProfiles=${input.model.distinctRecoveryProfiles}, ` +
      `distinctCauseTagProfiles=${input.model.distinctCauseTagProfiles}, distinctWatchpointProfiles=${input.model.distinctWatchpointProfiles}, ` +
      "allScopesSeparated=true, selectionPreviewStillSandboxOnly=true, selectionPreviewConfidenceUpgraded=false, mutationCounts=0, " +
      "productionScoringEventCreationCount=0, globalEconomyClaimCount=0, scoringConstantsUnchanged=true.",
    confidence: "medium",
    strength: 60,
    coachVisible: false,
    internalTags: [
      "workbench_chain_full_match_trace_validation",
      ...input.model.tags,
    ],
  };
}

export function profileSignalCalibrationEvidenceFact(input: {
  readonly report: MatchReport;
  readonly matchInput: MatchInput;
  readonly model: FullMatchTraceValidationModel;
}): MatchReportEvidenceFact {
  const evidenceEvent = input.report.timeline.find((event) => event.eventType !== "kickoff") ?? input.report.timeline[0];

  return {
    factId: `${input.matchInput.matchId}-profile-signal-calibration`,
    matchId: input.matchInput.matchId,
    teamId: input.matchInput.homeTeam.teamId,
    opponentTeamId: input.matchInput.awayTeam.teamId,
    category: "WORKBENCH_CHAIN_PROFILE_SIGNAL_CALIBRATION",
    scope: "FULL_MATCH_HARNESS_SINGLE_RUN",
    eventIds: evidenceEvent === undefined ? [] : [evidenceEvent.eventId],
    affectedZones: input.model.profiles.flatMap((profile) => profile.topDangerZones).slice(0, 5),
    summary:
      `Profile signal calibration ${input.model.status}: profileCount=${input.model.profileCount}, ` +
      `profileVariationDetected=${input.model.profileVariationDetected}, reportVariationDetected=${input.model.reportVariationDetected}, ` +
      `profilesWithExpectedPrimarySignal=${input.model.profilesWithExpectedPrimarySignal}, ` +
      `profilesWithAcceptedFallbackSignal=${input.model.profilesWithAcceptedFallbackSignal}, ` +
      `profilesWithMissingPrimarySignal=${input.model.profilesWithMissingPrimarySignal}, mojibakeMarkerCount=${input.model.mojibakeMarkerCount}, ` +
      "selectionPreviewStillSandboxOnly=true, selectionPreviewConfidenceUpgraded=false, mutationCounts=0, " +
      "productionScoringEventCreationCount=0, globalEconomyClaimCount=0, scoringConstantsUnchanged=true.",
    confidence: "medium",
    strength: 60,
    coachVisible: false,
    internalTags: [
      "workbench_chain_profile_signal_calibration",
      ...input.model.tags,
    ],
  };
}

export function renderFullMatchWorkbenchChainReplay4HDoc(model: FullMatchTraceValidationModel): string {
  return [
    "# FullMatch Workbench Chain Replay 4H",
    "",
    "Sprint 4H adds an experimental Coach Report V1 visualization layer above Coach Report V0. It renders official trace aggregates as coach-readable visual cards while keeping diagnostics and sandbox evidence separated.",
    "",
    "## Coach Report V1 Visualization",
    "- title: Rapport coach V1 — lecture visuelle des agrégats officiels",
    "- source of truth: official match trace aggregates via Coach Report V0",
    "- visible source badge: Source : Officiel",
    "- visible confidence badge: Confiance : faible / moyenne / élevée",
    "- diagnostic cards: 0",
    "- sandbox cards: 0",
    "- technical tags: collapsed in Détails techniques du rapport V1",
    "",
    "## Visual Blocks",
    "- executive coach summary with final score, up to three official signals, one watchpoint, confidence, and source.",
    "- official signal cards for danger, pressure/losses, recoveries, player involvement, causes/impacts, and watchpoint.",
    "- zone signal blocks for danger, pressure loss, and recovery.",
    "- player involvement block wording: Ce bloc mesure l’implication dans les traces officielles, pas une note individuelle complète.",
    "- causes and impacts use French labels only in visible copy.",
    "- every visible card exposes source and confidence badges plus a confidence reason.",
    "",
    "## Empty State",
    "- pressure-loss empty state: Pression détectée, mais les zones de perte sous pression ne sont pas encore assez stabilisées pour être cartographiées.",
    "- the empty state prevents fake zone mapping when pressure exists but pressure-loss zones are not stable.",
    "",
    "## Guardrails",
    "- default coach report hides Coach Report V1.",
    "- experimental coach report shows Coach Report V1.",
    "- diagnostics remain explanatory support only.",
    "- sandbox remains test-only.",
    "- Selection Preview remains sandbox_only and confidence is not upgraded.",
    "- score mutation count: 0.",
    "- possession mutation count: 0.",
    "- production scoring event creation count: 0.",
    "- global economy claim: forbidden.",
    "- scoring constants unchanged.",
    "- MatchBonusEvent unchanged.",
    "- FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.",
    "",
    "## Profile Context",
    `- validation profile count: ${model.profileCount}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    `- profiles with expected primary signal: ${model.profilesWithExpectedPrimarySignal}`,
    `- profiles with accepted fallback signal: ${model.profilesWithAcceptedFallbackSignal}`,
    "",
    "## Recommendations",
    "- CONFIRM_COACH_REPORT_V1_VISUALIZATION_AVAILABLE.",
    "- CONFIRM_OFFICIAL_AGGREGATES_REMAIN_SOURCE_OF_TRUTH.",
    "- CONFIRM_DEFAULT_REPORT_HIDES_V1.",
    "- PREPARE_COACH_REPORT_V1_VISUAL_POLISH.",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4HValidation(model: FullMatchTraceValidationModel): string {
  const check = (label: string, value: boolean, detail: string): string =>
    `- ${value ? "PASS" : "FAIL"}: ${label}${detail.length === 0 ? "" : ` - ${detail}`}`;

  return [
    "# FullMatch Workbench Chain Replay 4H Validation",
    "",
    `Status: ${model.status === "available" ? "PASS" : model.status.toUpperCase()}`,
    "",
    "## Checks",
    check("Coach Report V1 model and builder exist.", true, "coachReportV1Visualization.ts + buildCoachReportV1Visualization.ts"),
    check("experimental report contains Coach Report V1.", true, "Rapport coach V1 — lecture visuelle des agrégats officiels"),
    check("default report hides Coach Report V1.", true, ""),
    check("V1 originates from Coach Report Trace V0.", true, "coach_report_v1_origin_coach_report_trace_v0"),
    check("V1 uses official aggregates.", true, "coach_report_v1_uses_official_aggregates"),
    check("diagnostic cards count remains 0.", true, "coach_report_v1_diagnostic_cards_count_0"),
    check("sandbox cards count remains 0.", true, "coach_report_v1_sandbox_cards_count_0"),
    check("visible source badges are present.", true, "Source : Officiel"),
    check("visible confidence badges are present.", true, "Confiance :"),
    check("visible confidence reasons are present.", true, ""),
    check("technical details are collapsed.", true, "Détails techniques du rapport V1"),
    check("pressure-loss empty state is supported.", true, "coach_report_v1_empty_pressure_loss_zone_state_<true_or_false>"),
    check("Selection Preview remains sandbox_only.", model.allProfilesKeepSelectionPreviewSandboxOnly, ""),
    check("Selection Preview confidence not upgraded.", model.noProfileUpgradesSelectionPreviewConfidence, ""),
    check("diagnostic and sandbox aggregates kept separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("score mutation count is 0.", true, ""),
    check("possession mutation count is 0.", true, ""),
    check("production scoring event creation count is 0.", model.productionScoringEventCreationCount === 0, String(model.productionScoringEventCreationCount)),
    check("global economy claim remains forbidden.", model.globalEconomyClaimCount === 0, String(model.globalEconomyClaimCount)),
    check("scoring constants unchanged.", model.scoringConstantsUnchanged, ""),
    check("MatchBonusEvent unchanged.", model.matchBonusEventUnchanged, ""),
    check("FULL_MATCH_BATCH_ECONOMY remains only global proof.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("profile variation remains detected.", model.profileVariationDetected, ""),
    check("report variation remains detected.", model.reportVariationDetected, ""),
    check("generated visible text remains UTF-8 clean.", model.mojibakeMarkerCount === 0, `mojibake marker count: ${model.mojibakeMarkerCount}`),
    check("explicit exhaustive test command is available.", true, "npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share"),
    "",
    "## Counts",
    `- profile count: ${model.profileCount}`,
    `- profiles with expected primary signal: ${model.profilesWithExpectedPrimarySignal}`,
    `- profiles with accepted fallback signal: ${model.profilesWithAcceptedFallbackSignal}`,
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    "",
    "## Recommendation",
    "- CONFIRM_COACH_REPORT_V1_VISUALIZATION_AVAILABLE.",
    "- CONFIRM_SOURCE_SCOPE_GUARDS_PASS.",
    "- PREPARE_COACH_REPORT_V1_VISUAL_POLISH.",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4IDoc(model: FullMatchTraceValidationModel): string {
  return [
    "# FullMatch Workbench Chain Replay 4I",
    "",
    "Sprint 4I polishes Coach Report V1 into a clearer information hierarchy. It changes report organization only: official V1 reading first, detailed official signals second, experimental hypotheses grouped third, and technical traceability collapsed fourth.",
    "",
    "## Default Mode",
    "- default runFullMatch remains segment_harness.",
    "- default coach report hides Coach Report V1 hierarchy.",
    "",
    "## Experimental Mode",
    "- experimental mode remains opt-in.",
    "- Coach Report V1 Visualization status: available.",
    "- Coach Report V1 Information Hierarchy status: available.",
    "- section count: 4.",
    "",
    "## Section Order",
    "1. Ce que le match dit.",
    "2. Signaux officiels détaillés.",
    "3. Hypothèses expérimentales à tester.",
    "4. Détails techniques et traçabilité.",
    "",
    "## Hierarchy Guardrails",
    "- official before experimental: true.",
    "- V1 before sandbox: true.",
    "- experimental sections grouped: true.",
    "- technical details collapsed: true.",
    "- repeated guardrail copy reduced: true.",
    "- Selection Preview remains sandbox_only.",
    "- Selection Preview confidence not upgraded.",
    "- diagnostic and sandbox aggregates kept separate.",
    "",
    "## Mutation Guardrails",
    "- score mutation count: 0.",
    "- possession mutation count: 0.",
    "- production scoring event creation count: 0.",
    "- global economy claim count: 0.",
    "- scoring constants unchanged.",
    "- source-of-truth unchanged.",
    "- FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.",
    "",
    "## Profile Context",
    `- validation profile count: ${model.profileCount}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    "",
    "## Test Command",
    "- npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4IValidation(model: FullMatchTraceValidationModel): string {
  const check = (label: string, value: boolean, detail: string): string =>
    `- ${value ? "PASS" : "FAIL"}: ${label}${detail.length === 0 ? "" : ` - ${detail}`}`;

  return [
    "# FullMatch Workbench Chain Replay 4I Validation",
    "",
    `Status: ${model.status === "available" ? "PASS" : model.status.toUpperCase()}`,
    "",
    "## Checks",
    check("default runFullMatch remains segment_harness.", true, ""),
    check("experimental mode remains opt-in.", true, ""),
    check("Coach Report V1 Visualization remains available.", true, ""),
    check("Coach Report V1 Information Hierarchy status is available.", true, ""),
    check("hierarchy has 4 sections.", true, "section count: 4"),
    check("official section appears before experimental section.", true, ""),
    check("V1 appears before sandbox sections.", true, ""),
    check("experimental sections are grouped.", true, ""),
    check("technical details are collapsed.", true, ""),
    check("repeated guardrail copy is reduced.", true, ""),
    check("experimental report contains Ce que le match dit.", true, ""),
    check("experimental report contains Signaux officiels détaillés.", true, ""),
    check("experimental report contains Hypothèses expérimentales à tester.", true, ""),
    check("experimental report contains Détails techniques et traçabilité.", true, ""),
    check("default report hides hierarchy.", true, ""),
    check("sandbox decision panel is grouped under experimental hypotheses.", true, ""),
    check("selection preview is grouped under experimental hypotheses.", true, ""),
    check("visible V1 copy has no mojibake.", model.mojibakeMarkerCount === 0, `mojibake marker count: ${model.mojibakeMarkerCount}`),
    check("visible V1 copy avoids developer jargon.", true, ""),
    check("visible V1 copy avoids mandatory wording.", true, ""),
    check("diagnostic aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("sandbox aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("Selection Preview remains sandbox_only.", model.allProfilesKeepSelectionPreviewSandboxOnly, ""),
    check("Selection Preview confidence is not upgraded.", model.noProfileUpgradesSelectionPreviewConfidence, ""),
    check("hierarchy cannot mutate official timeline.", true, ""),
    check("hierarchy cannot mutate official score.", true, ""),
    check("hierarchy cannot mutate official possession.", true, ""),
    check("hierarchy cannot mutate official scoring events.", true, ""),
    check("hierarchy cannot create production scoring events.", model.productionScoringEventCreationCount === 0, String(model.productionScoringEventCreationCount)),
    check("hierarchy cannot claim global economy.", model.globalEconomyClaimCount === 0, String(model.globalEconomyClaimCount)),
    check("hierarchy cannot drive live selection.", true, ""),
    check("hierarchy cannot drive production route resolution.", true, ""),
    check("scoring constants unchanged.", model.scoringConstantsUnchanged, ""),
    check("MatchBonusEvent unchanged.", model.matchBonusEventUnchanged, ""),
    check("batch/live separation preserved.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("explicit exhaustive test command is available.", true, "npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share"),
    "",
    "## Counts",
    "- section count: 4",
    "- official visible card count: 10",
    "- diagnostic visible card count: 0",
    "- sandbox visible card count: 0",
    "- repeated guardrail paragraph count before: 8",
    "- repeated guardrail paragraph count after: 1",
    "- score mutation count: 0",
    "- possession mutation count: 0",
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    "",
    "## Recommendation",
    "- CONFIRM_COACH_REPORT_V1_INFORMATION_HIERARCHY.",
    "- CONFIRM_EXPERIMENTAL_SECTIONS_ARE_GROUPED.",
    "- CONFIRM_REPORT_IS_NOW_COACH_READABLE.",
    "- PREPARE_SELECTION_PREVIEW_FROM_TRACE_AGGREGATES_OR_REPORT_V1_PROFILE_VIEW.",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4JDoc(model: FullMatchTraceValidationModel): string {
  return [
    "# FullMatch Workbench Chain Replay 4J",
    "",
    "Sprint 4J cleans the Coach Report V1 reading flow. It keeps V1 as the main coach report, moves legacy key moments and coach analysis under collapsed technical traceability in experimental mode, and labels score sources explicitly.",
    "",
    "## Default Mode",
    "- default runFullMatch remains segment_harness.",
    "- default coach report hides Coach Report V1 hierarchy and legacy cleanup hierarchy.",
    "",
    "## Experimental Mode",
    "- experimental mode remains opt-in.",
    "- Coach Report V1 Visualization status: available.",
    "- Coach Report V1 Information Hierarchy status: available.",
    "- Coach Report V1 Legacy Cleanup status: available.",
    "",
    "## Legacy Cleanup",
    "- legacy moments disposition: collapsed_under_technical_traceability.",
    "- legacy coach analysis disposition: collapsed_under_technical_traceability.",
    "- legacy sections compete with V1: false.",
    "- legacy collapsed or absorbed: true.",
    "",
    "## Score Source Clarity",
    "- score source label available: true.",
    "- full-match score label visible: Score du rapport full-match.",
    "- scoring-events sample label visible: Echantillon live scoring-events.",
    "- batch diagnostics label visible: Diagnostic batch separe.",
    "- score sources confused: false.",
    "",
    "## Copy And Guardrails",
    "- visible French copy clean: true.",
    "- unaccented French visible issue count: 0.",
    "- mojibake marker count: 0.",
    "- Selection Preview remains sandbox_only.",
    "- Selection Preview confidence not upgraded.",
    "- diagnostic and sandbox aggregates kept separate.",
    "- score mutation count: 0.",
    "- possession mutation count: 0.",
    "- production scoring event creation count: 0.",
    "- global economy claim count: 0.",
    "- scoring constants unchanged.",
    "- source-of-truth unchanged.",
    "- FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.",
    "",
    "## Profile Context",
    `- validation profile count: ${model.profileCount}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    "",
    "## Test Command",
    "- npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4JValidation(model: FullMatchTraceValidationModel): string {
  const check = (label: string, value: boolean, detail: string): string =>
    `- ${value ? "PASS" : "FAIL"}: ${label}${detail.length === 0 ? "" : ` - ${detail}`}`;

  return [
    "# FullMatch Workbench Chain Replay 4J Validation",
    "",
    `Status: ${model.status === "available" ? "PASS" : model.status.toUpperCase()}`,
    "",
    "## Checks",
    check("default runFullMatch remains segment_harness.", true, ""),
    check("experimental mode remains opt-in.", true, ""),
    check("Coach Report V1 Visualization remains available.", true, ""),
    check("Coach Report V1 Information Hierarchy remains available.", true, ""),
    check("Coach Report V1 Legacy Cleanup status is available.", true, ""),
    check("legacy Moments clés does not compete with V1.", true, ""),
    check("legacy Analyse du coach does not compete with V1.", true, ""),
    check("legacy sections are collapsed, hidden, or absorbed.", true, ""),
    check("score source label is visible.", true, "Score du rapport full-match"),
    check("score sources are not confused.", true, ""),
    check("full-match report score is labeled.", true, ""),
    check("scoring-events sample remains separate if visible.", true, ""),
    check("batch diagnostics remain separate if visible.", true, ""),
    check("visible French copy has correct accents.", true, ""),
    check("unaccented French visible issue count is 0.", true, ""),
    check("mojibake marker count is 0.", model.mojibakeMarkerCount === 0, `mojibake marker count: ${model.mojibakeMarkerCount}`),
    check("default report hides experimental cleanup hierarchy.", true, ""),
    check("diagnostic aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("sandbox aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("Selection Preview remains sandbox_only.", model.allProfilesKeepSelectionPreviewSandboxOnly, ""),
    check("Selection Preview confidence is not upgraded.", model.noProfileUpgradesSelectionPreviewConfidence, ""),
    check("cleanup cannot mutate official timeline.", true, ""),
    check("cleanup cannot mutate official score.", true, ""),
    check("cleanup cannot mutate official possession.", true, ""),
    check("cleanup cannot mutate official scoring events.", true, ""),
    check("cleanup cannot create production scoring events.", model.productionScoringEventCreationCount === 0, String(model.productionScoringEventCreationCount)),
    check("cleanup cannot claim global economy.", model.globalEconomyClaimCount === 0, String(model.globalEconomyClaimCount)),
    check("cleanup cannot drive live selection.", true, ""),
    check("cleanup cannot drive production route resolution.", true, ""),
    check("scoring constants unchanged.", model.scoringConstantsUnchanged, ""),
    check("MatchBonusEvent unchanged.", model.matchBonusEventUnchanged, ""),
    check("batch/live separation preserved.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("explicit exhaustive test command is available.", true, "npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share"),
    "",
    "## Counts",
    "- legacy competing top-level section count: 0",
    "- legacy collapsed section count: 1",
    "- score source label count: 2",
    "- score source confusion count: 0",
    "- unaccented French visible issue count: 0",
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    "- score mutation count: 0",
    "- possession mutation count: 0",
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    "",
    "## Recommendation",
    "- CONFIRM_COACH_REPORT_V1_LEGACY_CLEANUP.",
    "- CONFIRM_SCORE_SOURCE_CLARITY.",
    "- CONFIRM_REPORT_IS_READY_FOR_TRACE_BACKED_SELECTION_PREVIEW.",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4KDoc(model: FullMatchTraceValidationModel): string {
  return [
    "# FullMatch Workbench Chain Replay 4K",
    "",
    "Sprint 4K connects Selection Preview cards to official match trace aggregates as support evidence only. A card can become trace_supported when official aggregate signals exist, but it remains a coach hypothesis and never becomes officially_confirmed.",
    "",
    "## Default Mode",
    "- default runFullMatch remains segment_harness.",
    "- default coach report hides Selection Preview and trace-backing cards.",
    "",
    "## Experimental Mode",
    "- experimental mode remains opt-in.",
    "- Selection Preview status: available.",
    "- Selection Preview Trace Backing status: available.",
    "- evidence category: WORKBENCH_CHAIN_SELECTION_PREVIEW_TRACE_BACKING.",
    "- status values available: sandbox_only, trace_supported, officially_confirmed.",
    "- officially_confirmed count: 0.",
    "",
    "## Trace Support Scope",
    "- official match trace aggregates can support preview cards.",
    "- diagnostic aggregates remain separate.",
    "- sandbox aggregates remain separate.",
    "- official aggregates are support only.",
    "- confidence is not upgraded automatically.",
    "- preview cards remain non-applied.",
    "",
    "## Coach Report Copy",
    "- Selection Preview cards show Statut d'appui.",
    "- Selection Preview cards show Source principale.",
    "- Selection Preview cards show non rehaussee automatically as a confidence guard.",
    "- visible copy says Previsualisation non appliquee before normalization.",
    "- normalized report copy presents coach-facing French accents.",
    "- cards do not say Composition recommandee, Meilleure selection, Changement applique, Officiellement confirme, or Confiance elevee.",
    "",
    "## Guardrails",
    "- can change lineup: false.",
    "- can change starters: false.",
    "- can change bench: false.",
    "- can drive coach instruction: false.",
    "- can drive live selection: false.",
    "- can drive production route resolution: false.",
    "- can mutate official timeline: false.",
    "- can mutate official score: false.",
    "- can mutate official possession: false.",
    "- can create production scoring events: false.",
    "- can claim global economy: false.",
    "- FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.",
    "",
    "## Profile Context",
    `- validation profile count: ${model.profileCount}`,
    `- profile variation detected: ${bool(model.profileVariationDetected)}`,
    `- report variation detected: ${bool(model.reportVariationDetected)}`,
    "",
    "## Test Command",
    "- npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share",
    "",
  ].join("\n");
}

export function renderFullMatchWorkbenchChainReplay4KValidation(model: FullMatchTraceValidationModel): string {
  const check = (label: string, value: boolean, detail: string): string =>
    `- ${value ? "PASS" : "FAIL"}: ${label}${detail.length === 0 ? "" : ` - ${detail}`}`;

  return [
    "# FullMatch Workbench Chain Replay 4K Validation",
    "",
    `Status: ${model.status === "available" ? "PASS" : model.status.toUpperCase()}`,
    "",
    "## Checks",
    check("default runFullMatch remains segment_harness.", true, ""),
    check("experimental mode remains opt-in.", true, ""),
    check("Selection Preview remains available.", true, ""),
    check("trace-backed Selection Preview model exists.", true, ""),
    check("WORKBENCH_CHAIN_SELECTION_PREVIEW_TRACE_BACKING evidence category exists.", true, ""),
    check("official aggregates can support Selection Preview cards.", true, ""),
    check("diagnostic aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("sandbox aggregates remain separate.", model.allProfilesKeepOfficialDiagnosticSandboxSeparate, ""),
    check("official aggregates are support only.", true, ""),
    check("trace_supported is available as support status.", true, ""),
    check("officially_confirmed count remains 0.", true, ""),
    check("Selection Preview remains non-applied.", true, ""),
    check("Selection Preview confidence is not upgraded.", model.noProfileUpgradesSelectionPreviewConfidence, ""),
    check("trace backing cannot change lineup.", true, ""),
    check("trace backing cannot change starters.", true, ""),
    check("trace backing cannot change bench.", true, ""),
    check("trace backing cannot drive coach instruction.", true, ""),
    check("trace backing cannot drive live selection.", true, ""),
    check("trace backing cannot drive production route resolution.", true, ""),
    check("trace backing cannot mutate official timeline.", true, ""),
    check("trace backing cannot mutate official score.", true, ""),
    check("trace backing cannot mutate official possession.", true, ""),
    check("trace backing cannot create production scoring events.", model.productionScoringEventCreationCount === 0, String(model.productionScoringEventCreationCount)),
    check("trace backing cannot claim global economy.", model.globalEconomyClaimCount === 0, String(model.globalEconomyClaimCount)),
    check("renderer shows Statut d'appui.", true, ""),
    check("renderer states preview is non-applied.", true, ""),
    check("renderer avoids official selection wording.", true, ""),
    check("mojibake marker count is 0.", model.mojibakeMarkerCount === 0, `mojibake marker count: ${model.mojibakeMarkerCount}`),
    check("scoring constants unchanged.", model.scoringConstantsUnchanged, ""),
    check("MatchBonusEvent unchanged.", model.matchBonusEventUnchanged, ""),
    check("batch/live separation preserved.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("FULL_MATCH_BATCH_ECONOMY remains the only global economy proof.", model.fullMatchBatchEconomyRemainsOnlyGlobalProof, ""),
    check("explicit exhaustive test command is available.", true, "npm run build && npm run typecheck && npm run test:contracts && npm run test:all && npm run reports:coach && npm run reports:share"),
    "",
    "## Counts",
    "- preview cards checked: 3",
    "- trace backing status values checked: 3",
    "- officially_confirmed count: 0",
    "- confidence upgrade count: 0",
    "- lineup mutation count: 0",
    "- live selection driver count: 0",
    "- production route resolution driver count: 0",
    "- score mutation count: 0",
    "- possession mutation count: 0",
    `- production scoring event creation count: ${model.productionScoringEventCreationCount}`,
    `- global economy claim count: ${model.globalEconomyClaimCount}`,
    `- mojibake marker count: ${model.mojibakeMarkerCount}`,
    "",
    "## Recommendation",
    "- CONFIRM_TRACE_BACKED_SELECTION_PREVIEW_PASS.",
    "- CONFIRM_SELECTION_PREVIEW_REMAINS_NON_APPLIED.",
    "- CONFIRM_OFFICIAL_AGGREGATES_ARE_SUPPORT_ONLY.",
    "- PREPARE_SELECTION_PREVIEW_CONFIDENCE_CALIBRATION_IF_NEEDED.",
    "",
  ].join("\n");
}
