export type CoachReplayUXIterationWarningCode =
  | "COACH_REPLAY_UX_ITERATION_COMPLETE"
  | "REPLAY_UX_READY"
  | "REPLAY_PRIORITY_READY"
  | "REPLAY_TIMELINE_READY"
  | "REPLAY_MOMENT_CARDS_READY"
  | "REPLAY_EVIDENCE_DISCLOSURE_READY"
  | "REPLAY_MOBILE_READY"
  | "REPLAY_PRINT_READY"
  | "REPLAY_EXPORT_READY"
  | "REPLAY_NO_NEW_TRUTH_LAYER"
  | "ACTOR_MAPPING_PRESERVED"
  | "NATURAL_NARRATIVE_PRESERVED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "EXPORT_LENGTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "REPLAY_UX_MISSING"
  | "PRIORITY_BLOCK_MISSING"
  | "PRIORITY_MOMENT_COUNT_INVALID"
  | "TIMELINE_RAIL_MISSING"
  | "TIMELINE_RAIL_COUNT_INVALID"
  | "ALL_REPLAY_MOMENTS_NOT_AVAILABLE"
  | "PROOF_DETAILS_NOT_COLLAPSED"
  | "SOURCE_OF_TRUTH_NOTE_MISSING"
  | "TECHNICAL_ID_IN_MAIN_TEXT"
  | "RAW_PLAYER_ID_IN_MAIN_TEXT"
  | "RAW_EVENT_ID_IN_MAIN_TEXT"
  | "RAW_EFFECT_LABEL_IN_MAIN_TEXT"
  | "REPEATED_MECHANICAL_UX_PHRASE"
  | "ACTOR_MAPPING_REGRESSED"
  | "ROLE_DIVERSITY_REGRESSED"
  | "SUSPICIOUS_GOALKEEPER_FALLBACK_REGRESSED"
  | "FATIGUE_CONTEXT_OVERPROMOTED"
  | "MOBILE_REPLAY_LAYOUT_FAIL"
  | "PRINT_REPLAY_LAYOUT_FAIL"
  | "EXPORT_LENGTH_REGRESSED"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SANDBOX_REPLAY_PROMOTED"
  | "DIAGNOSTIC_REPLAY_PROMOTED"
  | "BATCH_REPLAY_PROMOTED"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPLAY_UX_ITERATION_PARTIAL"
  | "COACH_REPLAY_UX_ITERATION_FAIL";

export const COACH_REPLAY_UX_ITERATION_BLOCKING_WARNINGS: readonly CoachReplayUXIterationWarningCode[] = [
  "REPLAY_UX_MISSING",
  "PRIORITY_BLOCK_MISSING",
  "PRIORITY_MOMENT_COUNT_INVALID",
  "TIMELINE_RAIL_MISSING",
  "TIMELINE_RAIL_COUNT_INVALID",
  "ALL_REPLAY_MOMENTS_NOT_AVAILABLE",
  "PROOF_DETAILS_NOT_COLLAPSED",
  "SOURCE_OF_TRUTH_NOTE_MISSING",
  "TECHNICAL_ID_IN_MAIN_TEXT",
  "RAW_PLAYER_ID_IN_MAIN_TEXT",
  "RAW_EVENT_ID_IN_MAIN_TEXT",
  "RAW_EFFECT_LABEL_IN_MAIN_TEXT",
  "REPEATED_MECHANICAL_UX_PHRASE",
  "ACTOR_MAPPING_REGRESSED",
  "ROLE_DIVERSITY_REGRESSED",
  "SUSPICIOUS_GOALKEEPER_FALLBACK_REGRESSED",
  "FATIGUE_CONTEXT_OVERPROMOTED",
  "MOBILE_REPLAY_LAYOUT_FAIL",
  "PRINT_REPLAY_LAYOUT_FAIL",
  "EXPORT_LENGTH_REGRESSED",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SANDBOX_REPLAY_PROMOTED",
  "DIAGNOSTIC_REPLAY_PROMOTED",
  "BATCH_REPLAY_PROMOTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
