const MOJIBAKE_MARKERS: readonly string[] = [
  "Ãƒ",
  "Ã‚",
  "Ã¢â‚¬",
  "Ã©",
  "Ã¨",
  "Ãª",
  "Ã«",
  "Ã ",
  "Ã¢",
  "Ã®",
  "Ã´",
  "Ã¹",
  "Ã»",
  "Ã§",
  "Ã‰",
  "Â",
  "â€”",
  "â€“",
  "â€™",
  "â€œ",
  "â€",
  "â€˜",
  "â€",
];

const COACH_COPY_REPLACEMENTS: readonly [string, string][] = [
  ["GÃƒÆ’Ã‚Â©nÃƒÆ’Ã‚Â©rÃƒÆ’Ã‚Â©", "Généré"],
  ["GÃƒÂ©nÃƒÂ©rÃƒÂ©", "Généré"],
  ["GÃ©nÃ©rÃ©", "Généré"],
  ["RÃƒÆ’Ã‚Â©sumÃƒÆ’Ã‚Â©", "Résumé"],
  ["RÃƒÂ©sumÃƒÂ©", "Résumé"],
  ["RÃ©sumÃ©", "Résumé"],
  ["Moments clÃƒÆ’Ã‚Â©s", "Moments clés"],
  ["Moments clÃƒÂ©s", "Moments clés"],
  ["Moments clÃ©s", "Moments clés"],
  ["sÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â©quences", "séquences"],
  ["sÃƒÆ’Ã‚Â©quences", "séquences"],
  ["sÃƒÂ©quences", "séquences"],
  ["sÃ©quences", "séquences"],
  ["dÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â©cisives", "décisives"],
  ["dÃƒÆ’Ã‚Â©cisives", "décisives"],
  ["dÃƒÂ©cisives", "décisives"],
  ["dÃ©cisives", "décisives"],
  ["ÃƒÆ’Ã¢â‚¬Â°quipe", "Équipe"],
  ["ÃƒÆ’Ã‚â€°quipe", "Équipe"],
  ["Ãƒâ€°quipe", "Équipe"],
  ["Ã‰quipe", "Équipe"],
  ["ÃƒÆ’Ã‚Â©vÃƒÆ’Ã‚Â©nement", "événement"],
  ["ÃƒÆ’Ã‚Â©vÃƒÆ’Ã‚Â©nements", "événements"],
  ["ÃƒÂ©vÃƒÂ©nement", "événement"],
  ["ÃƒÂ©vÃƒÂ©nements", "événements"],
  ["Ã©vÃ©nement", "événement"],
  ["Ã©vÃ©nements", "événements"],
  ["ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢", "’"],
  ["ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ", "“"],
  ["ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â", "”"],
  ["Ã¢â‚¬â€", "—"],
  ["Ã¢â‚¬â€œ", "–"],
  ["Ã¢â‚¬â„¢", "’"],
  ["Ã¢â‚¬Å“", "“"],
  ["Ã¢â‚¬Â", "”"],
  ["â€”", "—"],
  ["â€“", "–"],
  ["â€™", "’"],
  ["â€œ", "“"],
  ["â€", "”"],
  ["â€˜", "‘"],
  ["ÃƒÆ’Ã‚Â©", "é"],
  ["ÃƒÆ’Ã‚Â¨", "è"],
  ["ÃƒÆ’Ã‚Âª", "ê"],
  ["ÃƒÆ’Ã‚Â«", "ë"],
  ["ÃƒÆ’Ã‚Â ", "à"],
  ["ÃƒÆ’Ã‚Â¢", "â"],
  ["ÃƒÆ’Ã‚Â®", "î"],
  ["ÃƒÆ’Ã‚Â´", "ô"],
  ["ÃƒÆ’Ã‚Â¹", "ù"],
  ["ÃƒÆ’Ã‚Â»", "û"],
  ["ÃƒÆ’Ã‚Â§", "ç"],
  ["ÃƒÆ’Ã‚â€°", "É"],
  ["ÃƒÆ’Ã¢â€šÂ¬", "À"],
  ["ÃƒÂ©", "é"],
  ["ÃƒÂ¨", "è"],
  ["ÃƒÂª", "ê"],
  ["ÃƒÂ«", "ë"],
  ["ÃƒÂ ", "à"],
  ["ÃƒÂ¢", "â"],
  ["ÃƒÂ®", "î"],
  ["ÃƒÂ´", "ô"],
  ["ÃƒÂ¹", "ù"],
  ["ÃƒÂ»", "û"],
  ["ÃƒÂ§", "ç"],
  ["Ãƒâ€°", "É"],
  ["Ã©", "é"],
  ["Ã¨", "è"],
  ["Ãª", "ê"],
  ["Ã«", "ë"],
  ["Ã ", "à"],
  ["Ã¢", "â"],
  ["Ã®", "î"],
  ["Ã´", "ô"],
  ["Ã¹", "ù"],
  ["Ã»", "û"],
  ["Ã§", "ç"],
  ["Ã‰", "É"],
  ["Ã‚Â«", "«"],
  ["Ã‚Â»", "»"],
  ["Ã‚Â ", " "],
  ["Â«", "«"],
  ["Â»", "»"],
  ["Â ", " "],
];

export function normalizeCoachFacingCopy(value: string): string {
  let normalized = value;

  for (const [from, to] of COACH_COPY_REPLACEMENTS) {
    normalized = normalized.replaceAll(from, to);
  }

  return normalized;
}

export function containsMojibake(value: string): boolean {
  return MOJIBAKE_MARKERS.some((marker) => value.includes(marker));
}

export function assertNoMojibake(value: string, context: string): void {
  if (containsMojibake(value)) {
    throw new Error(`${context} contains mojibake.`);
  }
}
