export type CoachReportSeasonlessLearningLoopObservationOutcomeTrackerWarningCode =
  | "COACH_REPORT_SEASONLESS_LEARNING_LOOP_OBSERVATION_OUTCOME_TRACKER_COMPLETE"
  | "SEASONLESS_LEARNING_LOOP_READY"
  | "OBSERVATION_OUTCOME_TRACKER_READY"
  | "TRACKER_INITIAL_STATE_PENDING"
  | "CONFIRMATION_CRITERIA_READY"
  | "DISCONFIRMATION_CRITERIA_READY"
  | "INSUFFICIENT_EVIDENCE_CRITERIA_READY"
  | "MINIMUM_EVIDENCE_RULES_READY"
  | "MANUAL_POST_MATCH_USE_READY"
  | "NO_FUTURE_OUTCOME_CLAIM"
  | "NO_SEASON_MEMORY_CREATED"
  | "NO_TEAM_STYLE_MEMORY_CREATED"
  | "NO_DATABASE_PERSISTENCE_CREATED"
  | "NO_AUTOMATIC_DECISION_CREATED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "NEXT_MATCH_OBSERVATION_PLAN_8K_PRESERVED"
  | "PRODUCT_TRACKER_VISIBLE"
  | "EXPORT_TRACKER_VISIBLE"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "NUMERIC_THRESHOLD_GUARD_PRESERVED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "SEASONLESS_LEARNING_LOOP_MISSING"
  | "OBSERVATION_OUTCOME_TRACKER_MISSING"
  | "TRACKER_CARD_COUNT_INVALID"
  | "TRACKER_CARD_NOT_PENDING"
  | "CONFIRMATION_CRITERIA_MISSING"
  | "DISCONFIRMATION_CRITERIA_MISSING"
  | "INSUFFICIENT_EVIDENCE_CRITERIA_MISSING"
  | "MINIMUM_EVIDENCE_RULE_MISSING"
  | "FUTURE_OUTCOME_CLAIM_DETECTED"
  | "FABRICATED_NEXT_MATCH_EVIDENCE"
  | "UNSUPPORTED_CONFIRMATION_DETECTED"
  | "UNSUPPORTED_DISCONFIRMATION_DETECTED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "AUTOMATIC_DECISION_CREATED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SANDBOX_LEARNING_PROMOTED"
  | "DIAGNOSTIC_LEARNING_PROMOTED"
  | "BATCH_LEARNING_PROMOTED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_SEASONLESS_LEARNING_LOOP_OBSERVATION_OUTCOME_TRACKER_PARTIAL"
  | "COACH_REPORT_SEASONLESS_LEARNING_LOOP_OBSERVATION_OUTCOME_TRACKER_FAIL";

export const COACH_REPORT_SEASONLESS_LEARNING_LOOP_8L_BLOCKING_WARNINGS: readonly CoachReportSeasonlessLearningLoopObservationOutcomeTrackerWarningCode[] = [
  "SEASONLESS_LEARNING_LOOP_MISSING",
  "OBSERVATION_OUTCOME_TRACKER_MISSING",
  "TRACKER_CARD_COUNT_INVALID",
  "TRACKER_CARD_NOT_PENDING",
  "FUTURE_OUTCOME_CLAIM_DETECTED",
  "FABRICATED_NEXT_MATCH_EVIDENCE",
  "UNSUPPORTED_CONFIRMATION_DETECTED",
  "UNSUPPORTED_DISCONFIRMATION_DETECTED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "AUTOMATIC_DECISION_CREATED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SANDBOX_LEARNING_PROMOTED",
  "DIAGNOSTIC_LEARNING_PROMOTED",
  "BATCH_LEARNING_PROMOTED",
  "PRODUCT_DECISION_LAYER_8K_REGRESSED",
  "EXPORT_DECISION_LAYER_8K_REGRESSED",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "EXPORT_COMPACT_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_UNDER_900_BOOLEAN_MISMATCH",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
