export type CoachReportMultiMatchComparisonTrendSignalsWarningCode =
  | "COACH_REPORT_MULTI_MATCH_COMPARISON_TREND_SIGNALS_COMPLETE"
  | "BASELINE_METADATA_REPAIRED"
  | "BASELINE_7A_REPAIRED"
  | "NO_UNEXPLAINED_FAIL_IN_PASS_REPORT"
  | "TEMPLATE_PLACEHOLDERS_REMOVED"
  | "TREND_SIGNALS_READY"
  | "MULTI_MATCH_COMPARISON_READY"
  | "TREND_PRUDENCE_READY"
  | "HISTORY_SCOPE_CLEAN"
  | "REPORT_SCOPE_CLEAN_PRESERVED"
  | "EXPORT_SCOPE_CLEAN_PRESERVED"
  | "MAIN_BODY_COACH_ONLY_PRESERVED"
  | "TACTICAL_MAP_CARDS_PRESERVED"
  | "VISUAL_DENSITY_CONTROLLED"
  | "EXPRESS_READ_PRESERVED"
  | "ACTION_PLAN_STILL_PROMINENT"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "BASELINE_METADATA_INCONSISTENT"
  | "BASELINE_7A_STILL_CHECK"
  | "UNEXPLAINED_FAIL_IN_PASS_REPORT"
  | "TEMPLATE_PLACEHOLDER_STILL_PRESENT"
  | "TREND_SECTION_MISSING"
  | "TOO_MANY_TREND_CARDS"
  | "TREND_CARDS_TOO_DENSE"
  | "TREND_LIMITATION_MISSING"
  | "TREND_NEXT_MATCH_CHECK_MISSING"
  | "OVERCONFIDENT_TREND_CLAIM"
  | "GLOBAL_PROOF_CLAIM_DETECTED"
  | "HISTORY_USED_AS_OFFICIAL_TRUTH"
  | "HISTORY_USED_AS_SELECTION_TRUTH"
  | "SANDBOX_TREND_IN_OFFICIAL_BODY"
  | "DATABASE_SECTIONS_IN_MAIN_BODY"
  | "PERSISTENCE_SECTIONS_IN_MAIN_BODY"
  | "CALIBRATION_HISTORY_IN_MAIN_BODY"
  | "RECORD_DUMP_VISIBLE"
  | "EXPORT_TOO_LONG"
  | "VISUAL_DENSITY_TOO_HIGH"
  | "ACTION_PLAN_NOT_PROMINENT"
  | "EXPRESS_READ_REGRESSED"
  | "TACTICAL_MAP_CARDS_REGRESSED"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "FORBIDDEN_WORDING_DETECTED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_MULTI_MATCH_TRENDS_PARTIAL"
  | "COACH_REPORT_MULTI_MATCH_TRENDS_FAIL";

export const COACH_REPORT_MULTI_MATCH_TREND_BLOCKING_WARNINGS: readonly CoachReportMultiMatchComparisonTrendSignalsWarningCode[] = [
  "UNEXPLAINED_FAIL_IN_PASS_REPORT",
  "TEMPLATE_PLACEHOLDER_STILL_PRESENT",
  "TREND_SECTION_MISSING",
  "TOO_MANY_TREND_CARDS",
  "OVERCONFIDENT_TREND_CLAIM",
  "GLOBAL_PROOF_CLAIM_DETECTED",
  "HISTORY_USED_AS_OFFICIAL_TRUTH",
  "HISTORY_USED_AS_SELECTION_TRUTH",
  "SANDBOX_TREND_IN_OFFICIAL_BODY",
  "DATABASE_SECTIONS_IN_MAIN_BODY",
  "PERSISTENCE_SECTIONS_IN_MAIN_BODY",
  "CALIBRATION_HISTORY_IN_MAIN_BODY",
  "RECORD_DUMP_VISIBLE",
  "FORBIDDEN_WORDING_DETECTED",
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
