export type CoachReportStoryFirstRecompositionWarningCode =
  | "COACH_REPORT_STORY_FIRST_RECOMPOSITION_COMPLETE"
  | "VALIDATION_CONSISTENCY_CLEANUP_READY"
  | "STATUS_WARNING_CONSISTENCY_READY"
  | "NO_FAIL_WARNING_IN_PASS_REPORT"
  | "NATURAL_REPLAY_VISIBILITY_RECONCILED"
  | "STORY_FIRST_LAYOUT_READY"
  | "REPLAY_ENTRY_POINT_READY"
  | "COACH_READ_FLOW_READY"
  | "REPORT_SECTION_ORDER_READY"
  | "ACTION_PLAN_STILL_PROMINENT"
  | "TECHNICAL_SECTIONS_DEMOTED"
  | "EVIDENCE_DISCLOSURE_READY"
  | "EXPORT_STORY_FIRST_READY"
  | "MOBILE_STORY_FIRST_READY"
  | "PRINT_STORY_FIRST_READY"
  | "NATURAL_REPLAY_CONTENT_PRESERVED"
  | "ACTOR_MAPPING_PRESERVED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "EXPORT_LENGTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "VALIDATION_CONSISTENCY_CLEANUP_MISSING"
  | "FAIL_WARNING_IN_PASS_REPORT"
  | "FAIL_TEXT_IN_PASS_VALIDATION"
  | "CONTRADICTORY_WARNING_STATE"
  | "NATURAL_REPLAY_VISIBILITY_CONTRADICTION"
  | "STORY_FIRST_LAYOUT_MISSING"
  | "REPLAY_ENTRY_POINT_MISSING"
  | "STORY_AFTER_DETAILED_SIGNALS"
  | "TECHNICAL_SECTION_BEFORE_STORY"
  | "ACTION_PLAN_TOO_LOW"
  | "SANDBOX_TOO_HIGH_IN_REPORT"
  | "PROOF_DETAILS_NOT_COLLAPSED"
  | "ACTOR_MAPPING_REGRESSED"
  | "ROLE_DIVERSITY_REGRESSED"
  | "SUSPICIOUS_GOALKEEPER_FALLBACK_REGRESSED"
  | "TECHNICAL_ID_IN_MAIN_TEXT"
  | "RAW_PLAYER_ID_IN_MAIN_TEXT"
  | "RAW_EVENT_ID_IN_MAIN_TEXT"
  | "RAW_EFFECT_LABEL_IN_MAIN_TEXT"
  | "MOBILE_STORY_LAYOUT_FAIL"
  | "PRINT_STORY_LAYOUT_FAIL"
  | "EXPORT_LENGTH_REGRESSED"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SANDBOX_STORY_PROMOTED"
  | "DIAGNOSTIC_STORY_PROMOTED"
  | "BATCH_STORY_PROMOTED"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_STORY_FIRST_RECOMPOSITION_PARTIAL"
  | "COACH_REPORT_STORY_FIRST_RECOMPOSITION_FAIL";

export const COACH_REPORT_STORY_FIRST_BLOCKING_WARNINGS: readonly CoachReportStoryFirstRecompositionWarningCode[] = [
  "VALIDATION_CONSISTENCY_CLEANUP_MISSING",
  "FAIL_WARNING_IN_PASS_REPORT",
  "FAIL_TEXT_IN_PASS_VALIDATION",
  "CONTRADICTORY_WARNING_STATE",
  "NATURAL_REPLAY_VISIBILITY_CONTRADICTION",
  "STORY_FIRST_LAYOUT_MISSING",
  "REPLAY_ENTRY_POINT_MISSING",
  "STORY_AFTER_DETAILED_SIGNALS",
  "TECHNICAL_SECTION_BEFORE_STORY",
  "ACTION_PLAN_TOO_LOW",
  "SANDBOX_TOO_HIGH_IN_REPORT",
  "PROOF_DETAILS_NOT_COLLAPSED",
  "ACTOR_MAPPING_REGRESSED",
  "ROLE_DIVERSITY_REGRESSED",
  "SUSPICIOUS_GOALKEEPER_FALLBACK_REGRESSED",
  "TECHNICAL_ID_IN_MAIN_TEXT",
  "RAW_PLAYER_ID_IN_MAIN_TEXT",
  "RAW_EVENT_ID_IN_MAIN_TEXT",
  "RAW_EFFECT_LABEL_IN_MAIN_TEXT",
  "MOBILE_STORY_LAYOUT_FAIL",
  "PRINT_STORY_LAYOUT_FAIL",
  "EXPORT_LENGTH_REGRESSED",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SANDBOX_STORY_PROMOTED",
  "DIAGNOSTIC_STORY_PROMOTED",
  "BATCH_STORY_PROMOTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
