export type CoachReportDecisionLayerNextMatchObservationPlanWarningCode =
  | "COACH_REPORT_DECISION_LAYER_NEXT_MATCH_OBSERVATION_PLAN_COMPLETE"
  | "DECISION_LAYER_READY"
  | "NEXT_MATCH_OBSERVATION_PLAN_READY"
  | "CONFIRMATION_CRITERIA_READY"
  | "DISCONFIRMATION_CRITERIA_READY"
  | "COACH_DECISION_BOUNDARIES_READY"
  | "REPLAY_DECISION_LINKS_READY"
  | "TACTICAL_MAP_DECISION_LINKS_READY"
  | "ACTION_PLAN_DECISION_LINKS_READY"
  | "DECISION_WORDING_CLEAN"
  | "PRODUCT_RAW_ID_CLEANUP_READY"
  | "EXPORT_REPLAY_WORDING_CLEANUP_READY"
  | "PRODUCT_STORY_FIRST_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "NUMERIC_THRESHOLD_GUARD_PRESERVED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "DECISION_LAYER_MISSING"
  | "NEXT_MATCH_OBSERVATION_PLAN_MISSING"
  | "DECISION_CARD_COUNT_INVALID"
  | "OBSERVATION_ITEM_COUNT_INVALID"
  | "CONFIRMATION_CRITERIA_MISSING"
  | "DISCONFIRMATION_CRITERIA_MISSING"
  | "DO_NOT_OVERINTERPRET_MISSING"
  | "DECISION_REPLAY_LINK_MISSING"
  | "DECISION_ACTION_PLAN_LINK_MISSING"
  | "DECISION_TACTICAL_MAP_LINK_MISSING"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "AUTOMATIC_LINEUP_RECOMMENDATION_DETECTED"
  | "SANDBOX_DECISION_PROMOTED"
  | "DIAGNOSTIC_DECISION_PROMOTED"
  | "BATCH_DECISION_PROMOTED"
  | "REPLAY_EXPORT_DUPLICATE_TITLE"
  | "REPLAY_EXPORT_TRUNCATED_SENTENCE"
  | "PRODUCT_RAW_ID_MAIN_TEXT_REMAINING"
  | "TECHNICAL_LABEL_IN_DECISION_LAYER"
  | "RAW_EVENT_ID_IN_MAIN_TEXT"
  | "RAW_PLAYER_ID_IN_MAIN_TEXT"
  | "RAW_EFFECT_LABEL_IN_MAIN_TEXT"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "REPLAY_8G_REGRESSED"
  | "ACTOR_MAPPING_8F_REGRESSED"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SANDBOX_STORY_PROMOTED"
  | "DIAGNOSTIC_STORY_PROMOTED"
  | "BATCH_STORY_PROMOTED"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_DECISION_LAYER_NEXT_MATCH_OBSERVATION_PLAN_PARTIAL"
  | "COACH_REPORT_DECISION_LAYER_NEXT_MATCH_OBSERVATION_PLAN_FAIL";

export const COACH_DECISION_LAYER_8K_BLOCKING_WARNINGS: readonly CoachReportDecisionLayerNextMatchObservationPlanWarningCode[] = [
  "DECISION_LAYER_MISSING",
  "NEXT_MATCH_OBSERVATION_PLAN_MISSING",
  "DECISION_CARD_COUNT_INVALID",
  "OBSERVATION_ITEM_COUNT_INVALID",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "AUTOMATIC_LINEUP_RECOMMENDATION_DETECTED",
  "SANDBOX_DECISION_PROMOTED",
  "DIAGNOSTIC_DECISION_PROMOTED",
  "BATCH_DECISION_PROMOTED",
  "EXPORT_OVER_900",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "EXPORT_COMPACT_REGRESSED",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
