export type CoachReportExportLengthTrendCountCleanupWarningCode =
  | "COACH_REPORT_EXPORT_LENGTH_TREND_COUNT_CLEANUP_COMPLETE"
  | "EXPORT_LENGTH_READY"
  | "EXPORT_NOT_TOO_LONG"
  | "EXPORT_LENGTH_REDUCED"
  | "TREND_COUNT_CONSISTENT"
  | "VALIDATION_STATUS_CONSISTENT"
  | "NO_FAIL_INSIDE_PASS_REPORT"
  | "TREND_SIGNALS_PRESERVED"
  | "REPORT_SCOPE_CLEAN_PRESERVED"
  | "EXPORT_SCOPE_CLEAN_PRESERVED"
  | "MAIN_BODY_COACH_ONLY_PRESERVED"
  | "TACTICAL_MAP_CARDS_PRESERVED"
  | "VISUAL_DENSITY_CONTROLLED"
  | "EXPRESS_READ_PRESERVED"
  | "ACTION_PLAN_STILL_PROMINENT"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "NO_NEW_NARRATIVE_LAYER"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "EXPORT_STILL_TOO_LONG"
  | "EXPORT_LENGTH_NOT_REDUCED"
  | "EXPORT_TOO_DENSE"
  | "TREND_COUNT_MISMATCH"
  | "RENDERED_TREND_COUNT_MISMATCH"
  | "VALIDATION_PASS_CONTAINS_FAIL"
  | "UNEXPLAINED_FAIL_IN_PASS_REPORT"
  | "TEAM_STYLE_MEMORY_ADDED_PREMATURELY"
  | "SEASON_NARRATIVE_ADDED_PREMATURELY"
  | "NEW_HISTORY_ENGINE_ADDED_PREMATURELY"
  | "ACTION_PLAN_NOT_PROMINENT"
  | "EXPRESS_READ_REGRESSED"
  | "TACTICAL_MAP_CARDS_REGRESSED"
  | "TREND_SIGNALS_REGRESSED"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "FORBIDDEN_WORDING_DETECTED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "HISTORY_USED_AS_OFFICIAL_TRUTH"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_EXPORT_LENGTH_CLEANUP_PARTIAL"
  | "COACH_REPORT_EXPORT_LENGTH_CLEANUP_FAIL";

export const COACH_REPORT_EXPORT_LENGTH_TREND_COUNT_BLOCKING_WARNINGS: readonly CoachReportExportLengthTrendCountCleanupWarningCode[] = [
  "EXPORT_STILL_TOO_LONG",
  "TREND_COUNT_MISMATCH",
  "RENDERED_TREND_COUNT_MISMATCH",
  "VALIDATION_PASS_CONTAINS_FAIL",
  "UNEXPLAINED_FAIL_IN_PASS_REPORT",
  "TEAM_STYLE_MEMORY_ADDED_PREMATURELY",
  "SEASON_NARRATIVE_ADDED_PREMATURELY",
  "NEW_HISTORY_ENGINE_ADDED_PREMATURELY",
  "FORBIDDEN_WORDING_DETECTED",
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "HISTORY_USED_AS_OFFICIAL_TRUTH",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
