export type CoachReportPhaseVisualsTacticalMapCardsWarningCode =
  | "COACH_REPORT_PHASE_VISUALS_TACTICAL_MAP_CARDS_COMPLETE"
  | "TACTICAL_MAP_CARDS_READY"
  | "PHASE_VISUALS_READY"
  | "OFFICIAL_VISUAL_CARDS_READY"
  | "VISUAL_LEGENDS_READY"
  | "VISUAL_SOURCE_BADGES_READY"
  | "VISUAL_CONFIDENCE_BADGES_READY"
  | "VISUAL_ACTION_PLAN_LINKS_READY"
  | "VISUAL_NEXT_MATCH_CHECKS_READY"
  | "VISUAL_DENSITY_CONTROLLED"
  | "EXPRESS_READ_PRESERVED"
  | "ACTION_PLAN_STILL_PROMINENT"
  | "MOBILE_VISUAL_READABILITY_READY"
  | "EXPORT_VISUAL_READABILITY_READY"
  | "EMPTY_STATE_VISUAL_USED_CORRECTLY"
  | "TECHNICAL_APPENDICES_COLLAPSED"
  | "SANDBOX_BELOW_OFFICIAL_SECTIONS"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "VISUAL_CARDS_TOO_DENSE"
  | "TOO_MANY_VISUAL_CARDS"
  | "VISUAL_DENSITY_INCREASED_TOO_MUCH"
  | "ACTION_PLAN_NOT_PROMINENT"
  | "EXPRESS_READ_REGRESSED"
  | "VISUAL_LEGEND_MISSING"
  | "VISUAL_SOURCE_BADGE_MISSING"
  | "VISUAL_CONFIDENCE_BADGE_MISSING"
  | "VISUAL_ACTION_PLAN_LINK_MISSING"
  | "VISUAL_NEXT_MATCH_CHECK_MISSING"
  | "UNSUPPORTED_VISUAL_CLAIM"
  | "OVERCONFIDENT_VISUAL_CLAIM"
  | "SANDBOX_VISUAL_IN_OFFICIAL_BODY"
  | "BATCH_AS_OFFICIAL_VISUAL"
  | "EMPTY_STATE_MISSING_FOR_UNSTABLE_SIGNAL"
  | "MOBILE_VISUAL_READABILITY_PARTIAL"
  | "EXPORT_VISUAL_READABILITY_PARTIAL"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "DUPLICATED_VISUAL_SECTIONS_DETECTED"
  | "FORBIDDEN_WORDING_DETECTED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_PHASE_VISUALS_PARTIAL"
  | "COACH_REPORT_PHASE_VISUALS_FAIL";

export const COACH_REPORT_PHASE_VISUALS_TACTICAL_MAP_BLOCKING_WARNINGS: readonly CoachReportPhaseVisualsTacticalMapCardsWarningCode[] = [
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "SANDBOX_VISUAL_IN_OFFICIAL_BODY",
  "FORBIDDEN_WORDING_DETECTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
];
