export type CoachActionPlanCardsTrainingFocusPackagingWarningCode =
  | "COACH_ACTION_PLAN_CARDS_TRAINING_FOCUS_PACKAGING_COMPLETE"
  | "ACTION_PLAN_CARDS_VISIBLE"
  | "ACTION_PLAN_CARDS_CONCRETE"
  | "TRAINING_FOCUS_PACKAGED"
  | "NEXT_MATCH_PLAN_PACKAGED"
  | "SUCCESS_INDICATORS_VISIBLE"
  | "OBSERVABLE_SIGNALS_VISIBLE"
  | "TRADEOFFS_VISIBLE"
  | "COACH_LANGUAGE_POLISHED"
  | "MECHANICAL_WORDING_REMOVED"
  | "PROFILES_TO_OBSERVE_NOT_FORCED"
  | "SELECTION_PREVIEW_NON_APPLIED_CONFIRMED"
  | "OFFICIAL_DIAGNOSTIC_SANDBOX_SEPARATION_PRESERVED"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "ACTION_CARDS_TOO_LONG"
  | "ACTION_CARDS_TOO_VAGUE"
  | "TRAINING_FOCUS_TOO_GENERIC"
  | "NEXT_MATCH_PLAN_TOO_VAGUE"
  | "SUCCESS_INDICATORS_MISSING"
  | "OBSERVABLE_SIGNALS_MISSING"
  | "TRADEOFFS_MISSING"
  | "MECHANICAL_WORDING_STILL_PRESENT"
  | "DUPLICATED_LABELS_STILL_PRESENT"
  | "UNSUPPORTED_ACTION_CARD"
  | "FORCED_SELECTION_FROM_PREVIEW"
  | "FORCED_TACTICAL_PLAN_RECOMMENDATION"
  | "SANDBOX_CARD_IN_OFFICIAL_BODY"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "FORBIDDEN_WORDING_DETECTED"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "REPORT_TOO_TECHNICAL"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_ACTION_PLAN_PACKAGING_PARTIAL"
  | "COACH_ACTION_PLAN_PACKAGING_FAIL";

export const COACH_ACTION_PLAN_PACKAGING_BLOCKING_WARNINGS: readonly CoachActionPlanCardsTrainingFocusPackagingWarningCode[] = [
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "FORCED_SELECTION_FROM_PREVIEW",
  "FORCED_TACTICAL_PLAN_RECOMMENDATION",
  "SANDBOX_CARD_IN_OFFICIAL_BODY",
  "FORBIDDEN_WORDING_DETECTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
