export type CoachInsightDepthNextMatchRecommendationsWarningCode =
  | "COACH_INSIGHT_DEPTH_NEXT_MATCH_RECOMMENDATIONS_COMPLETE"
  | "DEEP_INSIGHTS_PRESENT"
  | "INSIGHT_CAUSALITY_SUPPORTED"
  | "NEXT_MATCH_PLAN_VISIBLE"
  | "NEXT_MATCH_RECOMMENDATIONS_CONCRETE"
  | "TRADEOFFS_VISIBLE"
  | "ACTIONABLE_INSIGHTS_DEEPENED"
  | "PROFILES_TO_OBSERVE_NOT_FORCED"
  | "SELECTION_PREVIEW_NON_APPLIED_CONFIRMED"
  | "OFFICIAL_DIAGNOSTIC_SANDBOX_SEPARATION_PRESERVED"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "INSIGHTS_TOO_GENERIC"
  | "CAUSALITY_UNSUPPORTED"
  | "NEXT_MATCH_PLAN_TOO_VAGUE"
  | "TRADEOFFS_MISSING"
  | "OBSERVABLE_SIGNALS_MISSING"
  | "UNSUPPORTED_RECOMMENDATION"
  | "FORCED_SELECTION_FROM_PREVIEW"
  | "FORCED_TACTICAL_PLAN_RECOMMENDATION"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "FORBIDDEN_WORDING_DETECTED"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "REPORT_TOO_TECHNICAL"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_INSIGHT_DEPTH_PARTIAL"
  | "COACH_INSIGHT_DEPTH_FAIL";

export const COACH_INSIGHT_DEPTH_BLOCKING_WARNINGS: readonly CoachInsightDepthNextMatchRecommendationsWarningCode[] = [
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "FORCED_SELECTION_FROM_PREVIEW",
  "FORCED_TACTICAL_PLAN_RECOMMENDATION",
  "FORBIDDEN_WORDING_DETECTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "COACH_INSIGHT_DEPTH_FAIL",
];
