export type CoachReportPremiumLayoutVisualHierarchyWarningCode =
  | "COACH_REPORT_PREMIUM_LAYOUT_VISUAL_HIERARCHY_COMPLETE"
  | "PREMIUM_LAYOUT_READY"
  | "VISUAL_HIERARCHY_READY"
  | "EXPRESS_READ_VISIBLE"
  | "OFFICIAL_SCORE_ABOVE_FOLD"
  | "SOURCE_OF_TRUTH_ABOVE_FOLD"
  | "ACTION_PLAN_PROMINENT"
  | "PRIMARY_ACTION_CARD_PROMINENT"
  | "NEXT_MATCH_PLAN_VISIBLE"
  | "MOBILE_READABILITY_READY"
  | "EXPORT_PRINT_READY"
  | "TECHNICAL_APPENDICES_COLLAPSED"
  | "SANDBOX_BELOW_OFFICIAL_SECTIONS"
  | "BASELINE_METADATA_CONSISTENT"
  | "BASELINE_METADATA_CORRECTED"
  | "ROADMAP_CONSISTENCY_READY"
  | "COACH_LANGUAGE_POLISHED"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "LAYOUT_TOO_DENSE"
  | "ACTION_PLAN_NOT_PROMINENT"
  | "PRIMARY_ACTION_CARD_NOT_PROMINENT"
  | "EXPRESS_READ_MISSING"
  | "SOURCE_OF_TRUTH_NOT_PROMINENT"
  | "MOBILE_READABILITY_PARTIAL"
  | "EXPORT_PRINT_PARTIAL"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "SANDBOX_TOO_HIGH_IN_REPORT"
  | "BASELINE_METADATA_INCONSISTENT"
  | "BASELINE_METADATA_CONTRADICTION_UNRESOLVED"
  | "DUPLICATED_SECTIONS_DETECTED"
  | "MECHANICAL_WORDING_STILL_PRESENT"
  | "FORBIDDEN_WORDING_DETECTED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "FORCED_SELECTION_FROM_PREVIEW"
  | "FORCED_TACTICAL_PLAN_RECOMMENDATION"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "COACH_REPORT_PREMIUM_LAYOUT_PARTIAL"
  | "COACH_REPORT_PREMIUM_LAYOUT_FAIL";

export const COACH_REPORT_PREMIUM_LAYOUT_BLOCKING_WARNINGS: readonly CoachReportPremiumLayoutVisualHierarchyWarningCode[] = [
  "FORBIDDEN_WORDING_DETECTED",
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "FORCED_SELECTION_FROM_PREVIEW",
  "FORCED_TACTICAL_PLAN_RECOMMENDATION",
  "BASELINE_METADATA_CONTRADICTION_UNRESOLVED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
];
