export type FullMatchOfficialScoringConnectionWarningCode =
  | "OFFICIAL_SCORING_PATH_CONNECTED"
  | "OFFICIAL_SCORING_PATH_STILL_PARALLEL"
  | "SHOT_DIFFICULTY_STILL_NOT_APPLIED"
  | "ROUTE_FAMILY_COMPETITION_STILL_MISSING"
  | "AFFORDANCE_VOLUME_STILL_NOT_APPLIED"
  | "GOALKEEPER_SUPPRESSION_STILL_NOT_APPLIED"
  | "DEFENSIVE_RESISTANCE_STILL_NOT_APPLIED"
  | "REBOUND_GATE_STILL_NOT_APPLIED"
  | "FATIGUE_PRECISION_STILL_NOT_APPLIED"
  | "SEGMENT_AMPLIFICATION_STILL_HIGH"
  | "SCORE_REDUCED_BY_OFFICIAL_RESOLUTION"
  | "SCORE_STILL_EXTREME_SINGLE_RUN"
  | "GLOBAL_ECONOMY_NOT_PROVEN"
  | "FULL_MATCH_BATCH_REQUIRED";

export const FULL_MATCH_OFFICIAL_SCORING_CONNECTION_WARNING_CODES: readonly FullMatchOfficialScoringConnectionWarningCode[] = [
  "OFFICIAL_SCORING_PATH_CONNECTED",
  "OFFICIAL_SCORING_PATH_STILL_PARALLEL",
  "SHOT_DIFFICULTY_STILL_NOT_APPLIED",
  "ROUTE_FAMILY_COMPETITION_STILL_MISSING",
  "AFFORDANCE_VOLUME_STILL_NOT_APPLIED",
  "GOALKEEPER_SUPPRESSION_STILL_NOT_APPLIED",
  "DEFENSIVE_RESISTANCE_STILL_NOT_APPLIED",
  "REBOUND_GATE_STILL_NOT_APPLIED",
  "FATIGUE_PRECISION_STILL_NOT_APPLIED",
  "SEGMENT_AMPLIFICATION_STILL_HIGH",
  "SCORE_REDUCED_BY_OFFICIAL_RESOLUTION",
  "SCORE_STILL_EXTREME_SINGLE_RUN",
  "GLOBAL_ECONOMY_NOT_PROVEN",
  "FULL_MATCH_BATCH_REQUIRED",
];
