export type FullMatchCalibrationCarryoverWarningCode =
  | "FULLMATCH_NOT_USING_SHOT_DIFFICULTY_CALIBRATION"
  | "FULLMATCH_NOT_USING_SCORING_CHOICE_BALANCE"
  | "FULLMATCH_NOT_USING_AFFORDANCE_VOLUME_CONSTRAINTS"
  | "FULLMATCH_ROUTE_FAMILY_COMPETITION_MISSING"
  | "FULLMATCH_SHOT_GOAL_MONO_FAMILY"
  | "FULLMATCH_SEGMENT_AMPLIFICATION_RISK"
  | "FULLMATCH_PARALLEL_SCORING_PATH"
  | "FULLMATCH_LEGACY_SCORING_PATH"
  | "FULLMATCH_GOALKEEPER_SUPPRESSION_NOT_APPLIED"
  | "FULLMATCH_DEFENSIVE_RESISTANCE_NOT_APPLIED"
  | "FULLMATCH_FATIGUE_OFFENSIVE_PRECISION_NOT_APPLIED"
  | "FULLMATCH_DANGER_PHASE_NOT_CONNECTED"
  | "CALIBRATION_DIAGNOSTIC_ONLY"
  | "GLOBAL_ECONOMY_NOT_PROVEN";

export const FULL_MATCH_CALIBRATION_CARRYOVER_WARNING_CODES: readonly FullMatchCalibrationCarryoverWarningCode[] = [
  "FULLMATCH_NOT_USING_SHOT_DIFFICULTY_CALIBRATION",
  "FULLMATCH_NOT_USING_SCORING_CHOICE_BALANCE",
  "FULLMATCH_NOT_USING_AFFORDANCE_VOLUME_CONSTRAINTS",
  "FULLMATCH_ROUTE_FAMILY_COMPETITION_MISSING",
  "FULLMATCH_SHOT_GOAL_MONO_FAMILY",
  "FULLMATCH_SEGMENT_AMPLIFICATION_RISK",
  "FULLMATCH_PARALLEL_SCORING_PATH",
  "FULLMATCH_LEGACY_SCORING_PATH",
  "FULLMATCH_GOALKEEPER_SUPPRESSION_NOT_APPLIED",
  "FULLMATCH_DEFENSIVE_RESISTANCE_NOT_APPLIED",
  "FULLMATCH_FATIGUE_OFFENSIVE_PRECISION_NOT_APPLIED",
  "FULLMATCH_DANGER_PHASE_NOT_CONNECTED",
  "CALIBRATION_DIAGNOSTIC_ONLY",
  "GLOBAL_ECONOMY_NOT_PROVEN",
];
