export type FullMatchBatchEconomyWarningCode =
  | "FULL_MATCH_BATCH_HEALTHY"
  | "FULL_MATCH_BATCH_PARTIAL"
  | "FULL_MATCH_BATCH_FAIL"
  | "TOO_MANY_SHOT_ONLY_MATCHES"
  | "SHOT_GOAL_SHARE_TOO_HIGH"
  | "NON_SHOT_SCORING_TOO_LOW"
  | "TRY_DROP_PRESENCE_TOO_LOW"
  | "TOO_MANY_SHUTOUTS"
  | "TOO_MANY_BLOWOUTS"
  | "SCORELINE_VARIATION_LOW"
  | "SEGMENT_AMPLIFICATION_REAPPEARED"
  | "OFFICIAL_PATH_LEAKAGE"
  | "LEGACY_PATH_LEAKAGE"
  | "FALLBACK_PATH_LEAKAGE"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "PENALTY_SHOT_LEAKAGE"
  | "FULL_MATCH_BATCH_ECONOMY_CONFIRMED"
  | "FULL_MATCH_BATCH_ECONOMY_NEEDS_TARGETED_FIX";

export const FULL_MATCH_BATCH_ECONOMY_WARNING_CODES: readonly FullMatchBatchEconomyWarningCode[] = [
  "FULL_MATCH_BATCH_HEALTHY",
  "FULL_MATCH_BATCH_PARTIAL",
  "FULL_MATCH_BATCH_FAIL",
  "TOO_MANY_SHOT_ONLY_MATCHES",
  "SHOT_GOAL_SHARE_TOO_HIGH",
  "NON_SHOT_SCORING_TOO_LOW",
  "TRY_DROP_PRESENCE_TOO_LOW",
  "TOO_MANY_SHUTOUTS",
  "TOO_MANY_BLOWOUTS",
  "SCORELINE_VARIATION_LOW",
  "SEGMENT_AMPLIFICATION_REAPPEARED",
  "OFFICIAL_PATH_LEAKAGE",
  "LEGACY_PATH_LEAKAGE",
  "FALLBACK_PATH_LEAKAGE",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "PENALTY_SHOT_LEAKAGE",
  "FULL_MATCH_BATCH_ECONOMY_CONFIRMED",
  "FULL_MATCH_BATCH_ECONOMY_NEEDS_TARGETED_FIX",
];
