export type ManualReviewInputFieldContractWarningCode8U =
  | "MANUAL_REVIEW_INPUT_FIELD_CONTRACT_COMPLETE"
  | "INPUT_FIELD_CONTRACT_READY"
  | "PRODUCT_INPUT_FIELD_CONTRACT_VISIBLE"
  | "EXPORT_INPUT_FIELD_CONTRACT_VISIBLE"
  | "INPUT_FIELD_CONTRACT_USES_8T"
  | "FIELD_SECTION_COUNT_READY"
  | "FIELD_COUNT_READY"
  | "DISABLED_FIELD_COUNT_READY"
  | "NO_ACTIVE_FIELD"
  | "VALIDATION_RULES_DOCUMENTED_INACTIVE"
  | "ERROR_STATES_DOCUMENTED_INACTIVE"
  | "REFUSAL_STATES_READY"
  | "ACTIVATION_REQUIREMENTS_READY"
  | "DEFERRED_DECISIONS_VISIBLE"
  | "INPUT_FIELD_CONTRACT_MARKED_FUTURE_ONLY"
  | "INPUT_FIELD_CONTRACT_MARKED_DISABLED"
  | "INPUT_FIELD_CONTRACT_MARKED_NON_OFFICIAL"
  | "INPUT_FIELD_CONTRACT_MARKED_NOT_PERSISTED"
  | "INPUT_FIELD_CONTRACT_MARKED_NOT_APPLIED"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_CREATE_SUBMIT"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_CREATE_API"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_CREATE_BACKEND"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_CREATE_STORAGE"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_CREATE_MEMORY"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_PROMOTE_OFFICIAL_TRUTH"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_CREATE_DECISION"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_DRIVE_SELECTION"
  | "INPUT_FIELD_CONTRACT_DOES_NOT_DRIVE_TACTIC"
  | "UX_INTERACTION_CONTRACT_8T_PRESERVED"
  | "WORKFLOW_UX_SKELETON_8S_PRESERVED"
  | "WORKFLOW_READINESS_8R_PRESERVED"
  | "DECISION_GATE_8Q_PRESERVED"
  | "PREVIEW_COMPARISON_8P_PRESERVED"
  | "MANUAL_PREVIEW_8O_PRESERVED"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_METADATA_8U_VISIBLE"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "INPUT_FIELD_CONTRACT_MISSING"
  | "PRODUCT_INPUT_FIELD_CONTRACT_MISSING"
  | "EXPORT_INPUT_FIELD_CONTRACT_MISSING"
  | "FIELD_SECTION_COUNT_INVALID"
  | "FIELD_COUNT_INVALID"
  | "DISABLED_FIELD_COUNT_INVALID"
  | "ACTIVE_FIELD_DETECTED"
  | "ENABLED_INPUT_CONTROL_DETECTED"
  | "EDITABLE_TEXT_FIELD_DETECTED"
  | "ENABLED_SELECT_DETECTED"
  | "ENABLED_CHECKBOX_DETECTED"
  | "VALIDATION_RULE_COUNT_INVALID"
  | "ACTIVE_VALIDATION_RULE_DETECTED"
  | "ERROR_STATE_COUNT_INVALID"
  | "ACTIVE_ERROR_STATE_DETECTED"
  | "REFUSAL_STATE_COUNT_INVALID"
  | "ACTIVATION_REQUIREMENT_COUNT_INVALID"
  | "DEFERRED_DECISION_MISSING"
  | "FIELD_CONTRACT_FUTURE_ONLY_MARKER_MISSING"
  | "FIELD_CONTRACT_DISABLED_MARKER_MISSING"
  | "FIELD_CONTRACT_NON_OFFICIAL_MARKER_MISSING"
  | "FIELD_CONTRACT_NOT_PERSISTED_MARKER_MISSING"
  | "FIELD_CONTRACT_NOT_APPLIED_MARKER_MISSING"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "REAL_PREVIEW_GENERATION_DETECTED"
  | "EXPORT_OVER_900"
  | "EXPORT_TITLE_MISSING_8U"
  | "EXPORT_BADGE_MISSING_8U"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8T"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8S"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8R"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8Q"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "MANUAL_REVIEW_INPUT_FIELD_CONTRACT_PARTIAL"
  | "MANUAL_REVIEW_INPUT_FIELD_CONTRACT_FAIL";

export const MANUAL_REVIEW_INPUT_FIELD_CONTRACT_8U_BLOCKING_WARNINGS: readonly ManualReviewInputFieldContractWarningCode8U[] = [
  "INPUT_FIELD_CONTRACT_MISSING",
  "PRODUCT_INPUT_FIELD_CONTRACT_MISSING",
  "EXPORT_INPUT_FIELD_CONTRACT_MISSING",
  "FIELD_SECTION_COUNT_INVALID",
  "FIELD_COUNT_INVALID",
  "DISABLED_FIELD_COUNT_INVALID",
  "ACTIVE_FIELD_DETECTED",
  "ENABLED_INPUT_CONTROL_DETECTED",
  "EDITABLE_TEXT_FIELD_DETECTED",
  "ENABLED_SELECT_DETECTED",
  "ENABLED_CHECKBOX_DETECTED",
  "VALIDATION_RULE_COUNT_INVALID",
  "ACTIVE_VALIDATION_RULE_DETECTED",
  "ERROR_STATE_COUNT_INVALID",
  "ACTIVE_ERROR_STATE_DETECTED",
  "REFUSAL_STATE_COUNT_INVALID",
  "ACTIVATION_REQUIREMENT_COUNT_INVALID",
  "DEFERRED_DECISION_MISSING",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "EXPORT_OVER_900",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
];
