export type ManualReviewPreviewPayloadContractWarningCode8X =
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_CONTRACT_COMPLETE"
  | "PREVIEW_PAYLOAD_CONTRACT_READY"
  | "PRODUCT_PREVIEW_PAYLOAD_CONTRACT_VISIBLE"
  | "EXPORT_PREVIEW_PAYLOAD_CONTRACT_VISIBLE"
  | "PREVIEW_PAYLOAD_CONTRACT_USES_ACTIVATION_GUARDS_8W"
  | "PREVIEW_PAYLOAD_CONTRACT_USES_FIELD_VISUAL_READINESS_8V"
  | "PREVIEW_PAYLOAD_CONTRACT_USES_INPUT_FIELD_CONTRACT_8U"
  | "PAYLOAD_SCHEMA_DEFINED"
  | "PAYLOAD_SOURCE_MANUAL_NON_OFFICIAL"
  | "PAYLOAD_SCOPE_PREVIEW_ONLY"
  | "PAYLOAD_OFFICIAL_TRUTH_FALSE"
  | "PAYLOAD_PERSISTENCE_NONE"
  | "PAYLOAD_APPLICATION_NONE"
  | "PAYLOAD_FIELD_GROUPS_READY"
  | "PAYLOAD_OBSERVATION_ENTRIES_READY"
  | "PAYLOAD_ALLOWED_FIELDS_READY"
  | "PAYLOAD_FORBIDDEN_FIELDS_READY"
  | "PAYLOAD_VALIDATION_RULES_READY"
  | "PAYLOAD_ERROR_STATES_READY"
  | "PAYLOAD_REFUSAL_STATES_READY"
  | "PAYLOAD_BOUNDARY_GUARDS_READY"
  | "PAYLOAD_CONTRACT_DOCUMENTED_NOT_INSTANTIATED"
  | "PAYLOAD_CONTRACT_DISTINCT_FROM_CREATION"
  | "PAYLOAD_CONTRACT_DISTINCT_FROM_PREVIEW_GENERATION"
  | "NO_REAL_PAYLOAD_CREATED"
  | "NO_REAL_PAYLOAD_INSTANCE"
  | "NO_REAL_INPUT_ACTIVATED"
  | "NO_REAL_PREVIEW_GENERATED"
  | "NO_SUBMIT_CREATED"
  | "NO_API_CREATED"
  | "NO_BACKEND_CREATED"
  | "NO_STORAGE_CREATED"
  | "NO_MEMORY_CREATED"
  | "NO_OFFICIAL_TRUTH_PROMOTION"
  | "NO_AUTOMATIC_DECISION"
  | "NO_SELECTION_OR_TACTIC"
  | "PREVIEW_ACTIVATION_GUARDS_8W_PRESERVED"
  | "FIELD_VISUAL_READINESS_8V_PRESERVED"
  | "INPUT_FIELD_CONTRACT_8U_PRESERVED"
  | "UX_INTERACTION_CONTRACT_8T_PRESERVED"
  | "WORKFLOW_UX_SKELETON_8S_PRESERVED"
  | "WORKFLOW_READINESS_8R_PRESERVED"
  | "REVIEW_GATE_8Q_NEEDS_COMPLETION_PRESERVED"
  | "PREVIEW_COMPARISON_8P_PRESERVED"
  | "MANUAL_PREVIEW_8O_PRESERVED"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_METADATA_8X_VISIBLE"
  | "EXPORT_ID_CLEANED_FROM_8W"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "PREVIEW_PAYLOAD_CONTRACT_MISSING"
  | "PRODUCT_PREVIEW_PAYLOAD_CONTRACT_MISSING"
  | "EXPORT_PREVIEW_PAYLOAD_CONTRACT_MISSING"
  | "PAYLOAD_SCHEMA_MISSING"
  | "PAYLOAD_SOURCE_INVALID"
  | "PAYLOAD_SCOPE_INVALID"
  | "PAYLOAD_OFFICIAL_TRUTH_NOT_FALSE"
  | "PAYLOAD_PERSISTENCE_NOT_NONE"
  | "PAYLOAD_APPLICATION_NOT_NONE"
  | "PAYLOAD_FIELD_GROUP_COUNT_INVALID"
  | "PAYLOAD_OBSERVATION_ENTRY_COUNT_INVALID"
  | "PAYLOAD_ALLOWED_FIELDS_MISSING"
  | "PAYLOAD_FORBIDDEN_FIELDS_MISSING"
  | "PAYLOAD_VALIDATION_RULES_MISSING"
  | "ACTIVE_PAYLOAD_VALIDATION_RULE_DETECTED"
  | "PAYLOAD_ERROR_STATES_MISSING"
  | "ACTIVE_PAYLOAD_ERROR_STATE_DETECTED"
  | "PAYLOAD_REFUSAL_STATE_COUNT_INVALID"
  | "PAYLOAD_BOUNDARY_GUARD_COUNT_INVALID"
  | "PAYLOAD_CONTRACT_STATUS_INVALID"
  | "PAYLOAD_CONTRACT_STATUS_UNEXPECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "REAL_PAYLOAD_INSTANCE_DETECTED"
  | "FIELD_TO_PAYLOAD_RUNTIME_DETECTED"
  | "PAYLOAD_VALIDATION_RUNTIME_DETECTED"
  | "REAL_PREVIEW_GENERATION_DETECTED"
  | "REAL_INPUT_ACTIVATED"
  | "ACTIVE_FIELD_DETECTED"
  | "ENABLED_INPUT_CONTROL_DETECTED"
  | "ENABLED_CTA_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "DRAFT_CREATED"
  | "HISTORY_CREATED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SEASON_TREND_CLAIM_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SCORE_OR_TIMELINE_MUTATION_DETECTED"
  | "WORKFLOW_READINESS_STATUS_MASKED"
  | "REVIEW_GATE_STATUS_NOT_PRESERVED"
  | "PREVIEW_ACTIVATION_STATUS_NOT_PRESERVED"
  | "FIELD_VISUAL_CLAIMS_REAL_USE_READY"
  | "PAYLOAD_CONTRACT_CLAIMS_REAL_USE_READY"
  | "PAYLOAD_CONTRACT_CLAIMS_PAYLOAD_CREATED"
  | "PAYLOAD_CONTRACT_CLAIMS_PREVIEW_GENERATED"
  | "PRODUCT_PREVIEW_ACTIVATION_GUARDS_8W_REGRESSED"
  | "EXPORT_PREVIEW_ACTIVATION_GUARDS_8W_REGRESSED"
  | "PRODUCT_FIELD_VISUAL_READINESS_8V_REGRESSED"
  | "EXPORT_FIELD_VISUAL_READINESS_8V_REGRESSED"
  | "PRODUCT_INPUT_FIELD_CONTRACT_8U_REGRESSED"
  | "EXPORT_INPUT_FIELD_CONTRACT_8U_REGRESSED"
  | "PRODUCT_INTERACTION_CONTRACT_8T_REGRESSED"
  | "EXPORT_INTERACTION_CONTRACT_8T_REGRESSED"
  | "PRODUCT_UX_SKELETON_8S_REGRESSED"
  | "EXPORT_UX_SKELETON_8S_REGRESSED"
  | "PRODUCT_WORKFLOW_READINESS_8R_REGRESSED"
  | "EXPORT_WORKFLOW_READINESS_8R_REGRESSED"
  | "PRODUCT_DECISION_GATE_8Q_REGRESSED"
  | "EXPORT_DECISION_GATE_8Q_REGRESSED"
  | "PRODUCT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "EXPORT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "PRODUCT_PREVIEW_RENDERER_8O_REGRESSED"
  | "EXPORT_PREVIEW_RENDERER_8O_REGRESSED"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_8X"
  | "EXPORT_BADGE_MISSING_8X"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8W"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8V"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8U"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8T"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8S"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8R"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8Q"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_CONTRACT_PARTIAL"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_CONTRACT_FAIL";

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_CONTRACT_8X_BLOCKING_WARNINGS: readonly ManualReviewPreviewPayloadContractWarningCode8X[] = [
  "PREVIEW_PAYLOAD_CONTRACT_MISSING",
  "PRODUCT_PREVIEW_PAYLOAD_CONTRACT_MISSING",
  "EXPORT_PREVIEW_PAYLOAD_CONTRACT_MISSING",
  "PAYLOAD_SCHEMA_MISSING",
  "PAYLOAD_SOURCE_INVALID",
  "PAYLOAD_SCOPE_INVALID",
  "PAYLOAD_OFFICIAL_TRUTH_NOT_FALSE",
  "PAYLOAD_PERSISTENCE_NOT_NONE",
  "PAYLOAD_APPLICATION_NOT_NONE",
  "PAYLOAD_FIELD_GROUP_COUNT_INVALID",
  "PAYLOAD_OBSERVATION_ENTRY_COUNT_INVALID",
  "PAYLOAD_ALLOWED_FIELDS_MISSING",
  "PAYLOAD_FORBIDDEN_FIELDS_MISSING",
  "PAYLOAD_VALIDATION_RULES_MISSING",
  "ACTIVE_PAYLOAD_VALIDATION_RULE_DETECTED",
  "PAYLOAD_ERROR_STATES_MISSING",
  "ACTIVE_PAYLOAD_ERROR_STATE_DETECTED",
  "PAYLOAD_REFUSAL_STATE_COUNT_INVALID",
  "PAYLOAD_BOUNDARY_GUARD_COUNT_INVALID",
  "PAYLOAD_CONTRACT_STATUS_INVALID",
  "PAYLOAD_CONTRACT_STATUS_UNEXPECTED",
  "PAYLOAD_CREATION_DETECTED",
  "REAL_PAYLOAD_INSTANCE_DETECTED",
  "FIELD_TO_PAYLOAD_RUNTIME_DETECTED",
  "PAYLOAD_VALIDATION_RUNTIME_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "REAL_INPUT_ACTIVATED",
  "ACTIVE_FIELD_DETECTED",
  "ENABLED_INPUT_CONTROL_DETECTED",
  "ENABLED_CTA_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "DRAFT_CREATED",
  "HISTORY_CREATED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED",
  "WORKFLOW_READINESS_STATUS_MASKED",
  "REVIEW_GATE_STATUS_NOT_PRESERVED",
  "PREVIEW_ACTIVATION_STATUS_NOT_PRESERVED",
  "FIELD_VISUAL_CLAIMS_REAL_USE_READY",
  "PAYLOAD_CONTRACT_CLAIMS_REAL_USE_READY",
  "PAYLOAD_CONTRACT_CLAIMS_PAYLOAD_CREATED",
  "PAYLOAD_CONTRACT_CLAIMS_PREVIEW_GENERATED",
  "EXPORT_COMPACT_REGRESSED",
  "EXPORT_OVER_900",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
