export type ManualReviewExportMetadataBadgeCleanupWarningCode9D =
  | "EXPORT_METADATA_BADGE_CLEANUP_COMPLETE"
  | "EXPORT_COVER_BADGE_9D_READY"
  | "EXPORT_TITLE_9D_READY"
  | "EXPORT_MAIN_ID_9D_READY"
  | "EXPORT_CURRENT_DATA_ATTRIBUTE_9D_READY"
  | "EXPORT_COVER_BADGE_AUDIT_STRICT_READY"
  | "EXPORT_METADATA_FALSE_POSITIVE_GUARD_READY"
  | "NO_BODY_FALLBACK_FOR_COVER_BADGE"
  | "METADATA_FALSE_POSITIVES_ZERO"
  | "BASELINE_9C_PRESERVED"
  | "DETAIL_CARDS_9C_PRESERVED"
  | "NO_RUNTIME_VALIDATION"
  | "NO_PAYLOAD_READ"
  | "NO_PAYLOAD_CREATED"
  | "NO_PAYLOAD_ACCEPTED"
  | "NO_PREVIEW_GENERATED"
  | "NO_PERSISTENCE"
  | "NO_OFFICIAL_TRUTH"
  | "NO_SELECTION_OR_TACTIC"
  | "NO_SCORE_TIMELINE_MUTATION"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "SCORING_CONSTANTS_UNCHANGED"
  | "MATCH_BONUS_EVENT_UNCHANGED"
  | "EXPORT_COVER_BADGE_STALE"
  | "EXPORT_COVER_BADGE_STILL_9C"
  | "EXPORT_COVER_BADGE_STILL_9B"
  | "EXPORT_COVER_BADGE_STILL_9A"
  | "EXPORT_TITLE_STALE"
  | "EXPORT_MAIN_ID_STALE"
  | "BODY_FALLBACK_USED_FOR_COVER_BADGE"
  | "METADATA_FALSE_POSITIVE_DETECTED"
  | "BASELINE_9C_REGRESSED"
  | "DETAIL_CARDS_9C_REGRESSED"
  | "VALIDATION_RUNTIME_ACTIVE_DETECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "PAYLOAD_ACCEPTANCE_DETECTED"
  | "PREVIEW_GENERATION_DETECTED"
  | "PERSISTENCE_DETECTED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "SELECTION_OR_TACTIC_DETECTED"
  | "SCORE_OR_TIMELINE_MUTATION_DETECTED"
  | "EXPORT_OVER_900"
  | "SHARE_PACK_FAIL";

export const MANUAL_REVIEW_EXPORT_METADATA_BADGE_CLEANUP_9D_BLOCKING_WARNINGS: readonly ManualReviewExportMetadataBadgeCleanupWarningCode9D[] = [
  "EXPORT_COVER_BADGE_STALE",
  "EXPORT_COVER_BADGE_STILL_9C",
  "EXPORT_COVER_BADGE_STILL_9B",
  "EXPORT_COVER_BADGE_STILL_9A",
  "EXPORT_TITLE_STALE",
  "EXPORT_MAIN_ID_STALE",
  "BODY_FALLBACK_USED_FOR_COVER_BADGE",
  "METADATA_FALSE_POSITIVE_DETECTED",
  "BASELINE_9C_REGRESSED",
  "DETAIL_CARDS_9C_REGRESSED",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "PAYLOAD_ACCEPTANCE_DETECTED",
  "PREVIEW_GENERATION_DETECTED",
  "PERSISTENCE_DETECTED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "SELECTION_OR_TACTIC_DETECTED",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED",
  "EXPORT_OVER_900",
  "SHARE_PACK_FAIL",
];

