export type ManualReviewWorkflowUxSkeletonWarningCode8S =
  | "MANUAL_REVIEW_WORKFLOW_UX_SKELETON_COMPLETE"
  | "UX_SKELETON_READY"
  | "PRODUCT_UX_SKELETON_VISIBLE"
  | "EXPORT_UX_SKELETON_VISIBLE"
  | "UX_STEP_COUNT_READY"
  | "UX_STEPS_LINKED"
  | "UX_USES_MANUAL_FORM_8M"
  | "UX_USES_INTAKE_BOUNDARY_8N"
  | "UX_USES_PREVIEW_RENDERER_8O"
  | "UX_USES_PREVIEW_COMPARISON_8P"
  | "UX_USES_DECISION_GATE_8Q"
  | "UX_USES_WORKFLOW_READINESS_8R"
  | "UX_SHOWS_WORKFLOW_READY_FOR_PREVIEW"
  | "UX_SHOWS_REVIEW_STILL_NEEDS_COMPLETION"
  | "UX_READINESS_DISTINCT_FROM_REVIEW_GATE"
  | "DISABLED_ACTIONS_READY"
  | "NO_ENABLED_CTA"
  | "NO_SUBMIT_BUTTON"
  | "NO_BACKEND_ACTION"
  | "NO_API_CALL"
  | "UX_MARKED_SKELETON_ONLY"
  | "UX_MARKED_DEMO_ONLY"
  | "UX_MARKED_NON_OFFICIAL"
  | "UX_MARKED_NOT_PERSISTED"
  | "UX_MARKED_NOT_APPLIED"
  | "UX_DOES_NOT_CREATE_AUTOMATIC_DECISION"
  | "UX_DOES_NOT_CREATE_MEMORY"
  | "UX_DOES_NOT_DRIVE_SELECTION"
  | "UX_DOES_NOT_DRIVE_TACTICAL_INSTRUCTION"
  | "UX_DOES_NOT_PROMOTE_OFFICIAL_TRUTH"
  | "UX_DOES_NOT_MUTATE_SCORE"
  | "UX_DOES_NOT_MUTATE_TIMELINE"
  | "UX_DOES_NOT_CREATE_SCORE_CHANGE"
  | "WORKFLOW_READINESS_8R_PRESERVED"
  | "DECISION_GATE_8Q_PRESERVED"
  | "PREVIEW_COMPARISON_8P_PRESERVED"
  | "MANUAL_PREVIEW_8O_PRESERVED"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_METADATA_8S_VISIBLE"
  | "EXPORT_ID_CLEANED_FROM_8R"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "UX_SKELETON_MISSING"
  | "PRODUCT_UX_SKELETON_MISSING"
  | "EXPORT_UX_SKELETON_MISSING"
  | "UX_STEP_COUNT_INVALID"
  | "UX_STEP_MISSING"
  | "UX_STEP_LINK_MISSING"
  | "UX_STEP_LABEL_MISSING"
  | "UX_STEP_PURPOSE_MISSING"
  | "UX_STEP_INPUT_MISSING"
  | "UX_STEP_OUTPUT_MISSING"
  | "UX_STEP_GUARDRAILS_MISSING"
  | "UX_STEP_INTERACTIVE_ENABLED"
  | "ENABLED_CTA_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SEASON_TREND_CLAIM_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "WORKFLOW_READINESS_STATUS_MASKED"
  | "REVIEW_GATE_STATUS_NOT_PRESERVED"
  | "UX_CLAIMS_REAL_USE_READY"
  | "PRODUCT_WORKFLOW_READINESS_8R_REGRESSED"
  | "EXPORT_WORKFLOW_READINESS_8R_REGRESSED"
  | "PRODUCT_DECISION_GATE_8Q_REGRESSED"
  | "EXPORT_DECISION_GATE_8Q_REGRESSED"
  | "PRODUCT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "EXPORT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "PRODUCT_PREVIEW_RENDERER_8O_REGRESSED"
  | "EXPORT_PREVIEW_RENDERER_8O_REGRESSED"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_8S"
  | "EXPORT_BADGE_MISSING_8S"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8R"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8Q"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_WORKFLOW_UX_SKELETON_PARTIAL"
  | "MANUAL_REVIEW_WORKFLOW_UX_SKELETON_FAIL";

export const MANUAL_REVIEW_WORKFLOW_UX_SKELETON_8S_BLOCKING_WARNINGS: readonly ManualReviewWorkflowUxSkeletonWarningCode8S[] = [
  "UX_SKELETON_MISSING",
  "PRODUCT_UX_SKELETON_MISSING",
  "EXPORT_UX_SKELETON_MISSING",
  "UX_STEP_COUNT_INVALID",
  "UX_STEP_MISSING",
  "UX_STEP_LINK_MISSING",
  "UX_STEP_INTERACTIVE_ENABLED",
  "ENABLED_CTA_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "REAL_NEXT_MATCH_CLAIM_DETECTED",
  "ENGINE_LEARNING_CLAIM_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "WORKFLOW_READINESS_STATUS_MASKED",
  "REVIEW_GATE_STATUS_NOT_PRESERVED",
  "UX_CLAIMS_REAL_USE_READY",
  "EXPORT_OVER_900",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
];
