export type ManualPostMatchObservationReviewFormWarningCode8M =
  | "MANUAL_REVIEW_FORM_COMPLETE"
  | "MANUAL_REVIEW_FORM_PARTIAL"
  | "MANUAL_REVIEW_FORM_FAIL"
  | "PRODUCT_FORM_MISSING"
  | "EXPORT_FORM_MISSING"
  | "REVIEW_SECTION_COUNT_INVALID"
  | "REVIEW_SECTION_NOT_LINKED_TO_8L"
  | "REVIEW_SECTION_STATE_NOT_PENDING_BLANK"
  | "OUTCOME_OPTION_COUNT_INVALID"
  | "DEFAULT_CHECKED_OUTCOME_DETECTED"
  | "AUTOMATIC_OUTCOME_DETECTED"
  | "EVIDENCE_FIELD_MISSING"
  | "CONTEXT_COMPARABLE_FIELD_MISSING"
  | "COACH_NOTES_FIELD_MISSING"
  | "CAUTION_FIELD_MISSING"
  | "SUBMIT_FLOW_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "LOCAL_STORAGE_DETECTED"
  | "DATABASE_PERSISTENCE_DETECTED"
  | "FILE_PERSISTENCE_DETECTED"
  | "FUTURE_EVIDENCE_CLAIM_DETECTED"
  | "FABRICATED_EVIDENCE_DETECTED"
  | "SEASON_MEMORY_CREATED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_INSTRUCTION_DETECTED"
  | "SANDBOX_PROMOTION_DETECTED"
  | "DIAGNOSTIC_PROMOTION_DETECTED"
  | "BATCH_PROMOTION_DETECTED"
  | "BASELINE_8L_REGRESSED"
  | "BASELINE_8K_REGRESSED"
  | "BASELINE_8I_REGRESSED"
  | "SOURCE_OF_TRUTH_REGRESSED"
  | "SCORING_CONSTANT_CHANGED"
  | "MATCH_BONUS_EVENT_MUTATED"
  | "BATCH_LIVE_SEPARATION_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_METADATA_MISSING"
  | "EXPORT_TITLE_ONLY_8I"
  | "PRODUCT_SECTION_ORDER_REGRESSED"
  | "COACH_USABILITY_REGRESSED";

export const MANUAL_POST_MATCH_REVIEW_FORM_8M_BLOCKING_WARNINGS: readonly ManualPostMatchObservationReviewFormWarningCode8M[] = [
  "PRODUCT_FORM_MISSING",
  "EXPORT_FORM_MISSING",
  "REVIEW_SECTION_COUNT_INVALID",
  "REVIEW_SECTION_NOT_LINKED_TO_8L",
  "REVIEW_SECTION_STATE_NOT_PENDING_BLANK",
  "OUTCOME_OPTION_COUNT_INVALID",
  "DEFAULT_CHECKED_OUTCOME_DETECTED",
  "AUTOMATIC_OUTCOME_DETECTED",
  "EVIDENCE_FIELD_MISSING",
  "CONTEXT_COMPARABLE_FIELD_MISSING",
  "COACH_NOTES_FIELD_MISSING",
  "CAUTION_FIELD_MISSING",
  "SUBMIT_FLOW_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "LOCAL_STORAGE_DETECTED",
  "DATABASE_PERSISTENCE_DETECTED",
  "FILE_PERSISTENCE_DETECTED",
  "FUTURE_EVIDENCE_CLAIM_DETECTED",
  "FABRICATED_EVIDENCE_DETECTED",
  "SEASON_MEMORY_CREATED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_INSTRUCTION_DETECTED",
  "SANDBOX_PROMOTION_DETECTED",
  "DIAGNOSTIC_PROMOTION_DETECTED",
  "BATCH_PROMOTION_DETECTED",
  "BASELINE_8L_REGRESSED",
  "BASELINE_8K_REGRESSED",
  "BASELINE_8I_REGRESSED",
  "SOURCE_OF_TRUTH_REGRESSED",
  "SCORING_CONSTANT_CHANGED",
  "MATCH_BONUS_EVENT_MUTATED",
  "BATCH_LIVE_SEPARATION_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_UNDER_900_BOOLEAN_MISMATCH",
  "EXPORT_UNDER_800_BOOLEAN_MISMATCH",
  "EXPORT_METADATA_MISSING",
  "EXPORT_TITLE_ONLY_8I",
  "PRODUCT_SECTION_ORDER_REGRESSED",
  "COACH_USABILITY_REGRESSED",
];
