export type ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyWarningCode9E =
  | "COACH_FACING_ERROR_COPY_COMPLETE"
  | "COACH_FACING_ERROR_COPY_READY"
  | "PRODUCT_COACH_FACING_ERROR_COPY_VISIBLE"
  | "EXPORT_COACH_FACING_ERROR_COPY_VISIBLE"
  | "ERROR_COPY_USES_DETAIL_CARDS_9C"
  | "ERROR_COPY_USES_DRY_RUN_VALIDATOR_9A"
  | "ERROR_COPY_RENDERED_WITHOUT_PREVIEW_ACTIVATION"
  | "ERROR_COPY_GROUPS_READY"
  | "ERROR_COPY_MESSAGES_READY"
  | "COMPATIBLE_CASE_COPY_NOT_ACCEPTED"
  | "ERROR_COPY_COVERAGE_COMPLETE"
  | "BLOCKER_COPY_COVERAGE_COMPLETE"
  | "REFUSAL_COPY_COVERAGE_COMPLETE"
  | "BOUNDARY_COPY_COVERAGE_COMPLETE"
  | "ERROR_COPY_NO_RUNTIME_VALIDATION"
  | "ERROR_COPY_NO_REAL_PAYLOAD_READ"
  | "ERROR_COPY_NO_PAYLOAD_CREATED"
  | "ERROR_COPY_NO_PAYLOAD_ACCEPTED"
  | "ERROR_COPY_NO_REAL_PREVIEW_GENERATED"
  | "ERROR_COPY_NO_PERSISTENCE"
  | "ERROR_COPY_NO_OFFICIAL_TRUTH"
  | "ERROR_COPY_NO_SELECTION_OR_TACTIC"
  | "ERROR_COPY_NO_SCORE_TIMELINE_MUTATION"
  | "WORDING_SCORE_PUBLISHED"
  | "WORDING_SCORE_PASS_READY"
  | "WORDING_SCORE_PASS_STRONG_READY"
  | "EXPORT_METADATA_9E_VISIBLE"
  | "EXPORT_COVER_BADGE_9E_READY"
  | "EXPORT_ID_CLEANED_FROM_9D"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "SCORING_CONSTANTS_UNCHANGED"
  | "MATCH_BONUS_EVENT_UNCHANGED"
  | "COACH_FACING_ERROR_COPY_MISSING"
  | "ERROR_COPY_COUNT_INVALID"
  | "BLOCKER_COPY_COUNT_INVALID"
  | "REFUSAL_COPY_COUNT_INVALID"
  | "COMPATIBLE_CASE_COPY_ACCEPTED"
  | "PAYLOAD_ACCEPTANCE_CLAIM_DETECTED"
  | "PREVIEW_GENERATION_CLAIM_DETECTED"
  | "RUNTIME_VALIDATION_CLAIM_DETECTED"
  | "ACTION_INSTRUCTION_WORDING_DETECTED"
  | "TACTICAL_INSTRUCTION_WORDING_DETECTED"
  | "SELECTION_INSTRUCTION_WORDING_DETECTED"
  | "STORAGE_READY_CLAIM_DETECTED"
  | "SUBMIT_READY_CLAIM_DETECTED"
  | "ERROR_COPY_COVERAGE_INCOMPLETE"
  | "BLOCKER_COPY_COVERAGE_INCOMPLETE"
  | "REFUSAL_COPY_COVERAGE_INCOMPLETE"
  | "BOUNDARY_COPY_COVERAGE_INCOMPLETE"
  | "WORDING_SCORE_MISSING"
  | "WORDING_SCORE_BELOW_PASS_THRESHOLD"
  | "WORDING_SCORE_BELOW_PASS_STRONG_THRESHOLD"
  | "AMBIGUOUS_ERROR_COPY_WORDING"
  | "VALIDATION_RUNTIME_ACTIVE_DETECTED"
  | "REAL_PAYLOAD_READ_DETECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "PAYLOAD_ACCEPTANCE_DETECTED"
  | "REAL_PREVIEW_GENERATION_DETECTED"
  | "PREVIEW_ACTIVATION_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "PERSISTENCE_DETECTED"
  | "MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SCORE_OR_TIMELINE_MUTATION_DETECTED"
  | "EXPORT_OVER_900"
  | "EXPORT_OVER_800_PASS_STRONG_BLOCKED"
  | "EXPORT_TITLE_MISSING_9E"
  | "EXPORT_BADGE_MISSING_9E"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_9D"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_COACH_FACING_ERROR_COPY_PARTIAL"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_COACH_FACING_ERROR_COPY_FAIL";

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_COACH_FACING_ERROR_COPY_9E_BLOCKING_WARNINGS: readonly ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyWarningCode9E[] = [
  "COACH_FACING_ERROR_COPY_MISSING",
  "ERROR_COPY_COUNT_INVALID",
  "BLOCKER_COPY_COUNT_INVALID",
  "REFUSAL_COPY_COUNT_INVALID",
  "COMPATIBLE_CASE_COPY_ACCEPTED",
  "PAYLOAD_ACCEPTANCE_CLAIM_DETECTED",
  "PREVIEW_GENERATION_CLAIM_DETECTED",
  "RUNTIME_VALIDATION_CLAIM_DETECTED",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED",
  "REAL_PAYLOAD_READ_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "PAYLOAD_ACCEPTANCE_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "PREVIEW_ACTIVATION_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "PERSISTENCE_DETECTED",
  "MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED",
  "EXPORT_OVER_900",
  "EXPORT_TITLE_MISSING_9E",
  "EXPORT_BADGE_MISSING_9E",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_9D",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
