export type ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyExportBudgetCompactionWarningCode9F =
  | "ERROR_COPY_EXPORT_COMPACTION_COMPLETE"
  | "ERROR_COPY_EXPORT_COMPACTION_READY"
  | "PRODUCT_ERROR_COPY_DETAILS_PRESERVED"
  | "EXPORT_ERROR_COPY_COMPACT_SECTION_VISIBLE"
  | "ERROR_COPY_COUNTS_PRESERVED"
  | "ERROR_COPY_COVERAGE_PRESERVED"
  | "COMPATIBLE_CASE_NON_ACCEPTED_PRESERVED"
  | "EXPORT_KEY_MESSAGES_PRESERVED"
  | "EXPORT_NO_RUNTIME_GUARD_PRESERVED"
  | "EXPORT_NO_PAYLOAD_ACCEPTED_GUARD_PRESERVED"
  | "EXPORT_NO_PREVIEW_GUARD_PRESERVED"
  | "EXPORT_METADATA_9F_VISIBLE"
  | "EXPORT_COVER_BADGE_9F_READY"
  | "EXPORT_ID_CLEANED_FROM_9E"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "EXPORT_UNDER_760_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "SCORING_CONSTANTS_UNCHANGED"
  | "MATCH_BONUS_EVENT_UNCHANGED"
  | "EXPORT_ERROR_COPY_COMPACTION_MISSING"
  | "PRODUCT_ERROR_COPY_DETAILS_LOST"
  | "EXPORT_ERROR_COPY_SUMMARY_MISSING"
  | "ERROR_COPY_COUNTS_REGRESSED"
  | "ERROR_COPY_COVERAGE_REGRESSED"
  | "COMPATIBLE_CASE_NON_ACCEPTED_LOST"
  | "EXPORT_KEY_MESSAGES_MISSING"
  | "EXPORT_NO_RUNTIME_GUARD_MISSING"
  | "EXPORT_NO_PAYLOAD_ACCEPTED_GUARD_MISSING"
  | "EXPORT_NO_PREVIEW_GUARD_MISSING"
  | "EXPORT_OVER_900"
  | "EXPORT_OVER_800_PASS_STRONG_BLOCKED"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_760_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_9F"
  | "EXPORT_BADGE_MISSING_9F"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_9E"
  | "VALIDATION_RUNTIME_ACTIVE_DETECTED"
  | "REAL_PAYLOAD_READ_DETECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "PAYLOAD_ACCEPTANCE_DETECTED"
  | "REAL_PREVIEW_GENERATION_DETECTED"
  | "PREVIEW_ACTIVATION_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "PERSISTENCE_DETECTED"
  | "MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SCORE_OR_TIMELINE_MUTATION_DETECTED"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_COACH_FACING_ERROR_COPY_EXPORT_BUDGET_COMPACTION_PARTIAL"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_COACH_FACING_ERROR_COPY_EXPORT_BUDGET_COMPACTION_FAIL";

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_COACH_FACING_ERROR_COPY_EXPORT_BUDGET_COMPACTION_9F_BLOCKING_WARNINGS: readonly ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyExportBudgetCompactionWarningCode9F[] = [
  "EXPORT_ERROR_COPY_COMPACTION_MISSING",
  "PRODUCT_ERROR_COPY_DETAILS_LOST",
  "EXPORT_ERROR_COPY_SUMMARY_MISSING",
  "ERROR_COPY_COUNTS_REGRESSED",
  "ERROR_COPY_COVERAGE_REGRESSED",
  "COMPATIBLE_CASE_NON_ACCEPTED_LOST",
  "EXPORT_NO_RUNTIME_GUARD_MISSING",
  "EXPORT_NO_PAYLOAD_ACCEPTED_GUARD_MISSING",
  "EXPORT_NO_PREVIEW_GUARD_MISSING",
  "EXPORT_OVER_900",
  "EXPORT_TITLE_MISSING_9F",
  "EXPORT_BADGE_MISSING_9F",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_9E",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED",
  "REAL_PAYLOAD_READ_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "PAYLOAD_ACCEPTANCE_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "PREVIEW_ACTIVATION_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "PERSISTENCE_DETECTED",
  "MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];

