export type ManualReviewResultIntakeBoundaryWarningCode8N =
  | "MANUAL_REVIEW_RESULT_INTAKE_BOUNDARY_COMPLETE"
  | "MANUAL_INTAKE_CONTRACT_READY"
  | "MANUAL_INTAKE_VALIDATOR_READY"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_VISIBLE"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_VISIBLE"
  | "ACCEPTED_OUTCOME_VALUES_READY"
  | "REJECTED_OUTCOME_VALUES_READY"
  | "LINKED_OBSERVATION_IDS_REQUIRED"
  | "EVIDENCE_COUNTS_MANUAL_ONLY"
  | "NO_AUTO_CLASSIFICATION"
  | "NO_PERSISTENCE_CREATED"
  | "NO_SUBMIT_FLOW_CREATED"
  | "NO_FUTURE_EVIDENCE_CREATED"
  | "NO_OFFICIAL_TRUTH_MUTATION"
  | "NO_SCORE_MUTATION"
  | "NO_TIMELINE_MUTATION"
  | "NO_SCORING_EVENT_MUTATION"
  | "EXPORT_METADATA_CLEANED"
  | "PRODUCT_MANUAL_FORM_8M_PRESERVED"
  | "EXPORT_MANUAL_FORM_8M_PRESERVED"
  | "PRODUCT_LEARNING_LOOP_8L_PRESERVED"
  | "EXPORT_LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "MANUAL_INTAKE_CONTRACT_MISSING"
  | "MANUAL_INTAKE_VALIDATOR_MISSING"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_MISSING"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_MISSING"
  | "ACCEPTED_OUTCOME_VALUES_INVALID"
  | "REJECTED_OUTCOME_FIXTURES_INSUFFICIENT"
  | "VALID_PAYLOAD_REJECTED"
  | "INVALID_OUTCOME_ACCEPTED"
  | "INVALID_ENTRY_COUNT_ACCEPTED"
  | "UNKNOWN_LINKED_SECTION_ACCEPTED"
  | "AUTO_CLASSIFIED_ACCEPTED"
  | "OFFICIAL_TRUTH_ACCEPTED"
  | "PERSISTENCE_INTENT_ACCEPTED"
  | "SCORE_MUTATION_ACCEPTED"
  | "TIMELINE_MUTATION_ACCEPTED"
  | "SCORING_EVENT_MUTATION_ACCEPTED"
  | "SEASON_MEMORY_ACCEPTED"
  | "TEAM_STYLE_MEMORY_ACCEPTED"
  | "SELECTION_AUTOMATION_ACCEPTED"
  | "TACTICAL_INSTRUCTION_ACCEPTED"
  | "MISSING_ACKNOWLEDGEMENT_ACCEPTED"
  | "VALIDATOR_MUTATES_INPUT"
  | "VALIDATOR_PERSISTS_OUTPUT"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_SUBMIT_ACTION_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "FUTURE_RESULT_CLAIM_DETECTED"
  | "FABRICATED_NEXT_MATCH_EVIDENCE"
  | "UNSUPPORTED_CONFIRMATION_DETECTED"
  | "UNSUPPORTED_DISCONFIRMATION_DETECTED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "AUTOMATIC_DECISION_CREATED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SANDBOX_MANUAL_INTAKE_PROMOTED"
  | "DIAGNOSTIC_MANUAL_INTAKE_PROMOTED"
  | "BATCH_MANUAL_INTAKE_PROMOTED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_STILL_ONLY_8I"
  | "EXPORT_TITLE_STILL_ONLY_8M"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "EXPORT_VISIBLE_BADGE_STILL_ONLY_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_RESULT_INTAKE_BOUNDARY_PARTIAL"
  | "MANUAL_REVIEW_RESULT_INTAKE_BOUNDARY_FAIL";

export const MANUAL_REVIEW_RESULT_INTAKE_BOUNDARY_8N_BLOCKING_WARNINGS: readonly ManualReviewResultIntakeBoundaryWarningCode8N[] = [
  "MANUAL_INTAKE_CONTRACT_MISSING",
  "MANUAL_INTAKE_VALIDATOR_MISSING",
  "PRODUCT_MANUAL_INTAKE_BOUNDARY_MISSING",
  "EXPORT_MANUAL_INTAKE_BOUNDARY_MISSING",
  "ACCEPTED_OUTCOME_VALUES_INVALID",
  "VALID_PAYLOAD_REJECTED",
  "INVALID_OUTCOME_ACCEPTED",
  "INVALID_ENTRY_COUNT_ACCEPTED",
  "UNKNOWN_LINKED_SECTION_ACCEPTED",
  "AUTO_CLASSIFIED_ACCEPTED",
  "OFFICIAL_TRUTH_ACCEPTED",
  "PERSISTENCE_INTENT_ACCEPTED",
  "SCORE_MUTATION_ACCEPTED",
  "TIMELINE_MUTATION_ACCEPTED",
  "SCORING_EVENT_MUTATION_ACCEPTED",
  "SEASON_MEMORY_ACCEPTED",
  "TEAM_STYLE_MEMORY_ACCEPTED",
  "SELECTION_AUTOMATION_ACCEPTED",
  "TACTICAL_INSTRUCTION_ACCEPTED",
  "MISSING_ACKNOWLEDGEMENT_ACCEPTED",
  "VALIDATOR_MUTATES_INPUT",
  "VALIDATOR_PERSISTS_OUTPUT",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_SUBMIT_ACTION_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "FUTURE_RESULT_CLAIM_DETECTED",
  "FABRICATED_NEXT_MATCH_EVIDENCE",
  "UNSUPPORTED_CONFIRMATION_DETECTED",
  "UNSUPPORTED_DISCONFIRMATION_DETECTED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "AUTOMATIC_DECISION_CREATED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SANDBOX_MANUAL_INTAKE_PROMOTED",
  "DIAGNOSTIC_MANUAL_INTAKE_PROMOTED",
  "BATCH_MANUAL_INTAKE_PROMOTED",
  "PRODUCT_MANUAL_FORM_8M_REGRESSED",
  "EXPORT_MANUAL_FORM_8M_REGRESSED",
  "PRODUCT_LEARNING_LOOP_8L_REGRESSED",
  "EXPORT_LEARNING_LOOP_8L_REGRESSED",
  "PRODUCT_DECISION_LAYER_8K_REGRESSED",
  "EXPORT_DECISION_LAYER_8K_REGRESSED",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "EXPORT_COMPACT_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_UNDER_900_BOOLEAN_MISMATCH",
  "EXPORT_UNDER_800_BOOLEAN_MISMATCH",
  "EXPORT_TITLE_STILL_ONLY_8I",
  "EXPORT_TITLE_STILL_ONLY_8M",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I",
  "EXPORT_VISIBLE_BADGE_STILL_ONLY_8I",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
