export type ManualReviewPreviewComparisonWarningCode8P =
  | "MANUAL_REVIEW_PREVIEW_COMPARISON_COMPLETE"
  | "PREVIEW_COMPARISON_READY"
  | "PRODUCT_PREVIEW_COMPARISON_VISIBLE"
  | "EXPORT_PREVIEW_COMPARISON_VISIBLE"
  | "COMPARISON_USES_VALIDATED_8O_PREVIEW_ONLY"
  | "INVALID_PREVIEW_COMPARISON_BLOCKED"
  | "COMPARISON_USES_8K_8L_OBSERVATION_PLAN"
  | "COMPARISON_CARDS_LINKED_TO_BASELINES"
  | "COMPARISON_ANSWER_STATUS_READY"
  | "PLAN_COVERAGE_READY"
  | "COMPARISON_MARKED_DEMO_ONLY"
  | "COMPARISON_MARKED_NON_OFFICIAL"
  | "COMPARISON_MARKED_NOT_PERSISTED"
  | "COMPARISON_MARKED_NOT_APPLIED"
  | "COMPARISON_DOES_NOT_AUTO_CLASSIFY"
  | "COMPARISON_DOES_NOT_CREATE_MEMORY"
  | "COMPARISON_DOES_NOT_DRIVE_SELECTION"
  | "COMPARISON_DOES_NOT_DRIVE_TACTICAL_INSTRUCTION"
  | "COMPARISON_DOES_NOT_PROMOTE_OFFICIAL_TRUTH"
  | "COMPARISON_DOES_NOT_MUTATE_SCORE"
  | "COMPARISON_DOES_NOT_MUTATE_TIMELINE"
  | "COMPARISON_DOES_NOT_CREATE_SCORE_CHANGE"
  | "MANUAL_PREVIEW_8O_PRESERVED"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_METADATA_8P_VISIBLE"
  | "EXPORT_ID_CLEANED_FROM_8N"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "PREVIEW_COMPARISON_MISSING"
  | "PRODUCT_PREVIEW_COMPARISON_MISSING"
  | "EXPORT_PREVIEW_COMPARISON_MISSING"
  | "COMPARISON_RENDERED_WITHOUT_VALIDATED_PREVIEW"
  | "INVALID_PREVIEW_COMPARISON_RENDERED"
  | "COMPARISON_PLAN_MISSING"
  | "COMPARISON_CARD_COUNT_INVALID"
  | "COMPARISON_CARD_LINK_MISSING"
  | "ORIGINAL_QUESTION_MISSING"
  | "ORIGINAL_CRITERIA_MISSING"
  | "ANSWER_STATUS_MISSING"
  | "ANSWER_STATUS_INVALID"
  | "GAP_TO_REVIEW_MISSING"
  | "PLAN_COVERAGE_COUNT_INVALID"
  | "COMPARISON_DEMO_MARKER_MISSING"
  | "COMPARISON_NON_OFFICIAL_MARKER_MISSING"
  | "COMPARISON_NOT_PERSISTED_MARKER_MISSING"
  | "COMPARISON_NOT_APPLIED_MARKER_MISSING"
  | "COMPARISON_AUTO_CLASSIFICATION_DETECTED"
  | "COMPARISON_AUTOMATIC_DECISION_DETECTED"
  | "COMPARISON_PERSISTENCE_DETECTED"
  | "COMPARISON_APPLICATION_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "BACKEND_SUBMIT_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SEASON_TREND_CLAIM_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SANDBOX_COMPARISON_PROMOTED"
  | "DIAGNOSTIC_COMPARISON_PROMOTED"
  | "BATCH_COMPARISON_PROMOTED"
  | "PRODUCT_PREVIEW_RENDERER_8O_REGRESSED"
  | "EXPORT_PREVIEW_RENDERER_8O_REGRESSED"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_8P"
  | "EXPORT_BADGE_MISSING_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_PREVIEW_COMPARISON_PARTIAL"
  | "MANUAL_REVIEW_PREVIEW_COMPARISON_FAIL";

export const MANUAL_REVIEW_PREVIEW_COMPARISON_8P_BLOCKING_WARNINGS: readonly ManualReviewPreviewComparisonWarningCode8P[] = [
  "PREVIEW_COMPARISON_MISSING",
  "PRODUCT_PREVIEW_COMPARISON_MISSING",
  "EXPORT_PREVIEW_COMPARISON_MISSING",
  "COMPARISON_RENDERED_WITHOUT_VALIDATED_PREVIEW",
  "INVALID_PREVIEW_COMPARISON_RENDERED",
  "COMPARISON_PLAN_MISSING",
  "COMPARISON_CARD_COUNT_INVALID",
  "COMPARISON_CARD_LINK_MISSING",
  "ORIGINAL_QUESTION_MISSING",
  "ORIGINAL_CRITERIA_MISSING",
  "ANSWER_STATUS_MISSING",
  "ANSWER_STATUS_INVALID",
  "GAP_TO_REVIEW_MISSING",
  "COMPARISON_DEMO_MARKER_MISSING",
  "COMPARISON_NON_OFFICIAL_MARKER_MISSING",
  "COMPARISON_NOT_PERSISTED_MARKER_MISSING",
  "COMPARISON_NOT_APPLIED_MARKER_MISSING",
  "COMPARISON_AUTO_CLASSIFICATION_DETECTED",
  "COMPARISON_AUTOMATIC_DECISION_DETECTED",
  "COMPARISON_PERSISTENCE_DETECTED",
  "COMPARISON_APPLICATION_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "BACKEND_SUBMIT_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "REAL_NEXT_MATCH_CLAIM_DETECTED",
  "ENGINE_LEARNING_CLAIM_DETECTED",
  "SEASON_TREND_CLAIM_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SANDBOX_COMPARISON_PROMOTED",
  "DIAGNOSTIC_COMPARISON_PROMOTED",
  "BATCH_COMPARISON_PROMOTED",
  "PRODUCT_PREVIEW_RENDERER_8O_REGRESSED",
  "EXPORT_PREVIEW_RENDERER_8O_REGRESSED",
  "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED",
  "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED",
  "PRODUCT_MANUAL_FORM_8M_REGRESSED",
  "EXPORT_MANUAL_FORM_8M_REGRESSED",
  "PRODUCT_LEARNING_LOOP_8L_REGRESSED",
  "EXPORT_LEARNING_LOOP_8L_REGRESSED",
  "PRODUCT_DECISION_LAYER_8K_REGRESSED",
  "EXPORT_DECISION_LAYER_8K_REGRESSED",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "EXPORT_COMPACT_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_UNDER_900_BOOLEAN_MISMATCH",
  "EXPORT_TITLE_MISSING_8P",
  "EXPORT_BADGE_MISSING_8P",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
