export type ManualReviewPreviewRendererWarningCode8O =
  | "MANUAL_REVIEW_PREVIEW_RENDERER_COMPLETE"
  | "PREVIEW_RENDERER_READY"
  | "PREVIEW_INPUT_VALIDATION_READY"
  | "PRODUCT_PREVIEW_RENDERER_VISIBLE"
  | "EXPORT_PREVIEW_RENDERER_VISIBLE"
  | "PREVIEW_USES_VALID_PAYLOAD_ONLY"
  | "INVALID_PAYLOAD_PREVIEW_BLOCKED"
  | "PREVIEW_MARKED_NON_OFFICIAL"
  | "PREVIEW_MARKED_NOT_PERSISTED"
  | "PREVIEW_MARKED_NOT_APPLIED"
  | "PREVIEW_DOES_NOT_MUTATE_OFFICIAL_REPORT"
  | "PREVIEW_DOES_NOT_MUTATE_SCORE"
  | "PREVIEW_DOES_NOT_MUTATE_TIMELINE"
  | "PREVIEW_DOES_NOT_CREATE_SCORE_CHANGE"
  | "PREVIEW_DOES_NOT_CREATE_MEMORY"
  | "PREVIEW_DOES_NOT_AUTO_CLASSIFY"
  | "PREVIEW_DOES_NOT_DRIVE_SELECTION"
  | "PREVIEW_DOES_NOT_DRIVE_TACTICAL_INSTRUCTION"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "PREVIEW_RENDERER_MISSING"
  | "PRODUCT_PREVIEW_RENDERER_MISSING"
  | "EXPORT_PREVIEW_RENDERER_MISSING"
  | "PREVIEW_RENDERED_WITHOUT_VALIDATION"
  | "INVALID_PAYLOAD_RENDERED"
  | "PREVIEW_CARD_COUNT_INVALID"
  | "PREVIEW_CARD_LINK_MISSING"
  | "PREVIEW_NON_OFFICIAL_MARKER_MISSING"
  | "PREVIEW_NOT_PERSISTED_MARKER_MISSING"
  | "PREVIEW_NOT_APPLIED_MARKER_MISSING"
  | "PREVIEW_AUTO_CLASSIFICATION_DETECTED"
  | "PREVIEW_PERSISTENCE_DETECTED"
  | "PREVIEW_APPLICATION_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "BACKEND_SUBMIT_ACTION_DETECTED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SANDBOX_PREVIEW_PROMOTED"
  | "DIAGNOSTIC_PREVIEW_PROMOTED"
  | "BATCH_PREVIEW_PROMOTED"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_8O"
  | "EXPORT_BADGE_MISSING_8O"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_PREVIEW_RENDERER_PARTIAL"
  | "MANUAL_REVIEW_PREVIEW_RENDERER_FAIL";

export const MANUAL_REVIEW_PREVIEW_RENDERER_8O_BLOCKING_WARNINGS: readonly ManualReviewPreviewRendererWarningCode8O[] = [
  "PREVIEW_RENDERER_MISSING",
  "PRODUCT_PREVIEW_RENDERER_MISSING",
  "EXPORT_PREVIEW_RENDERER_MISSING",
  "PREVIEW_RENDERED_WITHOUT_VALIDATION",
  "INVALID_PAYLOAD_RENDERED",
  "PREVIEW_CARD_COUNT_INVALID",
  "PREVIEW_CARD_LINK_MISSING",
  "PREVIEW_NON_OFFICIAL_MARKER_MISSING",
  "PREVIEW_NOT_PERSISTED_MARKER_MISSING",
  "PREVIEW_NOT_APPLIED_MARKER_MISSING",
  "PREVIEW_AUTO_CLASSIFICATION_DETECTED",
  "PREVIEW_PERSISTENCE_DETECTED",
  "PREVIEW_APPLICATION_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "BACKEND_SUBMIT_ACTION_DETECTED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "REAL_NEXT_MATCH_CLAIM_DETECTED",
  "ENGINE_LEARNING_CLAIM_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SANDBOX_PREVIEW_PROMOTED",
  "DIAGNOSTIC_PREVIEW_PROMOTED",
  "BATCH_PREVIEW_PROMOTED",
  "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED",
  "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED",
  "PRODUCT_MANUAL_FORM_8M_REGRESSED",
  "EXPORT_MANUAL_FORM_8M_REGRESSED",
  "PRODUCT_LEARNING_LOOP_8L_REGRESSED",
  "EXPORT_LEARNING_LOOP_8L_REGRESSED",
  "PRODUCT_DECISION_LAYER_8K_REGRESSED",
  "EXPORT_DECISION_LAYER_8K_REGRESSED",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "EXPORT_COMPACT_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_UNDER_900_BOOLEAN_MISMATCH",
  "EXPORT_TITLE_MISSING_8O",
  "EXPORT_BADGE_MISSING_8O",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
