export type ManualReviewFieldUxVisualReadinessWarningCode8V =
  | "MANUAL_REVIEW_FIELD_UX_VISUAL_READINESS_COMPLETE"
  | "FIELD_UX_VISUAL_READINESS_READY"
  | "PRODUCT_FIELD_UX_VISUAL_READINESS_VISIBLE"
  | "EXPORT_FIELD_UX_VISUAL_READINESS_VISIBLE"
  | "FIELD_UX_USES_INPUT_FIELD_CONTRACT_8U"
  | "VISUAL_SECTION_COUNT_READY"
  | "VISUAL_FIELD_CARD_COUNT_READY"
  | "VISUAL_FIELD_GROUP_COUNT_READY"
  | "VISUAL_HELP_TEXT_READY"
  | "VISUAL_CONSTRAINT_BADGES_READY"
  | "VISUAL_DISABLED_BADGES_READY"
  | "VISUAL_FUTURE_ONLY_BADGES_READY"
  | "VISUAL_NON_OFFICIAL_BADGES_READY"
  | "VISUAL_NOT_PERSISTED_BADGES_READY"
  | "VISUAL_NOT_APPLIED_BADGES_READY"
  | "VISUAL_VALIDATION_RULES_READY"
  | "VISUAL_ERROR_STATES_READY"
  | "VISUAL_REFUSAL_STATES_READY"
  | "FIELD_VISUAL_READY_FOR_STATIC_REVIEW"
  | "COACH_READABILITY_READY"
  | "VISUAL_DENSITY_ACCEPTABLE"
  | "FIELD_GROUPING_COACH_READABLE"
  | "FIELD_VISUAL_MARKED_FUTURE_ONLY"
  | "FIELD_VISUAL_MARKED_DISABLED"
  | "FIELD_VISUAL_MARKED_READ_ONLY"
  | "FIELD_VISUAL_MARKED_NON_OFFICIAL"
  | "FIELD_VISUAL_MARKED_NOT_PERSISTED"
  | "FIELD_VISUAL_MARKED_NOT_APPLIED"
  | "FIELD_VISUAL_DOES_NOT_CREATE_REAL_INPUT"
  | "FIELD_VISUAL_DOES_NOT_CREATE_SUBMIT"
  | "FIELD_VISUAL_DOES_NOT_CREATE_API"
  | "FIELD_VISUAL_DOES_NOT_CREATE_BACKEND"
  | "FIELD_VISUAL_DOES_NOT_CREATE_STORAGE"
  | "FIELD_VISUAL_DOES_NOT_CREATE_PAYLOAD"
  | "FIELD_VISUAL_DOES_NOT_CREATE_REAL_PREVIEW"
  | "FIELD_VISUAL_DOES_NOT_CREATE_MEMORY"
  | "FIELD_VISUAL_DOES_NOT_PROMOTE_OFFICIAL_TRUTH"
  | "FIELD_VISUAL_DOES_NOT_CREATE_AUTOMATIC_DECISION"
  | "FIELD_VISUAL_DOES_NOT_DRIVE_SELECTION"
  | "FIELD_VISUAL_DOES_NOT_DRIVE_TACTICAL_INSTRUCTION"
  | "INPUT_FIELD_CONTRACT_8U_PRESERVED"
  | "UX_INTERACTION_CONTRACT_8T_PRESERVED"
  | "WORKFLOW_UX_SKELETON_8S_PRESERVED"
  | "WORKFLOW_READINESS_8R_PRESERVED"
  | "DECISION_GATE_8Q_PRESERVED"
  | "PREVIEW_COMPARISON_8P_PRESERVED"
  | "MANUAL_PREVIEW_8O_PRESERVED"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_METADATA_8V_VISIBLE"
  | "EXPORT_ID_CLEANED_FROM_8U"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "FIELD_UX_VISUAL_READINESS_MISSING"
  | "PRODUCT_FIELD_UX_VISUAL_READINESS_MISSING"
  | "EXPORT_FIELD_UX_VISUAL_READINESS_MISSING"
  | "VISUAL_SECTION_COUNT_INVALID"
  | "VISUAL_FIELD_CARD_COUNT_INVALID"
  | "VISUAL_FIELD_GROUP_COUNT_INVALID"
  | "VISUAL_HELP_TEXT_MISSING"
  | "VISUAL_CONSTRAINT_BADGES_MISSING"
  | "VISUAL_DISABLED_BADGES_MISSING"
  | "VISUAL_FUTURE_ONLY_BADGES_MISSING"
  | "VISUAL_NON_OFFICIAL_BADGES_MISSING"
  | "VISUAL_NOT_PERSISTED_BADGES_MISSING"
  | "VISUAL_NOT_APPLIED_BADGES_MISSING"
  | "FIELD_VISUAL_REASON_MISSING"
  | "FIELD_VISUAL_VALIDATION_SUMMARY_MISSING"
  | "FIELD_VISUAL_ERROR_SUMMARY_MISSING"
  | "FIELD_VISUAL_READINESS_STATUS_INVALID"
  | "FIELD_VISUAL_READINESS_STATUS_UNEXPECTED"
  | "COACH_READABILITY_TOO_LOW"
  | "VISUAL_DENSITY_TOO_HIGH"
  | "FIELD_GROUPING_NOT_COACH_READABLE"
  | "ACTIVE_FIELD_DETECTED"
  | "ENABLED_INPUT_CONTROL_DETECTED"
  | "EDITABLE_TEXT_FIELD_DETECTED"
  | "ENABLED_SELECT_CONTROL_DETECTED"
  | "ENABLED_CHECKBOX_CONTROL_DETECTED"
  | "ACTIVE_VALIDATION_RULE_DETECTED"
  | "ACTIVE_ERROR_STATE_DETECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "REAL_PREVIEW_GENERATION_DETECTED"
  | "ENABLED_CTA_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SEASON_TREND_CLAIM_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "WORKFLOW_READINESS_STATUS_MASKED"
  | "REVIEW_GATE_STATUS_NOT_PRESERVED"
  | "FIELD_VISUAL_CLAIMS_REAL_USE_READY"
  | "PRODUCT_INPUT_FIELD_CONTRACT_8U_REGRESSED"
  | "EXPORT_INPUT_FIELD_CONTRACT_8U_REGRESSED"
  | "PRODUCT_INTERACTION_CONTRACT_8T_REGRESSED"
  | "EXPORT_INTERACTION_CONTRACT_8T_REGRESSED"
  | "PRODUCT_UX_SKELETON_8S_REGRESSED"
  | "EXPORT_UX_SKELETON_8S_REGRESSED"
  | "PRODUCT_WORKFLOW_READINESS_8R_REGRESSED"
  | "EXPORT_WORKFLOW_READINESS_8R_REGRESSED"
  | "PRODUCT_DECISION_GATE_8Q_REGRESSED"
  | "EXPORT_DECISION_GATE_8Q_REGRESSED"
  | "PRODUCT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "EXPORT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "PRODUCT_PREVIEW_RENDERER_8O_REGRESSED"
  | "EXPORT_PREVIEW_RENDERER_8O_REGRESSED"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_8V"
  | "EXPORT_BADGE_MISSING_8V"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8U"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8T"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8S"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8R"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8Q"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_FIELD_UX_VISUAL_READINESS_PARTIAL"
  | "MANUAL_REVIEW_FIELD_UX_VISUAL_READINESS_FAIL";

export const MANUAL_REVIEW_FIELD_UX_VISUAL_READINESS_8V_BLOCKING_WARNINGS: readonly ManualReviewFieldUxVisualReadinessWarningCode8V[] = [
  "FIELD_UX_VISUAL_READINESS_MISSING",
  "PRODUCT_FIELD_UX_VISUAL_READINESS_MISSING",
  "EXPORT_FIELD_UX_VISUAL_READINESS_MISSING",
  "VISUAL_SECTION_COUNT_INVALID",
  "VISUAL_FIELD_CARD_COUNT_INVALID",
  "VISUAL_FIELD_GROUP_COUNT_INVALID",
  "FIELD_VISUAL_READINESS_STATUS_INVALID",
  "FIELD_VISUAL_READINESS_STATUS_UNEXPECTED",
  "ACTIVE_FIELD_DETECTED",
  "ENABLED_INPUT_CONTROL_DETECTED",
  "EDITABLE_TEXT_FIELD_DETECTED",
  "ENABLED_SELECT_CONTROL_DETECTED",
  "ENABLED_CHECKBOX_CONTROL_DETECTED",
  "ACTIVE_VALIDATION_RULE_DETECTED",
  "ACTIVE_ERROR_STATE_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "ENABLED_CTA_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "WORKFLOW_READINESS_STATUS_MASKED",
  "REVIEW_GATE_STATUS_NOT_PRESERVED",
  "FIELD_VISUAL_CLAIMS_REAL_USE_READY",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "EXPORT_OVER_900",
];
