export type ManualReviewPreviewPayloadDryRunProgressiveDisclosureReportingConsistencyWarningCode9K =
  | "PROGRESSIVE_DISCLOSURE_REPORTING_CONSISTENCY_READY"
  | "GROUP_VIEW_TABLE_CORRECTED"
  | "WORDING_READABILITY_SCORE_PUBLISHED"
  | "WORDING_READABILITY_PASS_STRONG"
  | "BASELINE_9J_PROGRESSIVE_DISCLOSURE_PRESERVED"
  | "BASELINE_9H_GROUPING_PRESERVED"
  | "BASELINE_9G_KEY_MESSAGES_PRESERVED"
  | "NO_RUNTIME_ACTIVATION"
  | "NO_PAYLOAD_ACCEPTED"
  | "NO_PREVIEW_GENERATED"
  | "NO_PERSISTENCE"
  | "NO_OFFICIAL_TRUTH_PROMOTION"
  | "NO_DECISION_SELECTION_TACTIC_MUTATION"
  | "NO_SCORE_OR_TIMELINE_MUTATION"
  | "SCORING_CONSTANTS_UNCHANGED"
  | "PENALTY_SHOT_INACTIVE"
  | "MATCH_BONUS_EVENT_UNCHANGED"
  | "BATCH_LIVE_SEPARATION_PRESERVED"
  | "EXPORT_BUDGET_STRONG_PASS"
  | "EXPORT_BUDGET_PASS"
  | "EXPORT_OVER_790_MARGIN_WARNING"
  | "EXPORT_OVER_800_STRONG_PASS_BLOCKED"
  | "EXPORT_OVER_900_FAIL"
  | "GROUP_VIEW_ZERO_ROW_REMAINING"
  | "GROUP_VIEW_TOTAL_MISMATCH"
  | "WORDING_READABILITY_SCORE_MISSING"
  | "WORDING_READABILITY_THRESHOLD_MISMATCH"
  | "PROGRESSIVE_DISCLOSURE_REPORTING_PARTIAL"
  | "PROGRESSIVE_DISCLOSURE_REPORTING_FAIL";

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_PROGRESSIVE_DISCLOSURE_REPORTING_9K_BLOCKING_WARNINGS: readonly ManualReviewPreviewPayloadDryRunProgressiveDisclosureReportingConsistencyWarningCode9K[] =
  [
    "EXPORT_OVER_900_FAIL",
    "GROUP_VIEW_ZERO_ROW_REMAINING",
    "GROUP_VIEW_TOTAL_MISMATCH",
    "WORDING_READABILITY_SCORE_MISSING",
    "WORDING_READABILITY_THRESHOLD_MISMATCH",
    "PROGRESSIVE_DISCLOSURE_REPORTING_FAIL",
  ];

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_PROGRESSIVE_DISCLOSURE_REPORTING_9K_NEGATIVE_WARNINGS: readonly ManualReviewPreviewPayloadDryRunProgressiveDisclosureReportingConsistencyWarningCode9K[] =
  [
    "EXPORT_OVER_790_MARGIN_WARNING",
    "EXPORT_OVER_800_STRONG_PASS_BLOCKED",
    "PROGRESSIVE_DISCLOSURE_REPORTING_PARTIAL",
  ];

export function uniqueWarningCodes9K(
  codes: readonly ManualReviewPreviewPayloadDryRunProgressiveDisclosureReportingConsistencyWarningCode9K[],
): readonly ManualReviewPreviewPayloadDryRunProgressiveDisclosureReportingConsistencyWarningCode9K[] {
  return [...new Set(codes)];
}
