export type ManualReviewPreviewPayloadDryRunExportBudgetCushionWarningCode9I =
  | "EXPORT_BUDGET_CUSHION_READY_9I"
  | "EXPORT_9H_BASELINE_PRESERVED_9I"
  | "EXPORT_UNDER_900_READY_9I"
  | "EXPORT_UNDER_800_READY_9I"
  | "EXPORT_UNDER_780_READY_9I"
  | "EXPORT_CUSHION_CREATED_9I"
  | "EXPORT_METADATA_9I_VISIBLE"
  | "EXPORT_COVER_BADGE_9I_READY"
  | "BASELINE_9H_PRESERVED"
  | "BASELINE_9G_PRESERVED"
  | "BASELINE_9F_PRESERVED"
  | "BASELINE_9E_PRESERVED"
  | "NO_RUNTIME_VALIDATION_9I"
  | "NO_PAYLOAD_READ_9I"
  | "NO_PAYLOAD_CREATED_9I"
  | "NO_PAYLOAD_ACCEPTED_9I"
  | "NO_PREVIEW_GENERATED_9I"
  | "NO_PERSISTENCE_9I"
  | "NO_OFFICIAL_TRUTH_9I"
  | "NO_DECISION_SELECTION_OR_TACTIC_9I"
  | "NO_SCORE_TIMELINE_MUTATION_9I"
  | "SOURCE_OF_TRUTH_PRESERVED_9I"
  | "SCORING_CONSTANTS_UNCHANGED_9I"
  | "MATCH_BONUS_EVENT_UNCHANGED_9I"
  | "ERROR_COPY_UX_GROUPING_PRESERVED_9I"
  | "EXPORT_KEY_MESSAGES_9G_PRESERVED_9I"
  | "WARNING_CONTRADICTION_COUNT_ZERO_9I"
  | "EXPORT_BUDGET_CUSHION_PARTIAL_9I"
  | "EXPORT_BUDGET_CUSHION_FAIL_9I"
  | "BASELINE_9H_REGRESSED"
  | "BASELINE_9G_REGRESSED"
  | "BASELINE_9F_REGRESSED"
  | "BASELINE_9E_REGRESSED"
  | "EXPORT_OVER_900_9I"
  | "EXPORT_OVER_800_PASS_STRONG_BLOCKED_9I"
  | "EXPORT_OVER_790_CRITICAL_MARGIN_9I"
  | "EXPORT_OVER_780_MARGIN_WARNING_9I"
  | "EXPORT_CUSHION_NOT_CREATED_9I"
  | "EXPORT_METADATA_9I_MISSING"
  | "EXPORT_COVER_BADGE_9I_STALE"
  | "EXPORT_9H_GROUPING_REGRESSED_9I"
  | "EXPORT_KEY_MESSAGES_9G_REGRESSED_9I"
  | "WARNING_CONTRADICTION_REINTRODUCED_9I"
  | "VALIDATION_RUNTIME_ACTIVE_DETECTED_9I"
  | "REAL_PAYLOAD_READ_DETECTED_9I"
  | "PAYLOAD_CREATION_DETECTED_9I"
  | "PAYLOAD_ACCEPTANCE_DETECTED_9I"
  | "REAL_PREVIEW_GENERATION_DETECTED_9I"
  | "PERSISTENCE_DETECTED_9I"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED_9I"
  | "DECISION_SELECTION_OR_TACTIC_DETECTED_9I"
  | "SCORE_OR_TIMELINE_MUTATION_DETECTED_9I"
  | "SOURCE_OF_TRUTH_REGRESSED_9I"
  | "SCORE_MANIPULATION_DETECTED_9I"
  | "MATCH_BONUS_EVENT_CHANGED_9I"
  | "EXPORT_READ_TIME_BOOLEAN_MISMATCH_9I";

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_EXPORT_BUDGET_CUSHION_9I_NEGATIVE_WARNINGS: readonly ManualReviewPreviewPayloadDryRunExportBudgetCushionWarningCode9I[] = [
  "EXPORT_BUDGET_CUSHION_PARTIAL_9I",
  "EXPORT_BUDGET_CUSHION_FAIL_9I",
  "BASELINE_9H_REGRESSED",
  "BASELINE_9G_REGRESSED",
  "BASELINE_9F_REGRESSED",
  "BASELINE_9E_REGRESSED",
  "EXPORT_OVER_900_9I",
  "EXPORT_OVER_800_PASS_STRONG_BLOCKED_9I",
  "EXPORT_OVER_790_CRITICAL_MARGIN_9I",
  "EXPORT_OVER_780_MARGIN_WARNING_9I",
  "EXPORT_CUSHION_NOT_CREATED_9I",
  "EXPORT_METADATA_9I_MISSING",
  "EXPORT_COVER_BADGE_9I_STALE",
  "EXPORT_9H_GROUPING_REGRESSED_9I",
  "EXPORT_KEY_MESSAGES_9G_REGRESSED_9I",
  "WARNING_CONTRADICTION_REINTRODUCED_9I",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED_9I",
  "REAL_PAYLOAD_READ_DETECTED_9I",
  "PAYLOAD_CREATION_DETECTED_9I",
  "PAYLOAD_ACCEPTANCE_DETECTED_9I",
  "REAL_PREVIEW_GENERATION_DETECTED_9I",
  "PERSISTENCE_DETECTED_9I",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED_9I",
  "DECISION_SELECTION_OR_TACTIC_DETECTED_9I",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED_9I",
  "SOURCE_OF_TRUTH_REGRESSED_9I",
  "SCORE_MANIPULATION_DETECTED_9I",
  "MATCH_BONUS_EVENT_CHANGED_9I",
  "EXPORT_READ_TIME_BOOLEAN_MISMATCH_9I",
];

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_EXPORT_BUDGET_CUSHION_9I_BLOCKING_WARNINGS: readonly ManualReviewPreviewPayloadDryRunExportBudgetCushionWarningCode9I[] = [
  "EXPORT_BUDGET_CUSHION_FAIL_9I",
  "BASELINE_9H_REGRESSED",
  "BASELINE_9G_REGRESSED",
  "BASELINE_9F_REGRESSED",
  "BASELINE_9E_REGRESSED",
  "EXPORT_OVER_900_9I",
  "EXPORT_METADATA_9I_MISSING",
  "EXPORT_9H_GROUPING_REGRESSED_9I",
  "EXPORT_KEY_MESSAGES_9G_REGRESSED_9I",
  "WARNING_CONTRADICTION_REINTRODUCED_9I",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED_9I",
  "REAL_PAYLOAD_READ_DETECTED_9I",
  "PAYLOAD_CREATION_DETECTED_9I",
  "PAYLOAD_ACCEPTANCE_DETECTED_9I",
  "REAL_PREVIEW_GENERATION_DETECTED_9I",
  "PERSISTENCE_DETECTED_9I",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED_9I",
  "DECISION_SELECTION_OR_TACTIC_DETECTED_9I",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED_9I",
  "SOURCE_OF_TRUTH_REGRESSED_9I",
  "SCORE_MANIPULATION_DETECTED_9I",
  "MATCH_BONUS_EVENT_CHANGED_9I",
  "EXPORT_READ_TIME_BOOLEAN_MISMATCH_9I",
];

export function uniqueWarningCodes9I(
  warnings: readonly ManualReviewPreviewPayloadDryRunExportBudgetCushionWarningCode9I[],
): readonly ManualReviewPreviewPayloadDryRunExportBudgetCushionWarningCode9I[] {
  return [...new Set(warnings)];
}
