export type ManualReviewPreviewPayloadDryRunErrorCopyProgressiveDisclosureWarningCode9J =
  | "ERROR_COPY_PROGRESSIVE_DISCLOSURE_COMPLETE"
  | "ERROR_COPY_PROGRESSIVE_DISCLOSURE_READY"
  | "PRODUCT_PROGRESSIVE_DISCLOSURE_VISIBLE"
  | "EXPORT_PROGRESSIVE_DISCLOSURE_VISIBLE"
  | "DISCLOSURE_LEVELS_READY"
  | "DISCLOSURE_GROUPS_READY"
  | "SUMMARY_LEVEL_VISIBLE"
  | "COACH_DETAIL_LEVEL_VISIBLE"
  | "TECHNICAL_REFERENCES_COLLAPSED"
  | "DISCLOSURE_READ_ONLY_READY"
  | "DISCLOSURE_NO_JAVASCRIPT_REQUIRED"
  | "DISCLOSURE_NO_ACTIVE_CONTROLS"
  | "DISCLOSURE_NO_SUBMIT_BUTTON"
  | "DISCLOSURE_NO_ENABLED_INPUTS"
  | "BASELINE_9I_PRESERVED"
  | "EXPORT_BUDGET_CUSHION_9I_PRESERVED"
  | "UX_GROUPING_9H_PRESERVED"
  | "UX_GROUP_COUNTS_PRESERVED"
  | "UX_GROUP_ASSIGNMENTS_PRESERVED"
  | "COMPATIBLE_CASE_NON_ACCEPTED_PRESERVED"
  | "ERROR_COPY_COVERAGE_PRESERVED"
  | "WARNING_CONSISTENCY_9G_PRESERVED"
  | "EXPORT_KEY_MESSAGES_7_OF_7_PRESERVED"
  | "EXPORT_KEY_MESSAGES_MISSING_ABSENT"
  | "EXPORT_COMPACTION_9F_PRESERVED"
  | "ERROR_COPY_9E_PRESERVED"
  | "EXPORT_METADATA_9J_VISIBLE"
  | "EXPORT_COVER_BADGE_9J_READY"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "EXPORT_UNDER_790_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "NO_RUNTIME_VALIDATION"
  | "NO_PAYLOAD_READ"
  | "NO_PAYLOAD_CREATED"
  | "NO_PAYLOAD_ACCEPTED"
  | "NO_PREVIEW_GENERATED"
  | "NO_PERSISTENCE"
  | "NO_OFFICIAL_TRUTH"
  | "NO_SELECTION_OR_TACTIC"
  | "NO_SCORE_TIMELINE_MUTATION"
  | "SCORING_CONSTANTS_UNCHANGED"
  | "MATCH_BONUS_EVENT_UNCHANGED"
  | "ERROR_COPY_PROGRESSIVE_DISCLOSURE_MISSING"
  | "PRODUCT_PROGRESSIVE_DISCLOSURE_MISSING"
  | "EXPORT_PROGRESSIVE_DISCLOSURE_MISSING"
  | "DISCLOSURE_LEVEL_COUNT_INVALID"
  | "DISCLOSURE_GROUP_COUNT_INVALID"
  | "SUMMARY_LEVEL_MISSING"
  | "COACH_DETAIL_LEVEL_MISSING"
  | "TECHNICAL_REFERENCES_NOT_COLLAPSED"
  | "DISCLOSURE_JAVASCRIPT_REQUIRED"
  | "ACTIVE_CONTROLS_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "ENABLED_INPUTS_DETECTED"
  | "BASELINE_9I_REGRESSED"
  | "EXPORT_BUDGET_CUSHION_9I_LOST"
  | "UX_GROUPING_9H_REGRESSED"
  | "UX_GROUP_COUNTS_REGRESSED"
  | "UX_GROUP_ASSIGNMENTS_REGRESSED"
  | "COMPATIBLE_CASE_ACCEPTED_REGRESSION"
  | "ERROR_COPY_COVERAGE_REGRESSED"
  | "WARNING_CONSISTENCY_9G_REGRESSED"
  | "EXPORT_KEY_MESSAGES_MISSING_REINTRODUCED"
  | "EXPORT_KEY_MESSAGES_CONTRADICTION_REINTRODUCED"
  | "EXPORT_COMPACTION_9F_REGRESSED"
  | "ERROR_COPY_9E_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_OVER_800_PASS_STRONG_BLOCKED"
  | "EXPORT_OVER_790_MARGIN_WARNING"
  | "EXPORT_TITLE_MISSING_9J"
  | "EXPORT_BADGE_MISSING_9J"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_9I"
  | "METADATA_FALSE_POSITIVE_DETECTED"
  | "BODY_FALLBACK_USED_FOR_COVER_BADGE"
  | "VALIDATION_RUNTIME_ACTIVE_DETECTED"
  | "REAL_PAYLOAD_READ_DETECTED"
  | "PAYLOAD_CREATION_DETECTED"
  | "PAYLOAD_ACCEPTANCE_DETECTED"
  | "REAL_PREVIEW_GENERATION_DETECTED"
  | "PREVIEW_ACTIVATION_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "PERSISTENCE_DETECTED"
  | "MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "SCORE_OR_TIMELINE_MUTATION_DETECTED"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_ERROR_COPY_PROGRESSIVE_DISCLOSURE_PARTIAL"
  | "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_ERROR_COPY_PROGRESSIVE_DISCLOSURE_FAIL";

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_ERROR_COPY_PROGRESSIVE_DISCLOSURE_9J_NEGATIVE_WARNINGS: readonly ManualReviewPreviewPayloadDryRunErrorCopyProgressiveDisclosureWarningCode9J[] = [
  "ERROR_COPY_PROGRESSIVE_DISCLOSURE_MISSING",
  "PRODUCT_PROGRESSIVE_DISCLOSURE_MISSING",
  "EXPORT_PROGRESSIVE_DISCLOSURE_MISSING",
  "DISCLOSURE_LEVEL_COUNT_INVALID",
  "DISCLOSURE_GROUP_COUNT_INVALID",
  "SUMMARY_LEVEL_MISSING",
  "COACH_DETAIL_LEVEL_MISSING",
  "TECHNICAL_REFERENCES_NOT_COLLAPSED",
  "DISCLOSURE_JAVASCRIPT_REQUIRED",
  "ACTIVE_CONTROLS_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "ENABLED_INPUTS_DETECTED",
  "BASELINE_9I_REGRESSED",
  "EXPORT_BUDGET_CUSHION_9I_LOST",
  "UX_GROUPING_9H_REGRESSED",
  "UX_GROUP_COUNTS_REGRESSED",
  "UX_GROUP_ASSIGNMENTS_REGRESSED",
  "COMPATIBLE_CASE_ACCEPTED_REGRESSION",
  "ERROR_COPY_COVERAGE_REGRESSED",
  "WARNING_CONSISTENCY_9G_REGRESSED",
  "EXPORT_KEY_MESSAGES_MISSING_REINTRODUCED",
  "EXPORT_KEY_MESSAGES_CONTRADICTION_REINTRODUCED",
  "EXPORT_COMPACTION_9F_REGRESSED",
  "ERROR_COPY_9E_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_OVER_800_PASS_STRONG_BLOCKED",
  "EXPORT_OVER_790_MARGIN_WARNING",
  "EXPORT_TITLE_MISSING_9J",
  "EXPORT_BADGE_MISSING_9J",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_9I",
  "METADATA_FALSE_POSITIVE_DETECTED",
  "BODY_FALLBACK_USED_FOR_COVER_BADGE",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED",
  "REAL_PAYLOAD_READ_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "PAYLOAD_ACCEPTANCE_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "PREVIEW_ACTIVATION_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "PERSISTENCE_DETECTED",
  "MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_ERROR_COPY_PROGRESSIVE_DISCLOSURE_PARTIAL",
  "MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_ERROR_COPY_PROGRESSIVE_DISCLOSURE_FAIL",
];

export const MANUAL_REVIEW_PREVIEW_PAYLOAD_DRY_RUN_ERROR_COPY_PROGRESSIVE_DISCLOSURE_9J_BLOCKING_WARNINGS: readonly ManualReviewPreviewPayloadDryRunErrorCopyProgressiveDisclosureWarningCode9J[] = [
  "ERROR_COPY_PROGRESSIVE_DISCLOSURE_MISSING",
  "PRODUCT_PROGRESSIVE_DISCLOSURE_MISSING",
  "EXPORT_PROGRESSIVE_DISCLOSURE_MISSING",
  "DISCLOSURE_LEVEL_COUNT_INVALID",
  "DISCLOSURE_GROUP_COUNT_INVALID",
  "ACTIVE_CONTROLS_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "ENABLED_INPUTS_DETECTED",
  "BASELINE_9I_REGRESSED",
  "EXPORT_BUDGET_CUSHION_9I_LOST",
  "UX_GROUPING_9H_REGRESSED",
  "UX_GROUP_COUNTS_REGRESSED",
  "UX_GROUP_ASSIGNMENTS_REGRESSED",
  "COMPATIBLE_CASE_ACCEPTED_REGRESSION",
  "ERROR_COPY_COVERAGE_REGRESSED",
  "WARNING_CONSISTENCY_9G_REGRESSED",
  "EXPORT_KEY_MESSAGES_MISSING_REINTRODUCED",
  "EXPORT_KEY_MESSAGES_CONTRADICTION_REINTRODUCED",
  "EXPORT_COMPACTION_9F_REGRESSED",
  "ERROR_COPY_9E_REGRESSED",
  "EXPORT_OVER_900",
  "EXPORT_TITLE_MISSING_9J",
  "EXPORT_BADGE_MISSING_9J",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_9I",
  "METADATA_FALSE_POSITIVE_DETECTED",
  "BODY_FALLBACK_USED_FOR_COVER_BADGE",
  "VALIDATION_RUNTIME_ACTIVE_DETECTED",
  "REAL_PAYLOAD_READ_DETECTED",
  "PAYLOAD_CREATION_DETECTED",
  "PAYLOAD_ACCEPTANCE_DETECTED",
  "REAL_PREVIEW_GENERATION_DETECTED",
  "PREVIEW_ACTIVATION_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "PERSISTENCE_DETECTED",
  "MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "SCORE_OR_TIMELINE_MUTATION_DETECTED",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];

export function uniqueWarningCodes9J(
  warnings: readonly ManualReviewPreviewPayloadDryRunErrorCopyProgressiveDisclosureWarningCode9J[],
): readonly ManualReviewPreviewPayloadDryRunErrorCopyProgressiveDisclosureWarningCode9J[] {
  return [...new Set(warnings)];
}
