export type ManualReviewPreviewDecisionGateWarningCode8Q =
  | "MANUAL_REVIEW_PREVIEW_DECISION_GATE_COMPLETE"
  | "BASELINE_8P_MISSING"
  | "BASELINE_8P_INVALID"
  | "BASELINE_8O_INVALID"
  | "PRODUCT_DECISION_GATE_MISSING"
  | "EXPORT_DECISION_GATE_MISSING"
  | "GATE_NOT_USING_8P_ONLY"
  | "INVALID_COMPARISON_GATE_NOT_BLOCKED"
  | "GATE_CARD_COUNT_INVALID"
  | "GATE_CARD_LINK_MISSING"
  | "GATE_CARD_CONTENT_MISSING"
  | "GATE_MARKER_MISSING"
  | "GATE_LOGIC_INVALID"
  | "GLOBAL_GATE_STATUS_INVALID"
  | "MISSING_INFORMATION_NOT_VISIBLE"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "BACKEND_SUBMIT_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "MEMORY_CREATION_DETECTED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SEASON_TREND_CLAIM_DETECTED"
  | "TEAM_MEMORY_CLAIM_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "AUTO_CLASSIFICATION_REAL_MATCH_DETECTED"
  | "SELECTION_AUTOMATION_DETECTED"
  | "TACTICAL_INSTRUCTION_DETECTED"
  | "SANDBOX_PROMOTED"
  | "DIAGNOSTIC_PROMOTED"
  | "BATCH_PROMOTED"
  | "SCORE_MANIPULATION_DETECTED"
  | "TIMELINE_MUTATION_DETECTED"
  | "SCORE_CHANGE_CREATION_DETECTED"
  | "SOURCE_OF_TRUTH_REGRESSION"
  | "EXPORT_TITLE_MISSING_8Q"
  | "EXPORT_BADGE_MISSING_8Q"
  | "EXPORT_METADATA_MISSING_8Q"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "EXPORT_HISTORICAL_MARKERS_MISSING"
  | "EXPORT_OVER_900_SECONDS"
  | "EXPORT_UNDER_900_BOOLEAN_INVALID"
  | "EXPORT_UNDER_800_BOOLEAN_INVALID"
  | "EXPORT_COMPACTNESS_REGRESSION"
  | "INTEGRATION_SECTION_MISSING"
  | "WORDING_BOUNDARY_MISSING"
  | "AMBIGUOUS_GATE_WORDING";

export const MANUAL_REVIEW_PREVIEW_DECISION_GATE_8Q_BLOCKING_WARNINGS: readonly ManualReviewPreviewDecisionGateWarningCode8Q[] = [
  "BASELINE_8P_MISSING",
  "BASELINE_8P_INVALID",
  "BASELINE_8O_INVALID",
  "PRODUCT_DECISION_GATE_MISSING",
  "EXPORT_DECISION_GATE_MISSING",
  "GATE_NOT_USING_8P_ONLY",
  "INVALID_COMPARISON_GATE_NOT_BLOCKED",
  "GATE_CARD_COUNT_INVALID",
  "GATE_CARD_LINK_MISSING",
  "GATE_LOGIC_INVALID",
  "GLOBAL_GATE_STATUS_INVALID",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "BACKEND_SUBMIT_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "MEMORY_CREATION_DETECTED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "REAL_NEXT_MATCH_CLAIM_DETECTED",
  "ENGINE_LEARNING_CLAIM_DETECTED",
  "SEASON_TREND_CLAIM_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "AUTO_CLASSIFICATION_REAL_MATCH_DETECTED",
  "SELECTION_AUTOMATION_DETECTED",
  "TACTICAL_INSTRUCTION_DETECTED",
  "SANDBOX_PROMOTED",
  "DIAGNOSTIC_PROMOTED",
  "BATCH_PROMOTED",
  "SCORE_MANIPULATION_DETECTED",
  "TIMELINE_MUTATION_DETECTED",
  "SCORE_CHANGE_CREATION_DETECTED",
  "SOURCE_OF_TRUTH_REGRESSION",
  "EXPORT_OVER_900_SECONDS",
  "EXPORT_UNDER_900_BOOLEAN_INVALID",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N",
  "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I",
];
