export type ManualReviewUxInteractionContractWarningCode8T =
  | "MANUAL_REVIEW_UX_INTERACTION_CONTRACT_COMPLETE"
  | "INTERACTION_CONTRACT_READY"
  | "PRODUCT_INTERACTION_CONTRACT_VISIBLE"
  | "EXPORT_INTERACTION_CONTRACT_VISIBLE"
  | "INTERACTION_CONTRACT_USES_UX_SKELETON_8S"
  | "INTERACTION_STEP_COUNT_READY"
  | "FUTURE_INTERACTION_COUNT_READY"
  | "BLOCKED_INTERACTION_COUNT_READY"
  | "NO_ENABLED_INTERACTION"
  | "REFUSAL_STATES_READY"
  | "ACTIVATION_REQUIREMENTS_READY"
  | "STORAGE_DECISION_DEFERRED"
  | "PERMISSIONS_DECISION_DEFERRED"
  | "OFFICIALIZATION_DECISION_DEFERRED"
  | "INTERACTION_CONTRACT_MARKED_FUTURE_ONLY"
  | "INTERACTION_CONTRACT_MARKED_NON_INTERACTIVE"
  | "INTERACTION_CONTRACT_MARKED_NON_OFFICIAL"
  | "INTERACTION_CONTRACT_MARKED_NOT_PERSISTED"
  | "INTERACTION_CONTRACT_MARKED_NOT_APPLIED"
  | "INTERACTION_CONTRACT_DOES_NOT_CREATE_SUBMIT"
  | "INTERACTION_CONTRACT_DOES_NOT_CREATE_API"
  | "INTERACTION_CONTRACT_DOES_NOT_CREATE_BACKEND"
  | "INTERACTION_CONTRACT_DOES_NOT_CREATE_STORAGE"
  | "INTERACTION_CONTRACT_DOES_NOT_CREATE_MEMORY"
  | "INTERACTION_CONTRACT_DOES_NOT_PROMOTE_OFFICIAL_TRUTH"
  | "INTERACTION_CONTRACT_DOES_NOT_CREATE_AUTOMATIC_DECISION"
  | "INTERACTION_CONTRACT_DOES_NOT_DRIVE_SELECTION"
  | "INTERACTION_CONTRACT_DOES_NOT_DRIVE_TACTICAL_INSTRUCTION"
  | "WORKFLOW_READINESS_8S_PRESERVED"
  | "WORKFLOW_READINESS_8R_PRESERVED"
  | "DECISION_GATE_8Q_PRESERVED"
  | "PREVIEW_COMPARISON_8P_PRESERVED"
  | "MANUAL_PREVIEW_8O_PRESERVED"
  | "MANUAL_INTAKE_CONTRACT_8N_PRESERVED"
  | "MANUAL_FORM_8M_PRESERVED"
  | "LEARNING_LOOP_8L_PRESERVED"
  | "DECISION_LAYER_8K_PRESERVED"
  | "EXPORT_COMPACT_PRESERVED"
  | "EXPORT_METADATA_8T_VISIBLE"
  | "EXPORT_ID_CLEANED_FROM_8S"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "INTERACTION_CONTRACT_MISSING"
  | "PRODUCT_INTERACTION_CONTRACT_MISSING"
  | "EXPORT_INTERACTION_CONTRACT_MISSING"
  | "INTERACTION_STEP_COUNT_INVALID"
  | "FUTURE_INTERACTION_COUNT_INVALID"
  | "BLOCKED_INTERACTION_COUNT_INVALID"
  | "ENABLED_INTERACTION_DETECTED"
  | "REFUSAL_STATE_COUNT_INVALID"
  | "REFUSAL_STATE_MISSING"
  | "ACTIVATION_REQUIREMENT_MISSING"
  | "STORAGE_DECISION_NOT_DEFERRED"
  | "PERMISSIONS_DECISION_NOT_DEFERRED"
  | "OFFICIALIZATION_DECISION_NOT_DEFERRED"
  | "INTERACTION_CONTRACT_FUTURE_ONLY_MARKER_MISSING"
  | "INTERACTION_CONTRACT_NON_INTERACTIVE_MARKER_MISSING"
  | "INTERACTION_CONTRACT_NON_OFFICIAL_MARKER_MISSING"
  | "INTERACTION_CONTRACT_NOT_PERSISTED_MARKER_MISSING"
  | "INTERACTION_CONTRACT_NOT_APPLIED_MARKER_MISSING"
  | "ENABLED_CTA_DETECTED"
  | "SUBMIT_BUTTON_DETECTED"
  | "BACKEND_ACTION_DETECTED"
  | "API_CALL_DETECTED"
  | "LOCAL_STORAGE_PERSISTENCE_DETECTED"
  | "DATABASE_PERSISTENCE_CREATED"
  | "FILE_PERSISTENCE_CREATED"
  | "SEASON_MEMORY_CREATED"
  | "TEAM_STYLE_MEMORY_CREATED"
  | "OFFICIAL_TRUTH_PROMOTION_DETECTED"
  | "AUTOMATIC_DECISION_DETECTED"
  | "REAL_NEXT_MATCH_CLAIM_DETECTED"
  | "ENGINE_LEARNING_CLAIM_DETECTED"
  | "SEASON_TREND_CLAIM_DETECTED"
  | "SELECTION_IMPOSITION_DETECTED"
  | "TACTICAL_PLAN_IMPOSITION_DETECTED"
  | "WORKFLOW_READINESS_STATUS_MASKED"
  | "REVIEW_GATE_STATUS_NOT_PRESERVED"
  | "INTERACTION_CONTRACT_CLAIMS_REAL_USE_READY"
  | "PRODUCT_UX_SKELETON_8S_REGRESSED"
  | "EXPORT_UX_SKELETON_8S_REGRESSED"
  | "PRODUCT_WORKFLOW_READINESS_8R_REGRESSED"
  | "EXPORT_WORKFLOW_READINESS_8R_REGRESSED"
  | "PRODUCT_DECISION_GATE_8Q_REGRESSED"
  | "EXPORT_DECISION_GATE_8Q_REGRESSED"
  | "PRODUCT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "EXPORT_PREVIEW_COMPARISON_8P_REGRESSED"
  | "PRODUCT_PREVIEW_RENDERER_8O_REGRESSED"
  | "EXPORT_PREVIEW_RENDERER_8O_REGRESSED"
  | "PRODUCT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "EXPORT_MANUAL_INTAKE_BOUNDARY_8N_REGRESSED"
  | "PRODUCT_MANUAL_FORM_8M_REGRESSED"
  | "EXPORT_MANUAL_FORM_8M_REGRESSED"
  | "PRODUCT_LEARNING_LOOP_8L_REGRESSED"
  | "EXPORT_LEARNING_LOOP_8L_REGRESSED"
  | "PRODUCT_DECISION_LAYER_8K_REGRESSED"
  | "EXPORT_DECISION_LAYER_8K_REGRESSED"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "EXPORT_COMPACT_REGRESSED"
  | "EXPORT_OVER_900"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "EXPORT_TITLE_MISSING_8T"
  | "EXPORT_BADGE_MISSING_8T"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8S"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8R"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8Q"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8P"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8N"
  | "EXPORT_ID_STILL_COMPRESSED_EXPORT_8I"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "MANUAL_REVIEW_UX_INTERACTION_CONTRACT_PARTIAL"
  | "MANUAL_REVIEW_UX_INTERACTION_CONTRACT_FAIL";

export const MANUAL_REVIEW_UX_INTERACTION_CONTRACT_8T_BLOCKING_WARNINGS: readonly ManualReviewUxInteractionContractWarningCode8T[] = [
  "INTERACTION_CONTRACT_MISSING",
  "PRODUCT_INTERACTION_CONTRACT_MISSING",
  "EXPORT_INTERACTION_CONTRACT_MISSING",
  "INTERACTION_STEP_COUNT_INVALID",
  "FUTURE_INTERACTION_COUNT_INVALID",
  "BLOCKED_INTERACTION_COUNT_INVALID",
  "ENABLED_INTERACTION_DETECTED",
  "REFUSAL_STATE_COUNT_INVALID",
  "REFUSAL_STATE_MISSING",
  "ACTIVATION_REQUIREMENT_MISSING",
  "STORAGE_DECISION_NOT_DEFERRED",
  "PERMISSIONS_DECISION_NOT_DEFERRED",
  "OFFICIALIZATION_DECISION_NOT_DEFERRED",
  "ENABLED_CTA_DETECTED",
  "SUBMIT_BUTTON_DETECTED",
  "BACKEND_ACTION_DETECTED",
  "API_CALL_DETECTED",
  "LOCAL_STORAGE_PERSISTENCE_DETECTED",
  "DATABASE_PERSISTENCE_CREATED",
  "FILE_PERSISTENCE_CREATED",
  "SEASON_MEMORY_CREATED",
  "TEAM_STYLE_MEMORY_CREATED",
  "OFFICIAL_TRUTH_PROMOTION_DETECTED",
  "AUTOMATIC_DECISION_DETECTED",
  "REAL_NEXT_MATCH_CLAIM_DETECTED",
  "ENGINE_LEARNING_CLAIM_DETECTED",
  "SEASON_TREND_CLAIM_DETECTED",
  "SELECTION_IMPOSITION_DETECTED",
  "TACTICAL_PLAN_IMPOSITION_DETECTED",
  "WORKFLOW_READINESS_STATUS_MASKED",
  "REVIEW_GATE_STATUS_NOT_PRESERVED",
  "INTERACTION_CONTRACT_CLAIMS_REAL_USE_READY",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SCORE_MANIPULATION_DETECTED",
  "EXPORT_OVER_900",
];
