import type {
  ManualReviewPreviewPayloadDryRunCoachFacingErrorCopy9E,
  ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyGroup9E,
} from "./manualReviewPreviewPayloadDryRunCoachFacingErrorCopyTypes9E";

type CopySeed = Omit<
  ManualReviewPreviewPayloadDryRunCoachFacingErrorCopy9E,
  | "productVisible"
  | "exportVisible"
  | "canCreatePayloadIn9E"
  | "canAcceptPayloadIn9E"
  | "canGeneratePreviewIn9E"
  | "canPersistIn9E"
  | "canPromoteOfficialTruthIn9E"
  | "canDriveDecisionIn9E"
  | "canDriveSelectionIn9E"
  | "canDriveTacticIn9E"
  | "canMutateScoreIn9E"
  | "canMutateTimelineIn9E"
>;

export const EXPECTED_ERROR_COPY_ERROR_IDS_9E = [
  "INVALID_PAYLOAD_SOURCE_8Y",
  "INVALID_PAYLOAD_SCOPE_8Y",
  "OFFICIAL_TRUTH_FLAG_FORBIDDEN_8Y",
  "PERSISTED_FLAG_FORBIDDEN_8Y",
  "APPLIED_FLAG_FORBIDDEN_8Y",
  "ENTRY_COUNT_INVALID_8Y",
  "ENTRY_LINK_UNKNOWN_8Y",
  "INVALID_OUTCOME_VALUE_8Y",
  "INVALID_COUNTER_VALUE_8Y",
  "SIGNAL_COUNT_EXCEEDS_COMPARABLE_COUNT_8Y",
  "INVALID_CONTEXT_COMPARABILITY_8Y",
  "NOTE_TOO_LONG_8Y",
  "REQUIRED_ENTRY_FIELD_MISSING_8Y",
  "FORBIDDEN_TOP_LEVEL_FIELD_8Y",
  "SCORE_TIMELINE_MUTATION_FIELD_8Y",
  "AUTOMATION_FIELD_FORBIDDEN_8Y",
  "STORAGE_FIELD_FORBIDDEN_8Y",
  "ENGINE_LEARNING_FIELD_FORBIDDEN_8Y",
  "BOUNDARY_FLAGS_MISSING_8Y",
] as const;

export const EXPECTED_ERROR_COPY_BLOCKER_IDS_9E = [
  "BLOCK_INVALID_SOURCE_OR_SCOPE_8Y",
  "BLOCK_OFFICIAL_TRUTH_FLAG_8Y",
  "BLOCK_PERSISTENCE_FLAG_8Y",
  "BLOCK_MISSING_OR_INVALID_ENTRIES_8Y",
  "BLOCK_INVALID_ENTRY_VALUES_8Y",
  "BLOCK_MISSING_REQUIRED_ENTRY_FIELDS_8Y",
  "BLOCK_FORBIDDEN_FIELD_8Y",
  "BLOCK_SCORE_OR_TIMELINE_MUTATION_FIELD_8Y",
  "BLOCK_AUTOMATION_FIELD_8Y",
  "BLOCK_STORAGE_OR_API_FIELD_8Y",
  "BLOCK_ENGINE_LEARNING_FIELD_8Y",
  "BLOCK_PREVIEW_ACCEPTANCE_9A",
] as const;

export const EXPECTED_ERROR_COPY_BOUNDARY_GUARD_IDS_9E = [
  "GUARD_NO_RUNTIME_VALIDATION_9A",
  "GUARD_NO_REAL_PAYLOAD_READ_9A",
  "GUARD_NO_REAL_INPUT_READ_9A",
  "GUARD_NO_PAYLOAD_CREATION_9A",
  "GUARD_NO_PAYLOAD_ACCEPTANCE_9A",
  "GUARD_NO_PREVIEW_GENERATION_9A",
  "GUARD_NO_SUBMIT_API_BACKEND_9A",
  "GUARD_NO_PERSISTENCE_9A",
  "GUARD_NO_DRAFT_HISTORY_MEMORY_9A",
  "GUARD_NO_OFFICIAL_TRUTH_9A",
  "GUARD_NO_AUTOMATION_9A",
  "GUARD_NO_SELECTION_OR_TACTIC_9A",
  "GUARD_NO_SCORE_TIMELINE_MUTATION_9A",
  "GUARD_NO_SCORE_CHANGE_EVENT_MUTATION_9A",
] as const;

export const EXPECTED_ERROR_COPY_REFUSAL_IDS_9E = [
  "REFUSE_RUNTIME_ACTIVATION_9A",
  "REFUSE_REAL_PAYLOAD_READ_9E",
  "REFUSE_PAYLOAD_ACCEPTANCE_9A",
  "REFUSE_REAL_PREVIEW_GENERATION_9A",
  "REFUSE_SUBMIT_API_BACKEND_9A",
  "REFUSE_PERSISTENCE_MEMORY_HISTORY_9A",
  "REFUSE_OFFICIAL_TRUTH_DECISION_9A",
  "REFUSE_SELECTION_TACTIC_SCORE_TIMELINE_9A",
] as const;

function copy(seed: CopySeed): ManualReviewPreviewPayloadDryRunCoachFacingErrorCopy9E {
  return {
    ...seed,
    productVisible: true,
    exportVisible: true,
    canCreatePayloadIn9E: false,
    canAcceptPayloadIn9E: false,
    canGeneratePreviewIn9E: false,
    canPersistIn9E: false,
    canPromoteOfficialTruthIn9E: false,
    canDriveDecisionIn9E: false,
    canDriveSelectionIn9E: false,
    canDriveTacticIn9E: false,
    canMutateScoreIn9E: false,
    canMutateTimelineIn9E: false,
  };
}

const STILL_FORBIDDEN =
  "Validation runtime, lecture ou acceptation de payload, preview reelle, submit, API, stockage, official truth, decision automatique, selection, tactique, score et timeline restent interdits.";

export const COMPATIBLE_CASE_COPY_9E = copy({
  copyId: "COMPATIBLE_SHAPE_NOT_ACCEPTED_9E",
  source9CCardId: "valid_preview_only_payload_shape_9a_detail_card_9c",
  groupId: "compatible_but_not_accepted_copy_9e",
  title: "Forme compatible - non acceptee",
  shortMessage: "Cette forme pourrait passer une validation future, mais aucun payload n'est accepte ici.",
  whatHappened: "Le dry-run reconnait une forme coherente avec le contrat preview-only.",
  whyItBlocks: "9E reste une couche de lecture : elle ne valide, n'accepte et ne stocke rien.",
  howToFixLater: "Aucune correction necessaire pour ce cas. Il servira plus tard de reference positive.",
  protectedBoundary: "Un exemple compatible ne devient pas un payload accepte.",
  stillForbidden: STILL_FORBIDDEN,
  technicalReference: "valid_preview_only_payload_shape_9a / BLOCK_PREVIEW_ACCEPTANCE_9A",
  severity: "info",
  copyKind: "compatible_but_not_accepted",
  sourceBlockerId: "BLOCK_PREVIEW_ACCEPTANCE_9A",
  sourceBoundaryGuardId: "GUARD_NO_PAYLOAD_ACCEPTANCE_9A",
  sourceRefusalStateId: "REFUSE_PAYLOAD_ACCEPTANCE_9A",
});

export const ERROR_COPIES_9E: readonly ManualReviewPreviewPayloadDryRunCoachFacingErrorCopy9E[] = [
  copy({
    copyId: "INVALID_PAYLOAD_SOURCE_COPY_9E",
    sourceErrorStateId: "INVALID_PAYLOAD_SOURCE_8Y",
    sourceBlockerId: "BLOCK_INVALID_SOURCE_OR_SCOPE_8Y",
    sourceBoundaryGuardId: "GUARD_NO_REAL_PAYLOAD_READ_9A",
    sourceRefusalStateId: "REFUSE_REAL_PAYLOAD_READ_9E",
    source9CCardId: "invalid_source_payload_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Source non autorisee",
    shortMessage: "La revue doit venir d'une saisie manuelle non officielle.",
    whatHappened: "La source declaree ne correspond pas au perimetre manual_non_official.",
    whyItBlocks: "Une source externe ou automatique pourrait etre confondue avec une verite officielle.",
    howToFixLater: "Revenir plus tard a une source manuelle coach, non officielle.",
    protectedBoundary: "La revue coach reste separee de la verite officielle du match.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "INVALID_PAYLOAD_SOURCE_8Y / BLOCK_INVALID_SOURCE_OR_SCOPE_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "INVALID_PAYLOAD_SCOPE_COPY_9E",
    sourceErrorStateId: "INVALID_PAYLOAD_SCOPE_8Y",
    sourceBlockerId: "BLOCK_INVALID_SOURCE_OR_SCOPE_8Y",
    sourceBoundaryGuardId: "GUARD_NO_RUNTIME_VALIDATION_9A",
    sourceRefusalStateId: "REFUSE_RUNTIME_ACTIVATION_9A",
    source9CCardId: "invalid_scope_payload_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Scope incorrect",
    shortMessage: "La revue doit rester limitee a preview_only.",
    whatHappened: "Le payload demande un usage plus large qu'une simple preview.",
    whyItBlocks: "Le dry-run refuse toute application, stockage ou officialisation.",
    howToFixLater: "Limiter plus tard le scope a preview_only.",
    protectedBoundary: "La preview reste non persistee, non appliquee et non officielle.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "INVALID_PAYLOAD_SCOPE_8Y / BLOCK_INVALID_SOURCE_OR_SCOPE_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "OFFICIAL_TRUTH_FLAG_FORBIDDEN_COPY_9E",
    sourceErrorStateId: "OFFICIAL_TRUTH_FLAG_FORBIDDEN_8Y",
    sourceBlockerId: "BLOCK_OFFICIAL_TRUTH_FLAG_8Y",
    sourceBoundaryGuardId: "GUARD_NO_OFFICIAL_TRUTH_9A",
    sourceRefusalStateId: "REFUSE_OFFICIAL_TRUTH_DECISION_9A",
    source9CCardId: "official_truth_flag_true_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Official truth interdite",
    shortMessage: "Une revue coach ne peut pas devenir une verite officielle.",
    whatHappened: "Le payload contient ou simule un flag officialTruth.",
    whyItBlocks: "Les observations coach ne doivent pas modifier le score, la timeline ou les faits officiels.",
    howToFixLater: "Retirer plus tard tout flag officialTruth.",
    protectedBoundary: "Seuls les evenements officiels et score_change font foi.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "OFFICIAL_TRUTH_FLAG_FORBIDDEN_8Y / BLOCK_OFFICIAL_TRUTH_FLAG_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "PERSISTED_FLAG_FORBIDDEN_COPY_9E",
    sourceErrorStateId: "PERSISTED_FLAG_FORBIDDEN_8Y",
    sourceBlockerId: "BLOCK_PERSISTENCE_FLAG_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PERSISTENCE_9A",
    sourceRefusalStateId: "REFUSE_PERSISTENCE_MEMORY_HISTORY_9A",
    source9CCardId: "persisted_or_applied_flag_true_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Stockage interdit",
    shortMessage: "Cette revue ne peut pas etre marquee comme persistee.",
    whatHappened: "Le payload indique ou suggere une persistance.",
    whyItBlocks: "9E ne cree aucune memoire, historique, DB, fichier ou stockage.",
    howToFixLater: "Retirer plus tard toute indication de persistance.",
    protectedBoundary: "La revue reste non stockee.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "PERSISTED_FLAG_FORBIDDEN_8Y / BLOCK_PERSISTENCE_FLAG_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "APPLIED_FLAG_FORBIDDEN_COPY_9E",
    sourceErrorStateId: "APPLIED_FLAG_FORBIDDEN_8Y",
    sourceBlockerId: "BLOCK_PERSISTENCE_FLAG_8Y",
    sourceBoundaryGuardId: "GUARD_NO_AUTOMATION_9A",
    sourceRefusalStateId: "REFUSE_OFFICIAL_TRUTH_DECISION_9A",
    source9CCardId: "persisted_or_applied_flag_true_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Application interdite",
    shortMessage: "Cette revue ne peut pas etre marquee comme appliquee.",
    whatHappened: "Le payload indique ou suggere qu'une action est appliquee.",
    whyItBlocks: "Une revue dry-run ne doit declencher aucune decision coach ou effet match.",
    howToFixLater: "Retirer plus tard toute indication d'application.",
    protectedBoundary: "Lecture seulement, aucun effet applicatif.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "APPLIED_FLAG_FORBIDDEN_8Y / BLOCK_PERSISTENCE_FLAG_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "ENTRY_COUNT_INVALID_COPY_9E",
    sourceErrorStateId: "ENTRY_COUNT_INVALID_8Y",
    sourceBlockerId: "BLOCK_MISSING_OR_INVALID_ENTRIES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PREVIEW_GENERATION_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "invalid_entry_count_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Nombre d'entrees incorrect",
    shortMessage: "La revue doit contenir exactement 3 entrees d'observation.",
    whatHappened: "Le nombre d'entrees ne correspond pas aux 3 observations prevues.",
    whyItBlocks: "La comparaison 8K/8L/8Q depend de ces 3 axes.",
    howToFixLater: "Renseigner plus tard exactement les 3 entrees attendues.",
    protectedBoundary: "Chaque revue reste alignee sur le plan d'observation.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "ENTRY_COUNT_INVALID_8Y / BLOCK_MISSING_OR_INVALID_ENTRIES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "ENTRY_LINK_UNKNOWN_COPY_9E",
    sourceErrorStateId: "ENTRY_LINK_UNKNOWN_8Y",
    sourceBlockerId: "BLOCK_MISSING_OR_INVALID_ENTRIES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_REAL_INPUT_READ_9A",
    sourceRefusalStateId: "REFUSE_REAL_PAYLOAD_READ_9E",
    source9CCardId: "unknown_entry_link_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Observation inconnue",
    shortMessage: "Une entree pointe vers une observation non reconnue.",
    whatHappened: "Le lien d'observation ne correspond pas aux cartes attendues.",
    whyItBlocks: "Le systeme ne doit pas inventer ou relier une revue a une cible inconnue.",
    howToFixLater: "Utiliser plus tard seulement les observations prevues par le plan.",
    protectedBoundary: "Pas de lien implicite vers une observation inventee.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "ENTRY_LINK_UNKNOWN_8Y / BLOCK_MISSING_OR_INVALID_ENTRIES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "INVALID_OUTCOME_VALUE_COPY_9E",
    sourceErrorStateId: "INVALID_OUTCOME_VALUE_8Y",
    sourceBlockerId: "BLOCK_INVALID_ENTRY_VALUES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PREVIEW_GENERATION_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "invalid_outcome_value_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Resultat non reconnu",
    shortMessage: "Le resultat doit rester dans les choix autorises.",
    whatHappened: "La valeur outcome ne correspond pas aux etats prevus.",
    whyItBlocks: "Une valeur libre empecherait une lecture fiable du gate.",
    howToFixLater: "Utiliser plus tard Confirme, Infirme, Inconclusif ou Echantillon insuffisant.",
    protectedBoundary: "La revue reste structuree et comparable.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "INVALID_OUTCOME_VALUE_8Y / BLOCK_INVALID_ENTRY_VALUES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "INVALID_COUNTER_VALUE_COPY_9E",
    sourceErrorStateId: "INVALID_COUNTER_VALUE_8Y",
    sourceBlockerId: "BLOCK_INVALID_ENTRY_VALUES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PREVIEW_GENERATION_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "invalid_counter_value_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Compteur invalide",
    shortMessage: "Le compteur doit etre un nombre borne et coherent.",
    whatHappened: "Un compteur est absent, non numerique ou hors plage.",
    whyItBlocks: "Les compteurs soutiennent la lisibilite de la revue, sans devenir verite officielle.",
    howToFixLater: "Renseigner plus tard un entier dans la plage autorisee.",
    protectedBoundary: "Pas de metrique libre non controlee.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "INVALID_COUNTER_VALUE_8Y / BLOCK_INVALID_ENTRY_VALUES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "SIGNAL_COUNT_EXCEEDS_COMPARABLE_COUNT_COPY_9E",
    sourceErrorStateId: "SIGNAL_COUNT_EXCEEDS_COMPARABLE_COUNT_8Y",
    sourceBlockerId: "BLOCK_INVALID_ENTRY_VALUES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PREVIEW_GENERATION_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "signal_count_exceeds_comparable_count_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Signaux incoherents",
    shortMessage: "Les signaux positifs ou negatifs depassent le nombre de situations comparables.",
    whatHappened: "Le total des signaux est superieur au volume de situations observees.",
    whyItBlocks: "La revue deviendrait trompeuse.",
    howToFixLater: "Aligner plus tard les signaux avec le nombre de situations comparables.",
    protectedBoundary: "Pas de conclusion sur un echantillon incoherent.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "SIGNAL_COUNT_EXCEEDS_COMPARABLE_COUNT_8Y / BLOCK_INVALID_ENTRY_VALUES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "INVALID_CONTEXT_COMPARABILITY_COPY_9E",
    sourceErrorStateId: "INVALID_CONTEXT_COMPARABILITY_8Y",
    sourceBlockerId: "BLOCK_INVALID_ENTRY_VALUES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_SELECTION_OR_TACTIC_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "invalid_context_comparability_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Contexte non comparable",
    shortMessage: "Le niveau de comparabilite doit rester dans les valeurs prevues.",
    whatHappened: "Le contexte ne correspond pas a l'echelle attendue.",
    whyItBlocks: "Le coach doit savoir si les situations sont vraiment comparables.",
    howToFixLater: "Choisir plus tard une valeur de comparabilite autorisee.",
    protectedBoundary: "Pas de conclusion masquant un contexte different.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "INVALID_CONTEXT_COMPARABILITY_8Y / BLOCK_INVALID_ENTRY_VALUES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "NOTE_TOO_LONG_COPY_9E",
    sourceErrorStateId: "NOTE_TOO_LONG_8Y",
    sourceBlockerId: "BLOCK_INVALID_ENTRY_VALUES_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PREVIEW_GENERATION_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "note_too_long_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Note trop longue",
    shortMessage: "La note doit rester courte pour rester exploitable.",
    whatHappened: "Le texte depasse la limite de lisibilite.",
    whyItBlocks: "Le rapport compact doit rester lisible et exportable.",
    howToFixLater: "Reduire plus tard la note a l'essentiel : fait observe, contexte, limite.",
    protectedBoundary: "Lisibilite coach et export compact.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "NOTE_TOO_LONG_8Y / BLOCK_INVALID_ENTRY_VALUES_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "REQUIRED_ENTRY_FIELD_MISSING_COPY_9E",
    sourceErrorStateId: "REQUIRED_ENTRY_FIELD_MISSING_8Y",
    sourceBlockerId: "BLOCK_MISSING_REQUIRED_ENTRY_FIELDS_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PREVIEW_GENERATION_9A",
    sourceRefusalStateId: "REFUSE_REAL_PREVIEW_GENERATION_9A",
    source9CCardId: "missing_required_entry_field_9a_detail_card_9c",
    groupId: "validation_error_copy_9e",
    title: "Champ obligatoire manquant",
    shortMessage: "Une information necessaire a la revue est absente.",
    whatHappened: "Une entree ne contient pas tous les champs requis.",
    whyItBlocks: "La revue ne peut pas etre relue proprement sans ces champs.",
    howToFixLater: "Completer plus tard les champs requis avant toute future preview.",
    protectedBoundary: "Pas de preview sur une revue incomplete.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "REQUIRED_ENTRY_FIELD_MISSING_8Y / BLOCK_MISSING_REQUIRED_ENTRY_FIELDS_8Y",
    severity: "warning",
    copyKind: "validation_error",
  }),
  copy({
    copyId: "FORBIDDEN_TOP_LEVEL_FIELD_COPY_9E",
    sourceErrorStateId: "FORBIDDEN_TOP_LEVEL_FIELD_8Y",
    sourceBlockerId: "BLOCK_FORBIDDEN_FIELD_8Y",
    sourceBoundaryGuardId: "GUARD_NO_PAYLOAD_CREATION_9A",
    sourceRefusalStateId: "REFUSE_PAYLOAD_ACCEPTANCE_9A",
    source9CCardId: "forbidden_top_level_field_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Champ interdit",
    shortMessage: "Le payload contient un champ qui n'appartient pas au contrat preview-only.",
    whatHappened: "Un champ applicatif ou technique interdit apparait au niveau principal.",
    whyItBlocks: "Ces champs pourraient declencher un effet hors du perimetre dry-run.",
    howToFixLater: "Retirer plus tard tout champ non liste dans le contrat autorise.",
    protectedBoundary: "Contrat strict, pas d'effet implicite.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "FORBIDDEN_TOP_LEVEL_FIELD_8Y / BLOCK_FORBIDDEN_FIELD_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "SCORE_TIMELINE_MUTATION_FIELD_COPY_9E",
    sourceErrorStateId: "SCORE_TIMELINE_MUTATION_FIELD_8Y",
    sourceBlockerId: "BLOCK_SCORE_OR_TIMELINE_MUTATION_FIELD_8Y",
    sourceBoundaryGuardId: "GUARD_NO_SCORE_TIMELINE_MUTATION_9A",
    sourceRefusalStateId: "REFUSE_SELECTION_TACTIC_SCORE_TIMELINE_9A",
    source9CCardId: "score_timeline_mutation_attempt_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Mutation score/timeline interdite",
    shortMessage: "La revue ne peut pas modifier le score, la timeline ou les score_change.",
    whatHappened: "Le payload contient une tentative de mutation match.",
    whyItBlocks: "Le score officiel vient uniquement des evenements officiels.",
    howToFixLater: "Supprimer plus tard tout champ score, timeline, score_change ou event mutation.",
    protectedBoundary: "Source-of-truth du match intacte.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "SCORE_TIMELINE_MUTATION_FIELD_8Y / BLOCK_SCORE_OR_TIMELINE_MUTATION_FIELD_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "AUTOMATION_FIELD_FORBIDDEN_COPY_9E",
    sourceErrorStateId: "AUTOMATION_FIELD_FORBIDDEN_8Y",
    sourceBlockerId: "BLOCK_AUTOMATION_FIELD_8Y",
    sourceBoundaryGuardId: "GUARD_NO_AUTOMATION_9A",
    sourceRefusalStateId: "REFUSE_OFFICIAL_TRUTH_DECISION_9A",
    source9CCardId: "automation_storage_engine_learning_attempt_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Automation interdite",
    shortMessage: "La revue ne peut pas declencher une decision automatique.",
    whatHappened: "Un champ suggere une automatisation ou une decision.",
    whyItBlocks: "Le coach garde la decision ; le dry-run n'applique rien.",
    howToFixLater: "Retirer plus tard les champs d'automation.",
    protectedBoundary: "Pas de decision automatique.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "AUTOMATION_FIELD_FORBIDDEN_8Y / BLOCK_AUTOMATION_FIELD_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "STORAGE_FIELD_FORBIDDEN_COPY_9E",
    sourceErrorStateId: "STORAGE_FIELD_FORBIDDEN_8Y",
    sourceBlockerId: "BLOCK_STORAGE_OR_API_FIELD_8Y",
    sourceBoundaryGuardId: "GUARD_NO_SUBMIT_API_BACKEND_9A",
    sourceRefusalStateId: "REFUSE_SUBMIT_API_BACKEND_9A",
    source9CCardId: "automation_storage_engine_learning_attempt_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Stockage/API interdit",
    shortMessage: "La revue ne peut pas cibler un stockage, une API ou un backend.",
    whatHappened: "Un champ indique une destination technique ou de persistance.",
    whyItBlocks: "9E ne doit rien ecrire, envoyer ou sauvegarder.",
    howToFixLater: "Retirer plus tard tout storageTarget, apiEndpoint ou champ equivalent.",
    protectedBoundary: "Aucun submit, API, backend ou stockage.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "STORAGE_FIELD_FORBIDDEN_8Y / BLOCK_STORAGE_OR_API_FIELD_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "ENGINE_LEARNING_FIELD_FORBIDDEN_COPY_9E",
    sourceErrorStateId: "ENGINE_LEARNING_FIELD_FORBIDDEN_8Y",
    sourceBlockerId: "BLOCK_ENGINE_LEARNING_FIELD_8Y",
    sourceBoundaryGuardId: "GUARD_NO_DRAFT_HISTORY_MEMORY_9A",
    sourceRefusalStateId: "REFUSE_SELECTION_TACTIC_SCORE_TIMELINE_9A",
    source9CCardId: "automation_storage_engine_learning_attempt_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Apprentissage moteur interdit",
    shortMessage: "La revue ne peut pas entrainer ou ajuster le moteur.",
    whatHappened: "Un champ suggere un signal d'apprentissage moteur.",
    whyItBlocks: "Une revue coach ne doit pas modifier le moteur ni creer une memoire d'equipe.",
    howToFixLater: "Retirer plus tard tout champ engineLearningSignal.",
    protectedBoundary: "Pas d'engine learning depuis une revue manuelle.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "ENGINE_LEARNING_FIELD_FORBIDDEN_8Y / BLOCK_ENGINE_LEARNING_FIELD_8Y",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
  copy({
    copyId: "BOUNDARY_FLAGS_MISSING_COPY_9E",
    sourceErrorStateId: "BOUNDARY_FLAGS_MISSING_8Y",
    sourceBlockerId: "BLOCK_ENGINE_LEARNING_FIELD_8Y",
    sourceBoundaryGuardId: "GUARD_NO_SCORE_CHANGE_EVENT_MUTATION_9A",
    sourceRefusalStateId: "REFUSE_SELECTION_TACTIC_SCORE_TIMELINE_9A",
    source9CCardId: "automation_storage_engine_learning_attempt_9a_detail_card_9c",
    groupId: "preview_blocker_copy_9e",
    title: "Garde-fous boundary manquants",
    shortMessage: "Les flags qui prouvent l'absence d'effet reel doivent rester explicites.",
    whatHappened: "Le payload ne declare pas clairement les frontieres non-runtime.",
    whyItBlocks: "Sans ces flags, une future lecture pourrait confondre dry-run et action reelle.",
    howToFixLater: "Declarer plus tard explicitement no runtime, no payload accepted, no preview, no storage, no official truth.",
    protectedBoundary: "Dry-run lisible et non ambigu.",
    stillForbidden: STILL_FORBIDDEN,
    technicalReference: "BOUNDARY_FLAGS_MISSING_8Y / boundary guard set",
    severity: "blocking",
    copyKind: "preview_blocker",
  }),
] as const;

const BLOCKER_IDS_BY_COPY_ID: readonly (readonly [string, string])[] = [
  ["BLOCK_INVALID_SOURCE_OR_SCOPE_COPY_9E", "BLOCK_INVALID_SOURCE_OR_SCOPE_8Y"],
  ["BLOCK_OFFICIAL_TRUTH_FLAG_COPY_9E", "BLOCK_OFFICIAL_TRUTH_FLAG_8Y"],
  ["BLOCK_PERSISTENCE_FLAG_COPY_9E", "BLOCK_PERSISTENCE_FLAG_8Y"],
  ["BLOCK_MISSING_OR_INVALID_ENTRIES_COPY_9E", "BLOCK_MISSING_OR_INVALID_ENTRIES_8Y"],
  ["BLOCK_INVALID_ENTRY_VALUES_COPY_9E", "BLOCK_INVALID_ENTRY_VALUES_8Y"],
  ["BLOCK_MISSING_REQUIRED_ENTRY_FIELDS_COPY_9E", "BLOCK_MISSING_REQUIRED_ENTRY_FIELDS_8Y"],
  ["BLOCK_FORBIDDEN_FIELD_COPY_9E", "BLOCK_FORBIDDEN_FIELD_8Y"],
  ["BLOCK_SCORE_OR_TIMELINE_MUTATION_FIELD_COPY_9E", "BLOCK_SCORE_OR_TIMELINE_MUTATION_FIELD_8Y"],
  ["BLOCK_AUTOMATION_FIELD_COPY_9E", "BLOCK_AUTOMATION_FIELD_8Y"],
  ["BLOCK_STORAGE_OR_API_FIELD_COPY_9E", "BLOCK_STORAGE_OR_API_FIELD_8Y"],
  ["BLOCK_ENGINE_LEARNING_FIELD_COPY_9E", "BLOCK_ENGINE_LEARNING_FIELD_8Y"],
  ["BLOCK_PREVIEW_ACCEPTANCE_COPY_9E", "BLOCK_PREVIEW_ACCEPTANCE_9A"],
] as const;

export const BLOCKER_COPIES_9E: readonly ManualReviewPreviewPayloadDryRunCoachFacingErrorCopy9E[] = BLOCKER_IDS_BY_COPY_ID.map(([copyId, blockerId]) => copy({
  copyId,
  sourceBlockerId: blockerId,
  groupId: blockerId === "BLOCK_PREVIEW_ACCEPTANCE_9A" ? "compatible_but_not_accepted_copy_9e" : "preview_blocker_copy_9e",
  title: blockerId.replace(/_/gu, " "),
  shortMessage: "Ce blocker garde le dry-run dans une lecture non active.",
  whatHappened: "Le cas touche une frontiere qui bloquerait une future preview active.",
  whyItBlocks: "Le systeme doit rester lisible sans declencher d'effet reel.",
  howToFixLater: "Corriger plus tard la cause avant d'envisager une preview.",
  protectedBoundary: "Aucune validation active, aucune acceptation, aucune persistance.",
  stillForbidden: STILL_FORBIDDEN,
  technicalReference: blockerId,
  severity: blockerId === "BLOCK_PREVIEW_ACCEPTANCE_9A" ? "info" : "blocking",
  copyKind: blockerId === "BLOCK_PREVIEW_ACCEPTANCE_9A" ? "compatible_but_not_accepted" : "preview_blocker",
}));

const REFUSAL_IDS_BY_COPY_ID: readonly (readonly [string, string])[] = [
  ["REFUSE_RUNTIME_VALIDATION_COPY_9E", "REFUSE_RUNTIME_ACTIVATION_9A"],
  ["REFUSE_REAL_PAYLOAD_READ_COPY_9E", "REFUSE_REAL_PAYLOAD_READ_9E"],
  ["REFUSE_PAYLOAD_ACCEPTANCE_COPY_9E", "REFUSE_PAYLOAD_ACCEPTANCE_9A"],
  ["REFUSE_REAL_PREVIEW_GENERATION_COPY_9E", "REFUSE_REAL_PREVIEW_GENERATION_9A"],
  ["REFUSE_SUBMIT_API_BACKEND_COPY_9E", "REFUSE_SUBMIT_API_BACKEND_9A"],
  ["REFUSE_PERSISTENCE_MEMORY_HISTORY_COPY_9E", "REFUSE_PERSISTENCE_MEMORY_HISTORY_9A"],
  ["REFUSE_OFFICIAL_TRUTH_DECISION_COPY_9E", "REFUSE_OFFICIAL_TRUTH_DECISION_9A"],
  ["REFUSE_SELECTION_TACTIC_SCORE_TIMELINE_COPY_9E", "REFUSE_SELECTION_TACTIC_SCORE_TIMELINE_9A"],
] as const;

export const REFUSAL_COPIES_9E: readonly ManualReviewPreviewPayloadDryRunCoachFacingErrorCopy9E[] = REFUSAL_IDS_BY_COPY_ID.map(([copyId, refusalId]) => copy({
  copyId,
  sourceRefusalStateId: refusalId,
  groupId: "preview_blocker_copy_9e",
  title: refusalId.replace(/_/gu, " "),
  shortMessage: "Ce refus explique une limite non-runtime du dry-run.",
  whatHappened: "La demande irait au-dela d'une copy coach-facing statique.",
  whyItBlocks: "9E ne doit pas transformer un message d'erreur en action produit.",
  howToFixLater: "Traiter plus tard ce refus dans un vrai sprint de validation ou d'UX.",
  protectedBoundary: "La revue reste non officielle, non persistante et non appliquee.",
  stillForbidden: STILL_FORBIDDEN,
  technicalReference: refusalId,
  severity: "blocking",
  copyKind: "boundary_refusal",
}));

export function buildCopyGroups9E(): readonly ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyGroup9E[] {
  const allCopies = [COMPATIBLE_CASE_COPY_9E, ...ERROR_COPIES_9E];
  const group = (
    groupId: string,
    label: string,
    coachFacingMeaning: string,
    severity: ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyGroup9E["severity"],
  ): ManualReviewPreviewPayloadDryRunCoachFacingErrorCopyGroup9E => {
    const copies = allCopies.filter((item) => item.groupId === groupId);
    return {
      groupId,
      label,
      coachFacingMeaning,
      copyIds: copies.map((item) => item.copyId),
      copyCount: copies.length,
      severity,
      visibleInProduct: true,
      visibleInExport: true,
    };
  };
  return [
    group(
      "compatible_but_not_accepted_copy_9e",
      "Forme compatible - non acceptee",
      "La forme serait compatible avec un futur validator, mais elle n'est pas acceptee ici.",
      "info",
    ),
    group(
      "validation_error_copy_9e",
      "Erreur de validation future",
      "Ces erreurs indiquent ce qu'il faudra corriger plus tard avant de pouvoir generer une preview.",
      "warning",
    ),
    group(
      "preview_blocker_copy_9e",
      "Blocage de frontiere",
      "Ces cas touchent une frontiere interdite : official truth, stockage, API, automation, score/timeline ou preview.",
      "blocking",
    ),
  ];
}
