export type MatchStorylineImmersionCoachReplayViewWarningCode =
  | "MATCH_STORYLINE_IMMERSION_READY"
  | "MATCH_STORYLINE_IMMERSION_PARTIAL"
  | "COACH_REPLAY_VIEW_READY"
  | "COACH_REPLAY_VIEW_PARTIAL"
  | "NATURAL_NARRATIVE_WORDING_READY"
  | "TECHNICAL_ID_LEAKAGE"
  | "REPLAY_SCORE_SOURCE_OF_TRUTH_PRESERVED"
  | "REPLAY_SCORE_SOURCE_AMBIGUOUS"
  | "REPLAY_WORDING_TRANSFORMS_READY"
  | "REPLAY_WORDING_TRANSFORMS_MISSING"
  | "REPORT_INTEGRATION_READY"
  | "REPORT_INTEGRATION_PARTIAL"
  | "BASELINE_8D_PRESERVED"
  | "BASELINE_8D_REGRESSED";

export const MATCH_STORYLINE_IMMERSION_COACH_REPLAY_VIEW_BLOCKING_WARNINGS: readonly MatchStorylineImmersionCoachReplayViewWarningCode[] = [
  "MATCH_STORYLINE_IMMERSION_PARTIAL",
  "COACH_REPLAY_VIEW_PARTIAL",
  "TECHNICAL_ID_LEAKAGE",
  "REPLAY_SCORE_SOURCE_AMBIGUOUS",
  "REPLAY_WORDING_TRANSFORMS_MISSING",
  "REPORT_INTEGRATION_PARTIAL",
  "BASELINE_8D_REGRESSED",
];
