export type OfficialMatchStorySpineEngineCausalityProofWarningCode =
  | "OFFICIAL_MATCH_STORY_SPINE_COMPLETE"
  | "STORY_SPINE_READY"
  | "ENGINE_CAUSALITY_READY"
  | "OFFICIAL_TIMELINE_COVERAGE_READY"
  | "SCORING_CAUSALITY_READY"
  | "TEAM_STYLE_EXPRESSION_READY"
  | "FATIGUE_CAUSALITY_READY"
  | "PLAYER_IMPACT_READABLE"
  | "COACH_READABLE_NARRATIVE_READY"
  | "SHORT_NARRATIVE_READY"
  | "DETAILED_NARRATIVE_READY"
  | "TURNING_POINTS_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "REPORT_CONSUMPTION_READY"
  | "PRODUCT_STORY_SECTION_READY"
  | "EXPORT_STORY_SECTION_READY"
  | "EXPORT_LENGTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "STORY_SPINE_MISSING"
  | "STORY_SEGMENT_COUNT_INVALID"
  | "STORY_BEAT_COUNT_TOO_LOW"
  | "TURNING_POINT_COUNT_INVALID"
  | "SCORE_CHANGE_EVENT_NOT_COVERED"
  | "UNSUPPORTED_NARRATIVE_CLAIM"
  | "UNSUPPORTED_CAUSALITY_CLAIM"
  | "INVENTED_EVENT_IN_STORY"
  | "SANDBOX_CLAIM_IN_OFFICIAL_STORY"
  | "BATCH_CLAIM_IN_OFFICIAL_STORY"
  | "DIAGNOSTIC_CLAIM_IN_OFFICIAL_STORY"
  | "STORY_SCORE_MISMATCH"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "CAUSALITY_TOO_WEAK"
  | "ATTRIBUTE_CAUSALITY_NOT_PROVEN"
  | "FATIGUE_CAUSALITY_NOT_PROVEN"
  | "TEAM_STYLE_CAUSALITY_NOT_PROVEN"
  | "PLAYER_IMPACT_NOT_READABLE"
  | "NARRATIVE_TOO_ANALYTICAL"
  | "NARRATIVE_TOO_TECHNICAL"
  | "METRIC_DUMP_NARRATIVE"
  | "EXPORT_LENGTH_REGRESSED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "HISTORY_USED_AS_OFFICIAL_TRUTH"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "OFFICIAL_MATCH_STORY_SPINE_PARTIAL"
  | "OFFICIAL_MATCH_STORY_SPINE_FAIL";

export const OFFICIAL_MATCH_STORY_SPINE_BLOCKING_WARNINGS: readonly OfficialMatchStorySpineEngineCausalityProofWarningCode[] = [
  "STORY_SPINE_MISSING",
  "SCORE_CHANGE_EVENT_NOT_COVERED",
  "UNSUPPORTED_NARRATIVE_CLAIM",
  "UNSUPPORTED_CAUSALITY_CLAIM",
  "INVENTED_EVENT_IN_STORY",
  "SANDBOX_CLAIM_IN_OFFICIAL_STORY",
  "BATCH_CLAIM_IN_OFFICIAL_STORY",
  "DIAGNOSTIC_CLAIM_IN_OFFICIAL_STORY",
  "STORY_SCORE_MISMATCH",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
