export const PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_READY_WARNINGS = [
  "PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_UPGRADE_COMPLETE",
  "SEQUENCE_LEVEL_CAUSALITY_READY",
  "PLAYER_ROLE_CAUSALITY_READY",
  "ACTOR_CHAIN_READY",
  "ROLE_FUNCTION_CHAIN_READY",
  "SEQUENCE_STORY_UPGRADE_READY",
  "PLAYER_IMPACT_DEPTH_READY",
  "ROLE_FUNCTION_DEPTH_READY",
  "FATIGUE_EFFECT_SPECIFICITY_READY",
  "STRATEGY_SEQUENCE_LINK_READY",
  "COUNTER_CONSISTENCY_READY",
  "VALIDATION_LABEL_CLARITY_READY",
  "COACH_READABLE_SEQUENCE_STORY_READY",
  "SOURCE_OF_TRUTH_PRESERVED",
  "REPORT_INTEGRATION_READY",
  "EXPORT_LENGTH_PRESERVED",
  "MATCH_ECONOMY_BASELINE_PRESERVED",
  "PRODUCT_BASELINE_READY",
] as const;

export const PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_BLOCKING_WARNINGS = [
  "SEQUENCE_WITHOUT_OFFICIAL_EVENT",
  "INVENTED_SEQUENCE_EVENT",
  "PLAYER_NONE_CAUSALITY",
  "ROLE_NONE_CAUSALITY",
  "UNSUPPORTED_PLAYER_CLAIM",
  "UNSUPPORTED_ROLE_CLAIM",
  "FATIGUE_CLAIM_WITHOUT_SIGNAL",
  "FATIGUE_CLAIM_WITHOUT_EVENT",
  "EVENT_BACKED_LABEL_AMBIGUOUS",
  "COUNTER_MISMATCH",
  "SANDBOX_SEQUENCE_PROMOTED",
  "DIAGNOSTIC_SEQUENCE_PROMOTED",
  "BATCH_SEQUENCE_PROMOTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_FAIL",
] as const;

export type PlayerRoleCausalitySequenceLevelStoryUpgradeWarningCode =
  | typeof PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_READY_WARNINGS[number]
  | typeof PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_BLOCKING_WARNINGS[number]
  | "PLAYER_ROLE_CAUSALITY_SEQUENCE_LEVEL_STORY_PARTIAL"
  | "SEQUENCE_LEVEL_CAUSALITY_MISSING"
  | "SELECTED_SEQUENCE_COUNT_INVALID"
  | "ACTOR_CHAIN_MISSING"
  | "ROLE_CHAIN_MISSING"
  | "FATIGUE_VISIBLE_NOT_CAUSAL"
  | "FATIGUE_EFFECT_NOT_SPECIFIC"
  | "TACTICAL_PLAN_COUNTER_MISMATCH"
  | "GENERIC_SEQUENCE_SENTENCE"
  | "MECHANICAL_SEQUENCE_SENTENCE"
  | "METRIC_DUMP_SEQUENCE_NARRATIVE"
  | "PLAYER_NONE_IN_NARRATIVE"
  | "ROLE_NONE_IN_NARRATIVE"
  | "CAUSAL_SENTENCE_WITHOUT_EVIDENCE"
  | "SEQUENCE_CAUSAL_CLARITY_TOO_LOW"
  | "COACH_READABILITY_TOO_LOW"
  | "EXPORT_LENGTH_REGRESSED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "MATCH_ECONOMY_BASELINE_REGRESSED";
