export type ProductBaselineCoachReportReadinessWarningCode =
  | "PRODUCT_BASELINE_COACH_REPORT_READINESS_COMPLETE"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "OFFICIAL_SCORE_SOURCE_CLEAR"
  | "OFFICIAL_DIAGNOSTIC_SANDBOX_SEPARATION_CLEAR"
  | "ACTIONABLE_INSIGHTS_PRESENT"
  | "TECHNICAL_APPENDICES_COLLAPSED"
  | "SELECTION_PREVIEW_NON_APPLIED_CONFIRMED"
  | "PROFILES_TO_OBSERVE_NOT_FORCED"
  | "GUARDRAILS_SUMMARY_VISIBLE"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "REPORT_TOO_TECHNICAL"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "LOW_CONFIDENCE_LABEL_MISSING"
  | "UNSUPPORTED_RECOMMENDATION"
  | "FORCED_SELECTION_FROM_PREVIEW"
  | "FORBIDDEN_WORDING_DETECTED"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "ACTIONABLE_INSIGHTS_TOO_LOW"
  | "PRODUCT_EXPORT_TOO_VERBOSE"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "PRODUCT_BASELINE_PARTIAL"
  | "PRODUCT_BASELINE_FAIL";

export const PRODUCT_BASELINE_BLOCKING_WARNINGS: readonly ProductBaselineCoachReportReadinessWarningCode[] = [
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "FORCED_SELECTION_FROM_PREVIEW",
  "FORBIDDEN_WORDING_DETECTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
];

