export type ProductReportScopeDensityWordingCleanupWarningCode =
  | "PRODUCT_REPORT_SCOPE_DENSITY_WORDING_CLEANUP_COMPLETE"
  | "REPORT_SCOPE_CLEAN"
  | "EXPORT_SCOPE_CLEAN"
  | "MAIN_BODY_COACH_ONLY"
  | "DEVELOPER_SECTIONS_MOVED_TO_APPENDIX"
  | "PERSISTENCE_SECTIONS_NOT_IN_MAIN_BODY"
  | "DATABASE_SECTIONS_NOT_IN_MAIN_BODY"
  | "CALIBRATION_HISTORY_NOT_IN_MAIN_BODY"
  | "MECHANICAL_WORDING_REMOVED"
  | "DUPLICATED_LABELS_REMOVED"
  | "REPEATED_WARNINGS_REDUCED"
  | "VISUAL_DENSITY_CONTROLLED"
  | "EXPRESS_READ_PRESERVED"
  | "ACTION_PLAN_STILL_PROMINENT"
  | "TACTICAL_MAP_CARDS_PRESERVED"
  | "TECHNICAL_APPENDICES_COLLAPSED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "PRODUCT_REPORT_READY"
  | "COACH_EXPORT_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "REPORT_SCOPE_TOO_BROAD"
  | "EXPORT_SCOPE_TOO_BROAD"
  | "DEVELOPER_SECTIONS_IN_MAIN_BODY"
  | "PERSISTENCE_SECTIONS_IN_MAIN_BODY"
  | "DATABASE_SECTIONS_IN_MAIN_BODY"
  | "CALIBRATION_HISTORY_IN_MAIN_BODY"
  | "MECHANICAL_WORDING_STILL_PRESENT"
  | "DUPLICATED_LABELS_STILL_PRESENT"
  | "REPEATED_WARNINGS_STILL_PRESENT"
  | "EXPORT_TOO_LONG"
  | "VISUAL_DENSITY_TOO_HIGH"
  | "ACTION_PLAN_NOT_PROMINENT"
  | "EXPRESS_READ_REGRESSED"
  | "TACTICAL_MAP_CARDS_REGRESSED"
  | "TECHNICAL_DETAILS_NOT_COLLAPSED"
  | "FORBIDDEN_WORDING_DETECTED"
  | "SOURCE_OF_TRUTH_AMBIGUOUS"
  | "SANDBOX_TRUTH_LEAKAGE"
  | "DIAGNOSTIC_SCORE_LEAKAGE"
  | "BATCH_SCORE_LEAKAGE"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "PRODUCT_REPORT_SCOPE_CLEANUP_PARTIAL"
  | "PRODUCT_REPORT_SCOPE_CLEANUP_FAIL";

export const PRODUCT_REPORT_SCOPE_DENSITY_WORDING_BLOCKING_WARNINGS: readonly ProductReportScopeDensityWordingCleanupWarningCode[] = [
  "SOURCE_OF_TRUTH_AMBIGUOUS",
  "SANDBOX_TRUTH_LEAKAGE",
  "DIAGNOSTIC_SCORE_LEAKAGE",
  "BATCH_SCORE_LEAKAGE",
  "FORBIDDEN_WORDING_DETECTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "PRODUCT_REPORT_SCOPE_CLEANUP_FAIL",
];
