export type ReplayActorMappingNaturalNarrativeFixWarningCode =
  | "REPLAY_ACTOR_MAPPING_NATURAL_NARRATIVE_FIX_COMPLETE"
  | "ACTOR_MAPPING_FIXED"
  | "ROLE_DIVERSITY_RESTORED"
  | "GOALKEEPER_FALLBACK_CONTROLLED"
  | "NATURAL_REPLAY_NARRATIVE_READY"
  | "SOURCE_OF_TRUTH_NOTE_COMPACTED"
  | "REPLAY_PROOF_COMPACTION_READY"
  | "PRODUCT_REPLAY_SECTION_UPDATED"
  | "EXPORT_REPLAY_SECTION_UPDATED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "EXPORT_LENGTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "ACTOR_MAPPING_NOT_FIXED"
  | "ROLE_DIVERSITY_NOT_RESTORED"
  | "SUSPICIOUS_GOALKEEPER_FALLBACK"
  | "ACTOR_MISMATCH_WITH_8D"
  | "ROLE_MISMATCH_WITH_8D"
  | "ACTOR_WITHOUT_EVIDENCE"
  | "ROLE_WITHOUT_EVIDENCE"
  | "INVENTED_ACTOR"
  | "INVENTED_ROLE"
  | "TECHNICAL_ID_IN_MAIN_TEXT"
  | "RAW_PLAYER_ID_IN_MAIN_TEXT"
  | "RAW_EVENT_ID_IN_MAIN_TEXT"
  | "RAW_EFFECT_LABEL_IN_MAIN_TEXT"
  | "REPEATED_GUARDRAIL_PHRASE"
  | "MECHANICAL_REPLAY_PHRASE"
  | "GENERIC_REPLAY_PHRASE"
  | "PROOF_IN_MAIN_TEXT_TOO_LONG"
  | "SOURCE_OF_TRUTH_NOTE_REPEATED"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SANDBOX_REPLAY_PROMOTED"
  | "DIAGNOSTIC_REPLAY_PROMOTED"
  | "BATCH_REPLAY_PROMOTED"
  | "EXPORT_LENGTH_REGRESSED"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "REPLAY_ACTOR_MAPPING_NATURAL_NARRATIVE_PARTIAL"
  | "REPLAY_ACTOR_MAPPING_NATURAL_NARRATIVE_FAIL";

export const REPLAY_ACTOR_MAPPING_NATURAL_NARRATIVE_FIX_BLOCKING_WARNINGS: readonly ReplayActorMappingNaturalNarrativeFixWarningCode[] = [
  "SUSPICIOUS_GOALKEEPER_FALLBACK",
  "ACTOR_MISMATCH_WITH_8D",
  "ROLE_MISMATCH_WITH_8D",
  "ACTOR_WITHOUT_EVIDENCE",
  "ROLE_WITHOUT_EVIDENCE",
  "INVENTED_ACTOR",
  "INVENTED_ROLE",
  "TECHNICAL_ID_IN_MAIN_TEXT",
  "RAW_PLAYER_ID_IN_MAIN_TEXT",
  "RAW_EVENT_ID_IN_MAIN_TEXT",
  "RAW_EFFECT_LABEL_IN_MAIN_TEXT",
  "REPEATED_GUARDRAIL_PHRASE",
  "MECHANICAL_REPLAY_PHRASE",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SANDBOX_REPLAY_PROMOTED",
  "DIAGNOSTIC_REPLAY_PROMOTED",
  "BATCH_REPLAY_PROMOTED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
