export type SharePackCompletionExportActionPlanRestorationWarningCode =
  | "SHARE_PACK_COMPLETION_EXPORT_ACTION_PLAN_RESTORATION_COMPLETE"
  | "SHARE_PACK_CURRENT_SPRINT_FIXED"
  | "SHARE_PACK_8I_DOCS_INCLUDED"
  | "VALIDATION_8I_INCLUDED"
  | "EXPORT_THRESHOLD_VALIDATION_READY"
  | "EXPORT_ACTION_PLAN_RESTORED"
  | "REPLAY_EXPORT_WORDING_CLEAN"
  | "EXPORT_BUDGET_STILL_VALID"
  | "PRODUCT_STORY_FIRST_PRESERVED"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "SHARE_PACK_STILL_8H"
  | "SHARE_PACK_8I_DOCS_MISSING"
  | "VALIDATION_8I_MISSING"
  | "STALE_8H_CURRENT_SPRINT_REFERENCE"
  | "MANIFEST_STILL_8H"
  | "README_STILL_8H"
  | "EXPORT_THRESHOLD_VALIDATION_MISSING"
  | "PASS_MESSAGE_ON_FAILED_NUMERIC_RULE"
  | "FAILED_NUMERIC_RULE_MARKED_PASS"
  | "THRESHOLD_BOOLEAN_MISMATCH"
  | "EXPORT_OVER_900"
  | "EXPORT_ACTION_PLAN_EMPTY"
  | "EXPORT_ACTION_PLAN_MISSING"
  | "REPLAY_EXPORT_TRUNCATED_SENTENCE"
  | "REPLAY_EXPORT_INCOMPLETE_SENTENCE"
  | "FULL_TIMELINE_INCLUDED_IN_EXPORT"
  | "TECHNICAL_TRACEABILITY_INCLUDED_IN_EXPORT"
  | "SANDBOX_PANEL_INCLUDED_IN_EXPORT"
  | "LONG_BATCH_DIAGNOSTICS_INCLUDED_IN_EXPORT"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "REPLAY_8G_REGRESSED"
  | "ACTOR_MAPPING_8F_REGRESSED"
  | "RAW_EVENT_ID_IN_MAIN_TEXT"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SANDBOX_STORY_PROMOTED"
  | "DIAGNOSTIC_STORY_PROMOTED"
  | "BATCH_STORY_PROMOTED"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "SHARE_PACK_COMPLETION_EXPORT_ACTION_PLAN_RESTORATION_PARTIAL"
  | "SHARE_PACK_COMPLETION_EXPORT_ACTION_PLAN_RESTORATION_FAIL";

export const SHARE_PACK_COMPLETION_EXPORT_ACTION_PLAN_RESTORATION_BLOCKING_WARNINGS: readonly SharePackCompletionExportActionPlanRestorationWarningCode[] = [
  "SHARE_PACK_STILL_8H",
  "SHARE_PACK_8I_DOCS_MISSING",
  "VALIDATION_8I_MISSING",
  "STALE_8H_CURRENT_SPRINT_REFERENCE",
  "MANIFEST_STILL_8H",
  "README_STILL_8H",
  "EXPORT_THRESHOLD_VALIDATION_MISSING",
  "PASS_MESSAGE_ON_FAILED_NUMERIC_RULE",
  "FAILED_NUMERIC_RULE_MARKED_PASS",
  "THRESHOLD_BOOLEAN_MISMATCH",
  "EXPORT_OVER_900",
  "EXPORT_ACTION_PLAN_EMPTY",
  "EXPORT_ACTION_PLAN_MISSING",
  "REPLAY_EXPORT_TRUNCATED_SENTENCE",
  "REPLAY_EXPORT_INCOMPLETE_SENTENCE",
  "FULL_TIMELINE_INCLUDED_IN_EXPORT",
  "TECHNICAL_TRACEABILITY_INCLUDED_IN_EXPORT",
  "SANDBOX_PANEL_INCLUDED_IN_EXPORT",
  "LONG_BATCH_DIAGNOSTICS_INCLUDED_IN_EXPORT",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "REPLAY_8G_REGRESSED",
  "ACTOR_MAPPING_8F_REGRESSED",
  "RAW_EVENT_ID_IN_MAIN_TEXT",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SANDBOX_STORY_PROMOTED",
  "DIAGNOSTIC_STORY_PROMOTED",
  "BATCH_STORY_PROMOTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
