export type StoryFirstExportBudgetValidationThresholdFixWarningCode =
  | "STORY_FIRST_EXPORT_BUDGET_VALIDATION_THRESHOLD_FIX_COMPLETE"
  | "EXPORT_BUDGET_FIXED"
  | "EXPORT_UNDER_900_READY"
  | "EXPORT_UNDER_800_READY"
  | "NUMERIC_THRESHOLD_GUARD_READY"
  | "VALIDATION_HONESTY_READY"
  | "STORY_FIRST_EXPORT_PRESERVED"
  | "PRODUCT_STORY_FIRST_PRESERVED"
  | "REPLAY_EXPORT_PRESERVED"
  | "ACTION_PLAN_EXPORT_PRESERVED"
  | "TACTICAL_MAP_EXPORT_PRESERVED"
  | "TECHNICAL_EXPORT_COMPRESSION_READY"
  | "SOURCE_OF_TRUTH_PRESERVED"
  | "EXPORT_PRINT_READY"
  | "EXPORT_MOBILE_READY"
  | "MATCH_ECONOMY_BASELINE_PRESERVED"
  | "PRODUCT_BASELINE_READY"
  | "EXPORT_BUDGET_NOT_FIXED"
  | "EXPORT_OVER_900"
  | "EXPORT_OVER_800"
  | "EXPORT_UNDER_900_BOOLEAN_MISMATCH"
  | "EXPORT_UNDER_800_BOOLEAN_MISMATCH"
  | "PASS_MESSAGE_ON_FAILED_NUMERIC_RULE"
  | "FAILED_NUMERIC_RULE_MARKED_PASS"
  | "VALIDATION_STATUS_THRESHOLD_MISMATCH"
  | "FULL_TIMELINE_INCLUDED_IN_EXPORT"
  | "TECHNICAL_TRACEABILITY_INCLUDED_IN_EXPORT"
  | "SANDBOX_PANEL_INCLUDED_IN_EXPORT"
  | "LONG_BATCH_DIAGNOSTICS_INCLUDED_IN_EXPORT"
  | "STORY_FIRST_EXPORT_MISSING"
  | "MATCH_IN_2_MINUTES_MISSING"
  | "REPLAY_60_SECONDS_MISSING"
  | "ACTION_PLAN_EXPORT_MISSING"
  | "PRODUCT_STORY_FIRST_REGRESSED"
  | "REPLAY_8G_REGRESSED"
  | "ACTOR_MAPPING_8F_REGRESSED"
  | "RAW_EVENT_ID_IN_MAIN_TEXT"
  | "SCORE_CLAIM_WITHOUT_SCORE_CHANGE"
  | "SANDBOX_STORY_PROMOTED"
  | "DIAGNOSTIC_STORY_PROMOTED"
  | "BATCH_STORY_PROMOTED"
  | "MATCH_ECONOMY_BASELINE_REGRESSED"
  | "SCORE_MANIPULATION_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "STORY_FIRST_EXPORT_BUDGET_VALIDATION_THRESHOLD_FIX_PARTIAL"
  | "STORY_FIRST_EXPORT_BUDGET_VALIDATION_THRESHOLD_FIX_FAIL";

export const STORY_FIRST_EXPORT_BUDGET_8I_BLOCKING_WARNINGS: readonly StoryFirstExportBudgetValidationThresholdFixWarningCode[] = [
  "EXPORT_BUDGET_NOT_FIXED",
  "EXPORT_OVER_900",
  "EXPORT_UNDER_900_BOOLEAN_MISMATCH",
  "PASS_MESSAGE_ON_FAILED_NUMERIC_RULE",
  "FAILED_NUMERIC_RULE_MARKED_PASS",
  "VALIDATION_STATUS_THRESHOLD_MISMATCH",
  "FULL_TIMELINE_INCLUDED_IN_EXPORT",
  "TECHNICAL_TRACEABILITY_INCLUDED_IN_EXPORT",
  "SANDBOX_PANEL_INCLUDED_IN_EXPORT",
  "LONG_BATCH_DIAGNOSTICS_INCLUDED_IN_EXPORT",
  "STORY_FIRST_EXPORT_MISSING",
  "MATCH_IN_2_MINUTES_MISSING",
  "REPLAY_60_SECONDS_MISSING",
  "ACTION_PLAN_EXPORT_MISSING",
  "PRODUCT_STORY_FIRST_REGRESSED",
  "REPLAY_8G_REGRESSED",
  "ACTOR_MAPPING_8F_REGRESSED",
  "RAW_EVENT_ID_IN_MAIN_TEXT",
  "SCORE_CLAIM_WITHOUT_SCORE_CHANGE",
  "SANDBOX_STORY_PROMOTED",
  "DIAGNOSTIC_STORY_PROMOTED",
  "BATCH_STORY_PROMOTED",
  "MATCH_ECONOMY_BASELINE_REGRESSED",
  "SCORE_MANIPULATION_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
];
