import { PressureLevel } from "../../../models/match";
import { PlayerRole } from "../../../models/player";
import { TacticalStyle } from "../../../models/tactics";
import { SpatialMoveType } from "../../spatial/intention/types";
import type { RoleBehaviorProfile } from "./types";

function profile(input: Omit<RoleBehaviorProfile, "source">): RoleBehaviorProfile {
  return {
    ...input,
    source: "generic role",
  };
}

function teamOverride(input: Omit<RoleBehaviorProfile, "source">): RoleBehaviorProfile {
  return {
    ...input,
    source: "team override",
  };
}

export const ROLE_BEHAVIOR_PROFILES: Readonly<Record<PlayerRole, RoleBehaviorProfile>> = {
  [PlayerRole.TempoHalf]: profile({
    role: PlayerRole.TempoHalf,
    normalBehavior: "organizes tempo and prefers supported progression",
    pressingBehavior: "finds exits behind pressure and avoids isolated carries",
    transitionBehavior: "connects first pass, then follows as organizer",
    chaosBehavior: "slows unstable phases and protects structure",
    finishingBehavior: "prefers drops, final passes, or structured progression",
    fatigueBehavior: "recycles earlier and lowers direct-risk choices",
    supportBehavior: "inside support, third-man outlet, safe diagonal",
    riskTolerance: 38,
    moveBiases: {
      [SpatialMoveType.Progression]: 4,
      [SpatialMoveType.LateralCirculation]: 3,
      [SpatialMoveType.BackwardRecycle]: 3,
      [SpatialMoveType.DirectVerticalAttack]: -10,
    },
    chaosRiskResponse: -0.12,
    fatigueConservatism: 0.16,
    pressureConservatism: 5,
  }),
  [PlayerRole.HookLink]: profile({
    role: PlayerRole.HookLink,
    normalBehavior: "stabilizes possession and survives contact",
    pressingBehavior: "offers secure receiver under pressure",
    transitionBehavior: "secures first contact or phase connection",
    chaosBehavior: "protects ball and waits for support",
    finishingBehavior: "supports close-range continuation",
    fatigueBehavior: "becomes more conservative but remains reliable",
    supportBehavior: "connected outlet, pod support, contact support",
    riskTolerance: 42,
    moveBiases: {
      [SpatialMoveType.Progression]: 3,
      [SpatialMoveType.LateralCirculation]: 4,
      [SpatialMoveType.BackwardRecycle]: 2,
      [SpatialMoveType.DirectVerticalAttack]: -8,
    },
    chaosRiskResponse: -0.08,
    fatigueConservatism: 0.14,
    pressureConservatism: 4,
  }),
  [PlayerRole.ForwardLeader]: profile({
    role: PlayerRole.ForwardLeader,
    normalBehavior: "anchors structure and screens pressure",
    pressingBehavior: "screens nearest presser and protects gain-line support",
    transitionBehavior: "leads second wave and contact stabilization",
    chaosBehavior: "turns chaos into contact security",
    finishingBehavior: "supports try pressure and rebound security",
    fatigueBehavior: "loses explosiveness but keeps structure",
    supportBehavior: "pod organizer, pressure screen, support anchor",
    riskTolerance: 52,
    moveBiases: {
      [SpatialMoveType.Progression]: 5,
      [SpatialMoveType.DirectVerticalAttack]: 1,
      [SpatialMoveType.LateralCirculation]: 1,
    },
    chaosRiskResponse: -0.03,
    fatigueConservatism: 0.1,
    pressureConservatism: 2,
  }),
  [PlayerRole.GoalkeeperFreeSafety]: profile({
    role: PlayerRole.GoalkeeperFreeSafety,
    normalBehavior: "protects depth first and organizes last line",
    pressingBehavior: "offers emergency release only when structure needs it",
    transitionBehavior: "protects counter depth before joining",
    chaosBehavior: "prioritizes rebound control and last-line order",
    finishingBehavior: "saves below crossbar and controls rebounds",
    fatigueBehavior: "leaves line less often and clears earlier",
    supportBehavior: "deep outlet, rest-defense organizer",
    riskTolerance: 28,
    moveBiases: {
      [SpatialMoveType.SafetyClearance]: 8,
      [SpatialMoveType.BackwardRecycle]: 5,
      [SpatialMoveType.DirectVerticalAttack]: -12,
    },
    chaosRiskResponse: -0.14,
    fatigueConservatism: 0.18,
    pressureConservatism: 6,
  }),
  [PlayerRole.MobileLock]: profile({
    role: PlayerRole.MobileLock,
    normalBehavior: "closes lanes and protects emergency spaces",
    pressingBehavior: "steps into traps and blocks direct exits",
    transitionBehavior: "recovers against runners and covers central lanes",
    chaosBehavior: "reduces chaos by delaying the carrier",
    finishingBehavior: "last-line tackle, emergency block, forced wide",
    fatigueBehavior: "covers earlier as recovery range drops",
    supportBehavior: "covering support, defensive fold",
    riskTolerance: 50,
    moveBiases: {
      [SpatialMoveType.Progression]: 1,
      [SpatialMoveType.LateralCirculation]: 1,
      [SpatialMoveType.DirectVerticalAttack]: -2,
    },
    chaosRiskResponse: -0.04,
    fatigueConservatism: 0.12,
    pressureConservatism: 2,
  }),
  [PlayerRole.SpaceHunter]: profile({
    role: PlayerRole.SpaceHunter,
    normalBehavior: "waits for weak-side or depth window",
    pressingBehavior: "jumps pressing lanes when trigger is visible",
    transitionBehavior: "attacks depth aggressively and accepts isolation",
    chaosBehavior: "becomes rupture-oriented and less disciplined",
    finishingBehavior: "prefers try attack, weak-side finish, chaotic second chance",
    fatigueBehavior: "loses repeated sprint threat and becomes less reliable",
    supportBehavior: "depth runner, weak-side outlet, late support",
    riskTolerance: 76,
    moveBiases: {
      [SpatialMoveType.DirectVerticalAttack]: 12,
      [SpatialMoveType.Progression]: 7,
      [SpatialMoveType.WeakSideSwitch]: 5,
      [SpatialMoveType.BackwardRecycle]: -10,
    },
    chaosRiskResponse: 0.12,
    fatigueConservatism: 0.08,
    pressureConservatism: 0,
  }),
  [PlayerRole.Playmaker]: profile({
    role: PlayerRole.Playmaker,
    normalBehavior: "creates third-man solutions and controlled unlocks",
    pressingBehavior: "receives between lines to break pressure",
    transitionBehavior: "finds early final pass or controlled acceleration",
    chaosBehavior: "improvises without fully abandoning structure",
    finishingBehavior: "chooses drop, final pass, or red-zone unlock",
    fatigueBehavior: "creativity remains, execution risk rises",
    supportBehavior: "third-man creator, inside connector",
    riskTolerance: 62,
    moveBiases: {
      [SpatialMoveType.Progression]: 6,
      [SpatialMoveType.DirectVerticalAttack]: 4,
      [SpatialMoveType.WeakSideSwitch]: 5,
      [SpatialMoveType.Finishing]: 4,
    },
    chaosRiskResponse: 0.04,
    fatigueConservatism: 0.1,
    pressureConservatism: 2,
  }),
  [PlayerRole.Pivot]: profile({
    role: PlayerRole.Pivot,
    normalBehavior: "balances possession and rest defense",
    pressingBehavior: "offers central reset and protects axis",
    transitionBehavior: "stabilizes first secure phase",
    chaosBehavior: "pulls team back toward structure",
    finishingBehavior: "supports controlled second wave",
    fatigueBehavior: "sits deeper and protects rest defense",
    supportBehavior: "behind-ball support, central hinge",
    riskTolerance: 36,
    moveBiases: {
      [SpatialMoveType.Progression]: 2,
      [SpatialMoveType.LateralCirculation]: 4,
      [SpatialMoveType.BackwardRecycle]: 5,
      [SpatialMoveType.DirectVerticalAttack]: -10,
    },
    chaosRiskResponse: -0.12,
    fatigueConservatism: 0.16,
    pressureConservatism: 5,
  }),
  [PlayerRole.LeftPiston]: profile({
    role: PlayerRole.LeftPiston,
    normalBehavior: "provides left width and short-side protection",
    pressingBehavior: "offers touchline outlet or closes flank",
    transitionBehavior: "supports flank progression and recovery",
    chaosBehavior: "keeps width but avoids reckless isolation",
    finishingBehavior: "supports wide entry or switch reception",
    fatigueBehavior: "reduces overlap frequency and protects behind ball",
    supportBehavior: "wide support, short-side security",
    riskTolerance: 50,
    moveBiases: {
      [SpatialMoveType.LateralCirculation]: 4,
      [SpatialMoveType.WeakSideSwitch]: 5,
      [SpatialMoveType.Progression]: 3,
    },
    chaosRiskResponse: -0.02,
    fatigueConservatism: 0.1,
    pressureConservatism: 2,
  }),
  [PlayerRole.RightPiston]: profile({
    role: PlayerRole.RightPiston,
    normalBehavior: "provides right width and open-side reception",
    pressingBehavior: "offers escape lane or closes flank",
    transitionBehavior: "supports open-side progression and recovery",
    chaosBehavior: "keeps width but avoids reckless isolation",
    finishingBehavior: "supports wide entry or switch reception",
    fatigueBehavior: "reduces overlap frequency and protects behind ball",
    supportBehavior: "wide support, open-side outlet",
    riskTolerance: 50,
    moveBiases: {
      [SpatialMoveType.LateralCirculation]: 4,
      [SpatialMoveType.WeakSideSwitch]: 5,
      [SpatialMoveType.Progression]: 3,
    },
    chaosRiskResponse: -0.02,
    fatigueConservatism: 0.1,
    pressureConservatism: 2,
  }),
  [PlayerRole.LeftAnchor]: profile({
    role: PlayerRole.LeftAnchor,
    normalBehavior: "legacy left rest-defense behavior",
    pressingBehavior: "protects flank compactness",
    transitionBehavior: "recovers into structure",
    chaosBehavior: "stays conservative",
    finishingBehavior: "supports wide security",
    fatigueBehavior: "drops earlier",
    supportBehavior: "wide safety",
    riskTolerance: 40,
    moveBiases: {},
    chaosRiskResponse: -0.08,
    fatigueConservatism: 0.14,
    pressureConservatism: 4,
  }),
  [PlayerRole.RightAnchor]: profile({
    role: PlayerRole.RightAnchor,
    normalBehavior: "legacy right rest-defense behavior",
    pressingBehavior: "protects flank compactness",
    transitionBehavior: "recovers into structure",
    chaosBehavior: "stays conservative",
    finishingBehavior: "supports wide security",
    fatigueBehavior: "drops earlier",
    supportBehavior: "wide safety",
    riskTolerance: 40,
    moveBiases: {},
    chaosRiskResponse: -0.08,
    fatigueConservatism: 0.14,
    pressureConservatism: 4,
  }),
  [PlayerRole.PowerRunner]: profile({
    role: PlayerRole.PowerRunner,
    normalBehavior: "legacy contact runner behavior",
    pressingBehavior: "presses through contact lane",
    transitionBehavior: "runs direct support",
    chaosBehavior: "accepts contact chaos",
    finishingBehavior: "attacks contact finish",
    fatigueBehavior: "slows direct running",
    supportBehavior: "contact support",
    riskTolerance: 58,
    moveBiases: {
      [SpatialMoveType.Progression]: 4,
      [SpatialMoveType.DirectVerticalAttack]: 4,
    },
    chaosRiskResponse: 0.03,
    fatigueConservatism: 0.1,
    pressureConservatism: 1,
  }),
  [PlayerRole.FreeSafety]: profile({
    role: PlayerRole.FreeSafety,
    normalBehavior: "legacy depth protection behavior",
    pressingBehavior: "supports emergency release",
    transitionBehavior: "protects depth",
    chaosBehavior: "prioritizes last-line control",
    finishingBehavior: "last-line response",
    fatigueBehavior: "clears earlier",
    supportBehavior: "deep outlet",
    riskTolerance: 30,
    moveBiases: {
      [SpatialMoveType.SafetyClearance]: 6,
      [SpatialMoveType.BackwardRecycle]: 4,
    },
    chaosRiskResponse: -0.12,
    fatigueConservatism: 0.16,
    pressureConservatism: 5,
  }),
};

const BLITZ_ROLE_BEHAVIOR_OVERRIDES: Readonly<Partial<Record<PlayerRole, RoleBehaviorProfile>>> = {
  [PlayerRole.TempoHalf]: teamOverride({
    role: PlayerRole.TempoHalf,
    normalBehavior: "acts as the primary vertical trigger and looks for depth runners early",
    pressingBehavior: "accepts pressure to release beyond the first line",
    transitionBehavior: "prefers line-breaking release over slow support",
    chaosBehavior: "forces action under pressure and accepts contested lanes",
    finishingBehavior: "tries direct goal, drop, or fast final-release windows",
    fatigueBehavior: "decision volatility rises before patience appears",
    supportBehavior: "early vertical distributor, inside trigger, long-play launcher",
    riskTolerance: 74,
    moveBiases: {
      [SpatialMoveType.DirectVerticalAttack]: 18,
      [SpatialMoveType.Progression]: 12,
      [SpatialMoveType.Finishing]: 8,
      [SpatialMoveType.LateralCirculation]: -8,
      [SpatialMoveType.BackwardRecycle]: -14,
    },
    chaosRiskResponse: 0.1,
    fatigueConservatism: 0.06,
    pressureConservatism: -3,
  }),
  [PlayerRole.SpaceHunter]: teamOverride({
    role: PlayerRole.SpaceHunter,
    normalBehavior: "attacks depth aggressively and accepts isolation",
    pressingBehavior: "jumps loose lanes and chases broken receptions",
    transitionBehavior: "turns vertical releases into immediate depth pressure",
    chaosBehavior: "attacks loose balls, rebounds, and rupture moments",
    finishingBehavior: "forces chaotic tries and second-chance finishes",
    fatigueBehavior: "sprint threat remains high but execution becomes volatile",
    supportBehavior: "depth runner, rebound hunter, isolated rupture option",
    riskTolerance: 88,
    moveBiases: {
      [SpatialMoveType.DirectVerticalAttack]: 18,
      [SpatialMoveType.Progression]: 10,
      [SpatialMoveType.Finishing]: 12,
      [SpatialMoveType.WeakSideSwitch]: 8,
      [SpatialMoveType.BackwardRecycle]: -16,
    },
    chaosRiskResponse: 0.18,
    fatigueConservatism: 0.05,
    pressureConservatism: -2,
  }),
  [PlayerRole.Playmaker]: teamOverride({
    role: PlayerRole.Playmaker,
    normalBehavior: "creates high-risk line-breaking and finishing windows",
    pressingBehavior: "receives in unstable pockets and releases forward early",
    transitionBehavior: "tries direct goal, drop, or final pass before the block resets",
    chaosBehavior: "embraces variance to create sudden scoring pressure",
    finishingBehavior: "attempts direct goal/drop actions and risky unlocks",
    fatigueBehavior: "turnover risk rises but creative aggression remains",
    supportBehavior: "inside rupture creator, direct finisher, high-variance connector",
    riskTolerance: 84,
    moveBiases: {
      [SpatialMoveType.DirectVerticalAttack]: 14,
      [SpatialMoveType.Progression]: 10,
      [SpatialMoveType.Finishing]: 14,
      [SpatialMoveType.WeakSideSwitch]: 8,
      [SpatialMoveType.BackwardRecycle]: -12,
    },
    chaosRiskResponse: 0.16,
    fatigueConservatism: 0.06,
    pressureConservatism: -2,
  }),
  [PlayerRole.HookLink]: teamOverride({
    role: PlayerRole.HookLink,
    normalBehavior: "keeps chaotic phases alive as a contact connector",
    pressingBehavior: "offers contact outlet without fully slowing the attack",
    transitionBehavior: "supports second balls and forward continuation",
    chaosBehavior: "fights to keep loose phases alive rather than securing safely",
    finishingBehavior: "connects contact support and scramble continuation",
    fatigueBehavior: "contact security drops before aggression drops",
    supportBehavior: "second-ball support, contact connector, offload target",
    riskTolerance: 66,
    moveBiases: {
      [SpatialMoveType.Progression]: 8,
      [SpatialMoveType.DirectVerticalAttack]: 7,
      [SpatialMoveType.Finishing]: 5,
      [SpatialMoveType.LateralCirculation]: -4,
      [SpatialMoveType.BackwardRecycle]: -10,
    },
    chaosRiskResponse: 0.08,
    fatigueConservatism: 0.08,
    pressureConservatism: -1,
  }),
  [PlayerRole.ForwardLeader]: teamOverride({
    role: PlayerRole.ForwardLeader,
    normalBehavior: "launches collisions and screens long-play receivers",
    pressingBehavior: "counterpresses contact lanes aggressively",
    transitionBehavior: "attacks second contact after the vertical release",
    chaosBehavior: "turns broken play into collision pressure",
    finishingBehavior: "screens the finisher and attacks rebounds",
    fatigueBehavior: "rest-defense discipline drops under repeated collisions",
    supportBehavior: "collision launcher, screen, second-contact support",
    riskTolerance: 70,
    moveBiases: {
      [SpatialMoveType.Progression]: 9,
      [SpatialMoveType.DirectVerticalAttack]: 8,
      [SpatialMoveType.Finishing]: 5,
      [SpatialMoveType.BackwardRecycle]: -10,
    },
    chaosRiskResponse: 0.08,
    fatigueConservatism: 0.08,
    pressureConservatism: -1,
  }),
  [PlayerRole.MobileLock]: teamOverride({
    role: PlayerRole.MobileLock,
    normalBehavior: "recovers aggressively and counterpresses forward",
    pressingBehavior: "jumps into forward counterpress lanes and can overcommit",
    transitionBehavior: "chases the first recovery duel rather than holding shape",
    chaosBehavior: "tries to win chaos forward, risking gaps behind",
    finishingBehavior: "attacks emergency blocks and rebound contests",
    fatigueBehavior: "overcommitment risk rises as recovery timing drops",
    supportBehavior: "forward counterpress, emergency chase, aggressive cover",
    riskTolerance: 72,
    moveBiases: {
      [SpatialMoveType.Progression]: 6,
      [SpatialMoveType.DirectVerticalAttack]: 5,
      [SpatialMoveType.BackwardRecycle]: -8,
    },
    chaosRiskResponse: 0.08,
    fatigueConservatism: 0.08,
    pressureConservatism: -1,
  }),
  [PlayerRole.Pivot]: teamOverride({
    role: PlayerRole.Pivot,
    normalBehavior: "acts as a transition relay for vertical continuation",
    pressingBehavior: "keeps central counterpress pressure connected",
    transitionBehavior: "supports the next forward action instead of stabilizing",
    chaosBehavior: "holds enough structure to feed the next direct release",
    finishingBehavior: "arrives as second-wave support",
    fatigueBehavior: "positional stability drops under repeated transition load",
    supportBehavior: "vertical relay, second-wave hinge, loose-ball outlet",
    riskTolerance: 62,
    moveBiases: {
      [SpatialMoveType.Progression]: 8,
      [SpatialMoveType.DirectVerticalAttack]: 5,
      [SpatialMoveType.LateralCirculation]: -2,
      [SpatialMoveType.BackwardRecycle]: -9,
    },
    chaosRiskResponse: 0.05,
    fatigueConservatism: 0.08,
    pressureConservatism: 0,
  }),
  [PlayerRole.LeftPiston]: teamOverride({
    role: PlayerRole.LeftPiston,
    normalBehavior: "runs high-speed width and depth on the left",
    pressingBehavior: "jumps open-side lanes aggressively",
    transitionBehavior: "attacks open-side depth rather than protecting rest defense",
    chaosBehavior: "chases loose wide lanes and second balls",
    finishingBehavior: "arrives wide for final cutback or rebound pressure",
    fatigueBehavior: "rest-defense recovery weakens before running intent drops",
    supportBehavior: "wide depth runner, open-side outlet",
    riskTolerance: 78,
    moveBiases: {
      [SpatialMoveType.DirectVerticalAttack]: 12,
      [SpatialMoveType.Progression]: 9,
      [SpatialMoveType.WeakSideSwitch]: 10,
      [SpatialMoveType.LateralCirculation]: -2,
      [SpatialMoveType.BackwardRecycle]: -12,
    },
    chaosRiskResponse: 0.12,
    fatigueConservatism: 0.06,
    pressureConservatism: -1,
  }),
  [PlayerRole.RightPiston]: teamOverride({
    role: PlayerRole.RightPiston,
    normalBehavior: "runs high-speed width and depth on the right",
    pressingBehavior: "jumps open-side lanes aggressively",
    transitionBehavior: "attacks open-side depth rather than protecting rest defense",
    chaosBehavior: "chases loose wide lanes and second balls",
    finishingBehavior: "arrives wide for final cutback or rebound pressure",
    fatigueBehavior: "rest-defense recovery weakens before running intent drops",
    supportBehavior: "wide depth runner, open-side outlet",
    riskTolerance: 78,
    moveBiases: {
      [SpatialMoveType.DirectVerticalAttack]: 12,
      [SpatialMoveType.Progression]: 9,
      [SpatialMoveType.WeakSideSwitch]: 10,
      [SpatialMoveType.LateralCirculation]: -2,
      [SpatialMoveType.BackwardRecycle]: -12,
    },
    chaosRiskResponse: 0.12,
    fatigueConservatism: 0.06,
    pressureConservatism: -1,
  }),
  [PlayerRole.GoalkeeperFreeSafety]: teamOverride({
    role: PlayerRole.GoalkeeperFreeSafety,
    normalBehavior: "acts as an aggressive sweeper-kicker with strong long distribution",
    pressingBehavior: "offers risky long release outside the defensive goal area",
    transitionBehavior: "launches direct distribution before structure fully settles",
    chaosBehavior: "accepts more risk outside goal area than CONTROL goalkeeper",
    finishingBehavior: "still protects the frame but rebounds can be volatile",
    fatigueBehavior: "clearance risk rises as composure drops",
    supportBehavior: "deep long-play outlet, sweeper-kicker, risky reset",
    riskTolerance: 58,
    moveBiases: {
      [SpatialMoveType.SafetyClearance]: 4,
      [SpatialMoveType.DirectVerticalAttack]: 8,
      [SpatialMoveType.Progression]: 5,
      [SpatialMoveType.BackwardRecycle]: -4,
    },
    chaosRiskResponse: 0.04,
    fatigueConservatism: 0.08,
    pressureConservatism: 1,
  }),
};

export function getRoleBehaviorProfile(role: PlayerRole, tacticalStyle?: TacticalStyle): RoleBehaviorProfile {
  if (tacticalStyle === TacticalStyle.Blitz) {
    return BLITZ_ROLE_BEHAVIOR_OVERRIDES[role] ?? ROLE_BEHAVIOR_PROFILES[role];
  }

  return ROLE_BEHAVIOR_PROFILES[role];
}

export function getPressureConservatism(profile: RoleBehaviorProfile, pressure: PressureLevel): number {
  if (pressure === PressureLevel.High) {
    return profile.pressureConservatism;
  }

  if (pressure === PressureLevel.Medium) {
    return Math.round(profile.pressureConservatism * 0.5);
  }

  return 0;
}
