import { createMatchTraceEvent, type MatchTraceEvent } from "./matchTraceEvent";

export function matchTraceAggregateFixture(): readonly MatchTraceEvent[] {
  return [
    createMatchTraceEvent({
      traceId: "trace-official-1",
      sourceEventId: "event-1",
      source: "official_match_event",
      matchId: "fixture-match",
      minute: 12,
      sequenceId: "sequence-1",
      teamId: "CONTROL",
      opponentTeamId: "BLITZ",
      phase: "FINAL_ZONE_ATTACK",
      zone: "Z5-C",
      actionType: "SHOT",
      outcome: "SHOT_CREATED",
      primaryPlayerId: "control-space-hunter",
      pressureLevel: "MEDIUM",
      causeTags: ["good_decision"],
      impactTags: ["danger_created"],
      dangerDelta: 22,
      possessionValueDelta: 4,
      coachVisible: true,
      diagnosticWeight: 80,
      officialTruth: true,
      tags: ["fixture_official_shot"],
      warnings: [],
    }),
    createMatchTraceEvent({
      traceId: "trace-mini-duplicate",
      sourceEventId: "event-1",
      source: "mini_match_record",
      matchId: "fixture-match",
      minute: 12,
      sequenceId: "sequence-1",
      teamId: "CONTROL",
      opponentTeamId: "BLITZ",
      phase: "FINAL_ZONE_ATTACK",
      zone: "Z5-C",
      actionType: "SHOT",
      outcome: "SHOT_CREATED",
      primaryPlayerId: "control-space-hunter",
      pressureLevel: "MEDIUM",
      causeTags: ["good_decision"],
      impactTags: ["danger_created"],
      dangerDelta: 20,
      possessionValueDelta: 3,
      coachVisible: true,
      diagnosticWeight: 60,
      officialTruth: false,
      tags: ["fixture_mini_duplicate"],
      warnings: [],
    }),
    createMatchTraceEvent({
      traceId: "trace-official-2",
      source: "official_match_event",
      matchId: "fixture-match",
      minute: 18,
      sequenceId: "sequence-2",
      teamId: "BLITZ",
      opponentTeamId: "CONTROL",
      phase: "HIGH_PRESS",
      zone: "Z3-HSL",
      actionType: "PRESSURE",
      outcome: "TURNOVER_CONCEDED",
      primaryPlayerId: "blitz-forward-leader",
      pressureLevel: "HIGH",
      causeTags: ["pressure_forced_error"],
      impactTags: ["possession_lost", "chance_conceded"],
      dangerDelta: -12,
      possessionValueDelta: -18,
      fatigueImpact: 3,
      coachVisible: true,
      diagnosticWeight: 74,
      officialTruth: true,
      tags: ["fixture_official_pressure_loss"],
      warnings: [],
    }),
    createMatchTraceEvent({
      traceId: "trace-mini-2",
      source: "mini_match_record",
      matchId: "fixture-match",
      minute: 19,
      sequenceId: "sequence-2",
      teamId: "CONTROL",
      opponentTeamId: "BLITZ",
      phase: "DEFENSIVE_TRANSITION",
      zone: "Z3-C",
      actionType: "RECOVERY",
      outcome: "RECOVERY_WON",
      primaryPlayerId: "control-mobile-lock",
      pressureLevel: "HIGH",
      causeTags: ["defensive_recovery"],
      impactTags: ["possession_secured"],
      dangerDelta: -5,
      possessionValueDelta: 12,
      coachVisible: true,
      diagnosticWeight: 58,
      officialTruth: false,
      tags: ["fixture_mini_recovery"],
      warnings: [],
    }),
    createMatchTraceEvent({
      traceId: "trace-sandbox-1",
      source: "sandbox_event",
      matchId: "fixture-match",
      minute: 20,
      sequenceId: "sandbox-sequence",
      teamId: "CONTROL",
      opponentTeamId: "BLITZ",
      phase: "GOALKEEPER_SEQUENCE",
      zone: "Z5-C",
      actionType: "GOALKEEPER_SAVE",
      outcome: "SAVE_MADE",
      goalkeeperId: "blitz-goalkeeper-free-safety",
      pressureLevel: "UNKNOWN",
      causeTags: ["goalkeeper_quality"],
      impactTags: ["shot_prevented"],
      dangerDelta: -15,
      possessionValueDelta: -4,
      coachVisible: false,
      diagnosticWeight: 42,
      officialTruth: false,
      tags: ["fixture_sandbox_goalkeeper"],
      warnings: [],
    }),
  ];
}

