export type MatchEvidenceScope =
  | "MINI_MATCH_LOCAL"
  | "FULL_MATCH_HARNESS_SINGLE_RUN"
  | "FULL_MATCH_BATCH_ECONOMY"
  | "BATCH_DIAGNOSTIC_PROJECTION"
  | "LIVE_SCORING_STREAM"
  | "REPORT_RENDERING_ONLY"
  | "WORKBENCH_CHAIN_CONSUMPTION"
  | "WORKBENCH_CHAIN_SEGMENT_CONTEXT"
  | "WORKBENCH_CHAIN_ROUTE_CANDIDATE_INFLUENCE"
  | "WORKBENCH_CHAIN_SHADOW_ROUTE_SELECTION"
  | "WORKBENCH_CHAIN_CONTROLLED_SEGMENT_SELECTION"
  | "WORKBENCH_CHAIN_SEGMENT_ROUTE_INPUT"
  | "WORKBENCH_CHAIN_CONTROLLED_MINIMATCH_ROUTE_SOURCE"
  | "WORKBENCH_CHAIN_LIVE_SELECTION_OVERRIDE_GUARD"
  | "WORKBENCH_CHAIN_ISOLATED_MINIMATCH_OVERRIDE_EXPERIMENT"
  | "WORKBENCH_CHAIN_CONTROLLED_SEGMENT_REPLAY_COMPARISON"
  | "WORKBENCH_CHAIN_REAL_ISOLATED_SEGMENT_REPLAY"
  | "WORKBENCH_CHAIN_CONTROLLED_ROUTE_RESOLUTION_SANDBOX"
  | "WORKBENCH_CHAIN_SANDBOX_SCORING_OPPORTUNITY_MODEL"
  | "WORKBENCH_CHAIN_SANDBOX_SCORING_EVENT_CANDIDATE"
  | "WORKBENCH_CHAIN_SANDBOX_SCORING_EVENT_RESOLUTION"
  | "WORKBENCH_CHAIN_ATTRIBUTE_DRIVEN_SHOT_RESOLUTION_SANDBOX"
  | "WORKBENCH_CHAIN_GOALKEEPER_RESPONSE_MODEL_SANDBOX"
  | "WORKBENCH_CHAIN_REBOUND_SECOND_CHANCE_SANDBOX"
  | "WORKBENCH_CHAIN_MULTI_ACTION_CONTINUATION_SANDBOX"
  | "WORKBENCH_CHAIN_SANDBOX_SEQUENCE_REPLAY"
  | "WORKBENCH_CHAIN_CONTROLLED_SEGMENT_SANDBOX_TIMELINE"
  | "WORKBENCH_CHAIN_OFFICIAL_TIMELINE_DIFF_VIEW"
  | "WORKBENCH_CHAIN_COACH_FACING_TIMELINE_REVIEW"
  | "WORKBENCH_CHAIN_SANDBOX_DECISION_PANEL"
  | "WORKBENCH_CHAIN_SANDBOX_DECISION_EVIDENCE_CALIBRATION"
  | "WORKBENCH_CHAIN_SANDBOX_DECISION_BATCH_CONFIDENCE_CALIBRATION"
  | "WORKBENCH_CHAIN_MULTI_SCENARIO_COACH_TEST_PLAN"
  | "WORKBENCH_CHAIN_SELECTION_PREVIEW"
  | "WORKBENCH_CHAIN_SELECTION_PREVIEW_TRACE_BACKING"
  | "WORKBENCH_CHAIN_SELECTION_PREVIEW_COACH_COPY"
  | "WORKBENCH_CHAIN_SELECTION_PREVIEW_PROFILE_VIEW"
  | "WORKBENCH_CHAIN_PLAYER_MATCHUP_VIEW"
  | "WORKBENCH_CHAIN_PLAYER_MATCHUP_CALIBRATION"
  | "WORKBENCH_CHAIN_ROSTER_COVERAGE_MATCHUP"
  | "WORKBENCH_CHAIN_PLAYER_CANDIDATE_COMPARISON_VIEW"
  | "WORKBENCH_CHAIN_COACH_PRODUCT_REPORT_VIEW"
  | "WORKBENCH_CHAIN_COACH_PRODUCT_REPORT_POLISH"
  | "WORKBENCH_CHAIN_COACH_REPORT_EXPORT_SNAPSHOT"
  | "WORKBENCH_CHAIN_MATCH_EVENT_TRACE_SPINE"
  | "WORKBENCH_CHAIN_MATCH_TRACE_AGGREGATOR"
  | "WORKBENCH_CHAIN_COACH_REPORT_FROM_TRACE_AGGREGATES"
  | "WORKBENCH_CHAIN_COACH_REPORT_V1_VISUALIZATION"
  | "WORKBENCH_CHAIN_COACH_REPORT_V1_INFORMATION_HIERARCHY"
  | "WORKBENCH_CHAIN_COACH_REPORT_V1_LEGACY_CLEANUP"
  | "WORKBENCH_CHAIN_FULL_MATCH_TRACE_VALIDATION"
  | "WORKBENCH_CHAIN_PROFILE_SIGNAL_CALIBRATION";

export interface MatchEvidenceScopeDefinition {
  readonly scope: MatchEvidenceScope;
  readonly canProve: readonly string[];
  readonly canSuggest?: readonly string[];
  readonly cannotProve: readonly string[];
  readonly cannotOverride?: readonly string[];
  readonly cannotInclude?: readonly string[];
  readonly globalScoringEconomyVerdictAllowed: boolean;
}

export const MATCH_EVIDENCE_SCOPE_REGISTRY: Readonly<Record<MatchEvidenceScope, MatchEvidenceScopeDefinition>> = {
  MINI_MATCH_LOCAL: {
    scope: "MINI_MATCH_LOCAL",
    canProve: [
      "local sequence behavior",
      "local scoring trace",
      "event rendering",
      "tactical evidence for a short sample",
    ],
    cannotProve: [
      "full-match scoring economy",
      "0-0 rate",
      "average points",
      "long-match fatigue economy",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  FULL_MATCH_HARNESS_SINGLE_RUN: {
    scope: "FULL_MATCH_HARNESS_SINGLE_RUN",
    canProve: [
      "report can handle match-like volume",
      "timeline remains chronological",
      "event IDs remain unique",
      "score consequences match final score",
      "report signals are readable or not",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy incoherence",
      "meta-risk",
      "average scoring plausibility",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  FULL_MATCH_BATCH_ECONOMY: {
    scope: "FULL_MATCH_BATCH_ECONOMY",
    canProve: [
      "global scoring plausibility",
      "average total points",
      "0-0 rate",
      "scoring event volume",
      "route mix",
      "score diversity",
      "meta-risk status",
    ],
    cannotProve: [],
    globalScoringEconomyVerdictAllowed: true,
  },
  BATCH_DIAGNOSTIC_PROJECTION: {
    scope: "BATCH_DIAGNOSTIC_PROJECTION",
    canProve: [],
    canSuggest: [
      "monitoring risks",
      "local calibration concerns",
      "route imbalance hypotheses",
    ],
    cannotProve: [
      "final live score",
      "canonical scoring constants",
    ],
    cannotOverride: [
      "live score",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  LIVE_SCORING_STREAM: {
    scope: "LIVE_SCORING_STREAM",
    canProve: [
      "final live score",
      "active scoring events",
      "score consistency",
      "inactive scoring leakage",
    ],
    cannotProve: [
      "global scoring economy",
      "batch scoring plausibility",
    ],
    cannotInclude: [
      "MatchBonusEvent points",
      "batch projection points",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  REPORT_RENDERING_ONLY: {
    scope: "REPORT_RENDERING_ONLY",
    canProve: [
      "HTML/Markdown rendering quality",
      "missing sections",
      "repetitive copy",
      "[object Object] bugs",
    ],
    cannotProve: [
      "engine scoring incoherence",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_CONSUMPTION: {
    scope: "WORKBENCH_CHAIN_CONSUMPTION",
    canProve: [
      "experimental workbench chain was consumed behind an opt-in flag",
      "visual chain steps were replayed for diagnostic grounding",
      "chain consumption remained diagnostic-only",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "full-match batch economy",
      "scoring constants",
      "production route selection",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SEGMENT_CONTEXT: {
    scope: "WORKBENCH_CHAIN_SEGMENT_CONTEXT",
    canProve: [
      "experimental workbench chain context was attached to a segment",
      "diagnostic timeline tags were emitted",
      "chain final carrier and zone were exposed as metadata",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_ROUTE_CANDIDATE_INFLUENCE: {
    scope: "WORKBENCH_CHAIN_ROUTE_CANDIDATE_INFLUENCE",
    canProve: [
      "experimental chain context influenced diagnostic route candidate scores",
      "closed and unavailable route candidates remained blocked",
      "diagnostic selection changes were shadow-only",
    ],
    cannotProve: [
      "global scoring balance",
      "production route selection quality",
      "full-match economy coherence",
    ],
    cannotOverride: [
      "live score",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SHADOW_ROUTE_SELECTION: {
    scope: "WORKBENCH_CHAIN_SHADOW_ROUTE_SELECTION",
    canProve: [
      "experimental chain context produced a diagnostic shadow route selection",
      "shadow selection rejected closed and unavailable candidates",
      "shadow selection comparison remained production-forbidden",
    ],
    cannotProve: [
      "global scoring balance",
      "production route selection quality",
      "full-match economy coherence",
    ],
    cannotOverride: [
      "live score",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_CONTROLLED_SEGMENT_SELECTION: {
    scope: "WORKBENCH_CHAIN_CONTROLLED_SEGMENT_SELECTION",
    canProve: [
      "experimental shadow route selection was exposed as controlled segment metadata",
      "controlled selection rejected closed and unavailable candidates",
      "controlled selection remained diagnostic-only",
    ],
    cannotProve: [
      "global scoring balance",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SEGMENT_ROUTE_INPUT: {
    scope: "WORKBENCH_CHAIN_SEGMENT_ROUTE_INPUT",
    canProve: [
      "experimental controlled segment selection was converted into typed segment route input metadata",
      "segment route input rejected closed and unavailable candidates",
      "segment route input remained diagnostic-only",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_CONTROLLED_MINIMATCH_ROUTE_SOURCE: {
    scope: "WORKBENCH_CHAIN_CONTROLLED_MINIMATCH_ROUTE_SOURCE",
    canProve: [
      "experimental segment route input was exposed as a controlled mini-match route source",
      "controlled mini-match route source rejected closed and unavailable candidates",
      "controlled mini-match route source remained diagnostic-only",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "live mini-match route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "live mini-match route resolution",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_LIVE_SELECTION_OVERRIDE_GUARD: {
    scope: "WORKBENCH_CHAIN_LIVE_SELECTION_OVERRIDE_GUARD",
    canProve: [
      "experimental controlled mini-match route source prepared a guarded live selection override candidate",
      "live selection override guard rejected closed and unavailable candidates",
      "live selection override guard remained diagnostic-only and unapplied",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "normal live mini-match route resolution",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_ISOLATED_MINIMATCH_OVERRIDE_EXPERIMENT: {
    scope: "WORKBENCH_CHAIN_ISOLATED_MINIMATCH_OVERRIDE_EXPERIMENT",
    canProve: [
      "experimental live selection override was applied inside an isolated mini-match comparison",
      "isolated override experiment compared baseline and override selections",
      "isolated override experiment rejected closed and unavailable candidates",
      "isolated override experiment remained separated from normal live selection and official scoring",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_CONTROLLED_SEGMENT_REPLAY_COMPARISON: {
    scope: "WORKBENCH_CHAIN_CONTROLLED_SEGMENT_REPLAY_COMPARISON",
    canProve: [
      "experimental baseline and override segment replay paths were compared in isolation",
      "controlled replay comparison observed selection, progression, and danger divergence",
      "controlled replay comparison rejected closed and unavailable candidates",
      "controlled replay comparison remained separated from normal live selection and official scoring",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_REAL_ISOLATED_SEGMENT_REPLAY: {
    scope: "WORKBENCH_CHAIN_REAL_ISOLATED_SEGMENT_REPLAY",
    canProve: [
      "experimental baseline and override segment replay paths generated isolated replay events",
      "isolated replay events are experimental-only and not official MatchEvents",
      "real isolated replay observed selection, carrier, progression, and danger divergence",
      "real isolated replay rejected closed and unavailable candidates",
      "real isolated replay remained separated from official timeline, normal live selection, and official scoring",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_CONTROLLED_ROUTE_RESOLUTION_SANDBOX: {
    scope: "WORKBENCH_CHAIN_CONTROLLED_ROUTE_RESOLUTION_SANDBOX",
    canProve: [
      "experimental baseline and override routes were resolved inside an isolated sandbox",
      "sandbox route outcomes exposed pressure, reception, risk, danger, and scoring-opportunity probabilities",
      "sandbox resolution rejected closed and unavailable candidates",
      "sandbox resolution remained separated from official timeline, normal live selection, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "production route selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_SCORING_OPPORTUNITY_MODEL: {
    scope: "WORKBENCH_CHAIN_SANDBOX_SCORING_OPPORTUNITY_MODEL",
    canProve: [
      "experimental sandbox route metrics were classified into typed scoring-opportunity signals",
      "baseline and override opportunity type, family, probability, and creation divergence were exposed",
      "sandbox opportunity classification rejected closed and unavailable candidates through the route-resolution sandbox",
      "sandbox opportunity classification remained separated from official timeline, normal live selection, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production scoring opportunity quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_SCORING_EVENT_CANDIDATE: {
    scope: "WORKBENCH_CHAIN_SANDBOX_SCORING_EVENT_CANDIDATE",
    canProve: [
      "experimental sandbox scoring opportunities were converted into typed scoring-event candidates",
      "baseline and override candidate type, family, probability, conversion probability, and creation divergence were exposed",
      "sandbox scoring-event candidates rejected closed and unavailable candidates through upstream sandbox guards",
      "sandbox scoring-event candidates remained separated from official timeline, normal live selection, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production scoring-event quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_SCORING_EVENT_RESOLUTION: {
    scope: "WORKBENCH_CHAIN_SANDBOX_SCORING_EVENT_RESOLUTION",
    canProve: [
      "experimental sandbox scoring-event candidates were resolved into sandbox-only tactical scoring outcomes",
      "baseline and override resolution type, shot attempt creation, shot quality, goalkeeper response, and divergence were exposed",
      "sandbox scoring-event resolution rejected closed and unavailable candidates through upstream sandbox guards",
      "sandbox scoring-event resolution remained separated from official timeline, normal live selection, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production scoring-event resolution quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_ATTRIBUTE_DRIVEN_SHOT_RESOLUTION_SANDBOX: {
    scope: "WORKBENCH_CHAIN_ATTRIBUTE_DRIVEN_SHOT_RESOLUTION_SANDBOX",
    canProve: [
      "experimental sandbox shot resolution used shooter, reception, pressure, target-zone, fatigue, mental freshness, and goalkeeper attributes",
      "baseline and override attribute-driven shot outcome, shot quality, goalkeeper response quality, and divergence were exposed",
      "attribute-driven sandbox shot resolution rejected closed and unavailable candidates through upstream sandbox guards",
      "attribute-driven sandbox shot resolution remained separated from official timeline, normal live selection, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production scoring-event resolution quality",
      "production goalkeeper model quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_GOALKEEPER_RESPONSE_MODEL_SANDBOX: {
    scope: "WORKBENCH_CHAIN_GOALKEEPER_RESPONSE_MODEL_SANDBOX",
    canProve: [
      "experimental goalkeeper response model used positioning, trajectory reading, reaction, handling, rebound control, concentration, mental fatigue, shot quality, and pressure context",
      "baseline and override goalkeeper response type, rebound state, save margin, and divergence were exposed",
      "goalkeeper response model consumed the attribute-driven shot resolution sandbox output",
      "goalkeeper response model remained separated from official timeline, normal live selection, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production goalkeeper model quality",
      "production shot outcome quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_REBOUND_SECOND_CHANCE_SANDBOX: {
    scope: "WORKBENCH_CHAIN_REBOUND_SECOND_CHANCE_SANDBOX",
    canProve: [
      "experimental rebound and second-chance sandbox consumed the goalkeeper response model output",
      "baseline and override rebound outcome, loose-ball state, recovery candidate, second-chance probability, and divergence were exposed",
      "current sandbox rebound result remained separated from official timeline, official possession, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production rebound model quality",
      "production second-chance conversion quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_MULTI_ACTION_CONTINUATION_SANDBOX: {
    scope: "WORKBENCH_CHAIN_MULTI_ACTION_CONTINUATION_SANDBOX",
    canProve: [
      "experimental multi-action continuation sandbox consumed the rebound second chance sandbox output",
      "baseline and override continuation action, outcome, team, actor, target zone, possession security, pressure, transition risk, confidence, and divergence were exposed",
      "current continuation result remained separated from official timeline, official possession, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production continuation model quality",
      "production second-action selection quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_SEQUENCE_REPLAY: {
    scope: "WORKBENCH_CHAIN_SANDBOX_SEQUENCE_REPLAY",
    canProve: [
      "experimental sandbox sequence replay consumed the route-resolution to multi-action-continuation sandbox chain",
      "baseline and override sequence paths were replayed as typed sandbox steps",
      "sequence replay exposed final outcome, team, actor, zone, and divergence metadata",
      "current sequence replay remained separated from official timeline, official possession, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production sequence replay quality",
      "production continuation model quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_CONTROLLED_SEGMENT_SANDBOX_TIMELINE: {
    scope: "WORKBENCH_CHAIN_CONTROLLED_SEGMENT_SANDBOX_TIMELINE",
    canProve: [
      "experimental sandbox sequence replay steps were projected into a controlled segment sandbox timeline",
      "baseline and override sandbox timeline paths expose event type order, final outcome, team, actor, and zone metadata",
      "sandbox timeline events are not official MatchEvents and are not inserted into the official MatchReport timeline",
      "current sandbox timeline remained separated from official timeline, official possession, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production timeline quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_OFFICIAL_TIMELINE_DIFF_VIEW: {
    scope: "WORKBENCH_CHAIN_OFFICIAL_TIMELINE_DIFF_VIEW",
    canProve: [
      "official full-match timeline event count, scoring-event count, score, and possession remain unchanged around the sandbox comparison",
      "baseline and override sandbox timelines are visible as sandbox-only rows",
      "sandbox timeline events are not official MatchEvents and are not inserted into the official MatchReport timeline",
      "current official timeline diff view remained read-only and separated from official possession, official scoring, production route resolution, and global route success rates",
    ],
    cannotProve: [
      "global scoring balance",
      "production timeline quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_FACING_TIMELINE_REVIEW: {
    scope: "WORKBENCH_CHAIN_COACH_FACING_TIMELINE_REVIEW",
    canProve: [
      "the coach-facing report can separate the official timeline from sandbox replay evidence",
      "the official timeline, official score, official possession, and official scoring events remain unchanged in the review",
      "sandbox replay events remain sandbox-only and are not presented as official MatchEvents",
      "technical sandbox details can be hidden behind coach-readable details without changing production state",
    ],
    cannotProve: [
      "global scoring balance",
      "production timeline quality",
      "production route resolution quality",
      "normal live mini-match route resolution quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "normal live mini-match route resolution",
      "official scoring events",
      "production route resolution",
      "production route selection",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_DECISION_PANEL: {
    scope: "WORKBENCH_CHAIN_SANDBOX_DECISION_PANEL",
    canProve: [
      "the coach-facing report can expose a sandbox decision suggestion without changing official match state",
      "the sandbox decision panel remains suggestion-only and cannot drive live selection",
      "the sandbox decision panel keeps official timeline, score, possession, and scoring events unchanged",
      "technical sandbox evidence can be converted into coach-readable test options",
    ],
    canSuggest: [
      "coach-facing tactical tests",
      "risks to monitor before production use",
      "unproven evidence gaps",
    ],
    cannotProve: [
      "global scoring balance",
      "production route quality",
      "normal live selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_DECISION_EVIDENCE_CALIBRATION: {
    scope: "WORKBENCH_CHAIN_SANDBOX_DECISION_EVIDENCE_CALIBRATION",
    canProve: [
      "the sandbox decision suggestion has bounded evidence scoring",
      "supporting and limiting evidence signals are visible for coach review",
      "single-chain sandbox evidence remains low-confidence when goalkeeper recovery and no batch confirmation are present",
      "calibrated sandbox evidence remains suggestion-only and cannot drive live selection",
    ],
    canSuggest: [
      "coach-facing tactical tests",
      "evidence confidence explanations",
      "future multi-scenario validation needs",
    ],
    cannotProve: [
      "global scoring balance",
      "production route quality",
      "normal live selection quality",
      "full-match economy coherence",
      "production chain-driven full-match behavior",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SANDBOX_DECISION_BATCH_CONFIDENCE_CALIBRATION: {
    scope: "WORKBENCH_CHAIN_SANDBOX_DECISION_BATCH_CONFIDENCE_CALIBRATION",
    canProve: [
      "the sandbox coach suggestion has been checked across multiple local sandbox scenarios",
      "average, minimum, and maximum local evidence scores are visible",
      "local batch confidence is capped at medium",
      "scenario variation does not mutate official match truth",
    ],
    canSuggest: [
      "coach-facing tactical tests",
      "whether a suggestion remains worth testing across local scenario variants",
      "what support, goalkeeper, fatigue, and rebound conditions affect the suggestion",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "team-wide tactical superiority",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_MULTI_SCENARIO_COACH_TEST_PLAN: {
    scope: "WORKBENCH_CHAIN_MULTI_SCENARIO_COACH_TEST_PLAN",
    canProve: [
      "local sandbox batch results can be translated into practical coach test hypotheses",
      "each test remains linked to a local sandbox scenario",
      "coach-facing wording can stay suggestive and non-official",
    ],
    canSuggest: [
      "which tactical test a coach might try next",
      "what positive signal to watch",
      "what risk remains visible",
      "what remains unproven by the local sandbox batch",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "team-wide tactical superiority",
      "that a coach must apply the test plan",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SELECTION_PREVIEW: {
    scope: "WORKBENCH_CHAIN_SELECTION_PREVIEW",
    canProve: [
      "local coach test hypotheses can be translated into selection preview profiles",
      "each preview remains linked to a coach test and local sandbox scenario",
      "lineup, starters, bench, and live selection remain unchanged",
    ],
    canSuggest: [
      "which role family could support each coach test",
      "which player attributes are relevant to preview",
      "what benefit and trade-off to watch",
      "what remains unproven before any real selection decision",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "team-wide tactical superiority",
      "that a coach must apply any selection preview",
      "that a real player should replace another player",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SELECTION_PREVIEW_TRACE_BACKING: {
    scope: "WORKBENCH_CHAIN_SELECTION_PREVIEW_TRACE_BACKING",
    canProve: [
      "official aggregate traces can support a Selection Preview hypothesis",
      "trace_supported remains non-applied and non-binding",
      "officially_confirmed exists as a future status but is not used",
    ],
    canSuggest: [
      "which Selection Preview cards have official support",
      "which official danger, recovery, cause, impact, player, goalkeeper, or second-ball signals support each preview",
      "which preview ideas remain sandbox_only",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any selection preview",
      "that a selection preview is officially confirmed",
      "that a real lineup change is recommended",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SELECTION_PREVIEW_COACH_COPY: {
    scope: "WORKBENCH_CHAIN_SELECTION_PREVIEW_COACH_COPY",
    canProve: [
      "Selection Preview coach copy separates sandbox origin, official trace support, non-applied decision, and non-official confirmation",
      "visible Selection Preview wording avoids official recommendation claims",
      "coach-copy guardrails preserve non-applied and non-binding status",
    ],
    canSuggest: [
      "which Selection Preview ideas are clearer for coach review",
      "which trace-supported cards deserve coach observation",
      "which copy limits should stay visible",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any selection preview",
      "that a selection preview is officially confirmed",
      "that a real lineup change is recommended",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_SELECTION_PREVIEW_PROFILE_VIEW: {
    scope: "WORKBENCH_CHAIN_SELECTION_PREVIEW_PROFILE_VIEW",
    canProve: [
      "Selection Preview profile view renders coach-readable profile cards",
      "profile cards expose role families, useful attributes, expected benefits, tactical risks, and next-match signals",
      "profile cards remain non-applied and non-official",
    ],
    canSuggest: [
      "which profile families are worth observing next match",
      "which attributes could be useful to watch",
      "which tactical risks should be checked before any future selection decision",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any profile view",
      "that a selection preview is officially confirmed",
      "that a real lineup change is recommended",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_PLAYER_MATCHUP_VIEW: {
    scope: "WORKBENCH_CHAIN_PLAYER_MATCHUP_VIEW",
    canProve: [
      "Player Matchup View can render profile-player compatibility comparisons",
      "candidate cards can expose visible strengths, gaps, risks, and next observation signals",
      "profile-player comparisons remain non-applied and non-official",
    ],
    canSuggest: [
      "which roster players could be studied for each profile",
      "which player attributes currently look close to the profile",
      "which missing attributes or tactical risks should be observed before any future decision",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a player must be selected",
      "that a lineup change is recommended",
      "that a profile-player matchup is officially confirmed",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_PLAYER_MATCHUP_CALIBRATION: {
    scope: "WORKBENCH_CHAIN_PLAYER_MATCHUP_CALIBRATION",
    canProve: [
      "Player Matchup Calibration can filter profile-player comparisons by role, attributes, and context",
      "goalkeeper outfield false positives can be excluded or penalized",
      "visible candidate diversity can be guarded against universal-player matching",
      "empty profile blocks can remain honest when no candidate clears the calibrated threshold",
    ],
    canSuggest: [
      "which player/profile pairs remain worth studying after calibration",
      "which player/profile pairs are excluded or penalized by role compatibility",
      "which profile blocks need more roster evidence before showing a candidate",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a player must be selected",
      "that a lineup change is recommended",
      "that a profile-player matchup is officially confirmed",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_ROSTER_COVERAGE_MATCHUP: {
    scope: "WORKBENCH_CHAIN_ROSTER_COVERAGE_MATCHUP",
    canProve: [
      "Roster Coverage Matchup can stress profile-player calibration across a richer roster",
      "candidate visibility, exclusions, penalties, and honest empty states remain measurable across the roster",
      "goalkeeper outfield exclusions and universal-player guards remain active on the richer roster",
    ],
    canSuggest: [
      "which players remain worth studying for each profile on a larger roster",
      "which profiles still lack credible candidates",
      "which players are visible for one profile but not for another",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a player must be selected",
      "that a lineup change is recommended",
      "that a profile-player matchup is officially confirmed",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_PLAYER_CANDIDATE_COMPARISON_VIEW: {
    scope: "WORKBENCH_CHAIN_PLAYER_CANDIDATE_COMPARISON_VIEW",
    canProve: [
      "Player Candidate Comparison View can compress a dense candidate pool into readable coach-facing comparison cards",
      "compact cards can expose why visible, distinctive strength, point to check, risk, and next-match signal",
      "extra candidates can move into collapsed details without selecting a player",
    ],
    canSuggest: [
      "which visible candidate should be studied first for a given profile",
      "which alternative or complementary profile should be compared next",
      "which differentiator should be checked in the next match before any future decision",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a player must be selected",
      "that a lineup change is recommended",
      "that a profile-player comparison is officially confirmed",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_PRODUCT_REPORT_VIEW: {
    scope: "WORKBENCH_CHAIN_COACH_PRODUCT_REPORT_VIEW",
    canProve: [
      "coach product report HTML is generated",
      "product report exposes an eight-section coach-facing reading order",
      "technical, sandbox, traceability, legacy, and validation material is moved to appendices",
      "profile suggestions remain non-applied and non-official",
    ],
    canSuggest: [
      "which official signals a coach can read first",
      "which profile observations should be checked next match",
      "which appendices to open for technical review",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that any profile must be selected",
      "that sandbox or diagnostic content is official truth",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_PRODUCT_REPORT_POLISH: {
    scope: "WORKBENCH_CHAIN_COACH_PRODUCT_REPORT_POLISH",
    canProve: [
      "coach product report polish checks are available",
      "product report review-ready presentation flags are true",
      "header, executive summary, key signals, profile cards, next-match signals, and appendices are readable",
      "print-friendly CSS is present",
      "profile suggestions remain non-applied and non-official",
    ],
    canSuggest: [
      "whether the product report is ready for review",
      "which report areas were polished for coach readability",
      "which appendices remain available for technical review",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that any profile must be selected",
      "that sandbox or diagnostic content is official truth",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_REPORT_EXPORT_SNAPSHOT: {
    scope: "WORKBENCH_CHAIN_COACH_REPORT_EXPORT_SNAPSHOT",
    canProve: [
      "coach report export snapshot is derived from coach-report.product.html",
      "print-ready export HTML keeps the same score, sections, candidate comparison, and interpretation guard",
      "print CSS and page-break CSS are present",
      "export remains non-prescriptive and non-mutating",
    ],
    canSuggest: [
      "whether the coach report can be shared outside the app as a print-ready snapshot",
      "whether PDF generation can stay optional while print-ready HTML is validated",
      "which export layout constraints still need UI wiring later",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that any player should be selected or recommended",
    ],
    cannotOverride: [
      "lineup",
      "starters",
      "bench",
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_MATCH_EVENT_TRACE_SPINE: {
    scope: "WORKBENCH_CHAIN_MATCH_EVENT_TRACE_SPINE",
    canProve: [
      "official match events can be represented as read-only trace events",
      "mini-match records can be represented as diagnostic trace events",
      "sandbox events can be represented as non-official trace events",
      "trace sources remain separated by officialTruth",
      "trace events expose phase, zone, action, outcome, cause, and impact fields",
    ],
    canSuggest: [
      "which future aggregate dimensions should feed coach reports",
      "which future diagnostics can consume trace evidence",
      "where unknown mappings need richer source data later",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "future trace aggregate quality",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_MATCH_TRACE_AGGREGATOR: {
    scope: "WORKBENCH_CHAIN_MATCH_TRACE_AGGREGATOR",
    canProve: [
      "read-only trace rows can be aggregated into official, diagnostic, and sandbox scopes",
      "official aggregates exclude sandbox traces",
      "diagnostic aggregates remain non-official support",
      "sandbox aggregates remain hypothetical",
      "source-priority deduplication is visible and bounded",
    ],
    canSuggest: [
      "which future coach-report facts may be built from official aggregates",
      "which diagnostic or sandbox traces need richer source data later",
      "where future trace-backed selection preview confidence may need evidence",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that selection preview confidence should be upgraded",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_REPORT_FROM_TRACE_AGGREGATES: {
    scope: "WORKBENCH_CHAIN_COACH_REPORT_FROM_TRACE_AGGREGATES",
    canProve: [
      "official trace aggregates can seed cautious coach-facing cards",
      "diagnostic aggregates remain separated from official conclusions",
      "sandbox aggregates remain separated from official conclusions",
      "selection preview remains sandbox-backed and not upgraded",
      "coach-facing trace cards remain read-only",
    ],
    canSuggest: [
      "zones to monitor",
      "pressure-loss watchpoints",
      "recovery patterns to verify",
      "recurring official trace causes",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any recommendation",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_REPORT_V1_VISUALIZATION: {
    scope: "WORKBENCH_CHAIN_COACH_REPORT_V1_VISUALIZATION",
    canProve: [
      "official trace aggregate cards can be rendered as coach-facing visual summaries",
      "every visible V1 card can expose source and confidence badges",
      "diagnostic and sandbox evidence remain separated from official conclusions",
      "empty pressure-loss zone states can be represented without inventing a zone",
      "coach-facing visualization remains read-only",
    ],
    canSuggest: [
      "which official signals deserve coach attention",
      "which official zones are stable enough to visualize",
      "which signals need more samples before stronger interpretation",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any recommendation",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_REPORT_V1_INFORMATION_HIERARCHY: {
    scope: "WORKBENCH_CHAIN_COACH_REPORT_V1_INFORMATION_HIERARCHY",
    canProve: [
      "official Coach Report V1 sections can be rendered before sandbox and diagnostic sections",
      "experimental content can be grouped as secondary and collapsed by default",
      "technical traceability can remain available without dominating visible coach reading",
      "information hierarchy remains read-only",
    ],
    canSuggest: [
      "which official reading order is easier for coach review",
      "which experimental sections should stay grouped for future testing",
      "which technical markers should remain collapsed",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any recommendation",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_COACH_REPORT_V1_LEGACY_CLEANUP: {
    scope: "WORKBENCH_CHAIN_COACH_REPORT_V1_LEGACY_CLEANUP",
    canProve: [
      "legacy key moments and coach analysis can be collapsed under technical traceability",
      "visible score labels can distinguish full-match report score from live scoring-event samples and batch diagnostics",
      "visible French coach copy can be normalized without changing match logic",
      "legacy cleanup remains read-only",
    ],
    canSuggest: [
      "which legacy sections should remain available for traceability",
      "which visible report labels need copy cleanup",
      "where score-source wording should appear",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that legacy content is official V1 evidence unless absorbed from official aggregates",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_FULL_MATCH_TRACE_VALIDATION: {
    scope: "WORKBENCH_CHAIN_FULL_MATCH_TRACE_VALIDATION",
    canProve: [
      "multiple validation profiles can run through full-match trace spine, trace aggregator, and Coach Report V0",
      "official aggregate emphasis changes when match profile inputs change",
      "diagnostic and sandbox aggregates remain separated from official conclusions",
      "selection preview remains sandbox_only and is not upgraded",
    ],
    canSuggest: [
      "which Coach Report V0 cards are sensitive enough for future visualization",
      "which expected profile signals remain weak or missing",
      "where future Coach Report V1 evidence should deepen profile-specific language",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any recommendation",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
  WORKBENCH_CHAIN_PROFILE_SIGNAL_CALIBRATION: {
    scope: "WORKBENCH_CHAIN_PROFILE_SIGNAL_CALIBRATION",
    canProve: [
      "validation profiles expose expected or accepted fallback tactical signals",
      "generated profile validation artifacts are free of mojibake markers",
      "profile signal calibration remains separate from official state mutation",
      "selection preview remains sandbox_only and is not upgraded",
    ],
    canSuggest: [
      "which profile signals are strong enough for future Coach Report V1 visualization",
      "which profiles still rely on fallback evidence",
      "where future fixtures should deepen tactical distinction",
    ],
    cannotProve: [
      "global scoring balance",
      "full-match economy coherence",
      "production route quality",
      "normal live selection quality",
      "that a coach must apply any recommendation",
    ],
    cannotOverride: [
      "live score",
      "official timeline",
      "official possession",
      "official scoring events",
      "normal live selection",
      "production route resolution",
      "full-match batch economy",
      "scoring constants",
    ],
    globalScoringEconomyVerdictAllowed: false,
  },
} as const;
