export enum FocusCategory {
  WeakSideAttack = "WEAK_SIDE_ATTACK",
  OverloadCreation = "OVERLOAD_CREATION",
  DelayedRecovery = "DELAYED_RECOVERY",
  PressBreak = "PRESS_BREAK",
  CounterpressCollapse = "COUNTERPRESS_COLLAPSE",
  DepthAttack = "DEPTH_ATTACK",
  FinishingWindow = "FINISHING_WINDOW",
  TransitionEscape = "TRANSITION_ESCAPE",
  StructureReset = "STRUCTURE_RESET",
  SupportTriangle = "SUPPORT_TRIANGLE",
  GoalkeeperSweep = "GOALKEEPER_SWEEP",
  ChaosRecovery = "CHAOS_RECOVERY",
  ReboundPhase = "REBOUND_PHASE",
  LastLineBreak = "LAST_LINE_BREAK",
  CentralCombination = "CENTRAL_COMBINATION",
  WidthIsolation = "WIDTH_ISOLATION",
}
