import type { CurrentSharePackConfig } from "./sharePackTypes";

export const currentSprint: CurrentSharePackConfig = {
  name: "Sprint 2P - Canonical MatchReport Alignment + Report Evidence Contract",
  mode: "MINIMAL_REVIEW",
  requiredFiles: [
    "package.json",
    "tsconfig.json",
    "coach-report.latest.html",
    "scoring-events-summary.md",
    "validation.share-pack.md",
    "canonical-matchreport-evidence-contract.md",
    "validation.canonical-matchreport-evidence-contract.md",
    "README.md",
    "manifest.md",
    "00-share-manifest.txt",
    "bundle__contracts.md",
    "bundle__simulation.md",
    "bundle__reports.md",
    "bundle__docs.md",
  ],
  optionalFiles: [],
  excludedByDefault: [],
  fileReasons: {
    "package.json": "records npm scripts and the canonical MatchReport contract guard wiring",
    "tsconfig.json": "records the TypeScript compiler setup for the canonical evidence contract work",
    "coach-report.latest.html": "latest generated coach HTML sample consuming typed MatchReport warnings",
    "scoring-events-summary.md": "live scoring summary proving scoring values and score events remain intact",
    "validation.share-pack.md": "proves the Sprint 2P share pack is current, complete, and below 20 files",
    "canonical-matchreport-evidence-contract.md": "documents canonical evidenceFacts, warnings, and reportMeta alignment",
    "validation.canonical-matchreport-evidence-contract.md": "validates typed evidence, structured warnings, and preserved scoring guardrails",
    "README.md": "compact reviewer orientation for the Sprint 2P share pack",
    "manifest.md": "compatibility manifest listing the Sprint 2P share pack files",
    "00-share-manifest.txt": "detailed generated manifest with bundle contents and missing-file status",
    "bundle__contracts.md": "bundles official engine-to-coach contracts, evidence/warning contracts, and contract guards",
    "bundle__simulation.md": "bundles runMatch/runFullMatch, canonical evidence builders, warnings, moments, focus, and harness tests",
    "bundle__reports.md": "bundles coach report renderer, copy quality utilities, guards, and share-pack updater",
    "bundle__docs.md": "bundles engine-to-coach review documentation",
  },
};
