import type { CurrentSharePackConfig } from "./sharePackTypes";

export const currentSprint: CurrentSharePackConfig = {
  name: "Sprint 2N - Segment Diversity + Fatigue Propagation + Key Moment Diversity",
  mode: "MINIMAL_REVIEW",
  requiredFiles: [
    "package.json",
    "tsconfig.json",
    "coach-report.latest.html",
    "scoring-events-summary.md",
    "validation.share-pack.md",
    "full-match-segment-diversity-fatigue.md",
    "validation.full-match-segment-diversity-fatigue.md",
    "README.md",
    "manifest.md",
    "00-share-manifest.txt",
    "bundle__contracts.md",
    "bundle__simulation.md",
    "bundle__reports.md",
    "bundle__docs.md",
  ],
  optionalFiles: [],
  excludedByDefault: [],
  fileReasons: {
    "package.json": "records the Sprint 2N npm commands and contract test wiring",
    "tsconfig.json": "records the TypeScript compiler setup for the full-match harness work",
    "coach-report.latest.html": "latest generated coach HTML sample with segment/fatigue/key-moment improvements",
    "scoring-events-summary.md": "live scoring summary proving scoring values and score events remain intact",
    "validation.share-pack.md": "proves the Sprint 2N share pack is current, complete, and below 20 files",
    "full-match-segment-diversity-fatigue.md": "documents Sprint 2N segment state, fatigue propagation, diversity diagnostics, and key moment diversity",
    "validation.full-match-segment-diversity-fatigue.md": "validates Sprint 2N full-match harness improvements and preserved source-of-truth guardrails",
    "README.md": "compact reviewer orientation for the Sprint 2N share pack",
    "manifest.md": "compatibility manifest listing the Sprint 2N share pack files",
    "00-share-manifest.txt": "detailed generated manifest with bundle contents and missing-file status",
    "bundle__contracts.md": "bundles official engine-to-coach contracts and contract guards",
    "bundle__simulation.md": "bundles runFullMatch, segment state, fatigue propagation, diversity diagnostics, source-of-truth guards, and harness tests",
    "bundle__reports.md": "bundles share-pack updater and coach report generation/guard sources",
    "bundle__docs.md": "bundles engine-to-coach review documentation",
  },
};
