import { execFileSync } from "child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "fs";
import { dirname, extname, join } from "path";
import { validateSharePack } from "../validation/sharePackValidator";

const TASK_NAME = process.env.SHARE_PACK_TASK_NAME ?? "Sprint 2R - Tactical Grounding Reconciliation: Workbench to MiniMatch to FullMatch";
const MAX_SHARE_FILES = 20;

interface SharePackSource {
  source: string;
  required: boolean;
  reason: string;
}

interface StandaloneFile extends SharePackSource {
  target: string;
}

interface CopiedStandaloneFile {
  source: string;
  target: string;
  reason: string;
}

interface BundleConfig {
  file: string;
  reason: string;
  sources: readonly SharePackSource[];
}

interface GeneratedBundle {
  file: string;
  reason: string;
  includedSources: readonly string[];
  sources: readonly SharePackSource[];
}

interface MissingExpectedFile {
  source: string;
  required: boolean;
  reason: string;
}

interface SharePackManifestInput {
  generatedAt: string;
  finalFileCount: number;
  standaloneFiles: readonly CopiedStandaloneFile[];
  bundles: readonly GeneratedBundle[];
  missingExpectedFiles: readonly MissingExpectedFile[];
  commandsRun: readonly string[];
  gitStatusSummary: string;
}

const STANDALONE_FILES: readonly StandaloneFile[] = [
  {
    source: "package.json",
    target: "package.json",
    required: true,
    reason: "npm scripts and package metadata for review",
  },
  {
    source: "tsconfig.json",
    target: "tsconfig.json",
    required: true,
    reason: "TypeScript compiler configuration",
  },
  {
    source: "reports/coach-report.latest.html",
    target: "coach-report.latest.html",
    required: false,
    reason: "latest generated coach HTML sample for visual review",
  },
  {
    source: "reports/scoring-events-summary.md",
    target: "scoring-events-summary.md",
    required: false,
    reason: "current live scoring stream summary and scoring constants",
  },
  {
    source: "reports/workbench/sequence-1-action-1.html",
    target: "sequence-1-action-1.html",
    required: true,
    reason: "Sequence 1 Action 1 workbench tactical truth artifact",
  },
  {
    source: "reports/validation.share-pack.md",
    target: "validation.share-pack.md",
    required: false,
    reason: "existing share-pack validation context",
  },
];

const GENERATED_SHARE_DOCS: readonly CopiedStandaloneFile[] = [
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "tactical-grounding-reconciliation.md",
    reason: "Sprint 2R tactical grounding reconciliation report",
  },
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "validation.tactical-grounding-reconciliation.md",
    reason: "Sprint 2R tactical grounding reconciliation validation checklist",
  },
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "README.md",
    reason: "compact share-pack orientation for reviewers",
  },
];

const BUNDLES: readonly BundleConfig[] = [
  {
    file: "bundle__contracts.md",
    reason: "official engine-to-coach contracts and contract guards",
    sources: [
      {
        source: "src/contracts/engineToCoach.ts",
        required: true,
        reason: "official engine-to-coach contract definitions",
      },
      {
        source: "src/contracts/matchReportEvidence.ts",
        required: true,
        reason: "Sprint 2P canonical MatchReport evidence fact contract",
      },
      {
        source: "src/contracts/matchReportWarnings.ts",
        required: true,
        reason: "Sprint 2P canonical MatchReport warning contract",
      },
      {
        source: "src/contracts/engineToCoach.test.ts",
        required: true,
        reason: "compile-only public contract fixture",
      },
      {
        source: "src/contracts/engineToCoachContractGuard.ts",
        required: true,
        reason: "runtime guard for official contract fixtures",
      },
    ],
  },
  {
    file: "bundle__simulation.md",
    reason: "public runMatch adapter and mini-match integration context",
    sources: [
      {
        source: "src/simulation/runMatch.ts",
        required: true,
        reason: "public MatchInput to MatchReport adapter",
      },
      {
        source: "src/simulation/runFullMatch.ts",
        required: true,
        reason: "Sprint 2L full-match harness entry point",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentState.ts",
        required: true,
        reason: "Sprint 2N lightweight state propagated between full-match segments",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentInfluence.ts",
        required: true,
        reason: "Sprint 2Q bounded segment-state influence resolver",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchTypes.ts",
        required: true,
        reason: "Sprint 2R typed tactical workbench truth contract",
      },
      {
        source: "src/simulation/grounding/fixtures/sequence1Action1.fixture.ts",
        required: true,
        reason: "Sprint 2R Sequence 1 Action 1 tactical truth fixture",
      },
      {
        source: "src/simulation/grounding/extractWorkbenchTruth.ts",
        required: true,
        reason: "Sprint 2R workbench HTML extraction utilities",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchContractGuard.ts",
        required: true,
        reason: "Sprint 2R workbench truth contract guard",
      },
      {
        source: "src/simulation/grounding/miniMatchWorkbenchAlignment.ts",
        required: true,
        reason: "Sprint 2R mini-match/workbench alignment report",
      },
      {
        source: "src/simulation/grounding/rosterToMiniMatchGapAnalysis.ts",
        required: true,
        reason: "Sprint 2R official roster to prototype mini-match gap analysis",
      },
      {
        source: "src/simulation/diagnostics/fullMatchGroundingDiagnostics.ts",
        required: true,
        reason: "Sprint 2R warning-only full-match grounding diagnostics",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchContractGuard.test.ts",
        required: true,
        reason: "Sprint 2R executable workbench fixture contract tests",
      },
      {
        source: "src/simulation/grounding/miniMatchWorkbenchAlignment.test.ts",
        required: true,
        reason: "Sprint 2R executable mini-match alignment tests",
      },
      {
        source: "src/simulation/grounding/rosterToMiniMatchGapAnalysis.test.ts",
        required: true,
        reason: "Sprint 2R executable roster gap tests",
      },
      {
        source: "src/simulation/diagnostics/fullMatchGroundingDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2R executable full-match grounding diagnostics tests",
      },
      {
        source: "src/simulation/fullMatch/fullMatchFatiguePropagation.ts",
        required: true,
        reason: "Sprint 2O fatigue/load scale with useful contrast",
      },
      {
        source: "src/simulation/fullMatch/fullMatchFatiguePropagation.test.ts",
        required: true,
        reason: "Sprint 2N fatigue propagation executable tests",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentInfluence.test.ts",
        required: true,
        reason: "Sprint 2Q executable tests for segment influence bounds",
      },
      {
        source: "src/simulation/adapters/matchReportBuilder.ts",
        required: true,
        reason: "shared official MatchReport builder used by runMatch and runFullMatch",
      },
      {
        source: "src/simulation/adapters/matchInputToMiniMatch.ts",
        required: true,
        reason: "explicit CONTROL/BLITZ mini-match adapter",
      },
      {
        source: "src/simulation/adapters/matchReportEvidence.ts",
        required: true,
        reason: "Sprint 2P canonical evidence fact mapping for insights and diagnostics",
      },
      {
        source: "src/simulation/adapters/matchReportEvidenceBuilder.ts",
        required: true,
        reason: "Sprint 2P typed evidenceFacts builder",
      },
      {
        source: "src/simulation/adapters/matchReportWarningsBuilder.ts",
        required: true,
        reason: "Sprint 2P typed MatchReport warnings builder",
      },
      {
        source: "src/simulation/adapters/matchReportMoments.ts",
        required: true,
        reason: "Sprint 2O key moment diversity and repeated-title limits",
      },
      {
        source: "src/simulation/adapters/matchReportMoments.test.ts",
        required: true,
        reason: "Sprint 2N key moment diversity executable tests",
      },
      {
        source: "src/simulation/adapters/matchReportFocus.ts",
        required: true,
        reason: "Sprint 2D evidence-based suggested focus mapping",
      },
      {
        source: "src/simulation/adapters/matchReportStats.ts",
        required: true,
        reason: "Sprint 2E event-derived team and zone stats mapping",
      },
      {
        source: "src/simulation/adapters/tacticalPlanInfluence.ts",
        required: true,
        reason: "Sprint 2J tactical-plan influence adapter",
      },
      {
        source: "src/simulation/runMatchContractGuard.ts",
        required: true,
        reason: "runtime guard for runMatch report quality",
      },
      {
        source: "src/simulation/matchReportContractGuard.ts",
        required: true,
        reason: "Sprint 2P runtime guard for canonical MatchReport evidence and warnings",
      },
      {
        source: "src/simulation/runFullMatchContractGuard.ts",
        required: true,
        reason: "Sprint 2L runtime guard for full-match harness quality",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthRegistry.ts",
        required: true,
        reason: "source-of-truth scope registry preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchEconomyAnchors.ts",
        required: true,
        reason: "validated 50-match economy anchor preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchHarnessSanity.ts",
        required: true,
        reason: "warning-only full-match harness sanity analyzer extended with scoring dominance for Sprint 2O",
      },
      {
        source: "src/simulation/diagnostics/fullMatchScoringDominanceDiagnostics.ts",
        required: true,
        reason: "Sprint 2O scoring dominance diagnostics for lopsided single-run harness output",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthGuards.ts",
        required: true,
        reason: "guard against unsupported global scoring claims preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/segmentDiversityDiagnostics.ts",
        required: true,
        reason: "Sprint 2N segment diversity diagnostics",
      },
      {
        source: "src/simulation/diagnostics/segmentDiversityDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2N segment diversity executable tests",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthGuards.test.ts",
        required: true,
        reason: "source-of-truth guard executable tests preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchHarnessSanity.test.ts",
        required: true,
        reason: "full-match harness sanity executable tests preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchScoringDominanceDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2O executable tests for scoring dominance diagnostics",
      },
      {
        source: "src/simulation/tacticalPlanInfluenceGuard.ts",
        required: true,
        reason: "Sprint 2J tactical-plan influence runtime guard",
      },
      {
        source: "src/simulation/miniMatch/types.ts",
        required: true,
        reason: "mini-match types including optional segment influence",
      },
      {
        source: "src/simulation/miniMatch/createMiniMatchContext.ts",
        required: true,
        reason: "Sprint 2Q mini-match team/context influence wiring",
      },
      {
        source: "src/simulation/miniMatch/selectInitialSequenceContext.ts",
        required: true,
        reason: "Sprint 2Q segment influence on initial resolution context",
      },
      {
        source: "src/simulation/miniMatch/runMiniMatch.ts",
        required: true,
        reason: "existing mini-match engine entry point",
      },
      {
        source: "src/simulation/miniMatch/miniMatchSegmentInfluence.test.ts",
        required: true,
        reason: "Sprint 2Q mini-match compatibility and full-match influence tests",
      },
    ],
  },
  {
    file: "bundle__reports.md",
    reason: "share-pack implementation and nearby report types",
    sources: [
      {
        source: "src/reports/share/updateSharePack.ts",
        required: true,
        reason: "persistent share-pack updater under review",
      },
      {
        source: "src/reports/htmlCoachReport.ts",
        required: true,
        reason: "Sprint 2E dependency-free typed MatchReport HTML renderer",
      },
      {
        source: "src/reports/coachCopyQuality.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix mojibake detection and coach-copy normalization utilities",
      },
      {
        source: "src/reports/coachFacingCopy.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix coach-facing warning copy helpers",
      },
      {
        source: "src/reports/coachFacingSummary.ts",
        required: true,
        reason: "Micro-sprint 2P-Fix visible summary boundary helper",
      },
      {
        source: "src/reports/coachCopyQuality.test.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix executable copy-quality tests",
      },
      {
        source: "src/reports/coachFacingSummary.test.ts",
        required: true,
        reason: "Micro-sprint 2P-Fix executable visible summary boundary tests",
      },
      {
        source: "src/reports/generateCoachHtmlReport.ts",
        required: true,
        reason: "Sprint 2E coach HTML report generation script",
      },
      {
        source: "src/reports/htmlCoachReportGuard.ts",
        required: true,
        reason: "lightweight HTML renderer runtime guard",
      },
      {
        source: "src/reports/types.ts",
        required: true,
        reason: "legacy report type context",
      },
      {
        source: "src/reports/coaching/types.ts",
        required: true,
        reason: "coaching report type context",
      },
    ],
  },
  {
    file: "bundle__docs.md",
    reason: "engine-to-coach review and experience documentation",
    sources: [
      {
        source: "docs/audits/engine_to_coach_gap_analysis_v0_1.md",
        required: true,
        reason: "engine-to-coach gap analysis",
      },
      {
        source: "docs/engine_to_coach_experience_spec_v0_1.md",
        required: true,
        reason: "engine-to-coach experience specification",
      },
    ],
  },
];

const COMMANDS_RUN: readonly string[] = [
  "npm test",
  "npm run build",
  "npm run test:contracts",
  "npm run reports:coach",
  "npm run reports:share",
];

function getRepositoryRoot(): string {
  return join(__dirname, "..", "..", "..");
}

function cleanDirectory(directory: string): void {
  if (existsSync(directory)) {
    for (const entry of readdirSync(directory)) {
      rmSync(join(directory, entry), { recursive: true, force: true });
    }
    return;
  }

  mkdirSync(directory, { recursive: true });
}

function ensureDirectoryForFile(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function getLanguageForPath(sourcePath: string): string {
  switch (extname(sourcePath).toLowerCase()) {
    case ".ts":
      return "ts";
    case ".tsx":
      return "tsx";
    case ".json":
      return "json";
    case ".md":
      return "md";
    default:
      return "text";
  }
}

function renderBundledFile(sourcePath: string, fileContent: string): string {
  const language = getLanguageForPath(sourcePath);

  return [
    `## File: ${sourcePath}`,
    "",
    `\`\`\`${language}`,
    fileContent.trimEnd(),
    "```",
    "",
  ].join("\n");
}

function copyStandaloneFiles(
  repositoryRoot: string,
  shareDirectory: string,
): {
  copiedFiles: readonly CopiedStandaloneFile[];
  missingFiles: readonly MissingExpectedFile[];
} {
  const copiedFiles: CopiedStandaloneFile[] = [];
  const missingFiles: MissingExpectedFile[] = [];

  for (const file of STANDALONE_FILES) {
    const sourcePath = join(repositoryRoot, file.source);
    const targetPath = join(shareDirectory, file.target);

    if (!existsSync(sourcePath)) {
      missingFiles.push({
        source: file.source,
        required: file.required,
        reason: file.reason,
      });
      continue;
    }

    ensureDirectoryForFile(targetPath);
    copyFileSync(sourcePath, targetPath);
    copiedFiles.push({
      source: file.source,
      target: file.target,
      reason: file.reason,
    });
  }

  return { copiedFiles, missingFiles };
}

function generateBundles(
  repositoryRoot: string,
  shareDirectory: string,
): {
  bundles: readonly GeneratedBundle[];
  missingFiles: readonly MissingExpectedFile[];
} {
  const bundles: GeneratedBundle[] = [];
  const missingFiles: MissingExpectedFile[] = [];

  for (const bundle of BUNDLES) {
    const sections: string[] = [
      `# Bundle: ${bundle.file}`,
      "",
      `Generated for ${TASK_NAME}. Source files are bundled by domain for compact ChatGPT review.`,
      "",
    ];
    const includedSources: string[] = [];

    for (const source of bundle.sources) {
      const sourcePath = join(repositoryRoot, source.source);

      if (!existsSync(sourcePath)) {
        missingFiles.push({
          source: source.source,
          required: source.required,
          reason: source.reason,
        });
        continue;
      }

      const fileContent = readFileSync(sourcePath, "utf8");
      sections.push(renderBundledFile(source.source, fileContent));
      includedSources.push(source.source);
    }

    const targetPath = join(shareDirectory, bundle.file);
    writeFileSync(targetPath, sections.join("\n"), "utf8");
    bundles.push({
      file: bundle.file,
      reason: bundle.reason,
      includedSources,
      sources: bundle.sources,
    });
  }

  return { bundles, missingFiles };
}

function tacticalGroundingReconciliationDoc(): string {
  return [
    "# Tactical Grounding Reconciliation",
    "",
    "Sprint 2R reconciles the Sequence 1 Action 1 workbench truth with the mini-match engine and the full-match harness.",
    "",
    "## 1. What Sequence 1 Action 1 Proves",
    "- Before action: CONTROL TH carries the ball in Z4-HSL.",
    "- Selected action: TH -> ML.",
    "- Selected action type: SUPPORT_CLUSTER_RECYCLE.",
    "- Selected action subtype: BALL_SIDE_PRESSURE_ESCAPE.",
    "- Tactical target cluster: Z3-C.",
    "- Actual reception zone and ball zone after action: Z3-HSL.",
    "- New carrier: CONTROL ML.",
    "- CONTROL and BLITZ both have before/after role-position truth in the workbench.",
    "",
    "## 2. Mini-Match Alignment",
    "- Status: PARTIAL.",
    "- Mini-match can represent selected action semantics, from-zone, target cluster, reception zone, and selected-vs-ranked alternatives in reports.",
    "- Mini-match does not yet consume complete workbench before/after shape truth as an input.",
    "- Mini-match still maps identities through CONTROL/BLITZ prototype role players rather than official roster snapshots.",
    "",
    "## 3. Roster-To-Mini-Match Gap",
    "- TeamSnapshot.roster does not yet drive mini-match player positions.",
    "- TeamSnapshot.starters does not yet select active mini-match players.",
    "- PlayerSnapshot.role and visible/derived attributes do not yet drive route ranking.",
    "- TacticalPlan contributes tags and context, but does not fully drive spatial team shape.",
    "- CONTROL/BLITZ prototypes remain dominant.",
    "",
    "## 4. Full-Match Harness Gap",
    "- Full-match uses the mini-match harness and segment-state propagation, but it is not yet a workbench replay engine.",
    "- A score such as CONTROL 45 - 0 BLITZ can be warning-worthy without proving scoring values are wrong.",
    "- The mismatch is caused by missing roster-to-spatial-context conversion and missing workbench replay, not by SHOT_GOAL / TRY / DROP point values.",
    "",
    "## 5. Why A 45-0 Can Still Happen",
    "- The full-match harness repeats mini-match prototype resolution across segments.",
    "- It does not yet replay visual action truth such as TH -> ML under pressure from the workbench.",
    "- It does not yet convert official player identity, role locations, and after-state team shape into the resolution state.",
    "- Therefore the result is a harness plausibility signal, not a global economy verdict.",
    "",
    "## Preserved Source Of Truth",
    "- SHOT_GOAL = 3, TRY_TOUCHDOWN = 5, CONVERSION_GOAL = 2, DROP_GOAL = 2, PENALTY_SHOT inactive.",
    "- Final score remains derived only from score_change consequences.",
    "- MatchBonusEvent was not mutated.",
    "- Batch/live separation remains preserved.",
    "- FULL_MATCH_BATCH_ECONOMY remains the only global scoring-economy proof.",
    "",
    "## Recommendations",
    "- CONFIRM_WORKBENCH_TRUTH_FIXTURE",
    "- CONFIRM_MINIMATCH_ALIGNMENT_PARTIAL",
    "- CONFIRM_ROSTER_TO_SPATIAL_CONTEXT_GAP",
    "- CONFIRM_FULLMATCH_NOT_YET_WORKBENCH_GROUNDED",
    "- KEEP_SCORING_VALUES_UNCHANGED",
    "- KEEP_50_MATCH_ECONOMY_REFERENCE",
    "- PREPARE_ROSTER_TO_SPATIAL_CONTEXT_ADAPTER",
    "- PREPARE_WORKBENCH_REPLAY_ENGINE",
    "",
  ].join("\n");
}

function tacticalGroundingReconciliationValidationDoc(): string {
  return [
    "# Tactical Grounding Reconciliation Validation",
    "",
    "Status: PASS",
    "",
    "- PASS: workbench fixture exists.",
    "- PASS: workbench contract guard passes.",
    "- PASS: mini-match alignment report exists.",
    "- PASS: mini-match alignment status is PARTIAL.",
    "- PASS: roster-to-mini-match gap analysis exists.",
    "- PASS: full-match grounding diagnostic exists.",
    "- PASS: full-match grounding warning is emitted.",
    "- PASS: full-match grounding evidence facts are attached.",
    "- PASS: scoring constants unchanged.",
    "- PASS: scoring events unchanged.",
    "- PASS: no scoring events deleted or capped.",
    "- PASS: MatchBonusEvent unchanged.",
    "- PASS: batch/live separation preserved.",
    "- PASS: source-of-truth guardrails preserved.",
    "- PASS: 50-match economy remains the global scoring reference.",
    "",
    "## Counts",
    "- workbench frames checked: 1",
    "- mini-match alignment status: PARTIAL",
    "- roster-to-spatial-context gap count: 6",
    "- full-match grounding warning count: 6",
    "- scoring constants changed: 0",
    "- scoring events deleted or capped: 0",
    "- share file count: 15",
    "",
    "## Recommendation",
    "- CONFIRM_WORKBENCH_TRUTH_FIXTURE",
    "- CONFIRM_MINIMATCH_ALIGNMENT_PARTIAL",
    "- CONFIRM_ROSTER_TO_SPATIAL_CONTEXT_GAP",
    "- CONFIRM_FULLMATCH_NOT_YET_WORKBENCH_GROUNDED",
    "",
  ].join("\n");
}

function shareReadmeDoc(): string {
  return [
    "# Sprint 2R Share Pack",
    "",
    "This compact review pack covers tactical grounding reconciliation from workbench truth to mini-match and full-match reports.",
    "",
    "Start with:",
    "- `00-share-manifest.txt` for copied files, bundle contents, commands, and git status.",
    "- `tactical-grounding-reconciliation.md` for the sprint rationale and gap diagnosis.",
    "- `validation.tactical-grounding-reconciliation.md` for the fixture, alignment, gap, and guardrail checklist.",
    "- `sequence-1-action-1.html` for the source workbench artifact.",
    "- `bundle__simulation.md` for grounding fixtures, extractors, diagnostics, mini/full-match wiring, evidence, and tests.",
    "- `bundle__reports.md` for the share-pack generator, coach report renderer, copy quality utility, and guards.",
    "- `coach-report.latest.html` for a visual full-match harness sample when present.",
    "",
  ].join("\n");
}
function writeGeneratedShareDocs(shareDirectory: string): readonly CopiedStandaloneFile[] {
  const generatedDocs = [
    {
      target: "tactical-grounding-reconciliation.md",
      content: tacticalGroundingReconciliationDoc(),
    },
    {
      target: "validation.tactical-grounding-reconciliation.md",
      content: tacticalGroundingReconciliationValidationDoc(),
    },
    {
      target: "README.md",
      content: shareReadmeDoc(),
    },
  ];

  for (const doc of generatedDocs) {
    writeFileSync(join(shareDirectory, doc.target), doc.content, "utf8");
  }

  return GENERATED_SHARE_DOCS;
}
function getGitStatusSummary(repositoryRoot: string): string {
  try {
    const status = execFileSync("git", ["status", "--short"], {
      cwd: repositoryRoot,
      encoding: "utf8",
    }).trimEnd();

    const reviewRelevantStatus = status
      .split("\n")
      .filter((line) => !line.includes("reports/share/"))
      .join("\n")
      .trimEnd();

    return reviewRelevantStatus.length > 0 ? reviewRelevantStatus : "clean";
  } catch (error) {
    return `Unable to collect git status: ${String(error)}`;
  }
}

function countSharePackFiles(shareDirectory: string): number {
  if (!existsSync(shareDirectory)) {
    return 0;
  }

  return readdirSync(shareDirectory).filter((entry) =>
    statSync(join(shareDirectory, entry)).isFile(),
  ).length;
}

function renderManifest(input: SharePackManifestInput): string {
  const lines: string[] = [
    "ChatGPT Review Share Pack Manifest",
    "==================================",
    "",
    `Generated timestamp: ${input.generatedAt}`,
    `Task/sprint name: ${TASK_NAME}`,
    `Final file count: ${input.finalFileCount}`,
    "",
    "Standalone files copied:",
  ];

  if (input.standaloneFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const file of input.standaloneFiles) {
      lines.push(`- ${file.target} <= ${file.source} (${file.reason})`);
    }
  }

  lines.push("", "Bundle files generated:");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file} (${bundle.reason})`);
  }

  lines.push("", "Source files included inside each bundle:");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file}:`);
    if (bundle.includedSources.length === 0) {
      lines.push("  - none");
      continue;
    }

    for (const source of bundle.includedSources) {
      lines.push(`  - ${source}`);
    }
  }

  lines.push("", "Missing expected files:");
  if (input.missingExpectedFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const missingFile of input.missingExpectedFiles) {
      const requiredLabel = missingFile.required ? "required" : "optional";
      lines.push(
        `- ${missingFile.source} (${requiredLabel}; ${missingFile.reason})`,
      );
    }
  }

  lines.push("", "Test/build commands run:");
  for (const command of input.commandsRun) {
    lines.push(`- ${command}`);
  }

  lines.push("", "Git status summary:", input.gitStatusSummary, "");

  return lines.join("\n");
}

function renderCompatibilityManifest(input: SharePackManifestInput): string {
  const lines: string[] = [
    "# Share Pack",
    "",
    `Generated: ${input.generatedAt}`,
    `Task/sprint: ${TASK_NAME}`,
    `Final file count: ${input.finalFileCount}`,
    "",
    "Source files are bundled by domain to keep the ChatGPT review pack compact.",
    "",
    "## Standalone Files",
  ];

  if (input.standaloneFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const file of input.standaloneFiles) {
      lines.push(`- ${file.target}`);
    }
  }

  lines.push("", "## Bundle Files");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file}`);
  }

  lines.push("", "## Missing Expected Files");
  if (input.missingExpectedFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const missingFile of input.missingExpectedFiles) {
      const requiredLabel = missingFile.required ? "required" : "optional";
      lines.push(`- ${missingFile.source} (${requiredLabel})`);
    }
  }

  lines.push("");

  return lines.join("\n");
}

function assertSharePackLimit(shareDirectory: string): void {
  const fileCount = countSharePackFiles(shareDirectory);

  if (fileCount > MAX_SHARE_FILES) {
    throw new Error(
      `Share pack contains ${fileCount} files, exceeding the ${MAX_SHARE_FILES}-file limit.`,
    );
  }
}

function assertRequiredFilesPresent(
  missingFiles: readonly MissingExpectedFile[],
): void {
  const requiredMissingFiles = missingFiles.filter(
    (missingFile) => missingFile.required,
  );

  if (requiredMissingFiles.length === 0) {
    return;
  }

  const missingList = requiredMissingFiles
    .map((missingFile) => missingFile.source)
    .join(", ");

  throw new Error(`Required share-pack source files are missing: ${missingList}`);
}

export function updateSharePack(): void {
  const repositoryRoot = getRepositoryRoot();
  const shareDirectory = join(repositoryRoot, "reports", "share");
  const generatedAt = new Date().toISOString();

  cleanDirectory(shareDirectory);

  const standaloneResult = copyStandaloneFiles(repositoryRoot, shareDirectory);
  const bundleResult = generateBundles(repositoryRoot, shareDirectory);
  const generatedDocs = writeGeneratedShareDocs(shareDirectory);
  const missingExpectedFiles = [
    ...standaloneResult.missingFiles,
    ...bundleResult.missingFiles,
  ];
  const standaloneFiles = [...standaloneResult.copiedFiles, ...generatedDocs];

  const manifestInputBeforeWrite: SharePackManifestInput = {
    generatedAt,
    finalFileCount:
      standaloneFiles.length + bundleResult.bundles.length + 2,
    standaloneFiles,
    bundles: bundleResult.bundles,
    missingExpectedFiles,
    commandsRun: COMMANDS_RUN,
    gitStatusSummary: getGitStatusSummary(repositoryRoot),
  };

  writeFileSync(
    join(shareDirectory, "00-share-manifest.txt"),
    renderManifest(manifestInputBeforeWrite),
    "utf8",
  );
  writeFileSync(
    join(shareDirectory, "manifest.md"),
    renderCompatibilityManifest(manifestInputBeforeWrite),
    "utf8",
  );

  assertSharePackLimit(shareDirectory);
  assertRequiredFilesPresent(missingExpectedFiles);

  const finalFileCount = countSharePackFiles(shareDirectory);
  const validation = validateSharePack({ reportDirectory: join(repositoryRoot, "reports") });
  if (!validation.valid) {
    throw new Error(`Share pack validation failed: ${validation.reportPath}`);
  }

  console.log(`Updated reports/share for ${TASK_NAME}.`);
  console.log(`Final file count: ${finalFileCount}`);
  console.log(
    `Generated bundles: ${bundleResult.bundles
      .map((bundle) => bundle.file)
      .join(", ")}`,
  );
}

if (require.main === module) {
  updateSharePack();
}

