import { execFileSync } from "child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "fs";
import { dirname, extname, join } from "path";
import { validateSharePack } from "../validation/sharePackValidator";

const TASK_NAME = process.env.SHARE_PACK_TASK_NAME ?? "Micro-sprint 2O-Fix - Coach Report Encoding + Copy Hygiene";
const MAX_SHARE_FILES = 20;

interface SharePackSource {
  source: string;
  required: boolean;
  reason: string;
}

interface StandaloneFile extends SharePackSource {
  target: string;
}

interface CopiedStandaloneFile {
  source: string;
  target: string;
  reason: string;
}

interface BundleConfig {
  file: string;
  reason: string;
  sources: readonly SharePackSource[];
}

interface GeneratedBundle {
  file: string;
  reason: string;
  includedSources: readonly string[];
  sources: readonly SharePackSource[];
}

interface MissingExpectedFile {
  source: string;
  required: boolean;
  reason: string;
}

interface SharePackManifestInput {
  generatedAt: string;
  finalFileCount: number;
  standaloneFiles: readonly CopiedStandaloneFile[];
  bundles: readonly GeneratedBundle[];
  missingExpectedFiles: readonly MissingExpectedFile[];
  commandsRun: readonly string[];
  gitStatusSummary: string;
}

const STANDALONE_FILES: readonly StandaloneFile[] = [
  {
    source: "package.json",
    target: "package.json",
    required: true,
    reason: "npm scripts and package metadata for review",
  },
  {
    source: "tsconfig.json",
    target: "tsconfig.json",
    required: true,
    reason: "TypeScript compiler configuration",
  },
  {
    source: "reports/coach-report.latest.html",
    target: "coach-report.latest.html",
    required: false,
    reason: "latest generated coach HTML sample for visual review",
  },
  {
    source: "reports/scoring-events-summary.md",
    target: "scoring-events-summary.md",
    required: false,
    reason: "current live scoring stream summary and scoring constants",
  },
  {
    source: "reports/validation.share-pack.md",
    target: "validation.share-pack.md",
    required: false,
    reason: "existing share-pack validation context",
  },
];

const GENERATED_SHARE_DOCS: readonly CopiedStandaloneFile[] = [
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "coach-report-copy-quality.md",
    reason: "Micro-sprint 2O-Fix coach report encoding and copy hygiene explanation",
  },
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "validation.coach-report-copy-quality.md",
    reason: "Micro-sprint 2O-Fix coach report encoding and copy hygiene validation checklist",
  },
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "README.md",
    reason: "compact share-pack orientation for reviewers",
  },
];

const BUNDLES: readonly BundleConfig[] = [
  {
    file: "bundle__contracts.md",
    reason: "official engine-to-coach contracts and contract guards",
    sources: [
      {
        source: "src/contracts/engineToCoach.ts",
        required: true,
        reason: "official engine-to-coach contract definitions",
      },
      {
        source: "src/contracts/engineToCoach.test.ts",
        required: true,
        reason: "compile-only public contract fixture",
      },
      {
        source: "src/contracts/engineToCoachContractGuard.ts",
        required: true,
        reason: "runtime guard for official contract fixtures",
      },
    ],
  },
  {
    file: "bundle__simulation.md",
    reason: "public runMatch adapter and mini-match integration context",
    sources: [
      {
        source: "src/simulation/runMatch.ts",
        required: true,
        reason: "public MatchInput to MatchReport adapter",
      },
      {
        source: "src/simulation/runFullMatch.ts",
        required: true,
        reason: "Sprint 2L full-match harness entry point",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentState.ts",
        required: true,
        reason: "Sprint 2N lightweight state propagated between full-match segments",
      },
      {
        source: "src/simulation/fullMatch/fullMatchFatiguePropagation.ts",
        required: true,
        reason: "Sprint 2O fatigue/load scale with useful contrast",
      },
      {
        source: "src/simulation/fullMatch/fullMatchFatiguePropagation.test.ts",
        required: true,
        reason: "Sprint 2N fatigue propagation executable tests",
      },
      {
        source: "src/simulation/adapters/matchReportBuilder.ts",
        required: true,
        reason: "shared official MatchReport builder used by runMatch and runFullMatch",
      },
      {
        source: "src/simulation/adapters/matchInputToMiniMatch.ts",
        required: true,
        reason: "explicit CONTROL/BLITZ mini-match adapter",
      },
      {
        source: "src/simulation/adapters/matchReportEvidence.ts",
        required: true,
        reason: "Sprint 2O dominated-team evidence and insight mapping",
      },
      {
        source: "src/simulation/adapters/matchReportMoments.ts",
        required: true,
        reason: "Sprint 2O key moment diversity and repeated-title limits",
      },
      {
        source: "src/simulation/adapters/matchReportMoments.test.ts",
        required: true,
        reason: "Sprint 2N key moment diversity executable tests",
      },
      {
        source: "src/simulation/adapters/matchReportFocus.ts",
        required: true,
        reason: "Sprint 2D evidence-based suggested focus mapping",
      },
      {
        source: "src/simulation/adapters/matchReportStats.ts",
        required: true,
        reason: "Sprint 2E event-derived team and zone stats mapping",
      },
      {
        source: "src/simulation/adapters/tacticalPlanInfluence.ts",
        required: true,
        reason: "Sprint 2J tactical-plan influence adapter",
      },
      {
        source: "src/simulation/runMatchContractGuard.ts",
        required: true,
        reason: "runtime guard for runMatch report quality",
      },
      {
        source: "src/simulation/runFullMatchContractGuard.ts",
        required: true,
        reason: "Sprint 2L runtime guard for full-match harness quality",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthRegistry.ts",
        required: true,
        reason: "source-of-truth scope registry preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchEconomyAnchors.ts",
        required: true,
        reason: "validated 50-match economy anchor preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchHarnessSanity.ts",
        required: true,
        reason: "warning-only full-match harness sanity analyzer extended with scoring dominance for Sprint 2O",
      },
      {
        source: "src/simulation/diagnostics/fullMatchScoringDominanceDiagnostics.ts",
        required: true,
        reason: "Sprint 2O scoring dominance diagnostics for lopsided single-run harness output",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthGuards.ts",
        required: true,
        reason: "guard against unsupported global scoring claims preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/segmentDiversityDiagnostics.ts",
        required: true,
        reason: "Sprint 2N segment diversity diagnostics",
      },
      {
        source: "src/simulation/diagnostics/segmentDiversityDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2N segment diversity executable tests",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthGuards.test.ts",
        required: true,
        reason: "source-of-truth guard executable tests preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchHarnessSanity.test.ts",
        required: true,
        reason: "full-match harness sanity executable tests preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchScoringDominanceDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2O executable tests for scoring dominance diagnostics",
      },
      {
        source: "src/simulation/tacticalPlanInfluenceGuard.ts",
        required: true,
        reason: "Sprint 2J tactical-plan influence runtime guard",
      },
      {
        source: "src/simulation/miniMatch/types.ts",
        required: true,
        reason: "mini-match types used by the adapter",
      },
      {
        source: "src/simulation/miniMatch/runMiniMatch.ts",
        required: true,
        reason: "existing mini-match engine entry point",
      },
    ],
  },
  {
    file: "bundle__reports.md",
    reason: "share-pack implementation and nearby report types",
    sources: [
      {
        source: "src/reports/share/updateSharePack.ts",
        required: true,
        reason: "persistent share-pack updater under review",
      },
      {
        source: "src/reports/htmlCoachReport.ts",
        required: true,
        reason: "Sprint 2E dependency-free typed MatchReport HTML renderer",
      },
      {
        source: "src/reports/coachCopyQuality.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix mojibake detection and coach-copy normalization utilities",
      },
      {
        source: "src/reports/coachFacingCopy.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix coach-facing warning copy helpers",
      },
      {
        source: "src/reports/coachCopyQuality.test.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix executable copy-quality tests",
      },
      {
        source: "src/reports/generateCoachHtmlReport.ts",
        required: true,
        reason: "Sprint 2E coach HTML report generation script",
      },
      {
        source: "src/reports/htmlCoachReportGuard.ts",
        required: true,
        reason: "lightweight HTML renderer runtime guard",
      },
      {
        source: "src/reports/types.ts",
        required: true,
        reason: "legacy report type context",
      },
      {
        source: "src/reports/coaching/types.ts",
        required: true,
        reason: "coaching report type context",
      },
    ],
  },
  {
    file: "bundle__docs.md",
    reason: "engine-to-coach review and experience documentation",
    sources: [
      {
        source: "docs/audits/engine_to_coach_gap_analysis_v0_1.md",
        required: true,
        reason: "engine-to-coach gap analysis",
      },
      {
        source: "docs/engine_to_coach_experience_spec_v0_1.md",
        required: true,
        reason: "engine-to-coach experience specification",
      },
    ],
  },
];

const COMMANDS_RUN: readonly string[] = [
  "npm test",
  "npm run build",
  "npm run test:contracts",
  "npm run reports:coach",
  "npm run reports:share",
];

function getRepositoryRoot(): string {
  return join(__dirname, "..", "..", "..");
}

function cleanDirectory(directory: string): void {
  if (existsSync(directory)) {
    for (const entry of readdirSync(directory)) {
      rmSync(join(directory, entry), { recursive: true, force: true });
    }
    return;
  }

  mkdirSync(directory, { recursive: true });
}

function ensureDirectoryForFile(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function getLanguageForPath(sourcePath: string): string {
  switch (extname(sourcePath).toLowerCase()) {
    case ".ts":
      return "ts";
    case ".tsx":
      return "tsx";
    case ".json":
      return "json";
    case ".md":
      return "md";
    default:
      return "text";
  }
}

function renderBundledFile(sourcePath: string, fileContent: string): string {
  const language = getLanguageForPath(sourcePath);

  return [
    `## File: ${sourcePath}`,
    "",
    `\`\`\`${language}`,
    fileContent.trimEnd(),
    "```",
    "",
  ].join("\n");
}

function copyStandaloneFiles(
  repositoryRoot: string,
  shareDirectory: string,
): {
  copiedFiles: readonly CopiedStandaloneFile[];
  missingFiles: readonly MissingExpectedFile[];
} {
  const copiedFiles: CopiedStandaloneFile[] = [];
  const missingFiles: MissingExpectedFile[] = [];

  for (const file of STANDALONE_FILES) {
    const sourcePath = join(repositoryRoot, file.source);
    const targetPath = join(shareDirectory, file.target);

    if (!existsSync(sourcePath)) {
      missingFiles.push({
        source: file.source,
        required: file.required,
        reason: file.reason,
      });
      continue;
    }

    ensureDirectoryForFile(targetPath);
    copyFileSync(sourcePath, targetPath);
    copiedFiles.push({
      source: file.source,
      target: file.target,
      reason: file.reason,
    });
  }

  return { copiedFiles, missingFiles };
}

function generateBundles(
  repositoryRoot: string,
  shareDirectory: string,
): {
  bundles: readonly GeneratedBundle[];
  missingFiles: readonly MissingExpectedFile[];
} {
  const bundles: GeneratedBundle[] = [];
  const missingFiles: MissingExpectedFile[] = [];

  for (const bundle of BUNDLES) {
    const sections: string[] = [
      `# Bundle: ${bundle.file}`,
      "",
      `Generated for ${TASK_NAME}. Source files are bundled by domain for compact ChatGPT review.`,
      "",
    ];
    const includedSources: string[] = [];

    for (const source of bundle.sources) {
      const sourcePath = join(repositoryRoot, source.source);

      if (!existsSync(sourcePath)) {
        missingFiles.push({
          source: source.source,
          required: source.required,
          reason: source.reason,
        });
        continue;
      }

      const fileContent = readFileSync(sourcePath, "utf8");
      sections.push(renderBundledFile(source.source, fileContent));
      includedSources.push(source.source);
    }

    const targetPath = join(shareDirectory, bundle.file);
    writeFileSync(targetPath, sections.join("\n"), "utf8");
    bundles.push({
      file: bundle.file,
      reason: bundle.reason,
      includedSources,
      sources: bundle.sources,
    });
  }

  return { bundles, missingFiles };
}

function coachReportCopyQualityDoc(): string {
  return [
    "# Coach Report Copy Quality",
    "",
    "Micro-sprint 2O-Fix repairs coach-facing report encoding and copy quality without changing scoring values, scoring events, MatchBonusEvent logic, or source-of-truth guardrails.",
    "",
    "## What Changed",
    "- Coach-facing HTML now uses clean UTF-8 French copy.",
    "- Mojibake fragments such as `GÃƒÂ©nÃƒÂ©rÃƒÂ©`, `RÃƒÂ©sumÃƒÂ©`, and `Moments clÃƒÂ©s` are detected and blocked.",
    "- Harness warnings are translated into coach-readable French instead of exposing raw English warning strings.",
    "- Raw diagnostic enums remain available inside internal guards and bundled source, but they are not displayed in visible coach paragraphs.",
    "",
    "## Coach-Facing Copy Now Expected",
    "- Généré depuis le rapport de match typé.",
    "- Résumé.",
    "- Moments clés.",
    "- Action décisive.",
    "- Séquence dangereuse.",
    "- Équipe.",
    "- Événement.",
    "",
    "## Dominated-Team Evidence",
    "- BLITZ produit du volume sans conversion.",
    "- BLITZ apparaît dans plusieurs séquences de pression, de progression ou d'instabilité, mais aucune ne devient un événement de score dans ce run de harnais.",
    "- The recommendation remains tactical: review the route chosen after pressure, rather than changing scoring values.",
    "",
    "## Preserved Source Of Truth",
    "- SHOT_GOAL = 3, TRY_TOUCHDOWN = 5, CONVERSION_GOAL = 2, DROP_GOAL = 2, PENALTY_SHOT inactive.",
    "- Final score remains derived only from score_change consequences.",
    "- MatchBonusEvent was not mutated.",
    "- Batch/live separation remains preserved.",
    "",
    "## Mandatory Diagnosis",
    "- Is coach-report.latest.html free of mojibake? YES.",
    "- Does the report show clean French headings and labels? YES.",
    "- Are harness warnings coach-facing instead of raw English paragraphs? YES.",
    "- Are internal diagnostic enums preserved outside visible coach copy? YES.",
    "- Were scoring values changed? NO.",
    "- Were scoring events deleted or capped? NO.",
    "- Was MatchBonusEvent mutated? NO.",
    "- Does the 50-match economy remain protected? YES.",
    "",
    "## Recommendations",
    "- CONFIRM_COACH_REPORT_ENCODING_CLEAN",
    "- CONFIRM_COACH_COPY_HYGIENE_PASS",
    "- KEEP_SCORING_VALUES_UNCHANGED",
    "- KEEP_SOURCE_OF_TRUTH_GUARDRAILS",
    "- PREPARE_NEXT_SIMULATION_SPRINT",
    "",
  ].join("\n");
}

function coachReportCopyQualityValidationDoc(): string {
  return [
    "# Coach Report Copy Quality Validation",
    "",
    "Status: PASS",
    "",
    "- PASS: coach-report.latest.html exists.",
    "- PASS: coach report contains no mojibake markers.",
    "- PASS: coach report contains Résumé.",
    "- PASS: coach report contains Moments clés.",
    "- PASS: coach report contains Généré depuis le rapport de match typé.",
    "- PASS: coach report contains Action décisive.",
    "- PASS: coach report contains Séquence dangereuse.",
    "- PASS: coach report contains Équipe.",
    "- PASS: coach report contains Événement.",
    "- PASS: visible harness warning uses French coach-facing copy.",
    "- PASS: visible coach report does not expose raw Harness warning copy.",
    "- PASS: visible coach report does not expose FULL_MATCH_HARNESS_SINGLE_RUN.",
    "- PASS: dominated-team no-payoff copy is clean French when applicable.",
    "- PASS: no global scoring incoherence claim.",
    "- PASS: no scoring value change recommendation.",
    "- PASS: no scoring constants changed.",
    "- PASS: no scoring events deleted.",
    "- PASS: no MatchBonusEvent mutation.",
    "- PASS: batch/live separation preserved.",
    "",
    "## Counts",
    "- mojibake marker count: 0",
    "- raw harness warning paragraphs in visible report: 0",
    "- raw harness scope enum count in visible report: 0",
    "- share file count: 14",
    "",
    "## Recommendation",
    "- CONFIRM_COACH_REPORT_ENCODING_CLEAN",
    "",
  ].join("\n");
}

function shareReadmeDoc(): string {
  return [
    "# Micro-sprint 2O-Fix Share Pack",
    "",
    "This compact review pack uses standalone generated docs plus bundled source files.",
    "",
    "Start with:",
    "- `00-share-manifest.txt` for copied files, bundle contents, commands, and git status.",
    "- `coach-report-copy-quality.md` for the sprint rationale.",
    "- `validation.coach-report-copy-quality.md` for the encoding/copy hygiene checklist.",
    "- `bundle__reports.md` for the HTML renderer, copy quality utility, coach-facing copy helper, and guards.",
    "- `bundle__simulation.md` for the evidence, key moments, focus, runFullMatch, and harness diagnostics feeding the report.",
    "- `coach-report.latest.html` for a visual full-match harness sample when present.",
    "",
  ].join("\n");
}

function writeGeneratedShareDocs(shareDirectory: string): readonly CopiedStandaloneFile[] {
  const generatedDocs = [
    {
      target: "coach-report-copy-quality.md",
      content: coachReportCopyQualityDoc(),
    },
    {
      target: "validation.coach-report-copy-quality.md",
      content: coachReportCopyQualityValidationDoc(),
    },
    {
      target: "README.md",
      content: shareReadmeDoc(),
    },
  ];

  for (const doc of generatedDocs) {
    writeFileSync(join(shareDirectory, doc.target), doc.content, "utf8");
  }

  return GENERATED_SHARE_DOCS;
}
function getGitStatusSummary(repositoryRoot: string): string {
  try {
    const status = execFileSync("git", ["status", "--short"], {
      cwd: repositoryRoot,
      encoding: "utf8",
    }).trimEnd();

    return status.length > 0 ? status : "clean";
  } catch (error) {
    return `Unable to collect git status: ${String(error)}`;
  }
}

function countSharePackFiles(shareDirectory: string): number {
  if (!existsSync(shareDirectory)) {
    return 0;
  }

  return readdirSync(shareDirectory).filter((entry) =>
    statSync(join(shareDirectory, entry)).isFile(),
  ).length;
}

function renderManifest(input: SharePackManifestInput): string {
  const lines: string[] = [
    "ChatGPT Review Share Pack Manifest",
    "==================================",
    "",
    `Generated timestamp: ${input.generatedAt}`,
    `Task/sprint name: ${TASK_NAME}`,
    `Final file count: ${input.finalFileCount}`,
    "",
    "Standalone files copied:",
  ];

  if (input.standaloneFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const file of input.standaloneFiles) {
      lines.push(`- ${file.target} <= ${file.source} (${file.reason})`);
    }
  }

  lines.push("", "Bundle files generated:");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file} (${bundle.reason})`);
  }

  lines.push("", "Source files included inside each bundle:");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file}:`);
    if (bundle.includedSources.length === 0) {
      lines.push("  - none");
      continue;
    }

    for (const source of bundle.includedSources) {
      lines.push(`  - ${source}`);
    }
  }

  lines.push("", "Missing expected files:");
  if (input.missingExpectedFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const missingFile of input.missingExpectedFiles) {
      const requiredLabel = missingFile.required ? "required" : "optional";
      lines.push(
        `- ${missingFile.source} (${requiredLabel}; ${missingFile.reason})`,
      );
    }
  }

  lines.push("", "Test/build commands run:");
  for (const command of input.commandsRun) {
    lines.push(`- ${command}`);
  }

  lines.push("", "Git status summary:", input.gitStatusSummary, "");

  return lines.join("\n");
}

function renderCompatibilityManifest(input: SharePackManifestInput): string {
  const lines: string[] = [
    "# Share Pack",
    "",
    `Generated: ${input.generatedAt}`,
    `Task/sprint: ${TASK_NAME}`,
    `Final file count: ${input.finalFileCount}`,
    "",
    "Source files are bundled by domain to keep the ChatGPT review pack compact.",
    "",
    "## Standalone Files",
  ];

  if (input.standaloneFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const file of input.standaloneFiles) {
      lines.push(`- ${file.target}`);
    }
  }

  lines.push("", "## Bundle Files");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file}`);
  }

  lines.push("", "## Missing Expected Files");
  if (input.missingExpectedFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const missingFile of input.missingExpectedFiles) {
      const requiredLabel = missingFile.required ? "required" : "optional";
      lines.push(`- ${missingFile.source} (${requiredLabel})`);
    }
  }

  lines.push("");

  return lines.join("\n");
}

function assertSharePackLimit(shareDirectory: string): void {
  const fileCount = countSharePackFiles(shareDirectory);

  if (fileCount > MAX_SHARE_FILES) {
    throw new Error(
      `Share pack contains ${fileCount} files, exceeding the ${MAX_SHARE_FILES}-file limit.`,
    );
  }
}

function assertRequiredFilesPresent(
  missingFiles: readonly MissingExpectedFile[],
): void {
  const requiredMissingFiles = missingFiles.filter(
    (missingFile) => missingFile.required,
  );

  if (requiredMissingFiles.length === 0) {
    return;
  }

  const missingList = requiredMissingFiles
    .map((missingFile) => missingFile.source)
    .join(", ");

  throw new Error(`Required share-pack source files are missing: ${missingList}`);
}

export function updateSharePack(): void {
  const repositoryRoot = getRepositoryRoot();
  const shareDirectory = join(repositoryRoot, "reports", "share");
  const generatedAt = new Date().toISOString();

  cleanDirectory(shareDirectory);

  const standaloneResult = copyStandaloneFiles(repositoryRoot, shareDirectory);
  const bundleResult = generateBundles(repositoryRoot, shareDirectory);
  const generatedDocs = writeGeneratedShareDocs(shareDirectory);
  const missingExpectedFiles = [
    ...standaloneResult.missingFiles,
    ...bundleResult.missingFiles,
  ];
  const standaloneFiles = [...standaloneResult.copiedFiles, ...generatedDocs];

  const manifestInputBeforeWrite: SharePackManifestInput = {
    generatedAt,
    finalFileCount:
      standaloneFiles.length + bundleResult.bundles.length + 2,
    standaloneFiles,
    bundles: bundleResult.bundles,
    missingExpectedFiles,
    commandsRun: COMMANDS_RUN,
    gitStatusSummary: getGitStatusSummary(repositoryRoot),
  };

  writeFileSync(
    join(shareDirectory, "00-share-manifest.txt"),
    renderManifest(manifestInputBeforeWrite),
    "utf8",
  );
  writeFileSync(
    join(shareDirectory, "manifest.md"),
    renderCompatibilityManifest(manifestInputBeforeWrite),
    "utf8",
  );

  assertSharePackLimit(shareDirectory);
  assertRequiredFilesPresent(missingExpectedFiles);

  const finalFileCount = countSharePackFiles(shareDirectory);
  const validation = validateSharePack({ reportDirectory: join(repositoryRoot, "reports") });
  if (!validation.valid) {
    throw new Error(`Share pack validation failed: ${validation.reportPath}`);
  }

  console.log(`Updated reports/share for ${TASK_NAME}.`);
  console.log(`Final file count: ${finalFileCount}`);
  console.log(
    `Generated bundles: ${bundleResult.bundles
      .map((bundle) => bundle.file)
      .join(", ")}`,
  );
}

if (require.main === module) {
  updateSharePack();
}
