import { execFileSync } from "child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "fs";
import { dirname, extname, join } from "path";
import { validateSharePack } from "../validation/sharePackValidator";

const TASK_NAME = process.env.SHARE_PACK_TASK_NAME ?? "Sprint 2Y - Visual Workbench Expansion + Per-Step Spatial Replay Proof";
const MAX_SHARE_FILES = 20;

interface SharePackSource {
  source: string;
  required: boolean;
  reason: string;
}

interface StandaloneFile extends SharePackSource {
  target: string;
}

interface CopiedStandaloneFile {
  source: string;
  target: string;
  reason: string;
}

interface BundleConfig {
  file: string;
  reason: string;
  sources: readonly SharePackSource[];
}

interface GeneratedBundle {
  file: string;
  reason: string;
  includedSources: readonly string[];
  sources: readonly SharePackSource[];
}

interface MissingExpectedFile {
  source: string;
  required: boolean;
  reason: string;
}

interface SharePackManifestInput {
  generatedAt: string;
  finalFileCount: number;
  standaloneFiles: readonly CopiedStandaloneFile[];
  bundles: readonly GeneratedBundle[];
  missingExpectedFiles: readonly MissingExpectedFile[];
  commandsRun: readonly string[];
  gitStatusSummary: string;
}

const STANDALONE_FILES: readonly StandaloneFile[] = [
  {
    source: "package.json",
    target: "package.json",
    required: true,
    reason: "npm scripts and package metadata for review",
  },
  {
    source: "tsconfig.json",
    target: "tsconfig.json",
    required: true,
    reason: "TypeScript compiler configuration",
  },
  {
    source: "reports/coach-report.latest.html",
    target: "coach-report.latest.html",
    required: false,
    reason: "latest generated coach HTML sample for visual review",
  },
  {
    source: "reports/scoring-events-summary.md",
    target: "scoring-events-summary.md",
    required: false,
    reason: "current live scoring stream summary and scoring constants",
  },
  {
    source: "reports/workbench/sequence-1-action-1.html",
    target: "sequence-1-action-1.html",
    required: true,
    reason: "Sequence 1 Action 1 workbench tactical truth artifact",
  },
  {
    source: "reports/workbench/sequence-1-action-2.html",
    target: "sequence-1-action-2.html",
    required: true,
    reason: "Sequence 1 Action 2 visual workbench truth artifact",
  },
  {
    source: "reports/workbench/sequence-1-action-3.html",
    target: "sequence-1-action-3.html",
    required: true,
    reason: "Sequence 1 Action 3 visual workbench truth artifact",
  },
  {
    source: "reports/validation.share-pack.md",
    target: "validation.share-pack.md",
    required: false,
    reason: "existing share-pack validation context",
  },
];

const GENERATED_SHARE_DOCS: readonly CopiedStandaloneFile[] = [
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "fullmatch-workbench-chain-replay-2y.md",
    reason: "Sprint 2Y visual multi-action workbench chain replay report",
  },
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "validation.fullmatch-workbench-chain-replay-2y.md",
    reason: "Sprint 2Y visual multi-action workbench chain replay validation checklist",
  },
  {
    source: "generated by src/reports/share/updateSharePack.ts",
    target: "README.md",
    reason: "compact share-pack orientation for reviewers",
  },
];

const BUNDLES: readonly BundleConfig[] = [
  {
    file: "bundle__contracts.md",
    reason: "official engine-to-coach contracts and contract guards",
    sources: [
      {
        source: "src/contracts/engineToCoach.ts",
        required: true,
        reason: "official engine-to-coach contract definitions",
      },
      {
        source: "src/contracts/matchReportEvidence.ts",
        required: true,
        reason: "Sprint 2P canonical MatchReport evidence fact contract",
      },
      {
        source: "src/contracts/matchReportWarnings.ts",
        required: true,
        reason: "Sprint 2P canonical MatchReport warning contract",
      },
      {
        source: "src/contracts/engineToCoach.test.ts",
        required: true,
        reason: "compile-only public contract fixture",
      },
      {
        source: "src/contracts/engineToCoachContractGuard.ts",
        required: true,
        reason: "runtime guard for official contract fixtures",
      },
    ],
  },
  {
    file: "bundle__simulation.md",
    reason: "public runMatch adapter and mini-match integration context",
    sources: [
      {
        source: "src/simulation/runMatch.ts",
        required: true,
        reason: "public MatchInput to MatchReport adapter",
      },
      {
        source: "src/simulation/runFullMatch.ts",
        required: true,
        reason: "Sprint 2L full-match harness entry point",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentState.ts",
        required: true,
        reason: "Sprint 2N lightweight state propagated between full-match segments",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentInfluence.ts",
        required: true,
        reason: "Sprint 2Q bounded segment-state influence resolver",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchTypes.ts",
        required: true,
        reason: "Sprint 2R typed tactical workbench truth contract",
      },
      {
        source: "src/simulation/grounding/fixtures/sequence1Action1.fixture.ts",
        required: true,
        reason: "Sprint 2R Sequence 1 Action 1 tactical truth fixture",
      },
      {
        source: "src/simulation/grounding/fixtures/sequence1Action2.fixture.ts",
        required: true,
        reason: "Sprint 2Y Sequence 1 Action 2 visual tactical truth fixture",
      },
      {
        source: "src/simulation/grounding/fixtures/sequence1Action3.fixture.ts",
        required: true,
        reason: "Sprint 2Y Sequence 1 Action 3 visual tactical truth fixture",
      },
      {
        source: "src/simulation/grounding/workbenchChainTypes.ts",
        required: true,
        reason: "Sprint 2W WorkbenchChain contract and replay mode types",
      },
      {
        source: "src/simulation/grounding/fixtures/sequence1Action1.chain.fixture.ts",
        required: true,
        reason: "Sprint 2W one-step sequence-1-action-1 WorkbenchChain fixture",
      },
      {
        source: "src/simulation/grounding/fixtures/sequence1MultiAction.chain.fixture.ts",
        required: true,
        reason: "Sprint 2Y visual multi-action WorkbenchChain fixture with three visual truth steps",
      },
      {
        source: "src/simulation/grounding/fixtures/workbenchChainCatalog.ts",
        required: true,
        reason: "Sprint 2X WorkbenchChain catalog including one-step and multi-action chains",
      },
      {
        source: "src/simulation/grounding/workbenchChainState.ts",
        required: true,
        reason: "Sprint 2W WorkbenchChain runtime state propagation",
      },
      {
        source: "src/simulation/grounding/workbenchChainReplay.ts",
        required: true,
        reason: "Sprint 2Y diagnostic/controlled/fullmatch-warning WorkbenchChain replay with per-step preservation metrics",
      },
      {
        source: "src/simulation/fullMatch/fullMatchRouteSelectionMode.ts",
        required: true,
        reason: "Sprint 2X disabled-by-default full-match route selection mode flag skeleton",
      },
      {
        source: "src/simulation/grounding/extractWorkbenchTruth.ts",
        required: true,
        reason: "Sprint 2R workbench HTML extraction utilities",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchContractGuard.ts",
        required: true,
        reason: "Sprint 2R workbench truth contract guard",
      },
      {
        source: "src/simulation/grounding/miniMatchWorkbenchAlignment.ts",
        required: true,
        reason: "Sprint 2R mini-match/workbench alignment report",
      },
      {
        source: "src/simulation/grounding/rosterToMiniMatchGapAnalysis.ts",
        required: true,
        reason: "Sprint 2S official roster to spatial context and mini-match gap analysis",
      },
      {
        source: "src/simulation/spatialContext/spatialTeamContextTypes.ts",
        required: true,
        reason: "Sprint 2S SpatialTeamContext and SpatialMatchContext contract",
      },
      {
        source: "src/simulation/spatialContext/roleToTacticalFunctions.ts",
        required: true,
        reason: "Sprint 2S explicit role to tactical function mapping",
      },
      {
        source: "src/simulation/spatialContext/teamSnapshotToSpatialContext.ts",
        required: true,
        reason: "Sprint 2S TeamSnapshot to SpatialTeamContext adapter",
      },
      {
        source: "src/simulation/spatialContext/workbenchToSpatialMatchContext.ts",
        required: true,
        reason: "Sprint 2S WorkbenchTruth to SpatialMatchContext adapter",
      },
      {
        source: "src/simulation/grounding/runWorkbenchReplaySeed.ts",
        required: true,
        reason: "Sprint 2S controlled workbench replay seed runner",
      },
      {
        source: "src/simulation/routeRanking/routeAttributeInfluenceTypes.ts",
        required: true,
        reason: "Sprint 2U route attribute influence contract with candidate availability",
      },
      {
        source: "src/simulation/routeRanking/routeAttributeInfluence.ts",
        required: true,
        reason: "Sprint 2U bounded route attribute influence helpers",
      },
      {
        source: "src/simulation/routeRanking/applySpatialAttributeInfluenceToCandidates.ts",
        required: true,
        reason: "Sprint 2U candidate attribute adjustment adapter preserving lane availability",
      },
      {
        source: "src/simulation/routeRanking/routeRankingMode.ts",
        required: true,
        reason: "Sprint 2U route ranking mode contract",
      },
      {
        source: "src/simulation/routeRanking/attributeDrivenSelectionGuard.ts",
        required: true,
        reason: "Sprint 2U guard preventing attribute overrides of illegal or unavailable routes",
      },
      {
        source: "src/simulation/routeRanking/selectAttributeAdjustedCandidate.ts",
        required: true,
        reason: "Sprint 2U guarded attribute-adjusted candidate selector",
      },
      {
        source: "src/simulation/routeRanking/fixtures/attributeRankingContrast.fixture.ts",
        required: true,
        reason: "Sprint 2U contrast fixture proving legal flip and blocked closed/unavailable routes",
      },
      {
        source: "src/simulation/diagnostics/fullMatchGroundingDiagnostics.ts",
        required: true,
        reason: "Sprint 2U warning-only partial full-match grounding diagnostics with attribute candidate_modifier mode",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchContractGuard.test.ts",
        required: true,
        reason: "Sprint 2R executable workbench fixture contract tests",
      },
      {
        source: "src/simulation/grounding/tacticalWorkbenchContractGuard.multiActionVisual.test.ts",
        required: true,
        reason: "Sprint 2Y executable visual multi-action workbench contract tests",
      },
      {
        source: "src/simulation/grounding/miniMatchWorkbenchAlignment.test.ts",
        required: true,
        reason: "Sprint 2R executable mini-match alignment tests",
      },
      {
        source: "src/simulation/grounding/rosterToMiniMatchGapAnalysis.test.ts",
        required: true,
        reason: "Sprint 2S executable roster/spatial gap tests",
      },
      {
        source: "src/simulation/spatialContext/roleToTacticalFunctions.test.ts",
        required: true,
        reason: "Sprint 2S executable role-to-function mapping tests",
      },
      {
        source: "src/simulation/spatialContext/workbenchToSpatialMatchContext.test.ts",
        required: true,
        reason: "Sprint 2S executable workbench-to-spatial-context tests",
      },
      {
        source: "src/simulation/grounding/workbenchReplaySeed.test.ts",
        required: true,
        reason: "Sprint 2U executable workbench replay seed tests with candidate_modifier evaluation",
      },
      {
        source: "src/simulation/grounding/workbenchChainState.test.ts",
        required: true,
        reason: "Sprint 2W executable chain state propagation tests",
      },
      {
        source: "src/simulation/grounding/workbenchChainState.multiAction.test.ts",
        required: true,
        reason: "Sprint 2X executable multi-step chain state propagation tests",
      },
      {
        source: "src/simulation/grounding/workbenchChainState.visualMultiAction.test.ts",
        required: true,
        reason: "Sprint 2Y executable visual multi-step chain state propagation tests",
      },
      {
        source: "src/simulation/grounding/workbenchChainReplay.test.ts",
        required: true,
        reason: "Sprint 2W executable chain replay mode tests",
      },
      {
        source: "src/simulation/grounding/workbenchChainReplay.multiAction.test.ts",
        required: true,
        reason: "Sprint 2X executable multi-step chain replay tests",
      },
      {
        source: "src/simulation/grounding/workbenchChainReplay.visualMultiAction.test.ts",
        required: true,
        reason: "Sprint 2Y executable visual multi-step replay proof tests",
      },
      {
        source: "src/simulation/grounding/workbenchChainReplay.visualMismatch.test.ts",
        required: true,
        reason: "Sprint 2Y executable visual replay mismatch proof tests",
      },
      {
        source: "src/simulation/fullMatch/fullMatchRouteSelectionMode.test.ts",
        required: true,
        reason: "Sprint 2X executable full-match feature flag skeleton tests",
      },
      {
        source: "src/simulation/fullMatch/fullMatchRouteSelectionMode.guard.test.ts",
        required: true,
        reason: "Sprint 2Y executable full-match route selection mode guard tests",
      },
      {
        source: "src/simulation/routeRanking/routeAttributeInfluence.test.ts",
        required: true,
        reason: "Sprint 2U executable route attribute influence tests",
      },
      {
        source: "src/simulation/routeRanking/applySpatialAttributeInfluenceToCandidates.test.ts",
        required: true,
        reason: "Sprint 2U executable candidate attribute adjustment tests",
      },
      {
        source: "src/simulation/routeRanking/attributeDrivenSelectionGuard.test.ts",
        required: true,
        reason: "Sprint 2U executable attribute selection guard tests",
      },
      {
        source: "src/simulation/routeRanking/selectAttributeAdjustedCandidate.test.ts",
        required: true,
        reason: "Sprint 2U executable attribute-adjusted selector tests",
      },
      {
        source: "src/simulation/diagnostics/fullMatchGroundingDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2R executable full-match grounding diagnostics tests",
      },
      {
        source: "src/simulation/fullMatch/fullMatchFatiguePropagation.ts",
        required: true,
        reason: "Sprint 2O fatigue/load scale with useful contrast",
      },
      {
        source: "src/simulation/fullMatch/fullMatchFatiguePropagation.test.ts",
        required: true,
        reason: "Sprint 2N fatigue propagation executable tests",
      },
      {
        source: "src/simulation/fullMatch/fullMatchSegmentInfluence.test.ts",
        required: true,
        reason: "Sprint 2Q executable tests for segment influence bounds",
      },
      {
        source: "src/simulation/adapters/matchReportBuilder.ts",
        required: true,
        reason: "shared official MatchReport builder used by runMatch and runFullMatch",
      },
      {
        source: "src/simulation/adapters/matchInputToMiniMatch.ts",
        required: true,
        reason: "explicit CONTROL/BLITZ mini-match adapter",
      },
      {
        source: "src/simulation/adapters/matchReportEvidence.ts",
        required: true,
        reason: "Sprint 2P canonical evidence fact mapping for insights and diagnostics",
      },
      {
        source: "src/simulation/adapters/matchReportEvidenceBuilder.ts",
        required: true,
        reason: "Sprint 2P typed evidenceFacts builder",
      },
      {
        source: "src/simulation/adapters/matchReportWarningsBuilder.ts",
        required: true,
        reason: "Sprint 2P typed MatchReport warnings builder",
      },
      {
        source: "src/simulation/adapters/matchReportMoments.ts",
        required: true,
        reason: "Sprint 2O key moment diversity and repeated-title limits",
      },
      {
        source: "src/simulation/adapters/matchReportMoments.test.ts",
        required: true,
        reason: "Sprint 2N key moment diversity executable tests",
      },
      {
        source: "src/simulation/adapters/matchReportFocus.ts",
        required: true,
        reason: "Sprint 2D evidence-based suggested focus mapping",
      },
      {
        source: "src/simulation/adapters/matchReportStats.ts",
        required: true,
        reason: "Sprint 2E event-derived team and zone stats mapping",
      },
      {
        source: "src/simulation/adapters/tacticalPlanInfluence.ts",
        required: true,
        reason: "Sprint 2J tactical-plan influence adapter",
      },
      {
        source: "src/simulation/runMatchContractGuard.ts",
        required: true,
        reason: "runtime guard for runMatch report quality",
      },
      {
        source: "src/simulation/matchReportContractGuard.ts",
        required: true,
        reason: "Sprint 2P runtime guard for canonical MatchReport evidence and warnings",
      },
      {
        source: "src/simulation/runFullMatchContractGuard.ts",
        required: true,
        reason: "Sprint 2L runtime guard for full-match harness quality",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthRegistry.ts",
        required: true,
        reason: "source-of-truth scope registry preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchEconomyAnchors.ts",
        required: true,
        reason: "validated 50-match economy anchor preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchHarnessSanity.ts",
        required: true,
        reason: "warning-only full-match harness sanity analyzer extended with scoring dominance for Sprint 2O",
      },
      {
        source: "src/simulation/diagnostics/fullMatchScoringDominanceDiagnostics.ts",
        required: true,
        reason: "Sprint 2O scoring dominance diagnostics for lopsided single-run harness output",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthGuards.ts",
        required: true,
        reason: "guard against unsupported global scoring claims preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/segmentDiversityDiagnostics.ts",
        required: true,
        reason: "Sprint 2N segment diversity diagnostics",
      },
      {
        source: "src/simulation/diagnostics/segmentDiversityDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2N segment diversity executable tests",
      },
      {
        source: "src/simulation/diagnostics/sourceOfTruthGuards.test.ts",
        required: true,
        reason: "source-of-truth guard executable tests preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchHarnessSanity.test.ts",
        required: true,
        reason: "full-match harness sanity executable tests preserved for Sprint 2N",
      },
      {
        source: "src/simulation/diagnostics/fullMatchScoringDominanceDiagnostics.test.ts",
        required: true,
        reason: "Sprint 2O executable tests for scoring dominance diagnostics",
      },
      {
        source: "src/simulation/tacticalPlanInfluenceGuard.ts",
        required: true,
        reason: "Sprint 2J tactical-plan influence runtime guard",
      },
      {
        source: "src/simulation/miniMatch/types.ts",
        required: true,
        reason: "mini-match types including optional segment influence and routeSelectionSource",
      },
      {
        source: "src/simulation/miniMatch/createMiniMatchContext.ts",
        required: true,
        reason: "Sprint 2V mini-match team/context and route selection source wiring",
      },
      {
        source: "src/simulation/miniMatch/miniMatchRouteSelectionMode.ts",
        required: true,
        reason: "Sprint 2V mini-match route selection source contract",
      },
      {
        source: "src/simulation/miniMatch/spatialCandidateGeneration.ts",
        required: true,
        reason: "Sprint 2V SpatialContext route candidate generation adapter",
      },
      {
        source: "src/simulation/miniMatch/prototypeToSpatialCandidateMapper.ts",
        required: true,
        reason: "Sprint 2V prototype-to-spatial candidate bridge with fallback notes",
      },
      {
        source: "src/simulation/miniMatch/miniMatchRouteSelection.ts",
        required: true,
        reason: "Sprint 2V guarded mini-match route selection result resolver",
      },
      {
        source: "src/simulation/miniMatch/selectInitialSequenceContext.ts",
        required: true,
        reason: "Sprint 2V controlled spatial route selection metadata on initial resolution context",
      },
      {
        source: "src/simulation/miniMatch/runMiniMatch.ts",
        required: true,
        reason: "existing mini-match engine entry point",
      },
      {
        source: "src/simulation/miniMatch/miniMatchSegmentInfluence.test.ts",
        required: true,
        reason: "Sprint 2Q mini-match compatibility and full-match influence tests",
      },
      {
        source: "src/simulation/miniMatch/miniMatchSpatialSelection.test.ts",
        required: true,
        reason: "Sprint 2V executable controlled mini-match spatial selection test",
      },
      {
        source: "src/simulation/miniMatch/miniMatchSpatialSelectionContrast.test.ts",
        required: true,
        reason: "Sprint 2V executable spatial selection contrast and fallback test",
      },
    ],
  },
  {
    file: "bundle__reports.md",
    reason: "share-pack implementation and nearby report types",
    sources: [
      {
        source: "src/reports/share/updateSharePack.ts",
        required: true,
        reason: "persistent share-pack updater under review",
      },
      {
        source: "src/reports/htmlCoachReport.ts",
        required: true,
        reason: "Sprint 2E dependency-free typed MatchReport HTML renderer",
      },
      {
        source: "src/reports/coachCopyQuality.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix mojibake detection and coach-copy normalization utilities",
      },
      {
        source: "src/reports/coachFacingCopy.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix coach-facing warning copy helpers",
      },
      {
        source: "src/reports/coachFacingSummary.ts",
        required: true,
        reason: "Micro-sprint 2P-Fix visible summary boundary helper",
      },
      {
        source: "src/reports/coachCopyQuality.test.ts",
        required: true,
        reason: "Micro-sprint 2O-Fix executable copy-quality tests",
      },
      {
        source: "src/reports/coachFacingSummary.test.ts",
        required: true,
        reason: "Micro-sprint 2P-Fix executable visible summary boundary tests",
      },
      {
        source: "src/reports/generateCoachHtmlReport.ts",
        required: true,
        reason: "Sprint 2E coach HTML report generation script",
      },
      {
        source: "src/reports/htmlCoachReportGuard.ts",
        required: true,
        reason: "lightweight HTML renderer runtime guard",
      },
      {
        source: "src/reports/types.ts",
        required: true,
        reason: "legacy report type context",
      },
      {
        source: "src/reports/coaching/types.ts",
        required: true,
        reason: "coaching report type context",
      },
    ],
  },
];

const COMMANDS_RUN: readonly string[] = [
  "npm test",
  "npm run build",
  "npm run test:contracts",
  "npm run reports:coach",
  "npm run reports:share",
];

function getRepositoryRoot(): string {
  return join(__dirname, "..", "..", "..");
}

function cleanDirectory(directory: string): void {
  if (existsSync(directory)) {
    for (const entry of readdirSync(directory)) {
      rmSync(join(directory, entry), { recursive: true, force: true });
    }
    return;
  }

  mkdirSync(directory, { recursive: true });
}

function ensureDirectoryForFile(filePath: string): void {
  mkdirSync(dirname(filePath), { recursive: true });
}

function getLanguageForPath(sourcePath: string): string {
  switch (extname(sourcePath).toLowerCase()) {
    case ".ts":
      return "ts";
    case ".tsx":
      return "tsx";
    case ".json":
      return "json";
    case ".md":
      return "md";
    default:
      return "text";
  }
}

function renderBundledFile(sourcePath: string, fileContent: string): string {
  const language = getLanguageForPath(sourcePath);

  return [
    `## File: ${sourcePath}`,
    "",
    `\`\`\`${language}`,
    fileContent.trimEnd(),
    "```",
    "",
  ].join("\n");
}

function copyStandaloneFiles(
  repositoryRoot: string,
  shareDirectory: string,
): {
  copiedFiles: readonly CopiedStandaloneFile[];
  missingFiles: readonly MissingExpectedFile[];
} {
  const copiedFiles: CopiedStandaloneFile[] = [];
  const missingFiles: MissingExpectedFile[] = [];

  for (const file of STANDALONE_FILES) {
    const sourcePath = join(repositoryRoot, file.source);
    const targetPath = join(shareDirectory, file.target);

    if (!existsSync(sourcePath)) {
      missingFiles.push({
        source: file.source,
        required: file.required,
        reason: file.reason,
      });
      continue;
    }

    ensureDirectoryForFile(targetPath);
    copyFileSync(sourcePath, targetPath);
    copiedFiles.push({
      source: file.source,
      target: file.target,
      reason: file.reason,
    });
  }

  return { copiedFiles, missingFiles };
}

function generateBundles(
  repositoryRoot: string,
  shareDirectory: string,
): {
  bundles: readonly GeneratedBundle[];
  missingFiles: readonly MissingExpectedFile[];
} {
  const bundles: GeneratedBundle[] = [];
  const missingFiles: MissingExpectedFile[] = [];

  for (const bundle of BUNDLES) {
    const sections: string[] = [
      `# Bundle: ${bundle.file}`,
      "",
      `Generated for ${TASK_NAME}. Source files are bundled by domain for compact ChatGPT review.`,
      "",
    ];
    const includedSources: string[] = [];

    for (const source of bundle.sources) {
      const sourcePath = join(repositoryRoot, source.source);

      if (!existsSync(sourcePath)) {
        missingFiles.push({
          source: source.source,
          required: source.required,
          reason: source.reason,
        });
        continue;
      }

      const fileContent = readFileSync(sourcePath, "utf8");
      sections.push(renderBundledFile(source.source, fileContent));
      includedSources.push(source.source);
    }

    const targetPath = join(shareDirectory, bundle.file);
    writeFileSync(targetPath, sections.join("\n"), "utf8");
    bundles.push({
      file: bundle.file,
      reason: bundle.reason,
      includedSources,
      sources: bundle.sources,
    });
  }

  return { bundles, missingFiles };
}

function fullMatchWorkbenchChainReplayDoc(): string {
  return [
    "# FullMatch Workbench Chain Replay 2Y",
    "",
    "Sprint 2Y replaces synthetic continuation proof with visual/action-by-action workbench truth and proves per-step controlled replay.",
    "",
    "## Sprint 2Y Summary",
    "- Visual multi-action replay: controlled/diagnostic.",
    "- Full-match chain replay: feature flag skeleton only.",
    "- Normal full-match: still segment_harness by default.",
    "- Scoring economy: unchanged and still validated only by batch/full-match economy.",
    "",
    "## Visual Workbench Artifacts Checked",
    "- sequence-1-action-1.html: YES.",
    "- sequence-1-action-2.html: YES.",
    "- sequence-1-action-3.html: YES.",
    "- sequence-1-action-2 tactical truth fixture: YES.",
    "- sequence-1-action-3 tactical truth fixture: YES.",
    "",
    "## Multi-Action Chain Status",
    "- multi-action chain exists: YES.",
    "- chains checked: 2.",
    "- multi-action chain steps: 3.",
    "- visual workbench step count: 3.",
    "- synthetic step count: 0.",
    "- hybrid step count: 0.",
    "- Step 0: control-tempo-half -> control-mobile-lock, Z4-HSL -> Z3-HSL, SUPPORT_CLUSTER_RECYCLE.",
    "- Step 1: control-mobile-lock -> control-playmaker, Z3-HSL -> Z3-C, CENTRAL_RECONNECT.",
    "- Step 2: control-playmaker -> control-space-hunter, Z3-C -> Z4-HSR, FORWARD_PROGRESS.",
    "- continuation source status: VISUAL_WORKBENCH_TRUTH_3_OF_3.",
    "- final propagated carrier: control-space-hunter.",
    "- final propagated zone: Z4-HSR.",
    "",
    "## Per-Step Preservation Table",
    "| Step | Source | Actor | Receiver | Action type | Before carrier | Before zone | After carrier | After zone | Guard | Route selection |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    "| 0 | visual_workbench_truth | PASS | PASS | PASS | PASS | PASS | PASS | PASS | PASS | spatial_candidate_modifier |",
    "| 1 | visual_workbench_truth | PASS | PASS | PASS | PASS | PASS | PASS | PASS | PASS | spatial_candidate_modifier |",
    "| 2 | visual_workbench_truth | PASS | PASS | PASS | PASS | PASS | PASS | PASS | PASS | spatial_candidate_modifier |",
    "",
    "## Replay Evidence",
    "- diagnostic_only scoring events created: 0.",
    "- diagnostic_only replays all 3 visual steps.",
    "- controlled_minimatch attempts all 3 steps.",
    "- controlled_minimatch spatial selection step count: 3.",
    "- selected actor preserved: 3/3.",
    "- selected receiver preserved: 3/3.",
    "- selected action type preserved: 3/3.",
    "- before state preserved: 3/3.",
    "- after state preserved: 3/3.",
    "- prototype fallback status: enabled and observable, but not used to hide replay mismatch.",
    "- mismatch warning test status: PASS; Step 2 actor/zone mismatches produce propagation warnings and PARTIAL status.",
    "",
    "## Full-Match Feature Flag Status",
    "- FullMatchRouteSelectionMode exists.",
    "- default mode: segment_harness.",
    "- experimental mode: workbench_chain_replay_experimental.",
    "- experimental mode active by default: NO.",
    "- enabling experimental mode mutates score: NO.",
    "- enabling experimental mode mutates scoring events: NO.",
    "- normal full-match chain-driven claim: NO.",
    "",
    "## Source Notes",
    "- Step 0 is backed by reports/workbench/sequence-1-action-1.html.",
    "- Step 1 is backed by reports/workbench/sequence-1-action-2.html.",
    "- Step 2 is backed by reports/workbench/sequence-1-action-3.html.",
    "- synthetic_continuation remains absent from the PASS path.",
    "",
    "## Scoring Guardrails",
    "- SHOT_GOAL = 3.",
    "- TRY_TOUCHDOWN = 5.",
    "- CONVERSION_GOAL = 2.",
    "- DROP_GOAL = 2.",
    "- PENALTY_SHOT inactive.",
    "- final score remains derived only from score_change consequences.",
    "- scoring events deleted/capped/rewritten/fabricated: 0.",
    "- MatchBonusEvent unchanged.",
    "- batch/live separation preserved.",
    "- FULL_MATCH_BATCH_ECONOMY remains the only global scoring-economy proof.",
    "",
    "## Next Recommendations",
    "- CONFIRM_VISUAL_MULTI_ACTION_WORKBENCH_CHAIN",
    "- CONFIRM_PER_STEP_SPATIAL_REPLAY_PROOF",
    "- CONFIRM_CONTROLLED_MINIMATCH_SPATIAL_SELECTION_3_OF_3",
    "- CONFIRM_NORMAL_FULLMATCH_DEFAULT_UNCHANGED",
    "- KEEP_SCORING_VALUES_UNCHANGED",
    "- KEEP_50_MATCH_ECONOMY_REFERENCE",
    "- PREPARE_EXPERIMENTAL_FULLMATCH_CHAIN_CONSUMPTION",
    "",
  ].join("\n");
}

function fullMatchWorkbenchChainReplayValidationDoc(): string {
  return [
    "# FullMatch Workbench Chain Replay 2Y Validation",
    "",
    "Status: PASS",
    "",
    "## Checks",
    "- PASS: sequence-1-action-2 visual workbench artifact exists.",
    "- PASS: sequence-1-action-3 visual workbench artifact exists.",
    "- PASS: sequence-1-action-2 tactical truth fixture exists.",
    "- PASS: sequence-1-action-3 tactical truth fixture exists.",
    "- PASS: multi-action chain uses visual workbench truth for 3/3 steps.",
    "- PASS: no synthetic continuation remains in PASS path.",
    "- PASS: Step 1 consumes Step 0 after-state.",
    "- PASS: Step 2 consumes Step 1 after-state.",
    "- PASS: final propagated carrier is control-space-hunter.",
    "- PASS: final propagated zone is Z4-HSR.",
    "- PASS: diagnostic_only creates no scoring events.",
    "- PASS: controlled_minimatch uses spatial_candidate_modifier for 3/3 steps.",
    "- PASS: selected actor preserved for 3/3 steps.",
    "- PASS: selected receiver preserved for 3/3 steps.",
    "- PASS: selected action type preserved for 3/3 steps.",
    "- PASS: before state preserved for 3/3 steps.",
    "- PASS: after state preserved for 3/3 steps.",
    "- PASS: prototype fallback remains enabled and observable.",
    "- PASS: fallback does not hide replay mismatch.",
    "- PASS: full-match route selection mode flag exists.",
    "- PASS: runFullMatch default remains segment_harness.",
    "- PASS: experimental full-match chain replay remains opt-in.",
    "- PASS: normal full-match is not falsely claimed as chain-driven.",
    "- PASS: scoring constants unchanged.",
    "- PASS: no scoring events deleted or capped.",
    "- PASS: MatchBonusEvent unchanged.",
    "- PASS: batch/live separation preserved.",
    "- PASS: 50-match economy preserved.",
    "",
    "## Counts",
    "- visual workbench artifacts checked: 3",
    "- visual workbench steps: 3",
    "- synthetic continuation steps: 0",
    "- hybrid steps: 0",
    "- workbench chains checked: 2",
    "- workbench chain steps checked: 4",
    "- diagnostic_only scoring events created: 0",
    "- controlled_minimatch spatial selection steps: 3",
    "- actor preserved steps: 3",
    "- receiver preserved steps: 3",
    "- action type preserved steps: 3",
    "- before state preserved steps: 3",
    "- after state preserved steps: 3",
    "- mismatch warning types checked: 2",
    "- fullmatch feature flag default: segment_harness",
    "- fullmatch score mutation count: 0",
    "- scoring constants changed: 0",
    "- scoring events deleted or capped: 0",
    "- share file count: 16",
    "",
    "## Recommendation",
    "- CONFIRM_VISUAL_MULTI_ACTION_WORKBENCH_CHAIN",
    "- CONFIRM_PER_STEP_SPATIAL_REPLAY_PROOF",
    "- CONFIRM_CONTROLLED_MINIMATCH_SPATIAL_SELECTION_3_OF_3",
    "- CONFIRM_NORMAL_FULLMATCH_DEFAULT_UNCHANGED",
    "- KEEP_SCORING_VALUES_UNCHANGED",
    "- KEEP_50_MATCH_ECONOMY_REFERENCE",
    "- PREPARE_EXPERIMENTAL_FULLMATCH_CHAIN_CONSUMPTION",
    "",
  ].join("\n");
}

function shareReadmeDoc(): string {
  return [
    "# Sprint 2Y Share Pack",
    "",
    "This compact review pack covers visual multi-action WorkbenchChain replay, per-step spatial replay proof, and the disabled-by-default full-match route selection feature flag skeleton.",
    "",
    "Start with:",
    "- `00-share-manifest.txt` for copied files, bundle contents, commands, and git status.",
    "- `fullmatch-workbench-chain-replay-2y.md` for visual chain propagation, per-step preservation, controlled replay, and feature flag status.",
    "- `validation.fullmatch-workbench-chain-replay-2y.md` for visual workbench artifacts, 3/3 spatial replay proof, feature flag default, and source-of-truth checks.",
    "- `sequence-1-action-1.html`, `sequence-1-action-2.html`, and `sequence-1-action-3.html` for visual workbench truth.",
    "- `bundle__simulation.md` for multi-action WorkbenchChain files/tests, full-match route selection flag files/tests, mini-match route selection files/tests, replay seed, grounding diagnostics, and evidence.",
    "- `bundle__reports.md` for the share-pack generator, coach report renderer, copy quality utility, and guards.",
    "- `coach-report.latest.html` for a visual full-match harness sample when present.",
    "",
  ].join("\n");
}
function writeGeneratedShareDocs(shareDirectory: string): readonly CopiedStandaloneFile[] {
  const generatedDocs = [
    {
      target: "fullmatch-workbench-chain-replay-2y.md",
      content: fullMatchWorkbenchChainReplayDoc(),
    },
    {
      target: "validation.fullmatch-workbench-chain-replay-2y.md",
      content: fullMatchWorkbenchChainReplayValidationDoc(),
    },
    {
      target: "README.md",
      content: shareReadmeDoc(),
    },
  ];

  for (const doc of generatedDocs) {
    writeFileSync(join(shareDirectory, doc.target), doc.content, "utf8");
  }

  return GENERATED_SHARE_DOCS;
}
function getGitStatusSummary(repositoryRoot: string): string {
  try {
    const status = execFileSync("git", ["status", "--short"], {
      cwd: repositoryRoot,
      encoding: "utf8",
    }).trimEnd();

    const reviewRelevantStatus = status
      .split("\n")
      .filter((line) => !line.includes("reports/share/"))
      .join("\n")
      .trimEnd();

    return reviewRelevantStatus.length > 0 ? reviewRelevantStatus : "clean";
  } catch (error) {
    return `Unable to collect git status: ${String(error)}`;
  }
}

function countSharePackFiles(shareDirectory: string): number {
  if (!existsSync(shareDirectory)) {
    return 0;
  }

  return readdirSync(shareDirectory).filter((entry) =>
    statSync(join(shareDirectory, entry)).isFile(),
  ).length;
}

function renderManifest(input: SharePackManifestInput): string {
  const lines: string[] = [
    "ChatGPT Review Share Pack Manifest",
    "==================================",
    "",
    `Generated timestamp: ${input.generatedAt}`,
    `Task/sprint name: ${TASK_NAME}`,
    `Final file count: ${input.finalFileCount}`,
    "",
    "Standalone files copied:",
  ];

  if (input.standaloneFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const file of input.standaloneFiles) {
      lines.push(`- ${file.target} <= ${file.source} (${file.reason})`);
    }
  }

  lines.push("", "Bundle files generated:");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file} (${bundle.reason})`);
  }

  lines.push("", "Source files included inside each bundle:");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file}:`);
    if (bundle.includedSources.length === 0) {
      lines.push("  - none");
      continue;
    }

    for (const source of bundle.includedSources) {
      lines.push(`  - ${source}`);
    }
  }

  lines.push("", "Missing expected files:");
  if (input.missingExpectedFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const missingFile of input.missingExpectedFiles) {
      const requiredLabel = missingFile.required ? "required" : "optional";
      lines.push(
        `- ${missingFile.source} (${requiredLabel}; ${missingFile.reason})`,
      );
    }
  }

  lines.push("", "Test/build commands run:");
  for (const command of input.commandsRun) {
    lines.push(`- ${command}`);
  }

  lines.push("", "Git status summary:", input.gitStatusSummary, "");

  return lines.join("\n");
}

function renderCompatibilityManifest(input: SharePackManifestInput): string {
  const lines: string[] = [
    "# Share Pack",
    "",
    `Generated: ${input.generatedAt}`,
    `Task/sprint: ${TASK_NAME}`,
    `Final file count: ${input.finalFileCount}`,
    "",
    "Source files are bundled by domain to keep the ChatGPT review pack compact.",
    "",
    "## Standalone Files",
  ];

  if (input.standaloneFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const file of input.standaloneFiles) {
      lines.push(`- ${file.target}`);
    }
  }

  lines.push("", "## Bundle Files");
  for (const bundle of input.bundles) {
    lines.push(`- ${bundle.file}`);
  }

  lines.push("", "## Missing Expected Files");
  if (input.missingExpectedFiles.length === 0) {
    lines.push("- none");
  } else {
    for (const missingFile of input.missingExpectedFiles) {
      const requiredLabel = missingFile.required ? "required" : "optional";
      lines.push(`- ${missingFile.source} (${requiredLabel})`);
    }
  }

  lines.push("");

  return lines.join("\n");
}

function assertSharePackLimit(shareDirectory: string): void {
  const fileCount = countSharePackFiles(shareDirectory);

  if (fileCount > MAX_SHARE_FILES) {
    throw new Error(
      `Share pack contains ${fileCount} files, exceeding the ${MAX_SHARE_FILES}-file limit.`,
    );
  }
}

function assertRequiredFilesPresent(
  missingFiles: readonly MissingExpectedFile[],
): void {
  const requiredMissingFiles = missingFiles.filter(
    (missingFile) => missingFile.required,
  );

  if (requiredMissingFiles.length === 0) {
    return;
  }

  const missingList = requiredMissingFiles
    .map((missingFile) => missingFile.source)
    .join(", ");

  throw new Error(`Required share-pack source files are missing: ${missingList}`);
}

export function updateSharePack(): void {
  const repositoryRoot = getRepositoryRoot();
  const shareDirectory = join(repositoryRoot, "reports", "share");
  const generatedAt = new Date().toISOString();

  cleanDirectory(shareDirectory);

  const standaloneResult = copyStandaloneFiles(repositoryRoot, shareDirectory);
  const bundleResult = generateBundles(repositoryRoot, shareDirectory);
  const generatedDocs = writeGeneratedShareDocs(shareDirectory);
  const missingExpectedFiles = [
    ...standaloneResult.missingFiles,
    ...bundleResult.missingFiles,
  ];
  const standaloneFiles = [...standaloneResult.copiedFiles, ...generatedDocs];

  const manifestInputBeforeWrite: SharePackManifestInput = {
    generatedAt,
    finalFileCount:
      standaloneFiles.length + bundleResult.bundles.length + 2,
    standaloneFiles,
    bundles: bundleResult.bundles,
    missingExpectedFiles,
    commandsRun: COMMANDS_RUN,
    gitStatusSummary: getGitStatusSummary(repositoryRoot),
  };

  writeFileSync(
    join(shareDirectory, "00-share-manifest.txt"),
    renderManifest(manifestInputBeforeWrite),
    "utf8",
  );
  writeFileSync(
    join(shareDirectory, "manifest.md"),
    renderCompatibilityManifest(manifestInputBeforeWrite),
    "utf8",
  );

  assertSharePackLimit(shareDirectory);
  assertRequiredFilesPresent(missingExpectedFiles);

  const finalFileCount = countSharePackFiles(shareDirectory);
  const validation = validateSharePack({ reportDirectory: join(repositoryRoot, "reports") });
  if (!validation.valid) {
    throw new Error(`Share pack validation failed: ${validation.reportPath}`);
  }

  console.log(`Updated reports/share for ${TASK_NAME}.`);
  console.log(`Final file count: ${finalFileCount}`);
  console.log(
    `Generated bundles: ${bundleResult.bundles
      .map((bundle) => bundle.file)
      .join(", ")}`,
  );
}

if (require.main === module) {
  updateSharePack();
}

