export type BreakEventPostScoreResetWarningCode =
  | "POST_SCORE_IMMEDIATE_REATTACK_TOO_HIGH"
  | "POST_SCORE_IMMEDIATE_REATTACK_REDUCED"
  | "POST_SCORE_RESET_NOT_PROTECTED"
  | "POST_SCORE_RESET_PROTECTED"
  | "CONCEDING_TEAM_FIRST_POSSESSION_MISSING"
  | "DEFENSIVE_RECOVERY_BREAKS_TOO_WEAK"
  | "DEFENSIVE_RECOVERY_BREAKS_IMPROVED"
  | "GOALKEEPER_SECURE_BREAKS_MISSING"
  | "GOALKEEPER_SECURE_BREAKS_JUSTIFIED_ABSENT"
  | "DOMINANCE_DECAY_APPLICATION_ZERO"
  | "DOMINANCE_DECAY_APPLIED"
  | "DENSITY_CALIBRATION_PRESERVED"
  | "TEAM_OPPORTUNITY_BALANCE_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "SCORING_GUARDRAIL_REGRESSED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const BREAK_EVENT_POST_SCORE_RESET_WARNING_CODES: readonly BreakEventPostScoreResetWarningCode[] = [
  "POST_SCORE_IMMEDIATE_REATTACK_TOO_HIGH",
  "POST_SCORE_IMMEDIATE_REATTACK_REDUCED",
  "POST_SCORE_RESET_NOT_PROTECTED",
  "POST_SCORE_RESET_PROTECTED",
  "CONCEDING_TEAM_FIRST_POSSESSION_MISSING",
  "DEFENSIVE_RECOVERY_BREAKS_TOO_WEAK",
  "DEFENSIVE_RECOVERY_BREAKS_IMPROVED",
  "GOALKEEPER_SECURE_BREAKS_MISSING",
  "GOALKEEPER_SECURE_BREAKS_JUSTIFIED_ABSENT",
  "DOMINANCE_DECAY_APPLICATION_ZERO",
  "DOMINANCE_DECAY_APPLIED",
  "DENSITY_CALIBRATION_PRESERVED",
  "TEAM_OPPORTUNITY_BALANCE_PRESERVED",
  "ROUTE_FAMILY_DIVERSITY_PRESERVED",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "SCORING_GUARDRAIL_REGRESSED",
  "FULL_MATCH_BATCH_ECONOMY_PARTIAL",
  "FULL_MATCH_BATCH_ECONOMY_HEALTHY",
];
