export type CloseGameDistributionWarningCode =
  | "CLOSE_GAME_DISTRIBUTION_CALIBRATION_COMPLETE"
  | "CLOSE_GAME_DISTRIBUTION_MEASURED"
  | "CLOSE_GAME_RATE_HEALTHY"
  | "COMPETITIVE_GAME_RATE_HEALTHY"
  | "BLOWOUT_RATE_HEALTHY"
  | "SEVERE_BLOWOUT_RATE_HEALTHY"
  | "CLOSE_GAME_RATE_IMPROVED"
  | "COMPETITIVE_GAME_RATE_IMPROVED"
  | "BLOWOUT_RATE_REDUCED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "LATE_GAME_COMPETITION_PRESENT"
  | "TRAILING_TEAM_RESPONSE_HEALTHY"
  | "LEADING_TEAM_RUNAWAY_CONTROLLED"
  | "SCORE_GAP_CAUSES_MEASURED"
  | "COMPETITIVE_FAILURE_CAUSES_MEASURED"
  | "CHAIN_METRIC_INCONSISTENCY_FIXED"
  | "NO_RUBBER_BANDING_CONFIRMED"
  | "NO_FORCED_COMEBACK_CONFIRMED"
  | "GATE_SELECTIVITY_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "CALIBRATION_COVERAGE_COMPLETE"
  | "CLOSE_GAME_RATE_TOO_LOW"
  | "COMPETITIVE_GAME_RATE_TOO_LOW"
  | "BLOWOUT_RATE_TOO_HIGH"
  | "SEVERE_BLOWOUT_RATE_TOO_HIGH"
  | "SHUTOUT_RATE_TOO_HIGH"
  | "ONE_SIDED_SCORING_TOO_HIGH"
  | "LEADING_TEAM_RUNAWAY_TOO_HIGH"
  | "TRAILING_TEAM_RESPONSE_TOO_LOW"
  | "CHAIN_METRIC_INCONSISTENCY_REMAINS"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "CALIBRATION_COVERAGE_REGRESSED"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "RUBBER_BANDING_DETECTED"
  | "FORCED_COMEBACK_DETECTED"
  | "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const CLOSE_GAME_DISTRIBUTION_BLOCKING_WARNINGS: readonly CloseGameDistributionWarningCode[] = [
  "CLOSE_GAME_RATE_TOO_LOW",
  "COMPETITIVE_GAME_RATE_TOO_LOW",
  "BLOWOUT_RATE_TOO_HIGH",
  "SEVERE_BLOWOUT_RATE_TOO_HIGH",
  "CHAIN_METRIC_INCONSISTENCY_REMAINS",
  "DOMINANCE_CHAIN_REGRESSED",
  "CALIBRATION_COVERAGE_REGRESSED",
  "SCORING_OPPORTUNITY_VOLUME_REGRESSED",
  "SCORING_EVENTS_REGRESSED",
  "AVERAGE_TOTAL_POINTS_REGRESSED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "RUBBER_BANDING_DETECTED",
  "FORCED_COMEBACK_DETECTED",
];
