export type DominanceChainWarningCode =
  | "DOMINANCE_CHAIN_TOO_LONG"
  | "SAME_TEAM_OPPORTUNITY_CHAIN_TOO_HIGH"
  | "SAME_FAMILY_REPEAT_TOO_HIGH"
  | "SAME_ZONE_REPEAT_TOO_HIGH"
  | "DOMINANT_TEAM_IMMEDIATE_REATTACK_TOO_HIGH"
  | "RESET_NOT_BREAKING_DOMINANCE"
  | "DEFENSIVE_RECOVERY_NOT_BREAKING_DOMINANCE"
  | "GOALKEEPER_SECURE_NOT_BREAKING_DOMINANCE"
  | "TURNOVER_NOT_BREAKING_DOMINANCE"
  | "NEUTRAL_PHASE_NOT_BREAKING_DOMINANCE"
  | "FATIGUE_NOT_BREAKING_DOMINANCE"
  | "PRESSURE_NOT_BREAKING_DOMINANCE"
  | "TRAILING_TEAM_RESPONSE_AFTER_DOMINANCE_TOO_WEAK"
  | "MOMENTUM_TOO_STICKY"
  | "DOMINANCE_DECAY_MISSING"
  | "DOMINANCE_DECAY_TOO_WEAK"
  | "DOMINANCE_CHAIN_CALIBRATED"
  | "DOMINANCE_CHAIN_REDUCED"
  | "SAME_TEAM_OPPORTUNITY_CHAIN_REDUCED"
  | "SAME_FAMILY_REPEAT_REDUCED"
  | "POST_SCORE_IMMEDIATE_REATTACK_REDUCED"
  | "RESET_BREAKS_DOMINANCE_IMPROVED"
  | "DEFENSIVE_RECOVERY_BREAKS_DOMINANCE_IMPROVED"
  | "GOALKEEPER_SECURE_BREAKS_DOMINANCE_IMPROVED"
  | "TURNOVER_BREAKS_DOMINANCE_IMPROVED"
  | "NEUTRAL_PHASE_BREAKS_DOMINANCE_IMPROVED"
  | "TEAM_OPPORTUNITY_BALANCE_PRESERVED"
  | "DENSITY_CALIBRATION_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "BLOWOUT_RATE_REDUCED"
  | "DOMINANCE_CHAIN_STILL_TOO_LONG"
  | "SAME_TEAM_OPPORTUNITY_CHAIN_STILL_TOO_HIGH"
  | "SAME_FAMILY_REPEAT_STILL_TOO_HIGH"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "TEAM_BALANCE_REGRESSED"
  | "DENSITY_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const DOMINANCE_CHAIN_WARNING_CODES: readonly DominanceChainWarningCode[] = [
  "DOMINANCE_CHAIN_TOO_LONG",
  "SAME_TEAM_OPPORTUNITY_CHAIN_TOO_HIGH",
  "SAME_FAMILY_REPEAT_TOO_HIGH",
  "SAME_ZONE_REPEAT_TOO_HIGH",
  "DOMINANT_TEAM_IMMEDIATE_REATTACK_TOO_HIGH",
  "RESET_NOT_BREAKING_DOMINANCE",
  "DEFENSIVE_RECOVERY_NOT_BREAKING_DOMINANCE",
  "GOALKEEPER_SECURE_NOT_BREAKING_DOMINANCE",
  "TURNOVER_NOT_BREAKING_DOMINANCE",
  "NEUTRAL_PHASE_NOT_BREAKING_DOMINANCE",
  "FATIGUE_NOT_BREAKING_DOMINANCE",
  "PRESSURE_NOT_BREAKING_DOMINANCE",
  "TRAILING_TEAM_RESPONSE_AFTER_DOMINANCE_TOO_WEAK",
  "MOMENTUM_TOO_STICKY",
  "DOMINANCE_DECAY_MISSING",
  "DOMINANCE_DECAY_TOO_WEAK",
  "DOMINANCE_CHAIN_CALIBRATED",
  "DOMINANCE_CHAIN_REDUCED",
  "SAME_TEAM_OPPORTUNITY_CHAIN_REDUCED",
  "SAME_FAMILY_REPEAT_REDUCED",
  "POST_SCORE_IMMEDIATE_REATTACK_REDUCED",
  "RESET_BREAKS_DOMINANCE_IMPROVED",
  "DEFENSIVE_RECOVERY_BREAKS_DOMINANCE_IMPROVED",
  "GOALKEEPER_SECURE_BREAKS_DOMINANCE_IMPROVED",
  "TURNOVER_BREAKS_DOMINANCE_IMPROVED",
  "NEUTRAL_PHASE_BREAKS_DOMINANCE_IMPROVED",
  "TEAM_OPPORTUNITY_BALANCE_PRESERVED",
  "DENSITY_CALIBRATION_PRESERVED",
  "ROUTE_FAMILY_DIVERSITY_PRESERVED",
  "BLOWOUT_RATE_REDUCED",
  "DOMINANCE_CHAIN_STILL_TOO_LONG",
  "SAME_TEAM_OPPORTUNITY_CHAIN_STILL_TOO_HIGH",
  "SAME_FAMILY_REPEAT_STILL_TOO_HIGH",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "TEAM_BALANCE_REGRESSED",
  "DENSITY_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "FULL_MATCH_BATCH_ECONOMY_PARTIAL",
  "FULL_MATCH_BATCH_ECONOMY_HEALTHY",
];
