export type DominanceChainCalibrationCoverageWarningCode =
  | "DOMINANCE_CHAIN_COVERAGE_FIX_COMPLETE"
  | "DOMINANCE_CHAIN_REDUCED"
  | "DOMINANT_TEAM_CHAIN_MAX_HEALTHY"
  | "SAME_TEAM_CHAIN_REDUCED"
  | "SAME_FAMILY_CHAIN_REDUCED"
  | "CHAIN_BREAK_RESTORED"
  | "DEFENSIVE_RECOVERY_RESTORED"
  | "HIGH_QUALITY_TO_OPPORTUNITY_REDUCED"
  | "EARNED_DANGER_TO_OPPORTUNITY_REDUCED"
  | "NON_SCORING_LAYERS_PRESERVED"
  | "CALIBRATION_COVERAGE_COMPLETE"
  | "CALIBRATIONS_APPLIED_ALL_RUNS_TRUE"
  | "CALIBRATION_COVERAGE_EXPLAINED"
  | "LONGITUDINAL_DOMINANCE_STABLE"
  | "GATE_SELECTIVITY_PRESERVED"
  | "EARNED_DANGER_PRESERVED"
  | "AUTOMATIC_DANGER_STILL_BLOCKED"
  | "VOLUME_PRESERVED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "TEAM_BALANCE_PRESERVED"
  | "DOMINANCE_CHAIN_STILL_TOO_LONG"
  | "DOMINANT_TEAM_CHAIN_MAX_TOO_HIGH"
  | "SAME_TEAM_CHAIN_STILL_HIGH"
  | "SAME_FAMILY_CHAIN_STILL_HIGH"
  | "CHAIN_BREAK_FAILURE_TOO_HIGH"
  | "CALIBRATION_COVERAGE_PARTIAL"
  | "CALIBRATION_COVERAGE_MISSING_RUNS"
  | "CALIBRATION_FLAG_CONTRADICTION"
  | "CALIBRATION_VERSION_MISMATCH"
  | "VALIDATION_REPORT_CALIBRATION_DISAGREE"
  | "HIGH_QUALITY_TO_OPPORTUNITY_STILL_TOO_HIGH"
  | "EARNED_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH"
  | "NON_SCORING_LAYERS_REGRESSED"
  | "LONGITUDINAL_VARIANCE_TOO_HIGH"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const DOMINANCE_CHAIN_CALIBRATION_COVERAGE_BLOCKING_WARNINGS: readonly DominanceChainCalibrationCoverageWarningCode[] = [
  "DOMINANCE_CHAIN_STILL_TOO_LONG",
  "DOMINANT_TEAM_CHAIN_MAX_TOO_HIGH",
  "CALIBRATION_COVERAGE_PARTIAL",
  "CALIBRATION_COVERAGE_MISSING_RUNS",
  "CALIBRATION_FLAG_CONTRADICTION",
  "VALIDATION_REPORT_CALIBRATION_DISAGREE",
  "HIGH_QUALITY_TO_OPPORTUNITY_STILL_TOO_HIGH",
  "EARNED_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH",
  "NON_SCORING_LAYERS_REGRESSED",
  "LONGITUDINAL_VARIANCE_TOO_HIGH",
  "SCORING_OPPORTUNITY_VOLUME_REGRESSED",
  "SCORING_EVENTS_REGRESSED",
  "AVERAGE_TOTAL_POINTS_REGRESSED",
  "SEVERE_BLOWOUT_REGRESSED",
  "GATE_SELECTIVITY_REGRESSED",
  "AUTOMATIC_DANGER_RESTORED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
];
