export type EarnedDangerOutcomeDistributionWarningCode =
  | "EARNED_DANGER_OUTCOME_DISTRIBUTION_RECHECK_COMPLETE"
  | "EARNED_DANGER_TO_OPPORTUNITY_REDUCED"
  | "DANGER_OUTCOME_DISTRIBUTION_IMPROVED"
  | "DANGER_QUALITY_DISTRIBUTION_IMPROVED"
  | "MEDIUM_QUALITY_DANGER_REINTRODUCED"
  | "LOW_QUALITY_DANGER_REINTRODUCED"
  | "HALF_CHANCE_LAYER_EXPANDED"
  | "FORCED_DEFENSIVE_ACTION_LAYER_EXPANDED"
  | "TERRITORIAL_GAIN_LAYER_EXPANDED"
  | "LONGITUDINAL_ROUTE_ECONOMY_STABLE"
  | "GATE_SELECTIVITY_PRESERVED"
  | "EARNED_DANGER_PRESERVED"
  | "AUTOMATIC_DANGER_STILL_BLOCKED"
  | "VOLUME_PRESERVED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "TEAM_BALANCE_PRESERVED"
  | "EARNED_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH"
  | "HIGH_QUALITY_DANGER_OVERCLASSIFIED"
  | "MEDIUM_QUALITY_DANGER_UNDERREPRESENTED"
  | "LOW_QUALITY_DANGER_MISSING"
  | "HALF_CHANCE_LAYER_TOO_LOW"
  | "FORCED_DEFENSIVE_ACTION_LAYER_TOO_LOW"
  | "TERRITORIAL_GAIN_LAYER_TOO_LOW"
  | "LONGITUDINAL_VARIANCE_TOO_HIGH"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const EARNED_DANGER_OUTCOME_DISTRIBUTION_BLOCKING_WARNINGS: readonly EarnedDangerOutcomeDistributionWarningCode[] = [
  "EARNED_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH",
  "HIGH_QUALITY_DANGER_OVERCLASSIFIED",
  "MEDIUM_QUALITY_DANGER_UNDERREPRESENTED",
  "LOW_QUALITY_DANGER_MISSING",
  "HALF_CHANCE_LAYER_TOO_LOW",
  "FORCED_DEFENSIVE_ACTION_LAYER_TOO_LOW",
  "TERRITORIAL_GAIN_LAYER_TOO_LOW",
  "LONGITUDINAL_VARIANCE_TOO_HIGH",
  "SCORING_OPPORTUNITY_VOLUME_REGRESSED",
  "SCORING_EVENTS_REGRESSED",
  "AVERAGE_TOTAL_POINTS_REGRESSED",
  "SEVERE_BLOWOUT_REGRESSED",
  "GATE_SELECTIVITY_REGRESSED",
  "AUTOMATIC_DANGER_RESTORED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
];
