export type EarnedDangerGateTuningWarningCode =
  | "EARNED_DANGER_REINTRODUCED"
  | "BORDERLINE_DANGER_REINTRODUCED"
  | "AUTOMATIC_DANGER_STILL_BLOCKED"
  | "RESET_GATE_STILL_TOO_STRICT"
  | "RESET_GATE_TOO_LOOSE"
  | "VOLUME_STILL_HOT"
  | "SEVERE_BLOWOUT_STILL_HIGH"
  | "ROOT_CAUSE_AUDIT_CONSISTENT"
  | "ROOT_CAUSE_AUDIT_CONTRADICTORY"
  | "DENSITY_PRESERVED"
  | "DENSITY_REGRESSED"
  | "TEAM_BALANCE_PRESERVED"
  | "TEAM_BALANCE_REGRESSED"
  | "ROUTE_FAMILY_MIX_PRESERVED"
  | "ROUTE_FAMILY_MIX_REGRESSED"
  | "POST_SCORE_RESET_PRESERVED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_PRESERVED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "DOMINANCE_CHAIN_PRESERVED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "SCORING_GUARDRAILS_CLEAN"
  | "SCORING_GUARDRAILS_REGRESSED"
  | "PARTIAL_PROGRESS_REQUIRES_MONITORING";

export const EARNED_DANGER_GATE_TUNING_BLOCKING_WARNINGS: readonly EarnedDangerGateTuningWarningCode[] = [
  "RESET_GATE_STILL_TOO_STRICT",
  "RESET_GATE_TOO_LOOSE",
  "DENSITY_REGRESSED",
  "TEAM_BALANCE_REGRESSED",
  "ROUTE_FAMILY_MIX_REGRESSED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "DOMINANCE_CHAIN_REGRESSED",
  "SCORING_GUARDRAILS_REGRESSED",
  "ROOT_CAUSE_AUDIT_CONTRADICTORY",
];
