export type EarnedDangerGateWarningCode =
  | "EARNED_DANGER_GATE_CALIBRATED"
  | "EARNED_DANGER_GATE_CONNECTED"
  | "RESET_TO_IMMEDIATE_DANGER_REDUCED"
  | "AUTOMATIC_DANGER_REDUCED"
  | "EARNED_DANGER_INCREASED"
  | "DANGER_WITHOUT_SUPPORT_REDUCED"
  | "DANGER_WITHOUT_TACTICAL_EDGE_REDUCED"
  | "DANGER_WITHOUT_ATTRIBUTE_EDGE_REDUCED"
  | "DANGER_DESPITE_GOALKEEPER_SECURE_REDUCED"
  | "DANGER_DOWNGRADED_TO_NEUTRAL"
  | "DANGER_DOWNGRADED_TO_SAFE_POSSESSION"
  | "REBUILD_PHASE_INSERTED"
  | "GOALKEEPER_SECURE_RESET_GAINS_PRESERVED"
  | "POST_SCORE_RESET_GAINS_PRESERVED"
  | "DOMINANCE_CHAIN_GAINS_PRESERVED"
  | "TEAM_OPPORTUNITY_BALANCE_PRESERVED"
  | "DENSITY_CALIBRATION_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "BLOWOUT_RATE_REDUCED"
  | "RESET_TO_IMMEDIATE_DANGER_STILL_TOO_HIGH"
  | "AUTOMATIC_DANGER_STILL_TOO_HIGH"
  | "EARNED_DANGER_STILL_TOO_LOW"
  | "DANGER_WITHOUT_SUPPORT_STILL_HIGH"
  | "DANGER_WITHOUT_TACTICAL_EDGE_STILL_HIGH"
  | "DANGER_WITHOUT_ATTRIBUTE_EDGE_STILL_HIGH"
  | "RESET_GATE_TOO_STRICT"
  | "DENSITY_COLLAPSED"
  | "TEAM_BALANCE_REGRESSED"
  | "DENSITY_REGRESSED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const EARNED_DANGER_GATE_BLOCKING_WARNINGS: readonly EarnedDangerGateWarningCode[] = [
  "RESET_TO_IMMEDIATE_DANGER_STILL_TOO_HIGH",
  "AUTOMATIC_DANGER_STILL_TOO_HIGH",
  "EARNED_DANGER_STILL_TOO_LOW",
  "DANGER_WITHOUT_SUPPORT_STILL_HIGH",
  "DANGER_WITHOUT_TACTICAL_EDGE_STILL_HIGH",
  "DANGER_WITHOUT_ATTRIBUTE_EDGE_STILL_HIGH",
  "RESET_GATE_TOO_STRICT",
  "DENSITY_COLLAPSED",
  "TEAM_BALANCE_REGRESSED",
  "DENSITY_REGRESSED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "DOMINANCE_CHAIN_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
];
