export type FullMatchRouteFamilyMixWarningCode =
  | "ROUTE_FAMILY_MIX_ACTIVATED"
  | "NON_SHOT_ROUTES_AVAILABLE"
  | "NON_SHOT_ROUTES_ELIGIBLE_BUT_NOT_SELECTED"
  | "NON_SHOT_ROUTES_SELECTED_BUT_NOT_SCORING"
  | "TRY_ROUTE_AVAILABLE"
  | "TRY_ROUTE_NOT_AVAILABLE"
  | "DROP_ROUTE_AVAILABLE"
  | "DROP_ROUTE_NOT_AVAILABLE"
  | "CONVERSION_GENERATED_AFTER_TRY"
  | "CONVERSION_WITHOUT_TRY_BLOCKED"
  | "SHOT_ONLY_RISK_REDUCED"
  | "SHOT_ONLY_RISK_PERSISTENT"
  | "TOO_MANY_SHOT_ONLY_MATCHES"
  | "TRY_DROP_PRESENCE_TOO_LOW"
  | "NON_SHOT_SCORING_TOO_LOW"
  | "ONE_SIDED_SCORING_RISK"
  | "SHUTOUT_RATE_TOO_HIGH"
  | "OFFICIAL_SCORE_PATH_REGRESSION"
  | "GLOBAL_ECONOMY_NOT_CONFIRMED"
  | "FULL_MATCH_BATCH_REQUIRED_AGAIN";

export const FULL_MATCH_ROUTE_FAMILY_MIX_WARNING_CODES: readonly FullMatchRouteFamilyMixWarningCode[] = [
  "ROUTE_FAMILY_MIX_ACTIVATED",
  "NON_SHOT_ROUTES_AVAILABLE",
  "NON_SHOT_ROUTES_ELIGIBLE_BUT_NOT_SELECTED",
  "NON_SHOT_ROUTES_SELECTED_BUT_NOT_SCORING",
  "TRY_ROUTE_AVAILABLE",
  "TRY_ROUTE_NOT_AVAILABLE",
  "DROP_ROUTE_AVAILABLE",
  "DROP_ROUTE_NOT_AVAILABLE",
  "CONVERSION_GENERATED_AFTER_TRY",
  "CONVERSION_WITHOUT_TRY_BLOCKED",
  "SHOT_ONLY_RISK_REDUCED",
  "SHOT_ONLY_RISK_PERSISTENT",
  "TOO_MANY_SHOT_ONLY_MATCHES",
  "TRY_DROP_PRESENCE_TOO_LOW",
  "NON_SHOT_SCORING_TOO_LOW",
  "ONE_SIDED_SCORING_RISK",
  "SHUTOUT_RATE_TOO_HIGH",
  "OFFICIAL_SCORE_PATH_REGRESSION",
  "GLOBAL_ECONOMY_NOT_CONFIRMED",
  "FULL_MATCH_BATCH_REQUIRED_AGAIN",
];
