export type GateSelectivityVolumeWarningCode =
  | "GATE_SELECTIVITY_RESTORED"
  | "EARNED_DANGER_RATE_REDUCED_TO_HEALTHY_RANGE"
  | "BORDERLINE_DANGER_RESTORED"
  | "RESET_TO_DANGER_RATE_REDUCED"
  | "NEGATIVE_CONTEXT_NO_LONGER_TREATED_AS_POSITIVE"
  | "NEGATIVE_CONTEXT_TREATED_AS_POSITIVE"
  | "LOW_SPACING_NO_LONGER_POSITIVE"
  | "IMMEDIATE_AFTER_RESET_NO_LONGER_POSITIVE"
  | "LEADING_TEAM_REATTACK_NO_LONGER_POSITIVE"
  | "POST_SCORE_CONTEXT_NO_LONGER_POSITIVE"
  | "SCORING_OPPORTUNITY_VOLUME_REDUCED"
  | "SCORING_EVENTS_REDUCED"
  | "AVERAGE_TOTAL_POINTS_REDUCED"
  | "SEVERE_BLOWOUT_RATE_REDUCED"
  | "BLOWOUT_RATE_REDUCED"
  | "POST_SCORE_RESET_RESTORED"
  | "RESET_SPECIFICITY_RESTORED"
  | "DOMINANCE_CHAIN_RECALIBRATED"
  | "GATE_STILL_TOO_PERMISSIVE"
  | "EARNED_DANGER_RATE_STILL_TOO_HIGH"
  | "RESET_TO_DANGER_RATE_STILL_TOO_HIGH"
  | "SCORING_OPPORTUNITY_VOLUME_STILL_TOO_HIGH"
  | "SCORING_EVENTS_STILL_TOO_HIGH"
  | "AVERAGE_TOTAL_POINTS_STILL_TOO_HIGH"
  | "SEVERE_BLOWOUT_RATE_STILL_TOO_HIGH"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "POST_SCORE_RESET_STILL_REGRESSED"
  | "RESET_SPECIFICITY_STILL_REGRESSED"
  | "DOMINANCE_CHAIN_STILL_REGRESSED"
  | "EARNED_DANGER_LOST"
  | "AUTOMATIC_DANGER_RESTORED_TOO_MUCH"
  | "DENSITY_COLLAPSED"
  | "TEAM_BALANCE_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const GATE_SELECTIVITY_VOLUME_BLOCKING_WARNINGS: readonly GateSelectivityVolumeWarningCode[] = [
  "GATE_STILL_TOO_PERMISSIVE",
  "EARNED_DANGER_RATE_STILL_TOO_HIGH",
  "RESET_TO_DANGER_RATE_STILL_TOO_HIGH",
  "SCORING_OPPORTUNITY_VOLUME_STILL_TOO_HIGH",
  "SCORING_EVENTS_STILL_TOO_HIGH",
  "AVERAGE_TOTAL_POINTS_STILL_TOO_HIGH",
  "SEVERE_BLOWOUT_RATE_STILL_TOO_HIGH",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "POST_SCORE_RESET_STILL_REGRESSED",
  "RESET_SPECIFICITY_STILL_REGRESSED",
  "DOMINANCE_CHAIN_STILL_REGRESSED",
  "TEAM_BALANCE_REGRESSED",
  "NEGATIVE_CONTEXT_TREATED_AS_POSITIVE",
  "EARNED_DANGER_LOST",
  "AUTOMATIC_DANGER_RESTORED_TOO_MUCH",
  "DENSITY_COLLAPSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
];
