export type GoalkeeperSecureResetBreakWarningCode =
  | "GOALKEEPER_SECURE_RESET_BREAK_CALIBRATED"
  | "GOALKEEPER_SECURE_BREAK_CONNECTED"
  | "GOALKEEPER_SECURE_BREAK_EFFECTIVE"
  | "GOALKEEPER_SECURE_BREAK_STILL_ZERO"
  | "GOALKEEPER_SECURE_IMMEDIATE_REATTACK_REDUCED"
  | "POST_SCORE_IMMEDIATE_REATTACK_REDUCED"
  | "POST_SCORE_RESET_PROTECTED_IMPROVED"
  | "CONCEDING_TEAM_FIRST_POSSESSION_IMPROVED"
  | "DEFENSIVE_RECOVERY_BREAKS_DOMINANCE_IMPROVED"
  | "DOMINANCE_DECAY_METRICS_CLARIFIED"
  | "DOMINANCE_CHAIN_GAINS_PRESERVED"
  | "TEAM_OPPORTUNITY_BALANCE_PRESERVED"
  | "DENSITY_CALIBRATION_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "BLOWOUT_RATE_REDUCED"
  | "POST_SCORE_IMMEDIATE_REATTACK_STILL_TOO_HIGH"
  | "POST_SCORE_RESET_PROTECTED_STILL_TOO_LOW"
  | "CONCEDING_TEAM_FIRST_POSSESSION_STILL_TOO_LOW"
  | "GOALKEEPER_SECURE_BREAK_STILL_WEAK"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "TEAM_BALANCE_REGRESSED"
  | "DENSITY_REGRESSED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const GOALKEEPER_SECURE_RESET_BREAK_WARNING_CODES: readonly GoalkeeperSecureResetBreakWarningCode[] = [
  "GOALKEEPER_SECURE_RESET_BREAK_CALIBRATED",
  "GOALKEEPER_SECURE_BREAK_CONNECTED",
  "GOALKEEPER_SECURE_BREAK_EFFECTIVE",
  "GOALKEEPER_SECURE_BREAK_STILL_ZERO",
  "GOALKEEPER_SECURE_IMMEDIATE_REATTACK_REDUCED",
  "POST_SCORE_IMMEDIATE_REATTACK_REDUCED",
  "POST_SCORE_RESET_PROTECTED_IMPROVED",
  "CONCEDING_TEAM_FIRST_POSSESSION_IMPROVED",
  "DEFENSIVE_RECOVERY_BREAKS_DOMINANCE_IMPROVED",
  "DOMINANCE_DECAY_METRICS_CLARIFIED",
  "DOMINANCE_CHAIN_GAINS_PRESERVED",
  "TEAM_OPPORTUNITY_BALANCE_PRESERVED",
  "DENSITY_CALIBRATION_PRESERVED",
  "ROUTE_FAMILY_DIVERSITY_PRESERVED",
  "BLOWOUT_RATE_REDUCED",
  "POST_SCORE_IMMEDIATE_REATTACK_STILL_TOO_HIGH",
  "POST_SCORE_RESET_PROTECTED_STILL_TOO_LOW",
  "CONCEDING_TEAM_FIRST_POSSESSION_STILL_TOO_LOW",
  "GOALKEEPER_SECURE_BREAK_STILL_WEAK",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "TEAM_BALANCE_REGRESSED",
  "DENSITY_REGRESSED",
  "DOMINANCE_CHAIN_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "FULL_MATCH_BATCH_ECONOMY_PARTIAL",
  "FULL_MATCH_BATCH_ECONOMY_HEALTHY",
];
