export type LateGameThreatQualityMonitoringWarningCode =
  | "LATE_GAME_THREAT_MONITORING_COMPLETE"
  | "LATE_GAME_THREAT_AUTOMATICITY_MEASURED"
  | "LATE_GAME_THREAT_AUTOMATICITY_REDUCED"
  | "LATE_GAME_THREAT_AUTOMATICITY_EXPLAINED"
  | "LATE_GAME_THREAT_FROM_REAL_SIGNAL_CONFIRMED"
  | "LATE_GAME_THREAT_DOWNGRADED_WHEN_UNSUPPORTED"
  | "FORCED_COMEBACK_SUSPICION_MEASURED"
  | "FORCED_COMEBACK_SUSPICION_REDUCED"
  | "FORCED_COMEBACK_SUSPICION_EXPLAINED"
  | "FORCED_COMEBACK_FALSE_POSITIVES_CLASSIFIED"
  | "NATURAL_TRAILING_CONVERSION_PATH_MEASURED"
  | "NATURAL_TRAILING_CONVERSION_PATH_COMPLETE"
  | "NO_ACTUAL_FORCED_COMEBACK_CONFIRMED"
  | "NO_RUBBER_BANDING_CONFIRMED"
  | "NO_FORCED_COMEBACK_CONFIRMED"
  | "NO_TRAILING_SCORE_INJECTION_CONFIRMED"
  | "NO_TRAILING_OPPORTUNITY_FORCING_CONFIRMED"
  | "NO_TRAILING_SCORING_EVENT_INJECTION_CONFIRMED"
  | "CLOSE_GAME_RATE_PRESERVED"
  | "COMPETITIVE_GAME_RATE_PRESERVED"
  | "BLOWOUT_RATE_PRESERVED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "GATE_SELECTIVITY_PRESERVED"
  | "CALIBRATION_COVERAGE_COMPLETE"
  | "LATE_GAME_THREAT_AUTOMATICITY_TOO_HIGH"
  | "LATE_GAME_THREAT_WITHOUT_SIGNAL_TOO_HIGH"
  | "FORCED_COMEBACK_SUSPICION_UNEXPLAINED"
  | "ACTUAL_FORCED_COMEBACK_DETECTED"
  | "TRAILING_CONVERSION_PATH_INCOMPLETE"
  | "TRAILING_SCORING_EVENT_INJECTION_DETECTED"
  | "CLOSE_GAME_RATE_REGRESSED"
  | "COMPETITIVE_GAME_RATE_REGRESSED"
  | "BLOWOUT_RATE_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "CALIBRATION_COVERAGE_REGRESSED"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "RUBBER_BANDING_DETECTED"
  | "FORCED_COMEBACK_DETECTED"
  | "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const LATE_GAME_THREAT_MONITORING_BLOCKING_WARNINGS: readonly LateGameThreatQualityMonitoringWarningCode[] = [
  "ACTUAL_FORCED_COMEBACK_DETECTED",
  "TRAILING_SCORING_EVENT_INJECTION_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "RUBBER_BANDING_DETECTED",
  "FORCED_COMEBACK_DETECTED",
  "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
];
