export type LateGameThreatQualityTrailingConversionWarningCode =
  | "LATE_GAME_THREAT_QUALITY_FOLLOWUP_COMPLETE"
  | "TRAILING_THREAT_QUALITY_MEASURED"
  | "TRAILING_THREAT_QUALITY_IMPROVED"
  | "TRAILING_TERRITORIAL_GAIN_RESTORED"
  | "TRAILING_FORCED_DEFENSIVE_ACTION_RESTORED"
  | "TRAILING_HALF_CHANCE_IMPROVED"
  | "TRAILING_EARNED_DANGER_IMPROVED"
  | "NATURAL_TRAILING_CONVERSION_MEASURED"
  | "TRAILING_SCORING_SHARE_RESTORED_NATURALLY"
  | "LATE_GAME_THREAT_QUALITY_MEASURED"
  | "LATE_GAME_THREAT_QUALITY_IMPROVED"
  | "CLOSE_GAME_RATE_RECOVERED"
  | "COMPETITIVE_GAME_RATE_PRESERVED"
  | "BLOWOUT_RATE_PRESERVED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "NO_RUBBER_BANDING_CONFIRMED"
  | "NO_FORCED_COMEBACK_CONFIRMED"
  | "NO_TRAILING_SCORE_INJECTION_CONFIRMED"
  | "NO_TRAILING_OPPORTUNITY_FORCING_CONFIRMED"
  | "NO_TRAILING_SCORING_EVENT_INJECTION_CONFIRMED"
  | "GATE_SELECTIVITY_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "CALIBRATION_COVERAGE_COMPLETE"
  | "TRAILING_THREAT_QUALITY_TOO_LOW"
  | "TRAILING_TERRITORIAL_GAIN_STILL_ZERO"
  | "TRAILING_FORCED_DEFENSIVE_ACTION_STILL_ZERO"
  | "TRAILING_SCORING_SHARE_STILL_ZERO"
  | "LATE_GAME_THREAT_QUALITY_TOO_LOW"
  | "CLOSE_GAME_RATE_STILL_LOW"
  | "CLOSE_GAME_RATE_REGRESSED"
  | "COMPETITIVE_GAME_RATE_REGRESSED"
  | "BLOWOUT_RATE_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "CALIBRATION_COVERAGE_REGRESSED"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "RUBBER_BANDING_DETECTED"
  | "FORCED_COMEBACK_DETECTED"
  | "TRAILING_SCORING_EVENT_INJECTION_DETECTED"
  | "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const LATE_GAME_THREAT_QUALITY_BLOCKING_WARNINGS: readonly LateGameThreatQualityTrailingConversionWarningCode[] = [
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "RUBBER_BANDING_DETECTED",
  "FORCED_COMEBACK_DETECTED",
  "TRAILING_SCORING_EVENT_INJECTION_DETECTED",
  "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "CALIBRATION_COVERAGE_REGRESSED",
  "GATE_SELECTIVITY_REGRESSED",
  "AUTOMATIC_DANGER_RESTORED",
];
