export type MatchEconomyFinalStabilizationWarningCode =
  | "MATCH_ECONOMY_FINAL_STABILIZATION_COMPLETE"
  | "FINAL_METRIC_CONSISTENCY_AUDIT_COMPLETE"
  | "FINAL_GUARDRAIL_AUDIT_COMPLETE"
  | "FINAL_LONGITUDINAL_STABILITY_AUDIT_COMPLETE"
  | "FINAL_SCORE_ECONOMY_HEALTHY"
  | "FINAL_CLOSE_GAME_DISTRIBUTION_HEALTHY"
  | "FINAL_COMPETITIVE_DISTRIBUTION_HEALTHY"
  | "FINAL_BLOWOUT_RATE_CONTROLLED"
  | "FINAL_SEVERE_BLOWOUT_RATE_CONTROLLED"
  | "FINAL_ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "FINAL_TRAILING_RESPONSE_HEALTHY"
  | "FINAL_TRAILING_THREAT_QUALITY_HEALTHY"
  | "FINAL_LATE_GAME_AUTOMATICITY_LOW"
  | "FINAL_FORCED_COMEBACK_SUSPICION_EXPLAINED"
  | "FINAL_NATURAL_TRAILING_CONVERSION_PATH_COMPLETE"
  | "FINAL_CALIBRATION_COVERAGE_COMPLETE"
  | "PRODUCT_BASELINE_READY"
  | "NO_SCORE_MANIPULATION_CONFIRMED"
  | "NO_RUBBER_BANDING_CONFIRMED"
  | "NO_FORCED_COMEBACK_CONFIRMED"
  | "NO_TRAILING_SCORE_INJECTION_CONFIRMED"
  | "NO_TRAILING_OPPORTUNITY_FORCING_CONFIRMED"
  | "RATE_METRIC_RENAMED_AS_RATIO"
  | "LATE_GAME_THREAT_RATE_CORRECTED"
  | "METRIC_INCONSISTENCY_DETECTED"
  | "RATE_GREATER_THAN_100_WITHOUT_RATIO_DEFINITION"
  | "LATE_GAME_THREAT_RATE_STILL_INCONSISTENT"
  | "CLOSE_GAME_RATE_REGRESSED"
  | "COMPETITIVE_GAME_RATE_REGRESSED"
  | "BLOWOUT_RATE_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "ROUTE_FAMILY_DIVERSITY_REGRESSED"
  | "TRAILING_RESPONSE_REGRESSED"
  | "TRAILING_THREAT_QUALITY_REGRESSED"
  | "LATE_GAME_AUTOMATICITY_TOO_HIGH"
  | "FORCED_COMEBACK_SUSPICION_UNEXPLAINED"
  | "NATURAL_TRAILING_CONVERSION_PATH_INCOMPLETE"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "CALIBRATION_COVERAGE_REGRESSED"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "RUBBER_BANDING_DETECTED"
  | "FORCED_COMEBACK_DETECTED"
  | "TRAILING_SCORING_EVENT_INJECTION_DETECTED"
  | "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "UNKNOWN_SCORING_FAMILY_DETECTED"
  | "PENALTY_SHOT_LEAKAGE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const MATCH_ECONOMY_FINAL_STABILIZATION_BLOCKING_WARNINGS: readonly MatchEconomyFinalStabilizationWarningCode[] = [
  "METRIC_INCONSISTENCY_DETECTED",
  "RATE_GREATER_THAN_100_WITHOUT_RATIO_DEFINITION",
  "LATE_GAME_THREAT_RATE_STILL_INCONSISTENT",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "RUBBER_BANDING_DETECTED",
  "FORCED_COMEBACK_DETECTED",
  "TRAILING_SCORING_EVENT_INJECTION_DETECTED",
  "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "UNKNOWN_SCORING_FAMILY_DETECTED",
  "PENALTY_SHOT_LEAKAGE_DETECTED",
];

export const MATCH_ECONOMY_FINAL_STABILIZATION_HEALTHY_BLOCKERS: readonly MatchEconomyFinalStabilizationWarningCode[] = [
  ...MATCH_ECONOMY_FINAL_STABILIZATION_BLOCKING_WARNINGS,
  "CLOSE_GAME_RATE_REGRESSED",
  "COMPETITIVE_GAME_RATE_REGRESSED",
  "BLOWOUT_RATE_REGRESSED",
  "SEVERE_BLOWOUT_REGRESSED",
  "ROUTE_FAMILY_DIVERSITY_REGRESSED",
  "TRAILING_RESPONSE_REGRESSED",
  "TRAILING_THREAT_QUALITY_REGRESSED",
  "LATE_GAME_AUTOMATICITY_TOO_HIGH",
  "FORCED_COMEBACK_SUSPICION_UNEXPLAINED",
  "NATURAL_TRAILING_CONVERSION_PATH_INCOMPLETE",
  "DOMINANCE_CHAIN_REGRESSED",
  "CALIBRATION_COVERAGE_REGRESSED",
  "SCORING_OPPORTUNITY_VOLUME_REGRESSED",
  "SCORING_EVENTS_REGRESSED",
  "AVERAGE_TOTAL_POINTS_REGRESSED",
];
