export type ResetBreakBlowoutEconomyWarningCode =
  | "RESET_BREAK_BLOWOUT_ECONOMY_CALIBRATED"
  | "BLOWOUT_RATE_REDUCED"
  | "CLOSE_GAME_RATE_IMPROVED"
  | "COMPETITIVE_GAME_RATE_IMPROVED"
  | "RESET_TO_IMMEDIATE_DANGER_REDUCED"
  | "RESET_TO_IMMEDIATE_DANGER_CLASSIFIED"
  | "AUTOMATIC_DANGER_REDUCED"
  | "EARNED_DANGER_PRESERVED"
  | "GOALKEEPER_SECURE_RESET_GAINS_PRESERVED"
  | "POST_SCORE_RESET_GAINS_PRESERVED"
  | "DOMINANCE_CHAIN_GAINS_PRESERVED"
  | "TEAM_OPPORTUNITY_BALANCE_PRESERVED"
  | "DENSITY_CALIBRATION_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "RESET_TO_IMMEDIATE_DANGER_STILL_TOO_HIGH"
  | "AUTOMATIC_DANGER_STILL_TOO_HIGH"
  | "TEAM_BALANCE_REGRESSED"
  | "DENSITY_REGRESSED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const RESET_BREAK_BLOWOUT_BLOCKING_WARNINGS: readonly ResetBreakBlowoutEconomyWarningCode[] = [
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "RESET_TO_IMMEDIATE_DANGER_STILL_TOO_HIGH",
  "AUTOMATIC_DANGER_STILL_TOO_HIGH",
  "TEAM_BALANCE_REGRESSED",
  "DENSITY_REGRESSED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "DOMINANCE_CHAIN_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
] as const;
