export type RouteFamilyScoringRateWarningCode =
  | "ROUTE_FAMILY_SCORING_RATE_CALIBRATED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "SCORING_EVENTS_PER_MATCH_REDUCED"
  | "AVERAGE_TOTAL_POINTS_REDUCED"
  | "BLOWOUT_RATE_REDUCED"
  | "SEVERE_BLOWOUT_RATE_REDUCED"
  | "CONVERSION_SUCCESS_NOT_AUTOMATIC"
  | "TRY_SUCCESS_RATE_REDUCED"
  | "DROP_SUCCESS_RATE_REDUCED"
  | "SHOT_SUCCESS_RATE_MONITORED"
  | "NON_SCORING_OUTCOMES_INCREASED"
  | "CONTINUATION_PRESERVED"
  | "SCORE_STILL_TOO_HIGH"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "SHOT_ONLY_REGRESSION"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "GLOBAL_ECONOMY_NOT_CONFIRMED"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL";

export const routeFamilyScoringRateWarningCodes: readonly RouteFamilyScoringRateWarningCode[] = [
  "ROUTE_FAMILY_SCORING_RATE_CALIBRATED",
  "ROUTE_FAMILY_DIVERSITY_PRESERVED",
  "SCORING_EVENTS_PER_MATCH_REDUCED",
  "AVERAGE_TOTAL_POINTS_REDUCED",
  "BLOWOUT_RATE_REDUCED",
  "SEVERE_BLOWOUT_RATE_REDUCED",
  "CONVERSION_SUCCESS_NOT_AUTOMATIC",
  "TRY_SUCCESS_RATE_REDUCED",
  "DROP_SUCCESS_RATE_REDUCED",
  "SHOT_SUCCESS_RATE_MONITORED",
  "NON_SCORING_OUTCOMES_INCREASED",
  "CONTINUATION_PRESERVED",
  "SCORE_STILL_TOO_HIGH",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "SHOT_ONLY_REGRESSION",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "GLOBAL_ECONOMY_NOT_CONFIRMED",
  "FULL_MATCH_BATCH_ECONOMY_HEALTHY",
  "FULL_MATCH_BATCH_ECONOMY_PARTIAL",
];
