export type RouteEconomyRecheckWarningCode =
  | "ROUTE_ECONOMY_RECHECK_COMPLETE"
  | "DANGER_TO_OPPORTUNITY_DECOUPLED"
  | "EARNED_DANGER_TO_OPPORTUNITY_REDUCED"
  | "BORDERLINE_DANGER_TO_OPPORTUNITY_REDUCED"
  | "CONTINUATION_TO_OPPORTUNITY_REDUCED"
  | "HALF_CHANCE_LAYER_ADDED"
  | "FORCED_DEFENSIVE_ACTION_LAYER_ADDED"
  | "TERRITORIAL_GAIN_LAYER_ADDED"
  | "ROUTE_QUALITY_GATE_CONNECTED"
  | "OPPORTUNITY_QUALITY_GATE_CONNECTED"
  | "GOALKEEPER_SECURE_FOLLOWUP_CLARIFIED"
  | "GATE_SELECTIVITY_PRESERVED"
  | "EARNED_DANGER_PRESERVED"
  | "AUTOMATIC_DANGER_STILL_BLOCKED"
  | "VOLUME_PRESERVED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "TEAM_BALANCE_PRESERVED"
  | "EARNED_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH"
  | "BORDERLINE_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH"
  | "CONTINUATION_TO_OPPORTUNITY_STILL_TOO_HIGH"
  | "GOALKEEPER_SECURE_TO_DANGER_STILL_UNEXPLAINED"
  | "ROUTE_ECONOMY_REGRESSED"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const ROUTE_ECONOMY_RECHECK_BLOCKING_WARNINGS: readonly RouteEconomyRecheckWarningCode[] = [
  "EARNED_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH",
  "BORDERLINE_DANGER_TO_OPPORTUNITY_STILL_TOO_HIGH",
  "CONTINUATION_TO_OPPORTUNITY_STILL_TOO_HIGH",
  "GOALKEEPER_SECURE_TO_DANGER_STILL_UNEXPLAINED",
  "SCORING_OPPORTUNITY_VOLUME_REGRESSED",
  "SCORING_EVENTS_REGRESSED",
  "AVERAGE_TOTAL_POINTS_REGRESSED",
  "SEVERE_BLOWOUT_REGRESSED",
  "GATE_SELECTIVITY_REGRESSED",
  "AUTOMATIC_DANGER_RESTORED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
];
