export type SegmentScoringDensityWarningCode =
  | "SEGMENT_SCORING_DENSITY_CALIBRATED"
  | "SCORING_OPPORTUNITIES_PER_MATCH_REDUCED"
  | "SCORING_OPPORTUNITIES_PER_SEGMENT_REDUCED"
  | "SCORING_EVENTS_PER_MATCH_REDUCED"
  | "AVERAGE_TOTAL_POINTS_REDUCED"
  | "BLOWOUT_RATE_REDUCED"
  | "SEVERE_BLOWOUT_RATE_REDUCED"
  | "NEUTRAL_PHASES_INCREASED"
  | "DEFENSIVE_RECOVERIES_INCREASED"
  | "RESET_PHASES_INCREASED"
  | "CONTINUATION_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "DENSITY_STILL_TOO_HIGH"
  | "SCORE_STILL_TOO_HIGH"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY"
  | "SEGMENT_SCORING_DENSITY_TOO_HIGH"
  | "TOO_MANY_DANGER_PHASES"
  | "TOO_MANY_CONSECUTIVE_SCORING_OPPORTUNITIES"
  | "SAME_TEAM_OPPORTUNITY_CHAIN_TOO_LONG"
  | "SAME_FAMILY_REPEAT_TOO_HIGH"
  | "TOO_FEW_NEUTRAL_PHASES"
  | "TOO_FEW_DEFENSIVE_RECOVERIES"
  | "TOO_FEW_RESET_PHASES"
  | "CONTINUATION_NOT_REDUCING_DENSITY"
  | "FATIGUE_NOT_REDUCING_LATE_DENSITY"
  | "DEFENSIVE_RESPONSE_NOT_INTERRUPTING_CHAINS"
  | "GOALKEEPER_SECURE_NOT_RESETTING_PHASE"
  | "POSSESSION_RESET_MISSING_AFTER_SCORE"
  | "SEGMENT_AMPLIFICATION_REAPPEARED";

export const SEGMENT_SCORING_DENSITY_WARNING_CODES: readonly SegmentScoringDensityWarningCode[] = [
  "SEGMENT_SCORING_DENSITY_CALIBRATED",
  "SCORING_OPPORTUNITIES_PER_MATCH_REDUCED",
  "SCORING_OPPORTUNITIES_PER_SEGMENT_REDUCED",
  "SCORING_EVENTS_PER_MATCH_REDUCED",
  "AVERAGE_TOTAL_POINTS_REDUCED",
  "BLOWOUT_RATE_REDUCED",
  "SEVERE_BLOWOUT_RATE_REDUCED",
  "NEUTRAL_PHASES_INCREASED",
  "DEFENSIVE_RECOVERIES_INCREASED",
  "RESET_PHASES_INCREASED",
  "CONTINUATION_PRESERVED",
  "ROUTE_FAMILY_DIVERSITY_PRESERVED",
  "DENSITY_STILL_TOO_HIGH",
  "SCORE_STILL_TOO_HIGH",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FULL_MATCH_BATCH_ECONOMY_PARTIAL",
  "FULL_MATCH_BATCH_ECONOMY_HEALTHY",
  "SEGMENT_SCORING_DENSITY_TOO_HIGH",
  "TOO_MANY_DANGER_PHASES",
  "TOO_MANY_CONSECUTIVE_SCORING_OPPORTUNITIES",
  "SAME_TEAM_OPPORTUNITY_CHAIN_TOO_LONG",
  "SAME_FAMILY_REPEAT_TOO_HIGH",
  "TOO_FEW_NEUTRAL_PHASES",
  "TOO_FEW_DEFENSIVE_RECOVERIES",
  "TOO_FEW_RESET_PHASES",
  "CONTINUATION_NOT_REDUCING_DENSITY",
  "FATIGUE_NOT_REDUCING_LATE_DENSITY",
  "DEFENSIVE_RESPONSE_NOT_INTERRUPTING_CHAINS",
  "GOALKEEPER_SECURE_NOT_RESETTING_PHASE",
  "POSSESSION_RESET_MISSING_AFTER_SCORE",
  "SEGMENT_AMPLIFICATION_REAPPEARED",
];
