export type TeamOpportunityBalanceWarningCode =
  | "TEAM_OPPORTUNITY_IMBALANCE"
  | "TEAM_DANGER_PHASE_IMBALANCE"
  | "TEAM_SCORING_EVENT_IMBALANCE"
  | "TEAM_POINTS_IMBALANCE"
  | "ONE_SIDED_OPPORTUNITY_RISK"
  | "ONE_SIDED_SCORING_RISK"
  | "DOMINANCE_CHAIN_TOO_LONG"
  | "DOMINANT_TEAM_MOMENTUM_AMPLIFIED"
  | "TRAILING_TEAM_RESPONSE_TOO_WEAK"
  | "RESET_NOT_HELPING_TRAILING_TEAM"
  | "DEFENSIVE_RECOVERY_NOT_CREATING_RESPONSE"
  | "POSSESSION_AFTER_CONCEDING_TOO_WEAK"
  | "NON_SHOT_ACCESS_IMBALANCED"
  | "ROUTE_FAMILY_MIX_IMBALANCED_BY_TEAM"
  | "FATIGUE_IMBALANCE_AMPLIFIES_SCORE"
  | "PRESSURE_IMBALANCE_AMPLIFIES_SCORE"
  | "GOALKEEPER_IMPACT_IMBALANCED"
  | "TEAM_OPPORTUNITY_BALANCE_CALIBRATED"
  | "OPPORTUNITY_BALANCE_IMPROVED"
  | "DANGER_BALANCE_IMPROVED"
  | "SCORING_BALANCE_IMPROVED"
  | "POINT_BALANCE_IMPROVED"
  | "TRAILING_TEAM_RESPONSE_IMPROVED"
  | "DOMINANCE_CHAIN_REDUCED"
  | "RESET_TO_RESPONSE_IMPROVED"
  | "DEFENSIVE_RECOVERY_TO_DANGER_IMPROVED"
  | "DENSITY_CALIBRATION_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "BLOWOUT_RATE_REDUCED"
  | "SHUTOUT_RATE_REDUCED"
  | "ONE_SIDED_SCORING_REDUCED"
  | "TEAM_BALANCE_STILL_TOO_WEAK"
  | "BLOWOUT_RATE_STILL_TOO_HIGH"
  | "DOMINANT_TEAM_STILL_TOO_STICKY"
  | "TRAILING_TEAM_RESPONSE_STILL_TOO_WEAK"
  | "OPPORTUNITY_BALANCE_REGRESSED"
  | "DENSITY_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const TEAM_OPPORTUNITY_BALANCE_WARNING_CODES: readonly TeamOpportunityBalanceWarningCode[] = [
  "TEAM_OPPORTUNITY_IMBALANCE",
  "TEAM_DANGER_PHASE_IMBALANCE",
  "TEAM_SCORING_EVENT_IMBALANCE",
  "TEAM_POINTS_IMBALANCE",
  "ONE_SIDED_OPPORTUNITY_RISK",
  "ONE_SIDED_SCORING_RISK",
  "DOMINANCE_CHAIN_TOO_LONG",
  "DOMINANT_TEAM_MOMENTUM_AMPLIFIED",
  "TRAILING_TEAM_RESPONSE_TOO_WEAK",
  "RESET_NOT_HELPING_TRAILING_TEAM",
  "DEFENSIVE_RECOVERY_NOT_CREATING_RESPONSE",
  "POSSESSION_AFTER_CONCEDING_TOO_WEAK",
  "NON_SHOT_ACCESS_IMBALANCED",
  "ROUTE_FAMILY_MIX_IMBALANCED_BY_TEAM",
  "FATIGUE_IMBALANCE_AMPLIFIES_SCORE",
  "PRESSURE_IMBALANCE_AMPLIFIES_SCORE",
  "GOALKEEPER_IMPACT_IMBALANCED",
  "TEAM_OPPORTUNITY_BALANCE_CALIBRATED",
  "OPPORTUNITY_BALANCE_IMPROVED",
  "DANGER_BALANCE_IMPROVED",
  "SCORING_BALANCE_IMPROVED",
  "POINT_BALANCE_IMPROVED",
  "TRAILING_TEAM_RESPONSE_IMPROVED",
  "DOMINANCE_CHAIN_REDUCED",
  "RESET_TO_RESPONSE_IMPROVED",
  "DEFENSIVE_RECOVERY_TO_DANGER_IMPROVED",
  "DENSITY_CALIBRATION_PRESERVED",
  "ROUTE_FAMILY_DIVERSITY_PRESERVED",
  "BLOWOUT_RATE_REDUCED",
  "SHUTOUT_RATE_REDUCED",
  "ONE_SIDED_SCORING_REDUCED",
  "TEAM_BALANCE_STILL_TOO_WEAK",
  "BLOWOUT_RATE_STILL_TOO_HIGH",
  "DOMINANT_TEAM_STILL_TOO_STICKY",
  "TRAILING_TEAM_RESPONSE_STILL_TOO_WEAK",
  "OPPORTUNITY_BALANCE_REGRESSED",
  "DENSITY_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "FULL_MATCH_BATCH_ECONOMY_PARTIAL",
  "FULL_MATCH_BATCH_ECONOMY_HEALTHY",
];
