export type TrailingTeamResponseLateGamePressureWarningCode =
  | "TRAILING_TEAM_RESPONSE_FOLLOWUP_COMPLETE"
  | "TRAILING_TEAM_RESPONSE_MEASURED"
  | "TRAILING_TEAM_RESPONSE_RESTORED"
  | "TRAILING_TEAM_RESPONSE_HEALTHY"
  | "TRAILING_TEAM_RESPONSE_CAUSES_MEASURED"
  | "LATE_GAME_PRESSURE_MEASURED"
  | "LATE_GAME_PRESSURE_HEALTHY"
  | "LATE_GAME_COMPETITION_PRESERVED"
  | "FINAL_QUARTER_COMPETITION_PRESERVED"
  | "CLOSE_GAME_RATE_PRESERVED"
  | "COMPETITIVE_GAME_RATE_PRESERVED"
  | "BLOWOUT_RATE_PRESERVED"
  | "SEVERE_BLOWOUT_STILL_LOW"
  | "NO_RUBBER_BANDING_CONFIRMED"
  | "NO_FORCED_COMEBACK_CONFIRMED"
  | "NO_TRAILING_SCORE_INJECTION_CONFIRMED"
  | "NO_TRAILING_OPPORTUNITY_FORCING_CONFIRMED"
  | "GATE_SELECTIVITY_PRESERVED"
  | "ROUTE_FAMILY_DIVERSITY_PRESERVED"
  | "CALIBRATION_COVERAGE_COMPLETE"
  | "TRAILING_TEAM_RESPONSE_TOO_LOW"
  | "TRAILING_TEAM_OPPORTUNITY_SHARE_TOO_LOW"
  | "TRAILING_TEAM_SCORING_SHARE_TOO_LOW"
  | "TRAILING_TEAM_RECOVERY_SHARE_TOO_LOW"
  | "TRAILING_TEAM_PRESSURE_RELIEF_TOO_LOW"
  | "LATE_GAME_PRESSURE_TOO_LOW"
  | "TRAILING_TEAM_RESPONSE_FORCED_SUSPECTED"
  | "TRAILING_TEAM_SCORE_FORCED_DETECTED"
  | "TRAILING_TEAM_OPPORTUNITY_FORCED_DETECTED"
  | "CLOSE_GAME_RATE_REGRESSED"
  | "COMPETITIVE_GAME_RATE_REGRESSED"
  | "BLOWOUT_RATE_REGRESSED"
  | "SEVERE_BLOWOUT_REGRESSED"
  | "DOMINANCE_CHAIN_REGRESSED"
  | "CALIBRATION_COVERAGE_REGRESSED"
  | "SCORING_OPPORTUNITY_VOLUME_REGRESSED"
  | "SCORING_EVENTS_REGRESSED"
  | "AVERAGE_TOTAL_POINTS_REGRESSED"
  | "GATE_SELECTIVITY_REGRESSED"
  | "AUTOMATIC_DANGER_RESTORED"
  | "POST_SCORE_RESET_REGRESSED"
  | "GOALKEEPER_SECURE_RESET_REGRESSED"
  | "SHOT_ONLY_REGRESSION"
  | "NON_SHOT_ROUTES_DISAPPEARED"
  | "CONVERSION_WITHOUT_TRY_DETECTED"
  | "SCORE_CAP_DETECTED"
  | "POST_HOC_REWRITE_DETECTED"
  | "FORCED_SCORE_DETECTED"
  | "FORCED_TRAILING_TEAM_SCORE_DETECTED"
  | "RUBBER_BANDING_DETECTED"
  | "FORCED_COMEBACK_DETECTED"
  | "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED"
  | "FULL_MATCH_BATCH_ECONOMY_PARTIAL"
  | "FULL_MATCH_BATCH_ECONOMY_HEALTHY";

export const TRAILING_TEAM_RESPONSE_BLOCKING_WARNINGS: readonly TrailingTeamResponseLateGamePressureWarningCode[] = [
  "TRAILING_TEAM_RESPONSE_FORCED_SUSPECTED",
  "TRAILING_TEAM_SCORE_FORCED_DETECTED",
  "TRAILING_TEAM_OPPORTUNITY_FORCED_DETECTED",
  "CLOSE_GAME_RATE_REGRESSED",
  "COMPETITIVE_GAME_RATE_REGRESSED",
  "BLOWOUT_RATE_REGRESSED",
  "SEVERE_BLOWOUT_REGRESSED",
  "DOMINANCE_CHAIN_REGRESSED",
  "CALIBRATION_COVERAGE_REGRESSED",
  "SCORING_OPPORTUNITY_VOLUME_REGRESSED",
  "SCORING_EVENTS_REGRESSED",
  "AVERAGE_TOTAL_POINTS_REGRESSED",
  "GATE_SELECTIVITY_REGRESSED",
  "AUTOMATIC_DANGER_RESTORED",
  "POST_SCORE_RESET_REGRESSED",
  "GOALKEEPER_SECURE_RESET_REGRESSED",
  "SHOT_ONLY_REGRESSION",
  "NON_SHOT_ROUTES_DISAPPEARED",
  "CONVERSION_WITHOUT_TRY_DETECTED",
  "SCORE_CAP_DETECTED",
  "POST_HOC_REWRITE_DETECTED",
  "FORCED_SCORE_DETECTED",
  "FORCED_TRAILING_TEAM_SCORE_DETECTED",
  "RUBBER_BANDING_DETECTED",
  "FORCED_COMEBACK_DETECTED",
  "LEADING_TEAM_SCORE_SUPPRESSION_DETECTED",
];
